#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  libimagtimeui_0_2_0 = buildCratesLib {
    name = "libimagtimeui";
    version = "0.2.0";
    hash = "02442d6ec2ac61e1d07213f6c1cc1288ad6a519f11248624ff919977653d526d";
    deps = with allCrates; [ libimagerror clap lazy_static log regex chrono ];
  };}