#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libimagentryedit_0_2_0 = buildCratesLib {
    name = "libimagentryedit";
    version = "0.2.0";
    hash = "d077a12bb14af8d853542673a5b1c2b1d7aede12e6b6f9d16600f02e11cb2d4b";
    deps = with allCrates; [  all__libimagstore.libimagstore_0_2 all__libimagerror.libimagerror_0_2 all__libimagutil.libimagutil_0_2 all__libimagrt.libimagrt_0_2 ];
  };
  "libimagentryedit_0_2" = libimagentryedit_0_2_0;
  "libimagentryedit_0" = libimagentryedit_0_2_0;}