#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  primal-slowsieve_0_2_0 = buildCratesLib {
    name = "primal-slowsieve";
    version = "0.2.0";
    hash = "edd0a67418666a6facb21b24aec1501061dd3e3aefeed40151c2dd80e7e6b95f";
    deps = with allCrates; [  all__primal-bit.primal-bit_0_2 all__primal-estimate.primal-estimate_0_2 ];
  };
  "primal-slowsieve_0_2" = primal-slowsieve_0_2_0;
  "primal-slowsieve_0" = primal-slowsieve_0_2_0;}