#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  primesieve-sys_0_1_0 = buildCratesLib {
    name = "primesieve-sys";
    version = "0.1.0";
    hash = "bb3b03bea7e8da460e31d3ec93809ad28d4c488de9805d540371529c25f66e40";
    deps = with allCrates; [ libc gcc ];
  };}