#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  amethyst_renderer_0_2_0 = buildCratesLib {
    name = "amethyst_renderer";
    version = "0.2.0";
    hash = "ea572b0a9d07fc689c5c4e7eb0ab4022a8b1bf44ce23a8d93205248eae0a7b20";
    deps = with allCrates; [  all__gfx.gfx_0_9 ];
  };
  amethyst_renderer_0_2_1 = buildCratesLib {
    name = "amethyst_renderer";
    version = "0.2.1";
    hash = "437eb4121fd6fc4bf1a21d866997f3d99b2fafdd9fb8cc001a45b1de4bc28b2b";
    deps = with allCrates; [  all__gfx.gfx_0_9 ];
  };
  amethyst_renderer_0_3_0 = buildCratesLib {
    name = "amethyst_renderer";
    version = "0.3.0";
    hash = "6f7bdade170bcde85f064129d5c98b32b157413c337e82b38c581cedf945f0c3";
    deps = with allCrates; [  all__gfx.gfx_0_10 ];
  };
  "amethyst_renderer_0_2" = amethyst_renderer_0_2_1;
  amethyst_renderer_0_3_1 = buildCratesLib {
    name = "amethyst_renderer";
    version = "0.3.1";
    hash = "ea7c5c596136242b23d748c7ae231a567b6cd2cee913a8ab52fa8d53affe97c5";
    deps = with allCrates; [  all__gfx.gfx_0_10 ];
  };
  "amethyst_renderer_0_3" = amethyst_renderer_0_3_1;
  "amethyst_renderer_0" = amethyst_renderer_0_3_1;}