#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  pwf_0_1_0 = buildCratesLib {
    name = "pwf";
    version = "0.1.0";
    hash = "4051ca0b267879258c86c0946ca6e36b2d18682c14d2162933d9fa8bc77659e9";
    deps = with allCrates; [  ];
  };
  "pwf_0_1" = pwf_0_1_0;
  "pwf_0" = pwf_0_1_0;}