#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  udt_0_1_0 = buildCratesLib {
    name = "udt";
    version = "0.1.0";
    hash = "af0bcff42f1e398404db713ec974209b16def9cc57e38feb7b02bc0f4d5abf95";
    deps = with allCrates; [  all__libudt4-sys.libudt4-sys_0_1 all__libc.libc_0_1 ];
  };
  udt_0_1_1 = buildCratesLib {
    name = "udt";
    version = "0.1.1";
    hash = "7788acd85a75ac75117c75b428fd34643cabc040413e144804970ace87108303";
    deps = with allCrates; [  all__libudt4-sys.libudt4-sys_0_1 all__libc.libc_0_1 all__log.log_0_3 ];
  };
  udt_0_1_2 = buildCratesLib {
    name = "udt";
    version = "0.1.2";
    hash = "30ca77ad6d1f59aadb28502bd4b131430d52918437252493819951492937c4af";
    deps = with allCrates; [  all__bitflags.bitflags_0_3 all__libc.libc_0_1 all__libudt4-sys.libudt4-sys_0_1 all__log.log_0_3 ];
  };
  udt_0_1_4 = buildCratesLib {
    name = "udt";
    version = "0.1.4";
    hash = "55d50df66f1499e62cfda0591a27ec0aa47452da442119ca05de8533957628fa";
    deps = with allCrates; [  all__log.log_0_3 all__bitflags.bitflags_0_3 all__libc.libc_0_1 all__libudt4-sys.libudt4-sys_0_1 ];
  };
  "udt_0_1" = udt_0_1_4;
  "udt_0" = udt_0_1_4;}