#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  openexchangerates_0_1_0 = buildCratesLib {
    name = "openexchangerates";
    version = "0.1.0";
    hash = "88518c1ed4aa173296df8a18c699100adedb872ef72343f918fbe35915530be4";
    deps = with allCrates; [ yup-hyper-mock rustc-serialize log chrono hyper ];
  };
  openexchangerates_0_1_2 = buildCratesLib {
    name = "openexchangerates";
    version = "0.1.2";
    hash = "6e7ae022f25ab41dde3001000957f8f17e1888a1526deb9e3f4bf049a23fb4b0";
    deps = with allCrates; [ log yup-hyper-mock rustc-serialize hyper chrono ];
  };
  openexchangerates_0_1_3 = buildCratesLib {
    name = "openexchangerates";
    version = "0.1.3";
    hash = "5565df6e84e4831001a9d4140536c90aec266617370724c5cf7b59e7533a03b0";
    deps = with allCrates; [ chrono rustc-serialize hyper log yup-hyper-mock ];
  };
  openexchangerates_0_1_5 = buildCratesLib {
    name = "openexchangerates";
    version = "0.1.5";
    hash = "c6b24ecedd3945046ef0570bb51a380d37dc1524dada6bb7749623a44633005f";
    deps = with allCrates; [ yup-hyper-mock rustc-serialize log hyper chrono ];
  };
  openexchangerates_0_1_6 = buildCratesLib {
    name = "openexchangerates";
    version = "0.1.6";
    hash = "2cdff0fea008270ed07dc936b0ea0964f5ce0ba761145b50a8b8762b779fdc74";
    deps = with allCrates; [ log chrono hyper rustc-serialize ];
  };
  openexchangerates_0_1_7 = buildCratesLib {
    name = "openexchangerates";
    version = "0.1.7";
    hash = "05c3fb1c98fa49a49a31b682e3bea96af208d84d881e4c2ca3cdc5179550a213";
    deps = with allCrates; [ chrono serde_json hyper serde ];
  };}