#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  openzwave-sys_0_1_0 = buildCratesLib {
    name = "openzwave-sys";
    version = "0.1.0";
    hash = "48534686ace6568934e655aa20149ada2ad98deac1d4f4dfb9a0023e8f8482aa";
    deps = with allCrates; [ libc gcc ];
  };
  openzwave-sys_0_1_1 = buildCratesLib {
    name = "openzwave-sys";
    version = "0.1.1";
    hash = "d785e872de2f641a0cc8fded96a40c6dea6ff1f4f2c4512055a1276ccb6dbb8a";
    deps = with allCrates; [ libc gcc ];
  };}