#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  vdmdbg-sys_0_0_1 = buildCratesLib {
    name = "vdmdbg-sys";
    version = "0.0.1";
    hash = "0a5cc1366f75506e4e64e2a80f355cab674473e8cbdf1fa648a7a4e00f27c382";
    deps = with allCrates; [  winapi ];
  };
  "vdmdbg-sys_0_0" = vdmdbg-sys_0_0_1;
  "vdmdbg-sys_0" = vdmdbg-sys_0_0_1;}