#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  zero85_0_1_5 = buildCratesLib {
    name = "zero85";
    version = "0.1.5";
    hash = "0d64c87b6337e9fae57fd989aa9903ff9499a71a50d6bec24acbfca3f4f4c32d";
    deps = with allCrates; [ ];
  };
  zero85_0_2_0 = buildCratesLib {
    name = "zero85";
    version = "0.2.0";
    hash = "6687a10cb200d98c452f6745235b6a23eef23e4fdd324d0f8597d239c90c5e37";
    deps = with allCrates; [ ];
  };}