#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  zero_sum_0_1_0 = buildCratesLib {
    name = "zero_sum";
    version = "0.1.0";
    hash = "fb39642e7ea3d58b4aa1b73d44961b41f23a33d199ac31d19d370dc531bd59d9";
    deps = with allCrates; [ rand lazy_static time ];
  };
  zero_sum_0_2_0 = buildCratesLib {
    name = "zero_sum";
    version = "0.2.0";
    hash = "d5ee9f1fa3b99ce6d39f30c2acd5694cb8955d79b7e17bac320b81589489339b";
    deps = with allCrates; [ rand fnv lazy_static time ];
  };
  zero_sum_1_0_0 = buildCratesLib {
    name = "zero_sum";
    version = "1.0.0";
    hash = "ae8be8822c0b9e9ab14b46223b90fa49dee06f462e3eeeb28747ae94facc68ac";
    deps = with allCrates; [ fnv ];
  };}