#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  adorn_0_1_0 = buildCratesLib {
    name = "adorn";
    version = "0.1.0";
    hash = "8c3362aa7c5322f4914422e67d5a5ffbe3449b19bf65f0f4c3f2f0fd6ee1cebd";
    deps = with allCrates; [ ];
  };
  adorn_0_1_1 = buildCratesLib {
    name = "adorn";
    version = "0.1.1";
    hash = "7659a8a666acda757d639908e695d011f1a04019f68334ef292c4f364bc22312";
    deps = with allCrates; [ ];
  };
  adorn_0_1_2 = buildCratesLib {
    name = "adorn";
    version = "0.1.2";
    hash = "8d3611e8b0f90c37c068975c59ba16691130bb469832d57c9a5779605dccc67f";
    deps = with allCrates; [ ];
  };}