#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  monkeys_0_1_0 = buildCratesLib {
    name = "monkeys";
    version = "0.1.0";
    hash = "ebfc09c578e9ad9cdc4fdb6fb2cfc64f6f98677f794c859a17d25aed2bcd2681";
    deps = with allCrates; [  all__context.context_1_0 ];
  };
  "monkeys_0_1" = monkeys_0_1_0;
  "monkeys_0" = monkeys_0_1_0;}