#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  semantic-rs_0_0_1 = buildCratesLib {
    name = "semantic-rs";
    version = "0.0.1";
    hash = "50ad59a2ff51dd5aba4f7f38fc0a3246efbd8694a22cb1ab10e0d4872f0cf0bd";
    deps = with allCrates; [  ];
  };
  "semantic-rs_0_0" = semantic-rs_0_0_1;
  "semantic-rs_0" = semantic-rs_0_0_1;}