#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  mraa_0_0_1 = buildCratesLib {
    name = "mraa";
    version = "0.0.1";
    hash = "5e5e3b584ecd4b77bbf5cc9913b6a641406502df08797ced23526b9eab9ce034";
    deps = with allCrates; [ ];
  };}