#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  maybe_utf8_0_1_0 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.1.0";
    hash = "f160416c5a25e98635e4bc624b5cc8aaa1ad8355fa01203fa08dd6d304e0f35e";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_1_1 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.1.1";
    hash = "ae8d9ed65b19fc099d0e8ff8f064e0993f9a47ab5e8499de02671867570b17de";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_1_2 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.1.2";
    hash = "28303e17af11038cb0e3d20303912e142d2ec40ec472d6db16f9f567335684e2";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_1_3 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.1.3";
    hash = "7515959b00b4edc4a92d34f1a978224d221afd97e4219a6fdbccfd8041537a01";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_2_0 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.2.0";
    hash = "1b558296015ad1c91297fcc8f2eac167e5b576a5540cd82edba3582e7ddc9931";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_2_1 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.2.1";
    hash = "a9700edfd74d10e3c95862db3a7e9f3cfcb2bd498255801fe5ef78f64d0a1c17";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_2_2 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.2.2";
    hash = "441a2839c94b1fdcd7a3dd5ecb6b4387d7514198e829130d6807eba5c13e1946";
    deps = with allCrates; [ ];
  };
  maybe_utf8_0_2_3 = buildCratesLib {
    name = "maybe_utf8";
    version = "0.2.3";
    hash = "a657412b495e86bdd7119f42785886ce27b42e5a7330e85bef581e64ba052f54";
    deps = with allCrates; [ ];
  };}