#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  maybe_0_0_0 = buildCratesLib {
    name = "maybe";
    version = "0.0.0";
    hash = "aef4d3143ec7024ff3e0a130640f25cd94f92f3aee72a640bb626a5f270461e3";
    deps = with allCrates; [  ];
  };
  "maybe_0_0" = maybe_0_0_0;
  "maybe_0" = maybe_0_0_0;}