#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  handlers_0_1_0 = buildCratesLib {
    name = "handlers";
    version = "0.1.0";
    hash = "3f1829561f7d6e5c2c8fb399038679167e8e58a95c9720341606672febba1fbe";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  handlers_0_2_0 = buildCratesLib {
    name = "handlers";
    version = "0.2.0";
    hash = "deb3e130f6bd7b4eefec614fd9e066c246fe47c4b1477b779b6cdd9743277517";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_1" = handlers_0_1_0;
  handlers_0_3_0 = buildCratesLib {
    name = "handlers";
    version = "0.3.0";
    hash = "d457998f3e04adae715b66d66b8ffc6839b9512d60f4c08bfd9adfa0e399f9d4";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_2" = handlers_0_2_0;
  handlers_0_4_0 = buildCratesLib {
    name = "handlers";
    version = "0.4.0";
    hash = "25867670021124e2657827ddd72d77aa33ebc9234be4bdc8474c1977d4b837cb";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_3" = handlers_0_3_0;
  handlers_0_5_0 = buildCratesLib {
    name = "handlers";
    version = "0.5.0";
    hash = "dca68da395af242dff2efd59516b82dedcac842ad5aa45bf08ec3d71e8986fd0";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_4" = handlers_0_4_0;
  handlers_0_6_0 = buildCratesLib {
    name = "handlers";
    version = "0.6.0";
    hash = "c40b8f8dd8e496bce7785c3b8b901920ae0bce571df7090b4a2b19ae8387cfbd";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_5" = handlers_0_5_0;
  handlers_0_7_0 = buildCratesLib {
    name = "handlers";
    version = "0.7.0";
    hash = "3dd302d6bfb4ec5c848af6b4f423de01294fb5ebda1ec3cc0af53df849dd9617";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_6" = handlers_0_6_0;
  handlers_0_7_1 = buildCratesLib {
    name = "handlers";
    version = "0.7.1";
    hash = "15021fedc86d55f861cd9bc92530f1881cb77e6e5071f4260f0424ab5808ec7b";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  handlers_0_8_0 = buildCratesLib {
    name = "handlers";
    version = "0.8.0";
    hash = "b2f9e3cdd5618c987fb2bfa8fc999af3879e05536cddcfbee301f31c7e316c82";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 ];
  };
  "handlers_0_7" = handlers_0_7_1;
  handlers_0_9_0 = buildCratesLib {
    name = "handlers";
    version = "0.9.0";
    hash = "a3bf5ccd58e633aede695df3e2f6db7806ddea13031c0b22cda7db93ba85bc04";
    deps = with allCrates; [  all__interpolate_idents.interpolate_idents_0_0_10 ];
  };
  "handlers_0_8" = handlers_0_8_0;
  "handlers_0_9" = handlers_0_9_0;
  "handlers_0" = handlers_0_9_0;}