#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  enclave-interface_0_1_0 = buildCratesLib {
    name = "enclave-interface";
    version = "0.1.0";
    hash = "0dd4de8e4d328edb443ca5c3f308812bae84267f92dd55ec482b679591b2d694";
    deps = with allCrates; [  all__sgx-isa.sgx-isa_0_1 all__libc.libc_0_2 all__lazy_static.lazy_static_0_2 all__sgxs.sgxs_0_4 ];
  };
  enclave-interface_0_1_1 = buildCratesLib {
    name = "enclave-interface";
    version = "0.1.1";
    hash = "34e993197abc83976cf8b5977c9db697b930da6644e919c6ad3dac7ced45f006";
    deps = with allCrates; [  all__libc.libc_0_2 all__lazy_static.lazy_static_0_2 all__sgx-isa.sgx-isa_0_1 all__sgxs.sgxs_0_5 ];
  };
  "enclave-interface_0_1" = enclave-interface_0_1_1;
  "enclave-interface_0" = enclave-interface_0_1_1;}