#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ndn_0_0_0 = buildCratesLib {
    name = "ndn";
    version = "0.0.0";
    hash = "0114b025898123f0b5170892333fa6949c426d98c1fd35410c92bc1910167763";
    deps = with allCrates; [  ];
  };
  "ndn_0_0" = ndn_0_0_0;
  "ndn_0" = ndn_0_0_0;}