#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cathulhu_0_1_1 = buildCratesLib {
    name = "cathulhu";
    version = "0.1.1";
    hash = "3a22cbcb410a3f55abd6d1a96d9f8aae44fedc7cffe59a8d0d2c4c81b4d273ff";
    deps = with allCrates; [  all__clap.clap_2 all__hyper.hyper_0_9 all__hubcaps.hubcaps_0_2 ];
  };
  "cathulhu_0_1" = cathulhu_0_1_1;
  "cathulhu_0" = cathulhu_0_1_1;}