#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  debugln_0_0_1 = buildCratesLib {
    name = "debugln";
    version = "0.0.1";
    hash = "ad7ffcec72d0ff8ec23a63be1cd609603844b8b296a1e1f9c3f6c61d88c9e8a9";
    deps = with allCrates; [  ];
  };
  "debugln_0_0" = debugln_0_0_1;
  "debugln_0" = debugln_0_0_1;}