#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  imag_0_0_0 = buildCratesLib {
    name = "imag";
    version = "0.0.0";
    hash = "34e676ce0b467321f5fb7f19b489cdea191212b22db6937430065bc1f1fd8e25";
    deps = with allCrates; [  ];
  };
  imag_0_2_0 = buildCratesLib {
    name = "imag";
    version = "0.2.0";
    hash = "7c39d17554ee6411f75f2f7c3e47fee0e6df4cc17e59446bc97942c820c98304";
    deps = with allCrates; [  all__libimagerror.libimagerror_0_2 all__libimagrt.libimagrt_0_2 all__crossbeam.crossbeam_0_2 all__version.version_2_0 all__log.log_0_3 all__walkdir.walkdir_0_1 clap ];
  };
  "imag_0_0" = imag_0_0_0;
  "imag_0_2" = imag_0_2_0;
  "imag_0" = imag_0_2_0;}