#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  swagger_to_md_1_0_0 = buildCratesLib {
    name = "swagger_to_md";
    version = "1.0.0";
    hash = "7c935e8ecb1d218d7323aaf990b5c1747e7acf5435bcfae595a05f2aaea49ac2";
    deps = with allCrates; [  all__serde_macros.serde_macros_0_6 all__serde.serde_0_6 all__getopts.getopts_0_2 all__serde_json.serde_json_0_6 ];
  };
  "swagger_to_md_1_0" = swagger_to_md_1_0_0;
  "swagger_to_md_1" = swagger_to_md_1_0_0;}