#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  dual_quaternion_0_1_0 = buildCratesLib {
    name = "dual_quaternion";
    version = "0.1.0";
    hash = "f89dab3d9465bbb09283d38417f912722fb9e57c12dc141391a138f65d1cae75";
    deps = with allCrates; [ vecmath quaternion ];
  };}