#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  muldiv_0_1_0 = buildCratesLib {
    name = "muldiv";
    version = "0.1.0";
    hash = "1b7c26debeb36df2cba1d9bd0ea3ae41c66cd623baa1dba5d8cbe0aa73a4bed9";
    deps = with allCrates; [ ];
  };}