#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  scoped_log_0_1_0 = buildCratesLib {
    name = "scoped_log";
    version = "0.1.0";
    hash = "f784e86664cf1d1f3c6ce348ecf73f01bd6a7690538356bff8297505f2da026e";
    deps = with allCrates; [ log ];
  };}