#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  units_0_0_1 = buildCratesLib {
    name = "units";
    version = "0.0.1";
    hash = "39f04bb3c833ca5b932eb0e62d0c60dea265855a64f32492f5625094625c2c4c";
    deps = with allCrates; [ tylar ];
  };
  units_0_0_2 = buildCratesLib {
    name = "units";
    version = "0.0.2";
    hash = "a6e60925385c66052ffb960bab3de4ede8c2c0eabedb16f55c9ee0e573c6f571";
    deps = with allCrates; [ tylar ];
  };
  units_0_1_0 = buildCratesLib {
    name = "units";
    version = "0.1.0";
    hash = "bae6cad1565a50ee44804ad412e44aef37f579fd12740a806d0dae616e9266a3";
    deps = with allCrates; [ tylar ];
  };}