#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  sketchy_0_0_1 = buildCratesLib {
    name = "sketchy";
    version = "0.0.1";
    hash = "321a3ecaff0940e155af2ea56555af0d7483cb6ab31544c9980037f4e07ed9f4";
    deps = with allCrates; [ ];
  };}