#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  llvm-alt-sys_0_1_4 = buildCratesLib {
    name = "llvm-alt-sys";
    version = "0.1.4";
    hash = "db61b8f8cbf2dcc4821365acecbf4f5061007e0cdb9bac486288b3f071ae4802";
    deps = with allCrates; [ bitflags libc glob semver ];
  };}