#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  obj_0_0_2 = buildCratesLib {
    name = "obj";
    version = "0.0.2";
    hash = "649383b5cc09f5ad0d6030bc4286052bb720cdd29d6a60c531794cbf572d47e6";
    deps = with allCrates; [  all__genmesh.genmesh_0_0 ];
  };
  obj_0_0_3 = buildCratesLib {
    name = "obj";
    version = "0.0.3";
    hash = "059ea222cf221cfa6ddda37d1e790f16555aa3a49e34a8bc150f9da1761ea147";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_0_4 = buildCratesLib {
    name = "obj";
    version = "0.0.4";
    hash = "eeaf1b042191b4a4c598b6a6922257907178e7133f98b4bc1470bb790d36f11d";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_0_5 = buildCratesLib {
    name = "obj";
    version = "0.0.5";
    hash = "4ca0b4e0e680e0ad2d56dc13c27a8061d25e5d3708661fe70ad694b5199a4d33";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_0_6 = buildCratesLib {
    name = "obj";
    version = "0.0.6";
    hash = "f5fa2bc96168adffe20d874163cd40ba39357af86831de39f0b0030c89c6d834";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_0_7 = buildCratesLib {
    name = "obj";
    version = "0.0.7";
    hash = "7e730042520fab4dc9866e539f51f1e294aeaa0bb63e106c7ab08ba86110eb1a";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_0_8 = buildCratesLib {
    name = "obj";
    version = "0.0.8";
    hash = "0a564379ac190ba47fbbbde59bd75ad38d7c92e197dbb9f288e2870bcda8b7fb";
    deps = with allCrates; [  all__genmesh.genmesh_0_0_10 ];
  };
  obj_0_0_9 = buildCratesLib {
    name = "obj";
    version = "0.0.9";
    hash = "6831acad4b18a7f8e8bc3c161c9a49f86840b7b6acddbed5617683298c4daa43";
    deps = with allCrates; [  all__genmesh.genmesh_0_0_11 ];
  };
  obj_0_0_10 = buildCratesLib {
    name = "obj";
    version = "0.0.10";
    hash = "2d9f0124ac44a592870909348ce05322687c936540ce630b7505a7acc59f0c0b";
    deps = with allCrates; [  all__genmesh.genmesh_0_0_12 ];
  };
  obj_0_0_11 = buildCratesLib {
    name = "obj";
    version = "0.0.11";
    hash = "abb6fd0e529deb7e86d8c536cd28767722ebca351554f399983c5c181824f0c7";
    deps = with allCrates; [  all__genmesh.genmesh_0_0_13 ];
  };
  obj_0_1_0 = buildCratesLib {
    name = "obj";
    version = "0.1.0";
    hash = "68421fa89543919ac302d9019979779b1437cc0fa3bdb07d1913f3dc98e7b800";
    deps = with allCrates; [  genmesh ];
  };
  "obj_0_0" = obj_0_0_11;
  obj_0_1_1 = buildCratesLib {
    name = "obj";
    version = "0.1.1";
    hash = "482c22f78eff07e8db8130ea13bb2124178aab67a1796240975cad1d47e8e56b";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_1_2 = buildCratesLib {
    name = "obj";
    version = "0.1.2";
    hash = "028db88a202f41f5161677786b87760906465f300c6502d580cd1148d4a24350";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_2_0 = buildCratesLib {
    name = "obj";
    version = "0.2.0";
    hash = "881d8bf7a1bdcd0447fa119a6f092d071ff52b1fea47a5e21d71dde0f66e4ed3";
    deps = with allCrates; [  genmesh ];
  };
  "obj_0_1" = obj_0_1_2;
  obj_0_2_1 = buildCratesLib {
    name = "obj";
    version = "0.2.1";
    hash = "f549b3ecfeb06055b41b260f7941cca51ab4b4956eb247f517165b6c20f0f608";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_2_2 = buildCratesLib {
    name = "obj";
    version = "0.2.2";
    hash = "c67c5ee81aea7b8dd89dcfbfdc65e01d9845c9d7e8596965e1d8cd3d048ac5b2";
    deps = with allCrates; [  genmesh ];
  };
  obj_0_3_0 = buildCratesLib {
    name = "obj";
    version = "0.3.0";
    hash = "33c8fe492f4f3f9fbdc5da1a8338f3dd6c195cf6ae7f17dc36cb7150014c703c";
    deps = with allCrates; [  genmesh ];
  };
  "obj_0_2" = obj_0_2_2;
  obj_0_4_0 = buildCratesLib {
    name = "obj";
    version = "0.4.0";
    hash = "e1eb1eadb115e6eb3bf1ae1032de46dd377bfc4eb71065797a66bba19ab1fc7a";
    deps = with allCrates; [  ];
  };
  "obj_0_3" = obj_0_3_0;
  obj_0_5_0 = buildCratesLib {
    name = "obj";
    version = "0.5.0";
    hash = "02321812fe1f05349beba904c0c0533bbc5fdbca16c0c8c5f401c93b3e5d895e";
    deps = with allCrates; [  ];
  };
  "obj_0_4" = obj_0_4_0;
  "obj_0_5" = obj_0_5_0;
  "obj_0" = obj_0_5_0;}