#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  opc_0_1_0 = buildCratesLib {
    name = "opc";
    version = "0.1.0";
    hash = "8a8514a70729c0f2fc0d1b33d46c78f1084f43c9588c7d6bef8caeecf854fe14";
    deps = with allCrates; [ byteorder ];
  };
  opc_0_1_1 = buildCratesLib {
    name = "opc";
    version = "0.1.1";
    hash = "9aa73b1b9c6d26b5f8ec47d4a3abd0e7b82150679864e992249bd4a489419ca5";
    deps = with allCrates; [ byteorder ];
  };}