#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  orf_0_1_0 = buildCratesLib {
    name = "orf";
    version = "0.1.0";
    hash = "e18fac72456288a6a485381c317de1b81e872bd17e41102474e6f3df589eaa28";
    deps = with allCrates; [ monster num_cpus phf memmap phf_macros scoped_threadpool nom ];
  };}