#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  msctfmonitor-sys_0_0_1 = buildCratesLib {
    name = "msctfmonitor-sys";
    version = "0.0.1";
    hash = "7a711e626f3457afb62e5fd9a2ce7edeb96c8282c8ef73c9cbae90eca1af86da";
    deps = with allCrates; [ winapi ];
  };}