#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cobalt_0_1_0 = buildCratesLib {
    name = "cobalt";
    version = "0.1.0";
    hash = "0c0c5e1612c4c1f2c9a9264888d9a21774dbef897cf6e10751a413021083a84a";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_1_1 = buildCratesLib {
    name = "cobalt";
    version = "0.1.1";
    hash = "6ec60a55bcfe93eceb74523114d7d1d347bf76d51c3500636e6f7c1049214602";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_2_0 = buildCratesLib {
    name = "cobalt";
    version = "0.2.0";
    hash = "d381d5888b226370ba139a1c9f50999b6269d8f50aa318ee321f8e5345a5dce3";
    deps = with allCrates; [ clock_ticks rand ];
  };
  cobalt_0_3_0 = buildCratesLib {
    name = "cobalt";
    version = "0.3.0";
    hash = "8dde45ca49549c5fb07d7ee206330220979cf993bd9da71fd72b74744c90fbe5";
    deps = with allCrates; [ clock_ticks rand ];
  };
  cobalt_0_4_0 = buildCratesLib {
    name = "cobalt";
    version = "0.4.0";
    hash = "76ba93f5674dbe45c89d9b078c810d885137cb55ef2390a55082bfdf867ac304";
    deps = with allCrates; [ clock_ticks rand ];
  };
  cobalt_0_5_0 = buildCratesLib {
    name = "cobalt";
    version = "0.5.0";
    hash = "10373fc40b795f50aa21a30e527c94ed9b54bd0ebd438078338f126e11bcd209";
    deps = with allCrates; [ clock_ticks rand ];
  };
  cobalt_0_5_1 = buildCratesLib {
    name = "cobalt";
    version = "0.5.1";
    hash = "a54d7d3de11ecbd558c2c8b0b04d92595e1bf6fa85f7e6b7fb0540be4ef0f8bb";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_5_2 = buildCratesLib {
    name = "cobalt";
    version = "0.5.2";
    hash = "e43cb7a825683d4892b705c8c74f9f2137d375d69c16a4aa871a854da2c8fe53";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_5_3 = buildCratesLib {
    name = "cobalt";
    version = "0.5.3";
    hash = "d155aa5259a9efc751d320e8f55afc40635bf38a0e6dc11fda168adff4b5b5d3";
    deps = with allCrates; [ clock_ticks rand ];
  };
  cobalt_0_7_0 = buildCratesLib {
    name = "cobalt";
    version = "0.7.0";
    hash = "97bf01dc5621fe7b793cd5cfd042f018d85d36bcac821a0b3a3d543b83a26ca9";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_8_0 = buildCratesLib {
    name = "cobalt";
    version = "0.8.0";
    hash = "d4b015dbfbd570f32549c67fa9a822ae947846f03bf5c3ca4a2045775fd36238";
    deps = with allCrates; [ clock_ticks rand ];
  };
  cobalt_0_8_1 = buildCratesLib {
    name = "cobalt";
    version = "0.8.1";
    hash = "e5a17f2d4a6dd33d21d8b0d45ccb274d8f2e6520d1c07729a75f605b9d3cb7e5";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_10_0 = buildCratesLib {
    name = "cobalt";
    version = "0.10.0";
    hash = "8337f7cebf46b6dad0308519b09eebee43a1ba401069e50b2b833e62dfc9e695";
    deps = with allCrates; [ rand clock_ticks ];
  };
  cobalt_0_11_0 = buildCratesLib {
    name = "cobalt";
    version = "0.11.0";
    hash = "a60c24ddd1567c771d59d2f0e4cc360a1435986a42614468dd489f7b1047e99c";
    deps = with allCrates; [ rand clock_ticks ];
  };}