#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  derive_rand_0_1_1 = buildCratesLib {
    name = "derive_rand";
    version = "0.1.1";
    hash = "17a16fff6a061acbe00aefa1ae45ed9410f7726bad2223300f7c46d91d6da3c5";
    deps = with allCrates; [  ];
  };
  "derive_rand_0_1" = derive_rand_0_1_1;
  "derive_rand_0" = derive_rand_0_1_1;}