#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  derive_from_0_1_1 = buildCratesLib {
    name = "derive_from";
    version = "0.1.1";
    hash = "eae1831cc9a58bd9e5521937d09daad11f2da8c84ecc49ab7355b7fab56c787a";
    deps = with allCrates; [ ];
  };}