#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  etherdream_0_0_2 = buildCratesLib {
    name = "etherdream";
    version = "0.0.2";
    hash = "35f3ac43b691f8f4965fbd4cdb0a9e4a5dcdb92327b86db80e1a19e00648e4ed";
    deps = with allCrates; [  all__ilda.ilda_0_0_2 byteorder net2 log ];
  };
  etherdream_0_0_3 = buildCratesLib {
    name = "etherdream";
    version = "0.0.3";
    hash = "c452f1907939ee638d5927886f091bff9fb043ebd343f6045e90e672282efa65";
    deps = with allCrates; [  all__ilda.ilda_0_0_2 byteorder net2 log ];
  };
  "etherdream_0_0" = etherdream_0_0_3;
  "etherdream_0" = etherdream_0_0_3;}