#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  ferris_0_1_0 = buildCratesLib {
    name = "ferris";
    version = "0.1.0";
    hash = "d98957aeaf6ccb8d7039c9e399654222d351ccde4b6b50184a0a9e33696ed628";
    deps = with allCrates; [ time ];
  };
  ferris_0_1_1 = buildCratesLib {
    name = "ferris";
    version = "0.1.1";
    hash = "4d3a065de76ec3693f497af0043fa8f0d753b3fae8ff2b7837587d7e015f1df8";
    deps = with allCrates; [ time ];
  };}