#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  gluon_language-server_0_1_0 = buildCratesLib {
    name = "gluon_language-server";
    version = "0.1.0";
    hash = "afa10b199b67a77cb1b269a9e2540fe791494d33ce328b790b4fae181ac75c07";
    deps = with allCrates; [  all__serde_json.serde_json_0_7 all__gluon.gluon_0_1 all__env_logger.env_logger_0_3 all__log.log_0_3 all__serde.serde_0_7 all__jsonrpc-core.jsonrpc-core_2_0_7 ];
  };
  gluon_language-server_0_1_1 = buildCratesLib {
    name = "gluon_language-server";
    version = "0.1.1";
    hash = "df4b88c275ee38eb8392776bd435152efd1c0499aecb8b511b27b0c36304ba11";
    deps = with allCrates; [  all__log.log_0_3 all__jsonrpc-core.jsonrpc-core_2_0_7 all__serde_json.serde_json_0_7 all__gluon.gluon_0_1 all__serde.serde_0_7 all__env_logger.env_logger_0_3 ];
  };
  gluon_language-server_0_2_0 = buildCratesLib {
    name = "gluon_language-server";
    version = "0.2.0";
    hash = "3c73b27f0430addac9e933c582760ea25bfe32d620ce909a6f73215cc5a470ee";
    deps = with allCrates; [  all__languageserver-types.languageserver-types_0_4 all__serde.serde_0_8 all__env_logger.env_logger_0_3 all__serde_json.serde_json_0_8 all__gluon.gluon_0_2 all__log.log_0_3 all__jsonrpc-core.jsonrpc-core_3_0_0 all__url.url_1_2 ];
  };
  "gluon_language-server_0_1" = gluon_language-server_0_1_1;
  "gluon_language-server_0_2" = gluon_language-server_0_2_0;
  "gluon_language-server_0" = gluon_language-server_0_2_0;}