#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  item_0_1_0 = buildCratesLib {
    name = "item";
    version = "0.1.0";
    hash = "909dbf8cd674b0eb60779847fc0a5f50712ed9cc8575422086b767bf803b9ee7";
    deps = with allCrates; [  all__nom.nom_1_2 ];
  };
  item_0_2_0 = buildCratesLib {
    name = "item";
    version = "0.2.0";
    hash = "0d0693ab932dc909f01514d0b127f8b0f003cc2c2614148032a0207f5f02baa5";
    deps = with allCrates; [  all__nom.nom_1_2 ];
  };
  "item_0_1" = item_0_1_0;
  item_0_3_0 = buildCratesLib {
    name = "item";
    version = "0.3.0";
    hash = "d67414761827fe52327ffbcfe07cd5fe78bedd13b3fd402d7ff814bb7f665fe2";
    deps = with allCrates; [  ];
  };
  "item_0_2" = item_0_2_0;
  item_0_3_1 = buildCratesLib {
    name = "item";
    version = "0.3.1";
    hash = "12cd68ce6d2f4479da877b5dfc623f8b28c584d38931056b250bd9b86c979466";
    deps = with allCrates; [  ];
  };
  item_0_3_2 = buildCratesLib {
    name = "item";
    version = "0.3.2";
    hash = "d6cf4f91d433773b843e97c0cffc849860e2e9723b6a4d2530de1e05a8ca85e6";
    deps = with allCrates; [  ];
  };
  "item_0_3" = item_0_3_2;
  "item_0" = item_0_3_2;}