#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  munkres_0_0_1 = buildCratesLib {
    name = "munkres";
    version = "0.0.1";
    hash = "fad45d2c2e6eb14730aba5f0a70f79a0f31ca26412178a649ed45ca13d6b8a39";
    deps = with allCrates; [ bit-vec ];
  };
  munkres_0_0_2 = buildCratesLib {
    name = "munkres";
    version = "0.0.2";
    hash = "3a93eeb55838c10a1c9f5075673f60a07cf8a444033d42404475c75c92f97244";
    deps = with allCrates; [ bit-vec ];
  };
  munkres_0_1_0 = buildCratesLib {
    name = "munkres";
    version = "0.1.0";
    hash = "6e430766f2db30b72add178ef4526d08fdf3fe3bb62834ce02f4b09b9225b025";
    deps = with allCrates; [ fixedbitset ];
  };
  munkres_0_2_0 = buildCratesLib {
    name = "munkres";
    version = "0.2.0";
    hash = "a066da6b0b885354038ad6d9c49c9da88b0336f9e38d7d94e1f6cd221523af47";
    deps = with allCrates; [ fixedbitset ];
  };
  munkres_0_3_0 = buildCratesLib {
    name = "munkres";
    version = "0.3.0";
    hash = "84ca023813adf830e2537250f471f9928ff581527fe87d08a641f68b1b46c3e7";
    deps = with allCrates; [ fixedbitset ];
  };}