#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  prexcl_0_0_1 = buildCratesLib {
    name = "prexcl";
    version = "0.0.1";
    hash = "566a37409b1dc889209f78a03af598c0a6401d8873c2e37a60064d0a5890c0be";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_2 = buildCratesLib {
    name = "prexcl";
    version = "0.0.2";
    hash = "dceb1bba7520011491c9b3b4c7f1aac10989cb762f48817a9dda5dd12a9d6ba6";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_3 = buildCratesLib {
    name = "prexcl";
    version = "0.0.3";
    hash = "4066979255fd56cbbda5706d265e4111dd0f97c9ab4f9edd34bba5ecef41a23b";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_4 = buildCratesLib {
    name = "prexcl";
    version = "0.0.4";
    hash = "2bfd659fb0e00ab34f6bdd02781b58a2f0b6e023f482cf3a571e192fb1beea3d";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_5 = buildCratesLib {
    name = "prexcl";
    version = "0.0.5";
    hash = "59b3ab7de15db12341fd33dbd661574d2a8a2fcd62d7bc470e7d9dc510a2228f";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_6 = buildCratesLib {
    name = "prexcl";
    version = "0.0.6";
    hash = "26eda9feab21adeeac309f1bfe6dd21c47aa5c65e22a70c58f929036b4b7eb03";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_7 = buildCratesLib {
    name = "prexcl";
    version = "0.0.7";
    hash = "1ea16efb26482ea6ca9f8614652b5296ab47fea23f2f0db9a6681308e517b15d";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_8 = buildCratesLib {
    name = "prexcl";
    version = "0.0.8";
    hash = "fd2f95bac7c0556ade63cff062fe20dd4af4322b91a3f49edd60513ac804b912";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_9 = buildCratesLib {
    name = "prexcl";
    version = "0.0.9";
    hash = "38eda6e8a85edfeb0dd87fb1160de14c2ee3d48d62e14ef424a74989ec957f6c";
    deps = with allCrates; [  ];
  };
  prexcl_0_0_10 = buildCratesLib {
    name = "prexcl";
    version = "0.0.10";
    hash = "e170b97f30e769064c0cc5f99b84bcdbcfd4a14ff51120dedc03be577eac34f4";
    deps = with allCrates; [  ];
  };
  "prexcl_0_0" = prexcl_0_0_10;
  "prexcl_0" = prexcl_0_0_10;}