#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  sapi-sys_0_0_1 = buildCratesLib {
    name = "sapi-sys";
    version = "0.0.1";
    hash = "6259e71ea278065a7eb031ec84ca6a65ef65a6745523bc482f141aec4c542adf";
    deps = with allCrates; [  winapi ];
  };
  "sapi-sys_0_0" = sapi-sys_0_0_1;
  "sapi-sys_0" = sapi-sys_0_0_1;}