#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  gurobi_0_1_0 = buildCratesLib {
    name = "gurobi";
    version = "0.1.0";
    hash = "107f414178b9654372899f0f49d85ced81525231d8dda02ff1605d9761111c98";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_1 = buildCratesLib {
    name = "gurobi";
    version = "0.1.1";
    hash = "777ca5724acf10f68ce4e5eb9c3d496d9d75b3e2e89c32f624fd9ca2492085f1";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_2 = buildCratesLib {
    name = "gurobi";
    version = "0.1.2";
    hash = "2c144818b4a6d3e5d160c0b2c5685e1249e85beed353f282ae06c0b04331656c";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_3 = buildCratesLib {
    name = "gurobi";
    version = "0.1.3";
    hash = "2345c363bb17f30e7b835effbfbbdf592b33da93e5aa3e717f7da41affaa0450";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_4 = buildCratesLib {
    name = "gurobi";
    version = "0.1.4";
    hash = "061f7b7e892203dae3eb24954ad992703a261b034ff6a3411eb279c36bacbfa9";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_5 = buildCratesLib {
    name = "gurobi";
    version = "0.1.5";
    hash = "9d6d477bdc1c1a02f9202c0f9f62ae03a1f07e0900d2203d7e1672e2c57f04cb";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_6 = buildCratesLib {
    name = "gurobi";
    version = "0.1.6";
    hash = "efbc1928877ae02b27c63498bf65941119146f58f7ee01165ab08220349abcb9";
    deps = with allCrates; [ gurobi-sys ];
  };
  gurobi_0_1_7 = buildCratesLib {
    name = "gurobi";
    version = "0.1.7";
    hash = "e1d920b2980332809aab2f983ff264579cb85fb720c14831a70f2ea4cbb262d7";
    deps = with allCrates; [ gurobi-sys itertools ];
  };
  gurobi_0_1_8 = buildCratesLib {
    name = "gurobi";
    version = "0.1.8";
    hash = "17d3a20d971326d84c19977ef4193fe3bfc36e53903be1899c50cff8639a530d";
    deps = with allCrates; [ gurobi-sys itertools ];
  };
  gurobi_0_2_0 = buildCratesLib {
    name = "gurobi";
    version = "0.2.0";
    hash = "0256b034d92ac6cfed0160880e20cb93c55d2355c0043745d1a7481e65ad3f74";
    deps = with allCrates; [ itertools gurobi-sys ];
  };
  gurobi_0_3_0 = buildCratesLib {
    name = "gurobi";
    version = "0.3.0";
    hash = "376076921077076edb80ed01f6e956e759c833b30fb475a1b27c2500f1e38993";
    deps = with allCrates; [ itertools gurobi-sys ];
  };
  gurobi_0_3_1 = buildCratesLib {
    name = "gurobi";
    version = "0.3.1";
    hash = "9bec0bdcba5da95a31725254b3c0e36786125e07f9cd415e60272f1f81a2fcee";
    deps = with allCrates; [ gurobi-sys itertools ];
  };
  gurobi_0_3_2 = buildCratesLib {
    name = "gurobi";
    version = "0.3.2";
    hash = "2a0b590fe1ba58f8e7a607bde974183b1a69a96a0f01144c20cb3109d604bf69";
    deps = with allCrates; [ gurobi-sys itertools ];
  };}