#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  metl_0_0_0 = buildCratesLib {
    name = "metl";
    version = "0.0.0";
    hash = "6b82734905940ab721e65bef50ca2536f03859b36d928dddb2404917f00bf1bb";
    deps = with allCrates; [  all__cocoa.cocoa_0_2 all__objc.objc_0_1 all__metal-sys.metal-sys_0_0_0 core-foundation ];
  };
  "metl_0_0" = metl_0_0_0;
  "metl_0" = metl_0_0_0;}