#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  lz4-rs_1_0_127 = buildCratesLib {
    name = "lz4-rs";
    version = "1.0.127";
    hash = "39ad1755a66067e6b0b28a826bfc9af77762fff6f4d7fedf62f3f23a5b8572ed";
    deps = with allCrates; [ gcc ];
  };}