#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  dbghelp-sys_0_0_1 = buildCratesLib {
    name = "dbghelp-sys";
    version = "0.0.1";
    hash = "ef38010e93d0c513777b72178b727cb0edd02391c5a120bfb914d06a0803f9c5";
    deps = with allCrates; [  winapi ];
  };
  dbghelp-sys_0_1_0 = buildCratesLib {
    name = "dbghelp-sys";
    version = "0.1.0";
    hash = "8c29c52d6930e720b7fc8343a6c9e084d71a51e609b4900c99408ae3a48533f0";
    deps = with allCrates; [  winapi winapi-build ];
  };
  "dbghelp-sys_0_0" = dbghelp-sys_0_0_1;
  dbghelp-sys_0_2_0 = buildCratesLib {
    name = "dbghelp-sys";
    version = "0.2.0";
    hash = "97590ba53bcb8ac28279161ca943a924d1fd4a8fb3fa63302591647c4fc5b850";
    deps = with allCrates; [  all__winapi.winapi_0_2 all__winapi-build.winapi-build_0_1 ];
  };
  "dbghelp-sys_0_1" = dbghelp-sys_0_1_0;
  "dbghelp-sys_0_2" = dbghelp-sys_0_2_0;
  "dbghelp-sys_0" = dbghelp-sys_0_2_0;}