#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  getch_0_1_0 = buildCratesLib {
    name = "getch";
    version = "0.1.0";
    hash = "a93cbd0aeacaf4c75ed215b1415e2678cb599845a54e3c04b69ad0a1ae1d1346";
    deps = with allCrates; [ termios ];
  };}