#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cryptsetup_0_1_0 = buildCratesLib {
    name = "cryptsetup";
    version = "0.1.0";
    hash = "bb48612d2a50b8563a5ef67306fdc58ca0a9196f8dbfd974301defbc7cf8fd70";
    deps = with allCrates; [  all__bitflags.bitflags_0_7 all__libc.libc_0_2 all__nix.nix_0_6 ];
  };
  cryptsetup_0_2_0 = buildCratesLib {
    name = "cryptsetup";
    version = "0.2.0";
    hash = "24a85deb606cea50a8753940f384149ca6564c0f741185bc8bc33052acd27dd4";
    deps = with allCrates; [  all__nix.nix_0_6 all__bitflags.bitflags_0_7 all__libc.libc_0_2 ];
  };
  "cryptsetup_0_1" = cryptsetup_0_1_0;
  "cryptsetup_0_2" = cryptsetup_0_2_0;
  "cryptsetup_0" = cryptsetup_0_2_0;}