#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  websocket_0_1_0 = buildCratesLib {
    name = "websocket";
    version = "0.1.0";
    hash = "ebc006ef1cbaa7b7ebf291f56865db095db62e44f79c60f22c7bc3677c5cfcc2";
    deps = with allCrates; [  ];
  };
  websocket_0_2_0 = buildCratesLib {
    name = "websocket";
    version = "0.2.0";
    hash = "ae2ffa2b3239ca9ffc108ca170870ba4388e1750c1d909fcc99994be253024be";
    deps = with allCrates; [  all__url.url_0_2 ];
  };
  "websocket_0_1" = websocket_0_1_0;
  websocket_0_2_1 = buildCratesLib {
    name = "websocket";
    version = "0.2.1";
    hash = "e11c76fde1177736cca204027671a5ee8d55180af940c9904221b6c9277da7f2";
    deps = with allCrates; [  all__url.url_0_2 ];
  };
  websocket_0_3_0 = buildCratesLib {
    name = "websocket";
    version = "0.3.0";
    hash = "cc1488555b6118a277bb17b6d3e1987dbdcc95de82e7758dbd745d2523fb78c3";
    deps = with allCrates; [  all__url.url_0_2 ];
  };
  "websocket_0_2" = websocket_0_2_1;
  websocket_0_3_1 = buildCratesLib {
    name = "websocket";
    version = "0.3.1";
    hash = "9288627ddfed5eb0608c6c1aa3c963046bbe19aa7a6047fb4153544cf35acd7b";
    deps = with allCrates; [  all__url.url_0_2 ];
  };
  websocket_0_4_0 = buildCratesLib {
    name = "websocket";
    version = "0.4.0";
    hash = "5dfcea30a85790b0db3381a86386d7fcc8c7c6fe79934703d9851fa7744d5439";
    deps = with allCrates; [  all__url.url_0_2 all__sha1.sha1_0_0 ];
  };
  "websocket_0_3" = websocket_0_3_1;
  websocket_0_4_1 = buildCratesLib {
    name = "websocket";
    version = "0.4.1";
    hash = "4959681825ad0c5949552a28e4ec914f49184d043b359cb83b0f27e2076eaac2";
    deps = with allCrates; [  all__url.url_0_2 all__sha1.sha1_0_0 ];
  };
  websocket_0_5_0 = buildCratesLib {
    name = "websocket";
    version = "0.5.0";
    hash = "8eecb0c40d2b02e2b460aa7c2d0e9c7465fce7c171c1adbbf8604ca0f5385de3";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  "websocket_0_4" = websocket_0_4_1;
  websocket_0_6_0 = buildCratesLib {
    name = "websocket";
    version = "0.6.0";
    hash = "2ddd62bc3c64a308c1e5929095b243f9f1deba8054ae8b0686625b4d757712ae";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  "websocket_0_5" = websocket_0_5_0;
  websocket_0_6_1 = buildCratesLib {
    name = "websocket";
    version = "0.6.1";
    hash = "4f7f7edc3330a84baf2efd207d97e141f1f8d79846cde355637bc3f501b72003";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  websocket_0_7_0 = buildCratesLib {
    name = "websocket";
    version = "0.7.0";
    hash = "280d359b60b3c014b7251b28e167c0d1ef47b56043c0c4912948790cd654b499";
    deps = with allCrates; [  all__url.url_0_2 all__sha1.sha1_0_0 ];
  };
  "websocket_0_6" = websocket_0_6_1;
  websocket_0_7_1 = buildCratesLib {
    name = "websocket";
    version = "0.7.1";
    hash = "dde3b9e9df96b0ab05bf1c25b9dba2aa570b09ff410d023be067ede2b8b950b4";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  websocket_0_8_0 = buildCratesLib {
    name = "websocket";
    version = "0.8.0";
    hash = "282b4a3f9198c01dbf43b89d5a8079d32aa25746525c616425fdc5179fbbec7d";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  "websocket_0_7" = websocket_0_7_1;
  websocket_0_8_1 = buildCratesLib {
    name = "websocket";
    version = "0.8.1";
    hash = "91bc637ef635a181efe5f98fa0d28ffec4bad393348b1a5992f0cf53a4297f12";
    deps = with allCrates; [  all__url.url_0_2 all__sha1.sha1_0_0 ];
  };
  websocket_0_8_2 = buildCratesLib {
    name = "websocket";
    version = "0.8.2";
    hash = "936b8eba6b15bc66d6546fd528290f3eb7aa09663950af53830591f5a1b0d756";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  websocket_0_9_0 = buildCratesLib {
    name = "websocket";
    version = "0.9.0";
    hash = "2874cf4a9b551fac20c5a71d1b580fdb7d2ea7111cc24bdf6d1193af21b830db";
    deps = with allCrates; [  all__openssl.openssl_0_2 all__rustc-serialize.rustc-serialize_0_1 all__sha1.sha1_0_0 all__url.url_0_2 all__hyper.hyper_0_0 ];
  };
  "websocket_0_8" = websocket_0_8_2;
  websocket_0_9_1 = buildCratesLib {
    name = "websocket";
    version = "0.9.1";
    hash = "6e653bcc6bbec64fd73c4660527658f0588bf364db1e040e715bbac8c5754cc7";
    deps = with allCrates; [  all__hyper.hyper_0_0 all__url.url_0_2 all__openssl.openssl_0_2 all__sha1.sha1_0_0 all__rustc-serialize.rustc-serialize_0_1 ];
  };
  websocket_0_9_2 = buildCratesLib {
    name = "websocket";
    version = "0.9.2";
    hash = "002015f9a5243fd7c3651db474a03aa71522b651b72da68f927fb2d9e19f371b";
    deps = with allCrates; [  all__sha1.sha1_0_0 all__hyper.hyper_0_0 all__url.url_0_2 all__openssl.openssl_0_2 all__rustc-serialize.rustc-serialize_0_1 ];
  };
  websocket_0_9_3 = buildCratesLib {
    name = "websocket";
    version = "0.9.3";
    hash = "2ca6b9c3f5e284a89b82a2fd44a170318615e97793cabe9fd919d02f083eb380";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_1 all__sha1.sha1_0_0 all__url.url_0_2 all__hyper.hyper_0_0 all__openssl.openssl_0_2 ];
  };
  websocket_0_9_4 = buildCratesLib {
    name = "websocket";
    version = "0.9.4";
    hash = "3de79f5ab6a7b29ecce2456bfe5aa0517ab6ec2514dfbca93ae1c92ecb74e76f";
    deps = with allCrates; [  all__hyper.hyper_0_0 all__rustc-serialize.rustc-serialize_0_1 all__openssl.openssl_0_2 all__sha1.sha1_0_0 all__url.url_0_2 ];
  };
  websocket_0_9_5 = buildCratesLib {
    name = "websocket";
    version = "0.9.5";
    hash = "1f8b43a5cd718d383439cbf80202f84784fffb152a8718dcc1f87bc7d7a4186d";
    deps = with allCrates; [  rustc-serialize hyper sha1 url openssl ];
  };
  websocket_0_9_6 = buildCratesLib {
    name = "websocket";
    version = "0.9.6";
    hash = "a64f22dc099d2e628548c76f7bc1d062aaaeccc62e670190d31ec6277da4ff06";
    deps = with allCrates; [  sha1-hasher url openssl rustc-serialize hyper ];
  };
  websocket_0_9_7 = buildCratesLib {
    name = "websocket";
    version = "0.9.7";
    hash = "35bcfc5cf69fe5ff2aeef75b74e3f323c9bbb0979e1749dd43fdcee4be8206cb";
    deps = with allCrates; [  hyper rustc-serialize sha1-hasher url openssl ];
  };
  websocket_0_10_0 = buildCratesLib {
    name = "websocket";
    version = "0.10.0";
    hash = "d3dcc93f8154a0e2fb87af58bd411ab1d528d442bce77886deacdcb8b2a8ddb6";
    deps = with allCrates; [  hyper openssl url rustc-serialize bitflags ];
  };
  "websocket_0_9" = websocket_0_9_7;
  websocket_0_10_1 = buildCratesLib {
    name = "websocket";
    version = "0.10.1";
    hash = "f6a7b7ba87746c62b68d8b5a256fa99a6293540588d8d992fe9f04a753535f79";
    deps = with allCrates; [  hyper rustc-serialize bitflags url openssl ];
  };
  websocket_0_10_2 = buildCratesLib {
    name = "websocket";
    version = "0.10.2";
    hash = "8b1f731577a587cba2e1092503bd817320a5114504866b8f17297ea080a17df9";
    deps = with allCrates; [  url unicase bitflags hyper rustc-serialize openssl ];
  };
  websocket_0_10_3 = buildCratesLib {
    name = "websocket";
    version = "0.10.3";
    hash = "927fe96167195c6d475b4efec82d84cfb2764dfc171b7dce2c4834f1c9f8eb76";
    deps = with allCrates; [  unicase hyper bitflags openssl rustc-serialize url ];
  };
  websocket_0_10_4 = buildCratesLib {
    name = "websocket";
    version = "0.10.4";
    hash = "24443a11f35747a0e83c4c5acdb57c068bc5afbb49c3e0f4aaeb2176fbe1c153";
    deps = with allCrates; [  bitflags rustc-serialize url hyper unicase openssl ];
  };
  websocket_0_10_5 = buildCratesLib {
    name = "websocket";
    version = "0.10.5";
    hash = "f9041171a8aafa78ac8386a89da167e2f5c39c531e4a876ccfc754d1e9331d06";
    deps = with allCrates; [  rand unicase hyper bitflags openssl rustc-serialize url ];
  };
  websocket_0_11_0 = buildCratesLib {
    name = "websocket";
    version = "0.11.0";
    hash = "9ec78616d4c7876b31d21ae29785cdd3cd0edad9b675fa23fd67c85dc5803dd0";
    deps = with allCrates; [  unicase url byteorder rand openssl rustc-serialize hyper bitflags ];
  };
  "websocket_0_10" = websocket_0_10_5;
  websocket_0_11_2 = buildCratesLib {
    name = "websocket";
    version = "0.11.2";
    hash = "5b1336eae08d4377e764275999f5d619c65571476b167a55d339b049b91ed961";
    deps = with allCrates; [  bitflags rustc-serialize openssl unicase byteorder hyper rand url ];
  };
  websocket_0_11_3 = buildCratesLib {
    name = "websocket";
    version = "0.11.3";
    hash = "8ea46c772b3732951503bfa772021446d9110ad3b64fe469d5a28a821b810643";
    deps = with allCrates; [  bitflags url unicase openssl byteorder hyper rand rustc-serialize ];
  };
  websocket_0_11_4 = buildCratesLib {
    name = "websocket";
    version = "0.11.4";
    hash = "a7dd671f78b766e995ef90b16b7cb26f5de2eb8e1c4c0b2949abc8aa0b47ce95";
    deps = with allCrates; [  byteorder rand url hyper unicase bitflags openssl rustc-serialize ];
  };
  websocket_0_11_5 = buildCratesLib {
    name = "websocket";
    version = "0.11.5";
    hash = "62b5d1e1ce2585da452810f9b87dfea36fd803ba21657c0f0b9fd7961b9f4a2e";
    deps = with allCrates; [  hyper url openssl bitflags rand rustc-serialize unicase byteorder ];
  };
  websocket_0_11_6 = buildCratesLib {
    name = "websocket";
    version = "0.11.6";
    hash = "721f238d44dba00c220be3666beb4ba2e246183350cdcb7c742c48df547799f6";
    deps = with allCrates; [  bitflags openssl rand unicase byteorder rustc-serialize hyper url ];
  };
  websocket_0_11_7 = buildCratesLib {
    name = "websocket";
    version = "0.11.7";
    hash = "fecd038fe5ee22d0dadb27bea71567b70e6c6fafd829b4f55b04b6147b1ce673";
    deps = with allCrates; [  hyper rand rustc-serialize openssl bitflags url unicase byteorder ];
  };
  websocket_0_11_8 = buildCratesLib {
    name = "websocket";
    version = "0.11.8";
    hash = "79368ceb23e64dc6c9061a0e2ff1fa876d1e7d2bf62f24b99d813256a672acb9";
    deps = with allCrates; [  unicase rustc-serialize openssl bitflags hyper rand url byteorder ];
  };
  websocket_0_11_9 = buildCratesLib {
    name = "websocket";
    version = "0.11.9";
    hash = "e6d518709a0ec918d60928999787ac8226a753289ceeac8da122f41374d987ea";
    deps = with allCrates; [  rand unicase hyper url rustc-serialize bitflags openssl byteorder ];
  };
  websocket_0_11_10 = buildCratesLib {
    name = "websocket";
    version = "0.11.10";
    hash = "0b72e303024bbd3b23b0f6f4512916b23ee1cc546274f019d12d6192bec49a34";
    deps = with allCrates; [  rustc-serialize bitflags rand hyper unicase url byteorder openssl ];
  };
  websocket_0_11_11 = buildCratesLib {
    name = "websocket";
    version = "0.11.11";
    hash = "490c2951669a5f04ca8df019ede425163f4f57ccd9d866ba56e24f54dd84ded9";
    deps = with allCrates; [  rustc-serialize unicase openssl byteorder hyper bitflags url rand ];
  };
  websocket_0_12_0 = buildCratesLib {
    name = "websocket";
    version = "0.12.0";
    hash = "26debaab991809bb1ed9bd9e7d94444741fc1ae1cb30e34661095c6e711a6a3b";
    deps = with allCrates; [  unicase rustc-serialize url byteorder hyper openssl rand bitflags ];
  };
  "websocket_0_11" = websocket_0_11_11;
  websocket_0_12_1 = buildCratesLib {
    name = "websocket";
    version = "0.12.1";
    hash = "1990f115351690f35d267eba8c7ba3955f5e216eec62284df762e776328eecb6";
    deps = with allCrates; [  rustc-serialize byteorder hyper openssl rand bitflags unicase url ];
  };
  websocket_0_12_2 = buildCratesLib {
    name = "websocket";
    version = "0.12.2";
    hash = "e26e7e2edd78402a07fb0aa4ec79fe23ded64da3a97ce63509675a41ca1a2c9c";
    deps = with allCrates; [  openssl url unicase rand byteorder rustc-serialize bitflags hyper ];
  };
  websocket_0_13_0 = buildCratesLib {
    name = "websocket";
    version = "0.13.0";
    hash = "2aa184b6ef818aeb047332bd59ba233d7b6612336c0e14e1f5cc023686c503cb";
    deps = with allCrates; [  openssl byteorder hyper url rand unicase rustc-serialize bitflags net2 ];
  };
  "websocket_0_12" = websocket_0_12_2;
  websocket_0_13_1 = buildCratesLib {
    name = "websocket";
    version = "0.13.1";
    hash = "0323dacc578a0364d1eb5f900ebb4cc55d7eaa85e0fbb6011957dcf1f896e69e";
    deps = with allCrates; [  rand unicase bitflags openssl rustc-serialize byteorder url net2 hyper ];
  };
  websocket_0_13_2 = buildCratesLib {
    name = "websocket";
    version = "0.13.2";
    hash = "94c48cb21be608f1a44b37aec5549878974e405ee062f6f63de21f05584343d9";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__unicase.unicase_1_0_1 all__bitflags.bitflags_0_3 all__net2.net2_0_2 all__hyper.hyper_0_6 all__byteorder.byteorder_0_4 all__openssl.openssl_0_6 all__url.url_0_2 all__rand.rand_0_3 ];
  };
  websocket_0_14_0 = buildCratesLib {
    name = "websocket";
    version = "0.14.0";
    hash = "8cf415e2d6c0066abbe335158974f3ac006ef9e992ca75d6ecd6029a6bb20320";
    deps = with allCrates; [  all__net2.net2_0_2 all__rustc-serialize.rustc-serialize_0_3 all__bitflags.bitflags_0_3 all__rand.rand_0_3 all__unicase.unicase_1_0_1 all__openssl.openssl_0_7 all__hyper.hyper_0_7 all__byteorder.byteorder_0_4 all__url.url_0_5 ];
  };
  "websocket_0_13" = websocket_0_13_2;
  websocket_0_15_0 = buildCratesLib {
    name = "websocket";
    version = "0.15.0";
    hash = "07ecdd09bc407f2d5025eb3628d8fdfa7b1ae5a0363c99b74f757daff9871e66";
    deps = with allCrates; [  all__hyper.hyper_0_7 all__url.url_0_5 all__rand.rand_0_3 all__net2.net2_0_2 all__unicase.unicase_1_0_1 all__bitflags.bitflags_0_3 all__rustc-serialize.rustc-serialize_0_3 all__openssl.openssl_0_7 all__byteorder.byteorder_0_4 ];
  };
  "websocket_0_14" = websocket_0_14_0;
  websocket_0_15_1 = buildCratesLib {
    name = "websocket";
    version = "0.15.1";
    hash = "00e9b9654eb9e618d8a924be14ed1c6c8cc0a9a0c296bb1fa7e1c1e08e3dd3af";
    deps = with allCrates; [  all__net2.net2_0_2 all__url.url_0_5 all__hyper.hyper_0_7 all__openssl.openssl_0_7 all__unicase.unicase_1_0_1 all__rand.rand_0_3 all__rustc-serialize.rustc-serialize_0_3 all__byteorder.byteorder_0_4 all__bitflags.bitflags_0_3 ];
  };
  websocket_0_15_2 = buildCratesLib {
    name = "websocket";
    version = "0.15.2";
    hash = "8d7b30b458bee9718dea4e1d1f48902cebf6fd38bc48d52b4a203dc15fc56ea8";
    deps = with allCrates; [  all__url.url_0_5 all__bitflags.bitflags_0_3 all__unicase.unicase_1_0_1 all__rand.rand_0_3 all__net2.net2_0_2 all__byteorder.byteorder_0_4 all__openssl.openssl_0_7 all__rustc-serialize.rustc-serialize_0_3 hyper ];
  };
  websocket_0_16_0 = buildCratesLib {
    name = "websocket";
    version = "0.16.0";
    hash = "47893f6557b98bcc6227546d876f182cf0c20cf7e1e8514da8346f1c2cbc5be4";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__unicase.unicase_1_0_1 all__rand.rand_0_3 all__byteorder.byteorder_0_4 all__openssl.openssl_0_7 hyper all__net2.net2_0_2 all__bitflags.bitflags_0_3 all__url.url_0_5 ];
  };
  "websocket_0_15" = websocket_0_15_2;
  websocket_0_16_1 = buildCratesLib {
    name = "websocket";
    version = "0.16.1";
    hash = "c872078029dca368d786f282a9f261d335dc84ed6904324be770107f5430f2ea";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__url.url_0_5 hyper all__openssl.openssl_0_7 all__unicase.unicase_1_0_1 all__bitflags.bitflags_0_3 all__net2.net2_0_2 all__byteorder.byteorder_0_4 all__rand.rand_0_3 ];
  };
  websocket_0_16_2 = buildCratesLib {
    name = "websocket";
    version = "0.16.2";
    hash = "01f615a411d022054d0d08b51965945797a1a3b7b1a87a143f3c25ac947dcb72";
    deps = with allCrates; [  all__bitflags.bitflags_0_3 hyper all__rand.rand_0_3 all__openssl.openssl_0_7 all__byteorder.byteorder_0_5 all__net2.net2_0_2 all__rustc-serialize.rustc-serialize_0_3 all__unicase.unicase_1_0_1 all__url.url_0_5 ];
  };
  websocket_0_17_0 = buildCratesLib {
    name = "websocket";
    version = "0.17.0";
    hash = "dcfa0f07598b4d613e2863c238e296678976186f7cb541b3ce77f3478f5c4d7d";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__url.url_1_0 all__net2.net2_0_2 all__openssl.openssl_0_7 all__unicase.unicase_1_0_1 all__bitflags.bitflags_0_3 hyper all__rustc-serialize.rustc-serialize_0_3 all__rand.rand_0_3 ];
  };
  "websocket_0_16" = websocket_0_16_2;
  websocket_0_17_1 = buildCratesLib {
    name = "websocket";
    version = "0.17.1";
    hash = "bb4a1a6ea5ed0367f32eb3d94dcc58859ef4294b5f75ba983dbf56ac314af45d";
    deps = with allCrates; [  all__bitflags.bitflags_0_7 hyper all__rustc-serialize.rustc-serialize_0_3 all__rand.rand_0_3 all__openssl.openssl_0_7 all__net2.net2_0_2 all__unicase.unicase_1_0_1 all__byteorder.byteorder_0_5 all__url.url_1_0 ];
  };
  "websocket_0_17" = websocket_0_17_1;
  "websocket_0" = websocket_0_17_1;}