#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  colorparse_1_0_0 = buildCratesLib {
    name = "colorparse";
    version = "1.0.0";
    hash = "00b0ec3c019b9f87323cebe1d6f407f7c72efec067c3e81769c2003e6ef7480a";
    deps = with allCrates; [ ansi_term quick-error ];
  };
  colorparse_1_1_0 = buildCratesLib {
    name = "colorparse";
    version = "1.1.0";
    hash = "f9c7ac090ab83abc44407672d3370ca8831256d3e20e281e080f511e3a3362c2";
    deps = with allCrates; [ ansi_term quick-error ];
  };
  colorparse_2_0_0 = buildCratesLib {
    name = "colorparse";
    version = "2.0.0";
    hash = "1f17d109f5ea071d5f4a07f8c6d2eb023a9b276032d16a8466eed6189560ace9";
    deps = with allCrates; [ quick-error ansi_term ];
  };}