#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  dynasm_0_0_1 = buildCratesLib {
    name = "dynasm";
    version = "0.0.1";
    hash = "574ecdda7a5eb4ce3408be8dad6d4ce75287f2a6bc36de87aa50469dbb5dc708";
    deps = with allCrates; [  lazy_static bitflags owning_ref ];
  };
  dynasm_0_0_2 = buildCratesLib {
    name = "dynasm";
    version = "0.0.2";
    hash = "19cf70c9abe58b8da16718763585540e16c1512853cb6510254db7183edc61d3";
    deps = with allCrates; [  bitflags owning_ref lazy_static ];
  };
  dynasm_0_0_3 = buildCratesLib {
    name = "dynasm";
    version = "0.0.3";
    hash = "c319b34076bc3b7b2d4bc7c7027cb73a433ee3f3d033f21cd05d716be4252e17";
    deps = with allCrates; [  owning_ref bitflags lazy_static ];
  };
  dynasm_0_0_4 = buildCratesLib {
    name = "dynasm";
    version = "0.0.4";
    hash = "211c5caee66f330244d3e7fc337fd6ad88141a2d7b135564c6694a45f801e7cc";
    deps = with allCrates; [  owning_ref lazy_static bitflags ];
  };
  dynasm_0_0_5 = buildCratesLib {
    name = "dynasm";
    version = "0.0.5";
    hash = "5abc7a46624e5018323912d6488287d5d4a8b41e17660d05864537e6be411b16";
    deps = with allCrates; [  owning_ref bitflags lazy_static ];
  };
  dynasm_0_0_6 = buildCratesLib {
    name = "dynasm";
    version = "0.0.6";
    hash = "aae1cf98627b5f5d7ce5743222854f1af24953f3e109b0e59edbff747d4e665d";
    deps = with allCrates; [  lazy_static bitflags owning_ref ];
  };
  "dynasm_0_0" = dynasm_0_0_6;
  "dynasm_0" = dynasm_0_0_6;}