#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  bronze_0_1_0 = buildCratesLib {
    name = "bronze";
    version = "0.1.0";
    hash = "6e6e603e75d3e0dc88c197715e34f14a24f92a68031db4aa7cae6474beed9fde";
    deps = with allCrates; [ mio ];
  };}