#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  file_diff_0_1_0 = buildCratesLib {
    name = "file_diff";
    version = "0.1.0";
    hash = "aaabe84746a229cb58ae65b15086f0b5cf1a685437554f6d1a98fe8281594e90";
    deps = with allCrates; [ ];
  };
  file_diff_0_2_0 = buildCratesLib {
    name = "file_diff";
    version = "0.2.0";
    hash = "fdbcfe17623e0891cfc866ab83361e39d92fb440ca5a91f3986e08998a6a40fd";
    deps = with allCrates; [ ];
  };
  file_diff_1_0_0 = buildCratesLib {
    name = "file_diff";
    version = "1.0.0";
    hash = "31a7a908b8f32538a2143e59a6e4e2508988832d5d4d6f7c156b3cbc762643a5";
    deps = with allCrates; [ ];
  };}