#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  file_logger_0_1_0 = buildCratesLib {
    name = "file_logger";
    version = "0.1.0";
    hash = "00f06c88fc24a89a34b911a2b08bf337d026152f2d12750545df9c4101432fad";
    deps = with allCrates; [ time toml nom log regex ];
  };}