#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  scuttlebutt_0_1_0 = buildCratesLib {
    name = "scuttlebutt";
    version = "0.1.0";
    hash = "4e2746fc101f60dce2796ba32bda7789a9ac85ba3382ec7c01854bafc15de8bc";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__log.log_0_3 all__serde_codegen.serde_codegen_0_8 ];
  };
  scuttlebutt_0_1_1 = buildCratesLib {
    name = "scuttlebutt";
    version = "0.1.1";
    hash = "f2ec221326b01b2c5da5e24d82ac5d249986a9f7930d91df4764e9bc368fe6be";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__log.log_0_3 all__hyper.hyper_0_9 all__serde_codegen.serde_codegen_0_8 ];
  };
  "scuttlebutt_0_1" = scuttlebutt_0_1_1;
  "scuttlebutt_0" = scuttlebutt_0_1_1;}