#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  dmoguids-sys_0_0_1 = buildCratesLib {
    name = "dmoguids-sys";
    version = "0.0.1";
    hash = "0f6463919789a222a291db67e6e3a9039d0558ed69808516df6f15d644a6277e";
    deps = with allCrates; [ winapi ];
  };}