#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  espeak-sys_0_0_1 = buildCratesLib {
    name = "espeak-sys";
    version = "0.0.1";
    hash = "2aa9d2c58796f656421bf21fa81cb9259d067cc2318baa8f197edbad3fae914e";
    deps = with allCrates; [ libc ];
  };
  espeak-sys_0_0_2 = buildCratesLib {
    name = "espeak-sys";
    version = "0.0.2";
    hash = "fc1930b0dbd31d3c8be5dc5f0a3729f009b12016e69cbe757cc561bcd367a842";
    deps = with allCrates; [ libc ];
  };}