#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  ascii_set_0_1_0 = buildCratesLib {
    name = "ascii_set";
    version = "0.1.0";
    hash = "0945be94ddbe391722b300e1ef256c522e352799b0f06739f282b5aec81593dc";
    deps = with allCrates; [ ];
  };}