#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  recursive_sync_0_0_1 = buildCratesLib {
    name = "recursive_sync";
    version = "0.0.1";
    hash = "b43c158d2aa20fcf7bb76ab4723be465b299e14585107a713001503d33dbd2b5";
    deps = with allCrates; [ gcc ];
  };
  recursive_sync_0_0_2 = buildCratesLib {
    name = "recursive_sync";
    version = "0.0.2";
    hash = "2dbf1053baaab29dd220c582595e7c8e030855172a88751c5b1c6c85447373cb";
    deps = with allCrates; [ gcc ];
  };}