#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ocl-core_0_1_0 = buildCratesLib {
    name = "ocl-core";
    version = "0.1.0";
    hash = "f663a3a86c760a4b54bb71266805b47dfb995a4606c83381869983c2c1dbc54e";
    deps = with allCrates; [  all__rand.rand_0_3 all__enum_primitive.enum_primitive_0_1 all__cl-sys.cl-sys_0_1 all__bitflags.bitflags_0_5 all__num.num_0_1 all__libc.libc_0_2 ];
  };
  ocl-core_0_2_0 = buildCratesLib {
    name = "ocl-core";
    version = "0.2.0";
    hash = "e07e4866eca737f84c817a4fe37e934ca81862ed37c33f62c57398fe4900b731";
    deps = with allCrates; [  all__enum_primitive.enum_primitive_0_1 all__bitflags.bitflags_0_5 all__num.num_0_1 all__cl-sys.cl-sys_0_2 all__libc.libc_0_2 all__rand.rand_0_3 ];
  };
  "ocl-core_0_1" = ocl-core_0_1_0;
  ocl-core_0_2_1 = buildCratesLib {
    name = "ocl-core";
    version = "0.2.1";
    hash = "dcd4df7c0c21e2345473ca918d457eb00c1fd1672c60e573c61ec2840a889d4b";
    deps = with allCrates; [  all__cl-sys.cl-sys_0_2 all__num.num_0_1 all__enum_primitive.enum_primitive_0_1 all__rand.rand_0_3 all__bitflags.bitflags_0_5 all__libc.libc_0_2 ];
  };
  ocl-core_0_2_2 = buildCratesLib {
    name = "ocl-core";
    version = "0.2.2";
    hash = "0eb1633c481a9379cd22c718eb9c40a99a26db1a7d2567d90614ceb431e5b358";
    deps = with allCrates; [  all__enum_primitive.enum_primitive_0_1 all__cl-sys.cl-sys_0_2 all__bitflags.bitflags_0_5 all__rand.rand_0_3 all__libc.libc_0_2 all__num.num_0_1 ];
  };
  ocl-core_0_2_3 = buildCratesLib {
    name = "ocl-core";
    version = "0.2.3";
    hash = "fe96cb4e7a9520b61647c73de191abcc67612636894e051bdb01a11c383a7a00";
    deps = with allCrates; [  all__bitflags.bitflags_0_5 all__rand.rand_0_3 all__libc.libc_0_2 all__num.num_0_1 all__cl-sys.cl-sys_0_2 all__enum_primitive.enum_primitive_0_1 ];
  };
  ocl-core_0_2_4 = buildCratesLib {
    name = "ocl-core";
    version = "0.2.4";
    hash = "4e2aeb783aa5b145fadf3cff552465778c73991021be99671dee8c252eed41f6";
    deps = with allCrates; [  all__bitflags.bitflags_0_5 all__num.num_0_1 all__libc.libc_0_2 all__enum_primitive.enum_primitive_0_1 all__cl-sys.cl-sys_0_2 ];
  };
  ocl-core_0_3_0 = buildCratesLib {
    name = "ocl-core";
    version = "0.3.0";
    hash = "2b5ad32c55940d2a6cac906d4bf2f7e2797e7701e2f2d6e6184984779a483e28";
    deps = with allCrates; [  all__enum_primitive.enum_primitive_0_1 all__cl-sys.cl-sys_0_2 all__libc.libc_0_2 all__num.num_0_1 all__bitflags.bitflags_0_5 ];
  };
  "ocl-core_0_2" = ocl-core_0_2_4;
  ocl-core_0_3_1 = buildCratesLib {
    name = "ocl-core";
    version = "0.3.1";
    hash = "3d1a6efad9f7dd4f5571c635aaa25b2ae9def3ecedd33ebd5027226c8858ac80";
    deps = with allCrates; [  all__enum_primitive.enum_primitive_0_1 all__num.num_0_1 all__libc.libc_0_2 all__cl-sys.cl-sys_0_2 all__bitflags.bitflags_0_5 ];
  };
  "ocl-core_0_3" = ocl-core_0_3_1;
  "ocl-core_0" = ocl-core_0_3_1;}