#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  crdt_rs_0_1_0 = buildCratesLib {
    name = "crdt_rs";
    version = "0.1.0";
    hash = "30b382df6995d9cb571ca18c94923ea087159c10f6f1fef8d6f804dcc23951c1";
    deps = with allCrates; [  ];
  };
  crdt_rs_0_1_1 = buildCratesLib {
    name = "crdt_rs";
    version = "0.1.1";
    hash = "19912831f0d3a98694daddef994d0e143131e58ad321e1bc08f8190e34e3b1d2";
    deps = with allCrates; [  ];
  };
  crdt_rs_0_1_2 = buildCratesLib {
    name = "crdt_rs";
    version = "0.1.2";
    hash = "8ee68d889286d35c0159278b3d1206ec7f818b529f97fd0a6fd571bd28ce3c14";
    deps = with allCrates; [  ];
  };
  "crdt_rs_0_1" = crdt_rs_0_1_2;
  "crdt_rs_0" = crdt_rs_0_1_2;}