#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  slippy-map-tiles_0_1_0 = buildCratesLib {
    name = "slippy-map-tiles";
    version = "0.1.0";
    hash = "d0695241d76f4c42f094f437a6cb7823bfce6c00daf674c91826a679bea2114e";
    deps = with allCrates; [  ];
  };
  slippy-map-tiles_0_3_0 = buildCratesLib {
    name = "slippy-map-tiles";
    version = "0.3.0";
    hash = "0a97066ddf5b775f36929f56452760b43d00194ba480bc740e3797558fe09afa";
    deps = with allCrates; [  all__regex.regex_0_1 ];
  };
  "slippy-map-tiles_0_1" = slippy-map-tiles_0_1_0;
  slippy-map-tiles_0_4_0 = buildCratesLib {
    name = "slippy-map-tiles";
    version = "0.4.0";
    hash = "998035325f5b7715f7f0388df3a681d78d5b3e6760083c7451db40ec99e74dcd";
    deps = with allCrates; [  all__regex.regex_0_1 ];
  };
  "slippy-map-tiles_0_3" = slippy-map-tiles_0_3_0;
  slippy-map-tiles_0_5_0 = buildCratesLib {
    name = "slippy-map-tiles";
    version = "0.5.0";
    hash = "30cc596019298ae72d999b015a4facd01aaee3cf3e1d1968b4cb639a97b41295";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 all__regex.regex_0_1 ];
  };
  "slippy-map-tiles_0_4" = slippy-map-tiles_0_4_0;
  slippy-map-tiles_0_7_0 = buildCratesLib {
    name = "slippy-map-tiles";
    version = "0.7.0";
    hash = "5edd17a5299b17ea2f259101ff6b6a4f493b5e10b6b94152519a3d47c9fb99df";
    deps = with allCrates; [  all__regex.regex_0_1 all__lazy_static.lazy_static_0_1 ];
  };
  "slippy-map-tiles_0_5" = slippy-map-tiles_0_5_0;
  slippy-map-tiles_0_8_0 = buildCratesLib {
    name = "slippy-map-tiles";
    version = "0.8.0";
    hash = "6cfa621b2683b92facc9afdd657a9f21d8a78262e0635ae6ca9f9eb324701470";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 all__regex.regex_0_1 ];
  };
  "slippy-map-tiles_0_7" = slippy-map-tiles_0_7_0;
  "slippy-map-tiles_0_8" = slippy-map-tiles_0_8_0;
  "slippy-map-tiles_0" = slippy-map-tiles_0_8_0;}