#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  solicit_0_0_1 = buildCratesLib {
    name = "solicit";
    version = "0.0.1";
    hash = "ef46c00e7a161ff4a820e82f50e968811c218ef3d12d17aaba149bca697af2cb";
    deps = with allCrates; [ hpack openssl log ];
  };
  solicit_0_1_0 = buildCratesLib {
    name = "solicit";
    version = "0.1.0";
    hash = "042b72866dc66a54ab3e984b531501a0777300f70a4312c5ddb445c59754ea91";
    deps = with allCrates; [ hpack openssl log ];
  };
  solicit_0_2_0 = buildCratesLib {
    name = "solicit";
    version = "0.2.0";
    hash = "f7ff7575807c233cc3e99d5a9ca39136b1e8b476499969957bda04321c382b31";
    deps = with allCrates; [ log hpack openssl ];
  };
  solicit_0_3_0 = buildCratesLib {
    name = "solicit";
    version = "0.3.0";
    hash = "8200cbbdf137b2dc5a630cb81758576e60c6e521ddc1401f3e95685a41588d21";
    deps = with allCrates; [ log hpack ];
  };
  solicit_0_4_0 = buildCratesLib {
    name = "solicit";
    version = "0.4.0";
    hash = "fa5bbbe30ad8c16b72870657690b5bdebc258c4445330e938b5db5c8ec6bf13c";
    deps = with allCrates; [ hpack log ];
  };
  solicit_0_4_1 = buildCratesLib {
    name = "solicit";
    version = "0.4.1";
    hash = "2e5b98b44effdc840631f29f932101d8d31fbe23240effbd87007d4b1f131e94";
    deps = with allCrates; [ hpack log ];
  };
  solicit_0_4_2 = buildCratesLib {
    name = "solicit";
    version = "0.4.2";
    hash = "ecabcf00bfd1d8c56392f3b40cd52440cc64339a59ce85407e3ff2e38da89c29";
    deps = with allCrates; [ hpack log ];
  };
  solicit_0_4_3 = buildCratesLib {
    name = "solicit";
    version = "0.4.3";
    hash = "dafc564ff7781909c4de3957fe33a91101fac35d3c83860bdbcb491938ab8b39";
    deps = with allCrates; [ log hpack ];
  };
  solicit_0_4_4 = buildCratesLib {
    name = "solicit";
    version = "0.4.4";
    hash = "172382bac9424588d7840732b250faeeef88942e37b6e35317dce98cafdd75b2";
    deps = with allCrates; [ hpack log ];
  };}