#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ng-log_0_1_0 = buildCratesLib {
    name = "ng-log";
    version = "0.1.0";
    hash = "2b9d9843ec9415a3937641f52b5196028ba66a052020980d4898b9512b68adc9";
    deps = with allCrates; [  ];
  };
  ng-log_0_1_1 = buildCratesLib {
    name = "ng-log";
    version = "0.1.1";
    hash = "42e3af0bb77aa2621d3a4db204f60aab19c317ae3630fa11dc1fe9ac3c592ad1";
    deps = with allCrates; [  ];
  };
  "ng-log_0_1" = ng-log_0_1_1;
  "ng-log_0" = ng-log_0_1_1;}