#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  graphql-rs_0_1_0 = buildCratesLib {
    name = "graphql-rs";
    version = "0.1.0";
    hash = "6a2e30fb0c770dc4981a04c60df07162b5c10747b0a962c3e35b350d4154d897";
    deps = with allCrates; [  ];
  };
  "graphql-rs_0_1" = graphql-rs_0_1_0;
  "graphql-rs_0" = graphql-rs_0_1_0;}