#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  forklift_0_1_0 = buildCratesLib {
    name = "forklift";
    version = "0.1.0";
    hash = "0ddb9511867e8ff208ff05c78a7dd04f485d454c91d6dd950c35e63ed5c093d6";
    deps = with allCrates; [  ];
  };
  "forklift_0_1" = forklift_0_1_0;
  "forklift_0" = forklift_0_1_0;}