#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cfgmgr32-sys_0_0_1 = buildCratesLib {
    name = "cfgmgr32-sys";
    version = "0.0.1";
    hash = "da4756a19b5a0dacbe69856f6bceceda6e5b366336a3fa1ace2565025992cf49";
    deps = with allCrates; [ winapi ];
  };}