#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  buffoon_0_5_0 = buildCratesLib {
    name = "buffoon";
    version = "0.5.0";
    hash = "63d583f21aca006c52e4b8aa3b3a583644274e23938cd3dcb787528917fddc2a";
    deps = with allCrates; [ ];
  };}