#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  egg-mode_0_1_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.1.0";
    hash = "6957ad037959b6768497dbab3da7abe16139e2d5f815f38b97d6d9940c8fec4f";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__rust-crypto.rust-crypto_0_2 all__time.time_0_1 all__url.url_1_1 all__hyper.hyper_0_9 all__mime.mime_0_2 all__rand.rand_0_3 ];
  };
  egg-mode_0_1_1 = buildCratesLib {
    name = "egg-mode";
    version = "0.1.1";
    hash = "19ae16ca6e1eb05b3d5b84faf9a89c8d95b1521a7bfeeaa073aa882eb064eed0";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__rust-crypto.rust-crypto_0_2 all__time.time_0_1 all__hyper.hyper_0_9 all__rand.rand_0_3 all__url.url_1_1 all__mime.mime_0_2 ];
  };
  egg-mode_0_2_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.2.0";
    hash = "ee615eb8a0f752e285ddb0d273c75cff5836cccf9fd93b95c47b189e5f5b9571";
    deps = with allCrates; [  all__mime.mime_0_2 all__url.url_1_1 all__rand.rand_0_3 all__rustc-serialize.rustc-serialize_0_3 all__rust-crypto.rust-crypto_0_2 all__hyper.hyper_0_9 ];
  };
  "egg-mode_0_1" = egg-mode_0_1_1;
  egg-mode_0_3_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.3.0";
    hash = "07037607cfad9e747fd7e998f44a1b0c3e303cbfc61b0193e990e97e9c2c2861";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__hyper.hyper_0_9 all__mime.mime_0_2 all__rust-crypto.rust-crypto_0_2 all__rand.rand_0_3 all__url.url_1_1 ];
  };
  "egg-mode_0_2" = egg-mode_0_2_0;
  egg-mode_0_4_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.4.0";
    hash = "e46ad706be1ae7d3c476dc1d7722c2cdff3dbb58041262473add0a31c6e988b9";
    deps = with allCrates; [  all__url.url_1_1 all__mime.mime_0_2 all__rand.rand_0_3 all__rust-crypto.rust-crypto_0_2 all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "egg-mode_0_3" = egg-mode_0_3_0;
  egg-mode_0_5_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.5.0";
    hash = "e46675a01b23bda9852e7212371e0add17af9299fd424f6592ce0437ebdd31fe";
    deps = with allCrates; [  all__url.url_1_1 all__mime.mime_0_2 all__rustc-serialize.rustc-serialize_0_3 all__rand.rand_0_3 all__hyper.hyper_0_9 all__rust-crypto.rust-crypto_0_2 ];
  };
  "egg-mode_0_4" = egg-mode_0_4_0;
  egg-mode_0_6_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.6.0";
    hash = "c5731c80276181438d553d1eb161c6d5572a8c62ace77ce52fff3b4a8e14bf67";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__lazy_static.lazy_static_0_2 all__hyper.hyper_0_9 all__url.url_1_1 all__mime.mime_0_2 all__rand.rand_0_3 all__regex.regex_0_1 all__rust-crypto.rust-crypto_0_2 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "egg-mode_0_5" = egg-mode_0_5_0;
  egg-mode_0_7_0 = buildCratesLib {
    name = "egg-mode";
    version = "0.7.0";
    hash = "c1de04c9906ee0a390fcd3001ce8e3c73fb596aebe0a6001914dccf1ea3876a7";
    deps = with allCrates; [  all__url.url_1_1 all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__unicode-normalization.unicode-normalization_0_1 all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__mime.mime_0_2 all__rand.rand_0_3 all__rust-crypto.rust-crypto_0_2 ];
  };
  "egg-mode_0_6" = egg-mode_0_6_0;
  "egg-mode_0_7" = egg-mode_0_7_0;
  "egg-mode_0" = egg-mode_0_7_0;}