#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rendarray_0_1_0 = buildCratesLib {
    name = "rendarray";
    version = "0.1.0";
    hash = "cd3167480b80804f9564d28e492b2fc4a6901e9b9566f4d3db4c69f88feaf30a";
    deps = with allCrates; [  all__itertools.itertools_0_4 all__num.num_0_1 ];
  };
  rendarray_0_1_1 = buildCratesLib {
    name = "rendarray";
    version = "0.1.1";
    hash = "d1e8cf102ab2ac6440c86810f5c6335252a4b35cc3b58aab912a6af102c904b0";
    deps = with allCrates; [  all__num.num_0_1 all__itertools.itertools_0_4 ];
  };
  "rendarray_0_1" = rendarray_0_1_1;
  "rendarray_0" = rendarray_0_1_1;}