#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  bvh_0_0_0 = buildCratesLib {
    name = "bvh";
    version = "0.0.0";
    hash = "201c271fa79873c67dc1962dd70465331be665b043f62f9a70b3defdd7e056d7";
    deps = with allCrates; [ clippy ];
  };
  bvh_0_1_0 = buildCratesLib {
    name = "bvh";
    version = "0.1.0";
    hash = "30bfd23a42fa6b79d202ee00abc3c7a6424909383f5feac688a5e620f9899e2b";
    deps = with allCrates; [ clippy nalgebra ];
  };
  bvh_0_1_1 = buildCratesLib {
    name = "bvh";
    version = "0.1.1";
    hash = "bb9720ec7e203919f185b5fdea531ac26e94b42ef6a9a58e55c9d156ca8bc79a";
    deps = with allCrates; [ nalgebra ];
  };}