#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  recycler_0_1_0 = buildCratesLib {
    name = "recycler";
    version = "0.1.0";
    hash = "e9757007eb0639da5c93793b97e2d6cb8aa713c5cbe3b7655700a131745ad1fd";
    deps = with allCrates; [ ];
  };
  recycler_0_1_1 = buildCratesLib {
    name = "recycler";
    version = "0.1.1";
    hash = "7dd59d47b757b915a139dbeb047a3c0bef3a06cc1c342c8c15e1e64bcfab04b7";
    deps = with allCrates; [ ];
  };
  recycler_0_1_2 = buildCratesLib {
    name = "recycler";
    version = "0.1.2";
    hash = "aafafe23727c986a202c5670bccbf3fcc6670b1d29f3aac0f1f9209757ab02ba";
    deps = with allCrates; [ ];
  };
  recycler_0_1_3 = buildCratesLib {
    name = "recycler";
    version = "0.1.3";
    hash = "a0b7aae4cf416fb7131c003cd7cd4e0a3098d6b0c69053e5227e667a972f4170";
    deps = with allCrates; [ ];
  };
  recycler_0_1_4 = buildCratesLib {
    name = "recycler";
    version = "0.1.4";
    hash = "98dc27328efeb3250fc4f8b7b79fe34339856513229f19d374ca78aeb10694fa";
    deps = with allCrates; [ ];
  };}