#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  faerie_0_0_0 = buildCratesLib {
    name = "faerie";
    version = "0.0.0";
    hash = "95b394124ba4c822700357f9afb37591d0ba9233b7d3cba61ad110bcf7d447dc";
    deps = with allCrates; [ ];
  };}