#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  const-cstr_0_1_0 = buildCratesLib {
    name = "const-cstr";
    version = "0.1.0";
    hash = "031af4d877b3a166acf7ae6a5c15095e6d4b0d1237ee9012e273c022fabca7dd";
    deps = with allCrates; [  all__libc.libc_0_1 ];
  };
  const-cstr_0_2_0 = buildCratesLib {
    name = "const-cstr";
    version = "0.2.0";
    hash = "a53837b51ebd5072f2050f3103915a065288beaf52400c18793d5495a61ab19e";
    deps = with allCrates; [  all__libc.libc_0_1 ];
  };
  "const-cstr_0_1" = const-cstr_0_1_0;
  const-cstr_0_2_1 = buildCratesLib {
    name = "const-cstr";
    version = "0.2.1";
    hash = "2e950b379a7f9c5a83d43257fa1df616689141f326b4fc3bfb7aa7f3c7bc44d2";
    deps = with allCrates; [  all__libc.libc_0_1 ];
  };
  "const-cstr_0_2" = const-cstr_0_2_1;
  "const-cstr_0" = const-cstr_0_2_1;}