#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  bzip2_0_1_0 = buildCratesLib {
    name = "bzip2";
    version = "0.1.0";
    hash = "0c15f63554f0a13e1b50a0f912f179326b6398710c496c86b5cb9af99b13975f";
    deps = with allCrates; [ bzip2-sys ];
  };
  bzip2_0_1_1 = buildCratesLib {
    name = "bzip2";
    version = "0.1.1";
    hash = "172d8204e60303649761016eace476be137d6337f54642236cb03184ba6e078a";
    deps = with allCrates; [ bzip2-sys ];
  };
  bzip2_0_1_2 = buildCratesLib {
    name = "bzip2";
    version = "0.1.2";
    hash = "f5d4c42d073a5fab6cf47297bc4f76e75c1839721d3e47c490d8a4459646a7de";
    deps = with allCrates; [ bzip2-sys ];
  };
  bzip2_0_1_3 = buildCratesLib {
    name = "bzip2";
    version = "0.1.3";
    hash = "09b471cd2f5be9ecd0c81fd712703fae2b8fd092c41bef2c880776211f6c3eb3";
    deps = with allCrates; [ bzip2-sys ];
  };
  bzip2_0_2_0 = buildCratesLib {
    name = "bzip2";
    version = "0.2.0";
    hash = "3aa8eb0999a3cad70aed02959fff6107d56a9264562841daf6ac89a8810028ba";
    deps = with allCrates; [ bzip2-sys libc ];
  };
  bzip2_0_2_1 = buildCratesLib {
    name = "bzip2";
    version = "0.2.1";
    hash = "32fa15577ae4d3e9478199e937d684c6fc737d712b268fe7e04112a6ff2131c4";
    deps = with allCrates; [ bzip2-sys libc ];
  };
  bzip2_0_2_2 = buildCratesLib {
    name = "bzip2";
    version = "0.2.2";
    hash = "d059db0c0d7cedeea7a0395d153295afec7c48760cd5f1d33069e9fd134a0beb";
    deps = with allCrates; [ bzip2-sys libc ];
  };
  bzip2_0_2_3 = buildCratesLib {
    name = "bzip2";
    version = "0.2.3";
    hash = "2498d940402fc49ef27875f2a36577ee1dfcb5103f7edb9e9c7bbe0514ebabde";
    deps = with allCrates; [ libc bzip2-sys ];
  };
  bzip2_0_2_4 = buildCratesLib {
    name = "bzip2";
    version = "0.2.4";
    hash = "d9830274bff73a50016b9cb77d63f1654f3c53999189fb4d01f18021cb34e56b";
    deps = with allCrates; [ libc bzip2-sys ];
  };
  bzip2_0_3_0 = buildCratesLib {
    name = "bzip2";
    version = "0.3.0";
    hash = "7c30a578393daf45ee6101aa043afa8d47a7e70f05032b15b88b28a7111c6a53";
    deps = with allCrates; [ libc bzip2-sys ];
  };}