#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  temporary_0_0_1 = buildCratesLib {
    name = "temporary";
    version = "0.0.1";
    hash = "5ec92e197e3b81b1579e0a856c816adc7897a939eeda86231c41cb9acd0b0a9a";
    deps = with allCrates; [ rand ];
  };
  temporary_0_0_2 = buildCratesLib {
    name = "temporary";
    version = "0.0.2";
    hash = "b7b38f62f5ad5f3ba955a6f7477c67abc9dd3a3cb9d7796b8b4cb478c459d525";
    deps = with allCrates; [ rand ];
  };
  temporary_0_0_3 = buildCratesLib {
    name = "temporary";
    version = "0.0.3";
    hash = "6427a0f44b7b290a78a7ce1360f299cb7da0628b053b00441e538bad09802b65";
    deps = with allCrates; [ rand ];
  };
  temporary_0_0_4 = buildCratesLib {
    name = "temporary";
    version = "0.0.4";
    hash = "bf8b74436d8111a104ce3d15b5962d1468c8ec47d6b7ba690d8a85dcd6ca91a8";
    deps = with allCrates; [ rand ];
  };
  temporary_0_0_5 = buildCratesLib {
    name = "temporary";
    version = "0.0.5";
    hash = "46babe914a46727ac7962d9aac64db72e4a6a34cdff88660ce5567712841596a";
    deps = with allCrates; [ rand ];
  };
  temporary_0_1_0 = buildCratesLib {
    name = "temporary";
    version = "0.1.0";
    hash = "fdee0c7bfd52569dcc95e1e50a139220885285fcecf8aeceb153020cd8bb95ac";
    deps = with allCrates; [ rand ];
  };
  temporary_0_1_1 = buildCratesLib {
    name = "temporary";
    version = "0.1.1";
    hash = "0217f26d7cc4eff61c4ee1b8e392e52a7134f12d28b2b76a40f4cce98fab780c";
    deps = with allCrates; [ rand ];
  };
  temporary_0_2_0 = buildCratesLib {
    name = "temporary";
    version = "0.2.0";
    hash = "896af7d1485ca43df7d0d1ff0d9f621d4099b3e6d90ac40471b8c91d355516a5";
    deps = with allCrates; [ rand ];
  };
  temporary_0_3_0 = buildCratesLib {
    name = "temporary";
    version = "0.3.0";
    hash = "8abb96ce5f8e9ccd56e820a75ff8d23fea0a69a9b7734d55aefb37ea433df689";
    deps = with allCrates; [ ];
  };
  temporary_0_4_0 = buildCratesLib {
    name = "temporary";
    version = "0.4.0";
    hash = "030f032c1d1b9d29c2d7471f59579d8a34e8ab4d39394cbd10a32344de3a3b08";
    deps = with allCrates; [ ];
  };
  temporary_0_4_1 = buildCratesLib {
    name = "temporary";
    version = "0.4.1";
    hash = "03bf2a9e12b268e51c1c3be91a1131f03ebdc9500ac7e5b92d4ff7690aa2f65f";
    deps = with allCrates; [ random ];
  };
  temporary_0_5_0 = buildCratesLib {
    name = "temporary";
    version = "0.5.0";
    hash = "5ef73d3ed9f8fdf56756135bd453e9a29d4e21ab5694e8d8cdb2b20f3f06b9e6";
    deps = with allCrates; [ random ];
  };
  temporary_0_5_1 = buildCratesLib {
    name = "temporary";
    version = "0.5.1";
    hash = "76c8c158f799838e36c294964bdf8f97e8bb8ca467863eda92dc8d6e6d3493f5";
    deps = with allCrates; [ random ];
  };
  temporary_0_6_0 = buildCratesLib {
    name = "temporary";
    version = "0.6.0";
    hash = "d5b97bbba621607961698b8d9723104809a3ac0569b3ead57bda92aa3d2bbf13";
    deps = with allCrates; [ random ];
  };
  temporary_0_6_1 = buildCratesLib {
    name = "temporary";
    version = "0.6.1";
    hash = "5ce2b35abda585cdd6d302079fac4b7e3a2b370ec9451bd9d8abcc9c1156cb3f";
    deps = with allCrates; [ random ];
  };
  temporary_0_6_2 = buildCratesLib {
    name = "temporary";
    version = "0.6.2";
    hash = "8a5a2bc9df324b6a595ca90ac2b916a98e2782370abd24c787c37bc0e1dcef8e";
    deps = with allCrates; [ random ];
  };
  temporary_0_6_3 = buildCratesLib {
    name = "temporary";
    version = "0.6.3";
    hash = "b634ddc8429dbab3bfa84158c1ffdb6cf5a24f518fb7ab5459b493b2bc791bfc";
    deps = with allCrates; [ random ];
  };}