#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rotor-capnp_0_1_0 = buildCratesLib {
    name = "rotor-capnp";
    version = "0.1.0";
    hash = "1de34534cddc26a5d57168a52cb91b094f366c391bd869bd2e6ab13ced0122e8";
    deps = with allCrates; [ rotor byteorder capnp rotor-stream quick-error ];
  };}