#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rotor-http_0_1_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.1.0";
    hash = "61c8260a0c18d6b7b2ee9ff9073fcfb7b44f12faedd77b21f7191f9ac717baf5";
    deps = with allCrates; [  all__rotor.rotor_0_1 log time mio httparse hyper netbuf ];
  };
  rotor-http_0_2_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.2.0";
    hash = "ff92658e765327e4b71ddf70cfcf5952d5b1585764df95d42a551f6553881e3a";
    deps = with allCrates; [  log all__rotor.rotor_0_1 httparse hyper time mio netbuf ];
  };
  "rotor-http_0_1" = rotor-http_0_1_0;
  rotor-http_0_2_1 = buildCratesLib {
    name = "rotor-http";
    version = "0.2.1";
    hash = "aea33c4f3e2a7306deb3bc63bb72e737a623466e24ed39c7a11fcc25798c056f";
    deps = with allCrates; [  mio all__rotor.rotor_0_2 time netbuf log httparse hyper ];
  };
  rotor-http_0_2_2 = buildCratesLib {
    name = "rotor-http";
    version = "0.2.2";
    hash = "370c13965f38e67416c6fc1cd484dbb83930d352dccfb5058fb77284f9e31d99";
    deps = with allCrates; [  all__httparse.httparse_0_1 all__hyper.hyper_0_6 log all__netbuf.netbuf_0_2 time all__mio.mio_0_4 all__rotor.rotor_0_2 ];
  };
  rotor-http_0_3_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.3.0";
    hash = "7d4de61d95a0993ab36b2be47736545b22ba551435c283f8cf35bb7a18ceb07c";
    deps = with allCrates; [  all__time.time_0_1 all__mio.mio_0_4 all__hyper.hyper_0_6 all__log.log_0_3 all__rotor.rotor_0_3 all__netbuf.netbuf_0_2 all__httparse.httparse_1_0_0 ];
  };
  "rotor-http_0_2" = rotor-http_0_2_2;
  rotor-http_0_4_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.4.0";
    hash = "01f7b0b0efdfb6405db817928dd6d68c0ecde8873fd2ea90dc7d32e645e2d3b8";
    deps = with allCrates; [  all__time.time_0_1 all__rotor.rotor_0_4 all__rotor-stream.rotor-stream_0_3 all__hyper.hyper_0_7 all__netbuf.netbuf_0_3 all__httparse.httparse_1_1 all__log.log_0_3 all__mio.mio_0_5 all__matches.matches_0_1 all__quick-error.quick-error_0_2 ];
  };
  "rotor-http_0_3" = rotor-http_0_3_0;
  rotor-http_0_5_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.5.0";
    hash = "7b4adebaa8e505a62edf4f5fa375308c995dca8a26bf2672c30c32f5e44a08ca";
    deps = with allCrates; [  all__ip.ip_1_0_0 all__rotor.rotor_0_5 all__hyper.hyper_0_7 all__time.time_0_1 all__rotor-stream.rotor-stream_0_4 all__quick-error.quick-error_0_2 all__matches.matches_0_1 all__log.log_0_3 all__void.void_0_0_5 all__httparse.httparse_1_1 ];
  };
  "rotor-http_0_4" = rotor-http_0_4_0;
  rotor-http_0_6_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.6.0";
    hash = "9b7536d48b7dd54c894a005342311ed2969f75d39d3f9d9a5ba3430ab000b661";
    deps = with allCrates; [  all__rotor.rotor_0_6 all__rotor-stream.rotor-stream_0_5 all__httparse.httparse_1_1 all__matches.matches_0_1 all__quick-error.quick-error_1_0_0 ];
  };
  "rotor-http_0_5" = rotor-http_0_5_0;
  rotor-http_0_7_0 = buildCratesLib {
    name = "rotor-http";
    version = "0.7.0";
    hash = "b8664d1902036a244ce7e47ea52296f097274b158c46917a6c25e40b19a18c57";
    deps = with allCrates; [  all__log.log_0_3 all__quick-error.quick-error_1_0_0 all__rotor.rotor_0_6 all__matches.matches_0_1 all__rotor-stream.rotor-stream_0_6 all__httparse.httparse_1_1 ];
  };
  "rotor-http_0_6" = rotor-http_0_6_0;
  "rotor-http_0_7" = rotor-http_0_7_0;
  "rotor-http_0" = rotor-http_0_7_0;}