#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mold2d_0_0_1 = buildCratesLib {
    name = "mold2d";
    version = "0.0.1";
    hash = "df435a4ad4f7b6ac60a9972fd5b280a863ebfde5dc4918678f2579e139c40f0c";
    deps = with allCrates; [  all__sdl2_image.sdl2_image_0_3 all__libc.libc_0_2 all__sdl2.sdl2_0_9 all__sdl2_ttf.sdl2_ttf_0_9 ];
  };
  mold2d_0_0_2 = buildCratesLib {
    name = "mold2d";
    version = "0.0.2";
    hash = "b570ea003e882fa238600c44a59d86489e4ba1b7f182f6229674c22b8195cd6e";
    deps = with allCrates; [  all__libc.libc_0_2 all__sdl2.sdl2_0_9 all__sdl2_ttf.sdl2_ttf_0_9 all__sdl2_image.sdl2_image_0_3 ];
  };
  "mold2d_0_0" = mold2d_0_0_2;
  "mold2d_0" = mold2d_0_0_2;}