#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  sdl_0_3_5 = buildCratesLib {
    name = "sdl";
    version = "0.3.5";
    hash = "8fe3ce69cc3401e5220a760d0b852a155ba622916073d9cc2e852d4d615a9aa0";
    deps = with allCrates; [ ];
  };
  sdl_0_3_6 = buildCratesLib {
    name = "sdl";
    version = "0.3.6";
    hash = "93bb02588a7a9dff425676818811b0a84e8a39e0739812ea3d7aca8c355a5d1b";
    deps = with allCrates; [ libc num rand ];
  };}