#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  copperline_0_0_1 = buildCratesLib {
    name = "copperline";
    version = "0.0.1";
    hash = "d24c8f3001e7d46b8d5b552c0ee335a53f9be33c936c8e637afe24f93d7de923";
    deps = with allCrates; [ libc nix ];
  };
  copperline_0_0_2 = buildCratesLib {
    name = "copperline";
    version = "0.0.2";
    hash = "5ebb81c3b58bf7ab22dc6b5c59e7d1617a541a6de866609f73099ccf27418507";
    deps = with allCrates; [ libc nix ];
  };
  copperline_0_0_3 = buildCratesLib {
    name = "copperline";
    version = "0.0.3";
    hash = "079b98ac52c8bd33517f81339aa4d98e40deb19fcb802c14657824d23869e14e";
    deps = with allCrates; [ libc nix ];
  };
  copperline_0_1_0 = buildCratesLib {
    name = "copperline";
    version = "0.1.0";
    hash = "9093e8ee34837cf85006084d0ba0597805b5842ab6e598248f8da42f6e35ca23";
    deps = with allCrates; [ nix libc ];
  };
  copperline_0_1_1 = buildCratesLib {
    name = "copperline";
    version = "0.1.1";
    hash = "8cf57e0dc85c596c70f7bc6721769412391d3ff35bc2d455e60b365ad7ecb042";
    deps = with allCrates; [ nix libc ];
  };
  copperline_0_1_2 = buildCratesLib {
    name = "copperline";
    version = "0.1.2";
    hash = "09ef7dc98659457b08d8ab2b104c27441a1a5a48f28777881b3b71aec3746fde";
    deps = with allCrates; [ nix libc ];
  };
  copperline_0_1_3 = buildCratesLib {
    name = "copperline";
    version = "0.1.3";
    hash = "037f7733b3a1c0ea24318979c237eeb2fbd3fa3a5048a1921df183a9e5d43c70";
    deps = with allCrates; [ nix libc ];
  };
  copperline_0_2_0 = buildCratesLib {
    name = "copperline";
    version = "0.2.0";
    hash = "2608f7505894d3fc6b941c36c44aa54960b29cb58efcfd15637ed4f991095a8d";
    deps = with allCrates; [ libc nix ];
  };
  copperline_0_2_1 = buildCratesLib {
    name = "copperline";
    version = "0.2.1";
    hash = "baa638b7f10a4526e99c1e8ff1536dc0ad0131522f3114c786783d7e6dedce8f";
    deps = with allCrates; [ libc nix ];
  };
  copperline_0_3_0 = buildCratesLib {
    name = "copperline";
    version = "0.3.0";
    hash = "3e80a6471b77449d3bd5c2192441ee3138184f69a2bba233c036ca21dcd626f3";
    deps = with allCrates; [ libc strcursor encoding unicode-width nix ];
  };}