#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  expectest_0_1_0 = buildCratesLib {
    name = "expectest";
    version = "0.1.0";
    hash = "1da536607a2f65d61c1f613506be89f1b62e73df4b9d38e407931a372620003c";
    deps = with allCrates; [  ];
  };
  expectest_0_1_1 = buildCratesLib {
    name = "expectest";
    version = "0.1.1";
    hash = "99f7e6fe820f13f2d8005ce004b4168d492c1f932f5f49d8e853cb0d61a7572b";
    deps = with allCrates; [  ];
  };
  expectest_0_1_2 = buildCratesLib {
    name = "expectest";
    version = "0.1.2";
    hash = "8818ec2ffc3d4409833e674a19ba64a04a60efc4d580aaab7ec1664b16d782de";
    deps = with allCrates; [  ];
  };
  expectest_0_1_3 = buildCratesLib {
    name = "expectest";
    version = "0.1.3";
    hash = "53697b9826876f9c66ebe412a9a32bb5cfb7b4223cea76685f4354e6b21e2696";
    deps = with allCrates; [  ];
  };
  expectest_0_1_4 = buildCratesLib {
    name = "expectest";
    version = "0.1.4";
    hash = "d6c40d19941b6325217af1a207275a778ade91dab4097b8ed4faa839029e2f95";
    deps = with allCrates; [  num ];
  };
  expectest_0_1_5 = buildCratesLib {
    name = "expectest";
    version = "0.1.5";
    hash = "8c90e41b1666f8692c3bc8779e6c4b66f181f1fff5658a476f795efdecad69a6";
    deps = with allCrates; [  num ];
  };
  expectest_0_1_6 = buildCratesLib {
    name = "expectest";
    version = "0.1.6";
    hash = "297f6c59a24ac73f69427fdd41789a903b3673c75283aaadbc35e1a3f4efd44f";
    deps = with allCrates; [  num ];
  };
  expectest_0_1_7 = buildCratesLib {
    name = "expectest";
    version = "0.1.7";
    hash = "89e29a8d8c0fff37252b53669f683fe0bbb9bf7ddcbadf8545a036d53e00f7b1";
    deps = with allCrates; [  num ];
  };
  expectest_0_1_8 = buildCratesLib {
    name = "expectest";
    version = "0.1.8";
    hash = "6af9fe5bad9c7b0f7a318d20ad9f5de24b654adfc1fbe8c952c87004f0e5531c";
    deps = with allCrates; [  num ];
  };
  expectest_0_2_0 = buildCratesLib {
    name = "expectest";
    version = "0.2.0";
    hash = "df20d7e467026c2fd2de34bfea07d56c8c14f47116fe0c8164d5916716c35841";
    deps = with allCrates; [  num ];
  };
  "expectest_0_1" = expectest_0_1_8;
  expectest_0_2_1 = buildCratesLib {
    name = "expectest";
    version = "0.2.1";
    hash = "b3f3576d072311e6c661c242df755706e748f3ff830a38af0252669d87cdb498";
    deps = with allCrates; [  num ];
  };
  expectest_0_2_2 = buildCratesLib {
    name = "expectest";
    version = "0.2.2";
    hash = "a7ccdd6ae3359af7cc40e61291831ad9e11f497c43b29f1aa65ac05d92801e8f";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_2_3 = buildCratesLib {
    name = "expectest";
    version = "0.2.3";
    hash = "2af7971f7ce484ef191e89c77cb9b8a00402fbcdf6c49a9d198f29b276b75429";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_2_4 = buildCratesLib {
    name = "expectest";
    version = "0.2.4";
    hash = "695175932ac547e8c2b120cdbef01f9a9d878c71bd30d258ff5127e79638f9a9";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_2_5 = buildCratesLib {
    name = "expectest";
    version = "0.2.5";
    hash = "378e7869631f30138525addd6d8dfa5a7e64cef04c712cb620c01efbce00cc2e";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_2_6 = buildCratesLib {
    name = "expectest";
    version = "0.2.6";
    hash = "3929e1abddde56730c757ebfa517482bf7ff6bf20d548440effd7f1a87700f14";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_3_0 = buildCratesLib {
    name = "expectest";
    version = "0.3.0";
    hash = "2b5d2dc94e27a3648689274d2dfcaa184c222a1586e0d458e6f0476708cfb669";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  "expectest_0_2" = expectest_0_2_6;
  expectest_0_3_1 = buildCratesLib {
    name = "expectest";
    version = "0.3.1";
    hash = "0452fc553e86b6d85063237958f088efe97a7bcbecd34eebf48f47048b0ee0a3";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_4_0 = buildCratesLib {
    name = "expectest";
    version = "0.4.0";
    hash = "9a0093be9646817751d628861ca1ef70cebfe41320ad8232684f021120427e94";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  "expectest_0_3" = expectest_0_3_1;
  expectest_0_4_1 = buildCratesLib {
    name = "expectest";
    version = "0.4.1";
    hash = "1c9fcc0b948c0acb591c947f9b61f21fdeec5580b10f7c6498c0b3305d6573e8";
    deps = with allCrates; [  all__num.num_0_1 ];
  };
  expectest_0_5_1 = buildCratesLib {
    name = "expectest";
    version = "0.5.1";
    hash = "50d89560b9a791f664a3e35ea593bc8891266becbd734e8dd481008bebcc2b70";
    deps = with allCrates; [  all__num-traits.num-traits_0_1 all__skeptic.skeptic_0_4 ];
  };
  "expectest_0_4" = expectest_0_4_1;
  expectest_0_6_0 = buildCratesLib {
    name = "expectest";
    version = "0.6.0";
    hash = "fe5ea378e61a20fdc7fabcf2a2f7b514c8d8555540562e2496d99df793f1f9bf";
    deps = with allCrates; [  all__num-traits.num-traits_0_1 all__skeptic.skeptic_0_5 ];
  };
  "expectest_0_5" = expectest_0_5_1;
  "expectest_0_6" = expectest_0_6_0;
  "expectest_0" = expectest_0_6_0;}