#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  css-color-parser_0_1_0 = buildCratesLib {
    name = "css-color-parser";
    version = "0.1.0";
    hash = "a37c81f1be9de02f98cd6c9c117640ee08bd3e0ab40d36dc63b4d3f2908f5938";
    deps = with allCrates; [  ];
  };
  css-color-parser_0_1_1 = buildCratesLib {
    name = "css-color-parser";
    version = "0.1.1";
    hash = "0c8f0ed3a31a72a27b47f9302bbc9a1e8103ce3b4876c553f5714a2e579c952d";
    deps = with allCrates; [  ];
  };
  "css-color-parser_0_1" = css-color-parser_0_1_1;
  "css-color-parser_0" = css-color-parser_0_1_1;}