#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  omdb_0_1_0 = buildCratesLib {
    name = "omdb";
    version = "0.1.0";
    hash = "f0b30cae4f25f182cf35b7c0217e4c58be118d026320614b3dd5227dfde50ee2";
    deps = with allCrates; [ serde hyper serde_json serde_codegen ];
  };
  omdb_0_1_1 = buildCratesLib {
    name = "omdb";
    version = "0.1.1";
    hash = "e5eb0866e2e2b41d114e614a5ad8a5c3c06ba674eb3f1abfbb9de55b0cf5373e";
    deps = with allCrates; [ hyper serde_json serde serde_codegen ];
  };}