#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  racer_0_0_1 = buildCratesLib {
    name = "racer";
    version = "0.0.1";
    hash = "186f5e388bae0e634f45d33e719125f2cf4aaf1271d7e755111fdbb1edb04dcd";
    deps = with allCrates; [  ];
  };
  racer_1_1_0 = buildCratesLib {
    name = "racer";
    version = "1.1.0";
    hash = "99e98245a5b2d1af1348f47ca83ae436e99704db639b1d87f5a47b36717fedb0";
    deps = with allCrates; [  syntex_syntax env_logger typed-arena log all__clap.clap_1_5 toml ];
  };
  "racer_0_0" = racer_0_0_1;
  "racer_0" = racer_0_0_1;
  racer_1_2_0 = buildCratesLib {
    name = "racer";
    version = "1.2.0";
    hash = "00a6db368db3ccddabaeb1b1942ebbdd5a0669df03c781884e966379c8c367dc";
    deps = with allCrates; [  all__syntex_syntax.syntex_syntax_0_24 all__env_logger.env_logger_0_3 all__log.log_0_3 all__clap.clap_1_5 all__toml.toml_0_1 all__typed-arena.typed-arena_1_0 ];
  };
  "racer_1_1" = racer_1_1_0;
  racer_1_2_1 = buildCratesLib {
    name = "racer";
    version = "1.2.1";
    hash = "9aa9de11a083f327ca3f7e1bbd1ed26eedd23cc1a98942b49e3e522115b05088";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__log.log_0_3 all__syntex_syntax.syntex_syntax_0_24 all__clap.clap_1_5 all__toml.toml_0_1 all__typed-arena.typed-arena_1_0 ];
  };
  racer_1_2_2 = buildCratesLib {
    name = "racer";
    version = "1.2.2";
    hash = "2667f0fd6d4b22f73f6aca53ea31da30dc917e61564a6be10d358ac9963ae82a";
    deps = with allCrates; [  all__log.log_0_3 all__syntex_syntax.syntex_syntax_0_24 all__toml.toml_0_1 all__env_logger.env_logger_0_3 all__clap.clap_1_5 all__typed-arena.typed-arena_1_0 ];
  };
  racer_1_2_3 = buildCratesLib {
    name = "racer";
    version = "1.2.3";
    hash = "1ed15daec65f2bd0ad54b889664550dbe980b823e41789a1db97a12f0b1db8be";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__toml.toml_0_1 all__log.log_0_3 all__clap.clap_1_5 all__typed-arena.typed-arena_1_1 all__syntex_syntax.syntex_syntax_0_26 ];
  };
  racer_1_2_4 = buildCratesLib {
    name = "racer";
    version = "1.2.4";
    hash = "26ab596b4f886fa7f51de845c8bac5ac9232bb82523ed21c70aaa211b3a1082d";
    deps = with allCrates; [  all__typed-arena.typed-arena_1_1 all__env_logger.env_logger_0_3 all__clap.clap_1_5 all__syntex_syntax.syntex_syntax_0_26 all__toml.toml_0_1 all__log.log_0_3 ];
  };
  racer_1_2_5 = buildCratesLib {
    name = "racer";
    version = "1.2.5";
    hash = "cbd86d84f4fc3d17711e3003d0a52c01a699dce70b1992ccefa605fe9b0de7c8";
    deps = with allCrates; [  all__typed-arena.typed-arena_1_1 all__env_logger.env_logger_0_3 all__log.log_0_3 all__toml.toml_0_1 all__syntex_syntax.syntex_syntax_0_24 all__clap.clap_1_5 ];
  };
  racer_1_2_6 = buildCratesLib {
    name = "racer";
    version = "1.2.6";
    hash = "503ec18a94935cba0d61518f0e5083d6e1e83557d446ed4f1969a32712dc8cc5";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__typed-arena.typed-arena_1_1 all__clap.clap_1_5 all__syntex_syntax.syntex_syntax_0_24 all__log.log_0_3 all__toml.toml_0_1 ];
  };
  racer_1_2_7 = buildCratesLib {
    name = "racer";
    version = "1.2.7";
    hash = "4b221fd0112595900ea6832fab52c0b9a773fee2023bdd34cf424d8586897b2a";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__log.log_0_3 all__toml.toml_0_1 all__typed-arena.typed-arena_1_1 all__clap.clap_2_2 all__syntex_syntax.syntex_syntax_0_24 ];
  };
  racer_1_2_8 = buildCratesLib {
    name = "racer";
    version = "1.2.8";
    hash = "6772bf74df283e3ac43043cd47e9f4851180a6966533270b3daa5a340227c47d";
    deps = with allCrates; [  all__syntex_syntax.syntex_syntax_0_24 all__env_logger.env_logger_0_3 all__typed-arena.typed-arena_1_1 all__clap.clap_2_2 all__toml.toml_0_1 all__log.log_0_3 ];
  };
  racer_1_2_9 = buildCratesLib {
    name = "racer";
    version = "1.2.9";
    hash = "352fa138e0232715324319e170ac61c0354295c9fbb2282d751b6f85384c858f";
    deps = with allCrates; [  all__syntex_syntax.syntex_syntax_0_24 all__clap.clap_2_2 all__toml.toml_0_1 all__typed-arena.typed-arena_1_1 all__log.log_0_3 all__env_logger.env_logger_0_3 ];
  };
  racer_1_2_10 = buildCratesLib {
    name = "racer";
    version = "1.2.10";
    hash = "73887d937ae9a27aa5dcc0b071fe90708c3dcf3d67b57193b037238dfb9c0592";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__clap.clap_2_2 all__toml.toml_0_1 all__log.log_0_3 all__syntex_syntax.syntex_syntax_0_32 all__typed-arena.typed-arena_1_1 ];
  };
  "racer_1_2" = racer_1_2_10;
  "racer_1" = racer_1_2_10;}