#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libedgegrid_0_0_1 = buildCratesLib {
    name = "libedgegrid";
    version = "0.0.1";
    hash = "b6734bfcbb9c781e906b57094666f3608fb2635d5e7784cf9b8fd8ee95a6280f";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__curl.curl_0_2 all__url.url_0_2 all__sodium-sys.sodium-sys_0_0 all__time.time_0_1 all__vergen.vergen_0_0 ];
  };
  libedgegrid_0_0_2 = buildCratesLib {
    name = "libedgegrid";
    version = "0.0.2";
    hash = "1e81aade52bad289d5c189afc34138a81771dd9c784af2aa0fa7fa53f765d808";
    deps = with allCrates; [  all__log.log_0_3 all__serde_json.serde_json_0_6 all__rustc-serialize.rustc-serialize_0_3 all__curl.curl_0_2 all__sodium-sys.sodium-sys_0_0 all__time.time_0_1 all__url.url_0_2 all__serde.serde_0_6 all__vergen.vergen_0_0 syntex ];
  };
  libedgegrid_0_1_0 = buildCratesLib {
    name = "libedgegrid";
    version = "0.1.0";
    hash = "0847ef10621ada04486e8f1f5f36779faf9f7f0b4e5539ba94067428aada2424";
    deps = with allCrates; [  all__log.log_0_3 all__rustc-serialize.rustc-serialize_0_3 all__url.url_0_2 all__sodium-sys.sodium-sys_0_0 all__serde.serde_0_6 all__serde_json.serde_json_0_6 all__time.time_0_1 all__curl.curl_0_2 all__glob.glob_0_2 all__syntex.syntex_0_22 all__vergen.vergen_0_0 ];
  };
  "libedgegrid_0_0" = libedgegrid_0_0_2;
  libedgegrid_0_1_1 = buildCratesLib {
    name = "libedgegrid";
    version = "0.1.1";
    hash = "3d2a1697f9ef82f1bb1ab2f38a8e30b1ad488a2cdbf2fefca211e754a97eed70";
    deps = with allCrates; [  all__serde.serde_0_6 all__log.log_0_3 all__curl.curl_0_2 all__url.url_0_2 all__time.time_0_1 all__rustc-serialize.rustc-serialize_0_3 all__serde_json.serde_json_0_6 all__sodium-sys.sodium-sys_0_0 all__syntex.syntex_0_26 all__glob.glob_0_2 all__vergen.vergen_0_1 ];
  };
  "libedgegrid_0_1" = libedgegrid_0_1_1;
  "libedgegrid_0" = libedgegrid_0_1_1;}