#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  libelf_0_0_1 = buildCratesLib {
    name = "libelf";
    version = "0.0.1";
    hash = "f4e88eeb436a8aec8d6c60afe333522d2dbfecc79b763b025fa986d573d760a4";
    deps = with allCrates; [ libelf-sys ];
  };}