#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  libxdo-sys_0_0_1 = buildCratesLib {
    name = "libxdo-sys";
    version = "0.0.1";
    hash = "c4da75a7dcb8a95e6be3df4d7662a8b0f08a38210da6880d404d970678b2b40d";
    deps = with allCrates; [ x11 libc ];
  };
  libxdo-sys_0_1_0 = buildCratesLib {
    name = "libxdo-sys";
    version = "0.1.0";
    hash = "dcd31346ff21889c4dac309b3a2c7efdedee9bc7295ba2dcad5e647697f4e649";
    deps = with allCrates; [ x11 libc ];
  };
  libxdo-sys_0_9_0 = buildCratesLib {
    name = "libxdo-sys";
    version = "0.9.0";
    hash = "ef01f0d6ae9da036665cdd58b908b37c014b7caf376dc593e30b641dc456717e";
    deps = with allCrates; [ libc x11 ];
  };
  libxdo-sys_0_10_0 = buildCratesLib {
    name = "libxdo-sys";
    version = "0.10.0";
    hash = "1e094ffd00b53dbef1a1394f2df970ff222210a1ea9f5dcdfd846e8c4c76a1ef";
    deps = with allCrates; [ x11 libc ];
  };}