#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  disjoint-set_0_0_1 = buildCratesLib {
    name = "disjoint-set";
    version = "0.0.1";
    hash = "1e66a7454f5836786a71995af1214b7d1d6b026e36150af2ef3901249bb3e109";
    deps = with allCrates; [  ];
  };
  disjoint-set_0_0_2 = buildCratesLib {
    name = "disjoint-set";
    version = "0.0.2";
    hash = "d102f1a462fdcdddce88d6d46c06c074a2d2749b262230333726b06c52bb7585";
    deps = with allCrates; [  ];
  };
  "disjoint-set_0_0" = disjoint-set_0_0_2;
  "disjoint-set_0" = disjoint-set_0_0_2;}