#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  theban_db_0_4_0 = buildCratesLib {
    name = "theban_db";
    version = "0.4.0";
    hash = "636fad8b1cf76354fe090b0fd213fdd04f0653c75c4a09699826c63b8ffdb25e";
    deps = with allCrates; [  all__rmp.rmp_0_7 theban_interval_tree memrange ];
  };
  theban_db_0_4_1 = buildCratesLib {
    name = "theban_db";
    version = "0.4.1";
    hash = "3c0b73b72ddf7b68539c6da0b0a1bf6fca584c45720539475ce433d49b0ea8cd";
    deps = with allCrates; [  all__rmp.rmp_0_7 memrange theban_interval_tree ];
  };
  theban_db_0_4_2 = buildCratesLib {
    name = "theban_db";
    version = "0.4.2";
    hash = "2fbe3208b97ae6500cac9fcdc673fdf75f51c202a5d7e5aecce2ab6b6de0f9be";
    deps = with allCrates; [  theban_interval_tree memrange all__rmp.rmp_0_7 ];
  };
  theban_db_0_5_0 = buildCratesLib {
    name = "theban_db";
    version = "0.5.0";
    hash = "448b4b71f0af66c13e1dc5462ea08ea85522d257c7a770c295eb10062f63ca41";
    deps = with allCrates; [  memrange all__rmp.rmp_0_7 theban_interval_tree ];
  };
  "theban_db_0_4" = theban_db_0_4_2;
  theban_db_0_5_1 = buildCratesLib {
    name = "theban_db";
    version = "0.5.1";
    hash = "7739374e852023387f481cc138e66a4b3ee6f7f044f37b813479fffbf1d40be6";
    deps = with allCrates; [  theban_interval_tree all__rmp.rmp_0_7 memrange ];
  };
  theban_db_0_5_2 = buildCratesLib {
    name = "theban_db";
    version = "0.5.2";
    hash = "efb826a561ad1c2ed78fc27aaf0b4196490ff18d89dc120889582c8fb95f4cea";
    deps = with allCrates; [  theban_interval_tree memrange all__rmp.rmp_0_7 ];
  };
  theban_db_0_6_0 = buildCratesLib {
    name = "theban_db";
    version = "0.6.0";
    hash = "a22c218ba2fce4b5db79b39e8907445b8b003a3c6a69bb472e73c1a3c1b8a9b7";
    deps = with allCrates; [  memrange all__quick-error.quick-error_1_0_0 rustc-serialize all__rmp.rmp_0_7 theban_interval_tree ];
  };
  "theban_db_0_5" = theban_db_0_5_2;
  theban_db_0_7_0 = buildCratesLib {
    name = "theban_db";
    version = "0.7.0";
    hash = "6d9a95fcd57360cc76a317a676c2ec482861d0ecd65b62f00564e2b2aadf18b5";
    deps = with allCrates; [  all__quick-error.quick-error_1_0_0 rustc-serialize all__rmp.rmp_0_7 theban_interval_tree memrange ];
  };
  "theban_db_0_6" = theban_db_0_6_0;
  "theban_db_0_7" = theban_db_0_7_0;
  "theban_db_0" = theban_db_0_7_0;}