#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  theban_interval_tree_0_6_2 = buildCratesLib {
    name = "theban_interval_tree";
    version = "0.6.2";
    hash = "3fd52e94e1b1603a64a9548cae6af47fa5a6ace15bfdbaf385edff40f69b89f1";
    deps = with allCrates; [ rand memrange time ];
  };
  theban_interval_tree_0_7_0 = buildCratesLib {
    name = "theban_interval_tree";
    version = "0.7.0";
    hash = "8f53098522793ceab6a4d01de8b2280f22dba9edf950e62b29741a2a6e71df54";
    deps = with allCrates; [ rand time memrange ];
  };}