#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tozny_auth_1_1_0 = buildCratesLib {
    name = "tozny_auth";
    version = "1.1.0";
    hash = "770aaf6e3cfccb7c0be4cea797f89929e2643dbccf7186d18791420209affde0";
    deps = with allCrates; [  all__rand.rand_0_2 all__url.url_0_2 all__chrono.chrono_0_2 all__rustc-serialize.rustc-serialize_0_3 all__hyper.hyper_0_3 all__rust-crypto.rust-crypto_0_2 ];
  };
  "tozny_auth_1_1" = tozny_auth_1_1_0;
  "tozny_auth_1" = tozny_auth_1_1_0;}