#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  newtype_derive_0_1_1 = buildCratesLib {
    name = "newtype_derive";
    version = "0.1.1";
    hash = "19330fedb0b4340e9abbb75469aec641af8e801f18fb4670b5dd3ba0f952b43b";
    deps = with allCrates; [ ];
  };
  newtype_derive_0_1_2 = buildCratesLib {
    name = "newtype_derive";
    version = "0.1.2";
    hash = "8ae5d21b884a8a46d82131e27b6f68693eefe7a6c9af206cacb6fa16d7ba6016";
    deps = with allCrates; [ ];
  };
  newtype_derive_0_1_3 = buildCratesLib {
    name = "newtype_derive";
    version = "0.1.3";
    hash = "47fcd2bec7a63a4b94fad6e70a8f45433b6e6822a9b194b700d7b7bb3a5a90a1";
    deps = with allCrates; [ ];
  };
  newtype_derive_0_1_4 = buildCratesLib {
    name = "newtype_derive";
    version = "0.1.4";
    hash = "4b679b023e5cf58a5d8e21632858477fd69e8ccec9e8bd9b923a966bd5e30e2c";
    deps = with allCrates; [ ];
  };
  newtype_derive_0_1_6 = buildCratesLib {
    name = "newtype_derive";
    version = "0.1.6";
    hash = "ac8cd24d9f185bb7223958d8c1ff7a961b74b1953fd05dba7cc568a63b3861ec";
    deps = with allCrates; [ rustc_version ];
  };}