#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  karplus_0_1_0 = buildCratesLib {
    name = "karplus";
    version = "0.1.0";
    hash = "c97e48a13cf6d17c421f97581603cb6a5771c9c7d759a955257f44876dbfc47c";
    deps = with allCrates; [ rand ];
  };}