#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  debian_0_1_0 = buildCratesLib {
    name = "debian";
    version = "0.1.0";
    hash = "8c6e75b24668059301069b6231a9d51c95ddb54a27e19c6eb89f9c9d3c672b93";
    deps = with allCrates; [ time tempdir log chrono ];
  };}