#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  gedcomx_date_0_0_1 = buildCratesLib {
    name = "gedcomx_date";
    version = "0.0.1";
    hash = "31433b36bbcc62c6ff388d8278823ec47702634bd16e989fa45675ac3fd08b7e";
    deps = with allCrates; [ nom ];
  };}