#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  capnp-futures_0_0_1 = buildCratesLib {
    name = "capnp-futures";
    version = "0.0.1";
    hash = "2cbeb29592fbb3e13fb8954c4120137945cf40a5f12bfd156abffaebb6cd34be";
    deps = with allCrates; [  all__futures.futures_0_1 all__byteorder.byteorder_0_5 all__capnp.capnp_0_7 ];
  };
  capnp-futures_0_0_2 = buildCratesLib {
    name = "capnp-futures";
    version = "0.0.2";
    hash = "e040dbc0ac20641b848955e188359851b20d20d9d9ea433ce88ed925e3b6b49b";
    deps = with allCrates; [  all__byteorder.byteorder_0_5 all__capnp.capnp_0_7 all__futures.futures_0_1 ];
  };
  "capnp-futures_0_0" = capnp-futures_0_0_2;
  "capnp-futures_0" = capnp-futures_0_0_2;}