#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  tealdeer_0_2_0 = buildCratesLib {
    name = "tealdeer";
    version = "0.2.0";
    hash = "9d4189562f79ede17cfe066205bb01c9eec87883c9f783c4f8ad78c13fc8e029";
    deps = with allCrates; [ flate2 curl tar time log walkdir ansi_term docopt rustc-serialize ];
  };
  tealdeer_0_3_0 = buildCratesLib {
    name = "tealdeer";
    version = "0.3.0";
    hash = "0d875b20603e10187a98d54804f025b70787d61398f51b8701e3941dd2f8cac7";
    deps = with allCrates; [ ansi_term rustc-serialize walkdir flate2 xdg log docopt curl tar time ];
  };
  tealdeer_0_4_0 = buildCratesLib {
    name = "tealdeer";
    version = "0.4.0";
    hash = "356292978f1ac7f8b829caba9900f46b8784d93f722c1390b3a8588c76860693";
    deps = with allCrates; [ time xdg log flate2 ansi_term curl walkdir docopt tar rustc-serialize ];
  };}