#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  nbits_vec_0_1_0 = buildCratesLib {
    name = "nbits_vec";
    version = "0.1.0";
    hash = "bd86e5cd36faf17fe01155041b3aaeab0a9c64ec55fd97da48afcff30a234f85";
    deps = with allCrates; [ num typenum ];
  };
  nbits_vec_0_1_1 = buildCratesLib {
    name = "nbits_vec";
    version = "0.1.1";
    hash = "3953d79ea0c7fe640e6fd56fc8e5fc796e767fd94210565414b0970c36300b82";
    deps = with allCrates; [ typenum num ];
  };}