#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  tsm-sys_0_1_0 = buildCratesLib {
    name = "tsm-sys";
    version = "0.1.0";
    hash = "313f2a89bd55762cbc30448907fb66fac447c647f899fbeffd95e663ecfd9b8c";
    deps = with allCrates; [ libc gcc glob ];
  };}