#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  clock_ticks_0_0_1 = buildCratesLib {
    name = "clock_ticks";
    version = "0.0.1";
    hash = "6cf53ef1dc351f227d3ef5237d3736fe0cb10f3fc154a1f0834363ed95939ae2";
    deps = with allCrates; [  ];
  };
  clock_ticks_0_0_2 = buildCratesLib {
    name = "clock_ticks";
    version = "0.0.2";
    hash = "eaab9ca97a634e8a636f8e362a13c106952d80a575bac09beaf7238d6854487e";
    deps = with allCrates; [  ];
  };
  clock_ticks_0_0_3 = buildCratesLib {
    name = "clock_ticks";
    version = "0.0.3";
    hash = "6349fd4aa92a064b4476827849eeb995ee86d6127abef767bd06ee9297b904da";
    deps = with allCrates; [  ];
  };
  clock_ticks_0_0_4 = buildCratesLib {
    name = "clock_ticks";
    version = "0.0.4";
    hash = "3c8b4e925c266284bfec1001dd374a1a8e9d43c4e8038dfe0c051cee9c1ea672";
    deps = with allCrates; [  ];
  };
  clock_ticks_0_0_5 = buildCratesLib {
    name = "clock_ticks";
    version = "0.0.5";
    hash = "3c1c6644e669ebf7db75f06c58193aa40f0c9d8aee69573ef51906a53d445b9e";
    deps = with allCrates; [  libc ];
  };
  clock_ticks_0_0_6 = buildCratesLib {
    name = "clock_ticks";
    version = "0.0.6";
    hash = "af2a00c56fb3ca01175086cecb8e87142744ee29c4ec8b504b81ce8557cdb1d9";
    deps = with allCrates; [  libc ];
  };
  clock_ticks_0_1_0 = buildCratesLib {
    name = "clock_ticks";
    version = "0.1.0";
    hash = "da9bd98fefcf1904a3f80ead86d366d9373c34db7b8a8e48c1fdcaac4787800d";
    deps = with allCrates; [  all__libc.libc_0_1 ];
  };
  "clock_ticks_0_0" = clock_ticks_0_0_6;
  "clock_ticks_0_1" = clock_ticks_0_1_0;
  "clock_ticks_0" = clock_ticks_0_1_0;}