#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  gtld-data_0_2_1 = buildCratesLib {
    name = "gtld-data";
    version = "0.2.1";
    hash = "6176056906d82cfac7ad7b7daea49ad94f009a2d58cdeb0e0d834bc522db0c04";
    deps = with allCrates; [ ];
  };
  gtld-data_0_2_2 = buildCratesLib {
    name = "gtld-data";
    version = "0.2.2";
    hash = "ce9214bebe370172832ca594f6b53db78bb87c1d71931caf7314db4c052c41af";
    deps = with allCrates; [ ];
  };
  gtld-data_0_2_3 = buildCratesLib {
    name = "gtld-data";
    version = "0.2.3";
    hash = "e5a5a6b81a035d9e57eb74fffe22fea3ed3684bb7e09ca2b14bfc8a5364056d3";
    deps = with allCrates; [ ];
  };
  gtld-data_0_2_4 = buildCratesLib {
    name = "gtld-data";
    version = "0.2.4";
    hash = "63878b276a237e329dcc8c89aa3be91fab16fc077c7a612d2425e32542455e94";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_0 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.0";
    hash = "1e0e1005246f8845b1ff161ea612f655c8893055f24b80a0a6321d5cb1e20c9e";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_1 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.1";
    hash = "88353b5056883da59ff380c9c96df8583f7b57f82bd64e619e484af663f706c5";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_3 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.3";
    hash = "ff072c2393caddd511412fc925396281da806a8d8ad2da449ce419906c7e5149";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_4 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.4";
    hash = "355fce16769fe5481cb881bbf077c28074b86427c64b15f11e992e0b70d5a9c4";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_5 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.5";
    hash = "c152918989775ceb7f363ca0e351e463a0c5aa9c20c71036c079fa8ecb1b9be6";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_6 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.6";
    hash = "2a3805d18c4d3e4f0377e057287dcbac4b2f3183ed55195e60a06c123e92e994";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_7 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.7";
    hash = "b593331bcbb1f00087e72381ada49dad1c41d90c92c0ce7636dcecfe80aaaadd";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_9 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.9";
    hash = "f1bafaa3b6a69a453b28d04ab834d3084c69be55486a692fa0ab9d48cd0b462d";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_10 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.10";
    hash = "8cfe9eff531a4e9d57d104cbcfa257060eb15bd438ffca98b67dca40b935c871";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_11 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.11";
    hash = "7511c87870ab7422bb8147eff9df5a6253685d9ce9e09ca7603c6cbeca04269d";
    deps = with allCrates; [ ];
  };
  gtld-data_0_3_12 = buildCratesLib {
    name = "gtld-data";
    version = "0.3.12";
    hash = "ac12ddd706effb35918f3a4aaee543bb873d82c1288d2683cde2a741a143713a";
    deps = with allCrates; [ ];
  };
  gtld-data_0_4_0 = buildCratesLib {
    name = "gtld-data";
    version = "0.4.0";
    hash = "26f122fb3879de9320ba13344967ee51812509018dbae38acd30e2ee8c5dae8c";
    deps = with allCrates; [ select curl ];
  };
  gtld-data_0_4_1 = buildCratesLib {
    name = "gtld-data";
    version = "0.4.1";
    hash = "084e3e0e8f23658ee26d543adda2d54484254fab18fde2794197a5cac5083840";
    deps = with allCrates; [ curl select ];
  };}