#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  restructure_0_1_0 = buildCratesLib {
    name = "restructure";
    version = "0.1.0";
    hash = "96bdd3859821ebe50d93c9dbb98f423927eeb617afb4f2f10d4610059b557853";
    deps = with allCrates; [  all__regex.regex_0_1 ];
  };
  restructure_0_1_1 = buildCratesLib {
    name = "restructure";
    version = "0.1.1";
    hash = "d3ea1f09c52b5235bd827fa505b73b5e16101856036c535d6ef741eb0cf3bfd7";
    deps = with allCrates; [  all__regex.regex_0_1 ];
  };
  "restructure_0_1" = restructure_0_1_1;
  "restructure_0" = restructure_0_1_1;}