#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  warp10_0_1_0 = buildCratesLib {
    name = "warp10";
    version = "0.1.0";
    hash = "b2888178d85c9587594a566132fbcd12eb92db021d2812580929991679336242";
    deps = with allCrates; [ url itertools hyper time ];
  };
  warp10_0_2_0 = buildCratesLib {
    name = "warp10";
    version = "0.2.0";
    hash = "c9fa21fe8095376ba72e8fc038db8153c6e1b54ecfda5c11cfbd65e47d1f68bc";
    deps = with allCrates; [ hyper url itertools time ];
  };
  warp10_0_3_0 = buildCratesLib {
    name = "warp10";
    version = "0.3.0";
    hash = "e89c5fbb59eab1d110b4767be48c6320fa0280a7a348b63bb42cbb3e51cf5ceb";
    deps = with allCrates; [ hyper time url itertools ];
  };
  warp10_0_4_0 = buildCratesLib {
    name = "warp10";
    version = "0.4.0";
    hash = "1c13218dbb466e622918951a44954d83d0fa07dd88e6a0cc445920167232a900";
    deps = with allCrates; [ url hyper itertools time ];
  };
  warp10_0_4_1 = buildCratesLib {
    name = "warp10";
    version = "0.4.1";
    hash = "493faae9594f94175839db78734d9309a8bcf4da2e48a4cea06e369e403b7dab";
    deps = with allCrates; [ itertools hyper time url ];
  };}