#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  largo_0_0_1 = buildCratesLib {
    name = "largo";
    version = "0.0.1";
    hash = "c9481de0f02b5b71ef734860657d6dfc80c206e2997d6ad9311600a5181874bc";
    deps = with allCrates; [  ];
  };
  largo_0_0_2 = buildCratesLib {
    name = "largo";
    version = "0.0.2";
    hash = "92e53f119cc2f34bf127d4a847eae928ec39918251c4f541a5aa824fa75b7cb8";
    deps = with allCrates; [  dotenv rand chrono libc ];
  };
  "largo_0_0" = largo_0_0_2;
  "largo_0" = largo_0_0_2;}