#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  beanstalkd-queue_0_1_0 = buildCratesLib {
    name = "beanstalkd-queue";
    version = "0.1.0";
    hash = "7000a2d9ec38e02a34c217e11455f200d25d6e9247f898c81ee308e8486066c4";
    deps = with allCrates; [ beanstalkd ];
  };}