#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  multi-input_0_0_1 = buildCratesLib {
    name = "multi-input";
    version = "0.0.1";
    hash = "54d3dc28e06db0ab76db1e90f98b92f5928bca1397d02486f65ac57d6d867864";
    deps = with allCrates; [ libc winapi kernel32-sys hid-sys user32-sys ];
  };}