#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  msdrm-sys_0_0_1 = buildCratesLib {
    name = "msdrm-sys";
    version = "0.0.1";
    hash = "a4a3763d180bcb7cdd51faec28d82dc881d583903013461bf156392a8235472e";
    deps = with allCrates; [  winapi ];
  };
  "msdrm-sys_0_0" = msdrm-sys_0_0_1;
  "msdrm-sys_0" = msdrm-sys_0_0_1;}