#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  drossel_0_1_0 = buildCratesLib {
    name = "drossel";
    version = "0.1.0";
    hash = "63a2d69961cabbc0be7e76358fd3bad77dc2d39b66044a4ff88008dcb41b0588";
    deps = with allCrates; [ leveldb drossel-journal strand ];
  };}