#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  nautilus-extension_0_1_0 = buildCratesLib {
    name = "nautilus-extension";
    version = "0.1.0";
    hash = "d03463e81c45a733d20ea93eaae833827c7220af175f87e2c478bcd152232fcd";
    deps = with allCrates; [ gio-sys gtk-sys nautilus-extension-sys gobject-sys lazy_static glib-sys libc ];
  };
  nautilus-extension_0_1_1 = buildCratesLib {
    name = "nautilus-extension";
    version = "0.1.1";
    hash = "ae79276a9da4cfc5376e9294e023970370759a751ef01baca13b466947e04eca";
    deps = with allCrates; [ gio-sys glib-sys gobject-sys lazy_static nautilus-extension-sys gtk-sys libc ];
  };
  nautilus-extension_0_1_2 = buildCratesLib {
    name = "nautilus-extension";
    version = "0.1.2";
    hash = "b6b66fc6b2e7bebad1a72fade363afb485d71c357e490d8df0898ba23e871636";
    deps = with allCrates; [ gtk-sys gobject-sys glib-sys gio-sys libc lazy_static nautilus-extension-sys ];
  };
  nautilus-extension_0_2_0 = buildCratesLib {
    name = "nautilus-extension";
    version = "0.2.0";
    hash = "e0f752f90ea28936578ca25a622e9d29dc2196c19b3d5f26648cbd1a554fa9f1";
    deps = with allCrates; [ glib-sys gobject-sys gio-sys gtk-sys nautilus-extension-sys libc lazy_static ];
  };
  nautilus-extension_0_2_1 = buildCratesLib {
    name = "nautilus-extension";
    version = "0.2.1";
    hash = "05a4e3a06bff5520e9709547b4e64c1d8ee858598f028715131826f1bb554670";
    deps = with allCrates; [ nautilus-extension-sys lazy_static libc gobject-sys gtk-sys gio-sys glib-sys ];
  };}