#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ncollide_math_0_2_0 = buildCratesLib {
    name = "ncollide_math";
    version = "0.2.0";
    hash = "9d1c7226493162c49935704b72fc644e07dc519282c433eb7b0fb21912f76ca1";
    deps = with allCrates; [  num rustc-serialize rand nalgebra ];
  };
  ncollide_math_0_2_1 = buildCratesLib {
    name = "ncollide_math";
    version = "0.2.1";
    hash = "dbb975cdc3829edb260d3866a504301005e4ae4d069cd53efbe06e1664404e55";
    deps = with allCrates; [  nalgebra rand rustc-serialize num ];
  };
  ncollide_math_0_2_2 = buildCratesLib {
    name = "ncollide_math";
    version = "0.2.2";
    hash = "9edbb01f565c095db22b0636c875789e076ece28634a6212e5c92022d331df99";
    deps = with allCrates; [  nalgebra num rand rustc-serialize ];
  };
  ncollide_math_0_3_0 = buildCratesLib {
    name = "ncollide_math";
    version = "0.3.0";
    hash = "b3009eb1c2eb1ec3c400c05af2d18e61ca681b89d38d09424f21ae464f3bd999";
    deps = with allCrates; [  nalgebra num rand rustc-serialize ];
  };
  "ncollide_math_0_2" = ncollide_math_0_2_2;
  ncollide_math_0_3_1 = buildCratesLib {
    name = "ncollide_math";
    version = "0.3.1";
    hash = "39851c628371c2dd22f227a28991de8cf8d4f8daeb82ede398df1c8e2ed4bf3c";
    deps = with allCrates; [  rand rustc-serialize nalgebra num ];
  };
  ncollide_math_0_4_0 = buildCratesLib {
    name = "ncollide_math";
    version = "0.4.0";
    hash = "c731e382a212c55ae3b432b0c772ca80dfd183e078ca23bc2fbfbc00b2c823ad";
    deps = with allCrates; [  rustc-serialize nalgebra num rand ];
  };
  "ncollide_math_0_3" = ncollide_math_0_3_1;
  ncollide_math_0_5_0 = buildCratesLib {
    name = "ncollide_math";
    version = "0.5.0";
    hash = "02b6d034e51e69922eb3940f74426833efc9683ab9c2f58554f49a0461785ddb";
    deps = with allCrates; [  num nalgebra rand rustc-serialize ];
  };
  "ncollide_math_0_4" = ncollide_math_0_4_0;
  "ncollide_math_0_5" = ncollide_math_0_5_0;
  "ncollide_math_0" = ncollide_math_0_5_0;}