#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  serde_xml_0_6_0 = buildCratesLib {
    name = "serde_xml";
    version = "0.6.0";
    hash = "e12dae782c3af9b87a49080a6f508050b986964d4e728ee58835868355420b2e";
    deps = with allCrates; [ log serde ];
  };
  serde_xml_0_6_1 = buildCratesLib {
    name = "serde_xml";
    version = "0.6.1";
    hash = "26292bd978aa3c6338f74388cee6f5756589d55adcf066d4be449c3525454da7";
    deps = with allCrates; [ serde log ];
  };
  serde_xml_0_6_2 = buildCratesLib {
    name = "serde_xml";
    version = "0.6.2";
    hash = "c5ef7eaaee35d07d313b074c1a6bf9a199577bf9780352b11eb9bd10c1c02de8";
    deps = with allCrates; [ log serde ];
  };
  serde_xml_0_6_3 = buildCratesLib {
    name = "serde_xml";
    version = "0.6.3";
    hash = "c1a28e79c70e87feb8fde1633eaf0e8f058f5b266e3978df1418e5a4479ea351";
    deps = with allCrates; [ log serde ];
  };
  serde_xml_0_7_0 = buildCratesLib {
    name = "serde_xml";
    version = "0.7.0";
    hash = "e30804b103af1482c6c20bd3774c3672ad86ee34af3e6ba7e79fadc7ed82d219";
    deps = with allCrates; [ serde log ];
  };
  serde_xml_0_7_1 = buildCratesLib {
    name = "serde_xml";
    version = "0.7.1";
    hash = "b0d5b2c24e76417805e8c2d0fb98e9083c4095c3befd3dafb04cfdc3baa4ace6";
    deps = with allCrates; [ serde log ];
  };
  serde_xml_0_8_0 = buildCratesLib {
    name = "serde_xml";
    version = "0.8.0";
    hash = "3f5163076f592ae598c32decfcd7e093a05f841b5d2a09745c68d022b4e12cff";
    deps = with allCrates; [ serde log ];
  };
  serde_xml_0_8_1 = buildCratesLib {
    name = "serde_xml";
    version = "0.8.1";
    hash = "2740253750814daddf54c5b5311886c034bc0efaccd9ae617a7cf46bd5323506";
    deps = with allCrates; [ serde log ];
  };
  serde_xml_0_9_0 = buildCratesLib {
    name = "serde_xml";
    version = "0.9.0";
    hash = "d84df96e3f5ae09560ee1cf87bee8f46ee9859f8ee9fa8c76dacde9b7924e47f";
    deps = with allCrates; [ serde log ];
  };
  serde_xml_0_9_1 = buildCratesLib {
    name = "serde_xml";
    version = "0.9.1";
    hash = "56346e526b0828da6b7a6a867076a6ae22d188ffd7a5511b4ffbd815def0ba95";
    deps = with allCrates; [ serde log ];
  };}