#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  serde_derive_0_8_4 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.4";
    hash = "2ade958097a21deadb84faa582066f9867d5fedb8f8b4f6d2a9ab0d4724a6c8f";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_6 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.6";
    hash = "a645ca2f9ceb3c5f2a51b1afd8c50bba6a7d7fee612cafdfe5e20f57a9987714";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_7 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.7";
    hash = "3d5cc6a559ece9d9ef70860447a5367a6b6745c25b8d84ad00d00aa6d124b306";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_8 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.8";
    hash = "d77b14207fabd204104f91222a8bb54eab3f313dfe7c46435d23c639f7a7a0b2";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_9 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.9";
    hash = "31169f3974f0d56160460dc5ab53a627331a6c9c3d0d8c1ab59071bb7941da65";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_10 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.10";
    hash = "658f0eea61a92a8574de65f05b84e210e08d5de5943fdc9a3d87ac17553803b9";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_11 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.11";
    hash = "39cf81d86cc21c37d7f458e62935f0f8a696e12b03a6fab9c15d3f5e4fb7f22b";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_12 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.12";
    hash = "2c7c2b01e85ca1330ba408325f6e85b8b4bf980320b0bd3bc366510e457c443f";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_13 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.13";
    hash = "019e4df3367c24623cadce1a2e4502ccd094a2072f0fe21d8ecbd64f2f411a2a";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_14 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.14";
    hash = "0a028b0cf4e249ac868938767d3275e561942feff36278575e5fb7b07e260cc9";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_15 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.15";
    hash = "d8a43a5a4613bf579925b115e86521d06bb2cddc45ff2641905754c47bc5146e";
    deps = with allCrates; [ serde_codegen post-expansion ];
  };
  serde_derive_0_8_16 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.16";
    hash = "de0edf3d328158ba2bbb0214427343881e5034aeb8df43cec66f9af6c25836d0";
    deps = with allCrates; [ serde_codegen post-expansion ];
  };
  serde_derive_0_8_17 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.17";
    hash = "c6a73f0e5fc193668afa2a714bf8397063af46e6c8df72686e53fbac15b2e38c";
    deps = with allCrates; [ post-expansion serde_codegen ];
  };
  serde_derive_0_8_18 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.18";
    hash = "d91be8acdeb9128d3a074986a36b90fc8ad0a3001c6bd1231aea219ae790aa4a";
    deps = with allCrates; [ serde_codegen ];
  };
  serde_derive_0_8_19 = buildCratesLib {
    name = "serde_derive";
    version = "0.8.19";
    hash = "a4b541549c4207d3602c9abcc3e31252e91751674264eb85c103bb20197054b4";
    deps = with allCrates; [ serde_codegen ];
  };}