#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  html5ever_0_1_0 = buildCratesLib {
    name = "html5ever";
    version = "0.1.0";
    hash = "b26fed3b1297664a2e4fcece52f95ff2fbce56becb1a0fcbc7796b958294c7dc";
    deps = with allCrates; [  all__log.log_0 all__time.time_0 all__string_cache.string_cache_0 all__html5ever_macros.html5ever_macros_0_1 all__phf_macros.phf_macros_0_7 all__phf.phf_0_7 all__mac.mac_0 all__string_cache_plugin.string_cache_plugin_0 ];
  };
  html5ever_0_1_1 = buildCratesLib {
    name = "html5ever";
    version = "0.1.1";
    hash = "03dee027455ca3b31fd7512b7f9071b373733597e01cbb4a2dde2db29e9ee7de";
    deps = with allCrates; [  all__mac.mac_0 all__log.log_0 all__string_cache.string_cache_0 all__phf.phf_0_7 all__phf_macros.phf_macros_0_7 all__html5ever_macros.html5ever_macros_0_1 all__string_cache_plugin.string_cache_plugin_0 all__time.time_0 ];
  };
  html5ever_0_2_0 = buildCratesLib {
    name = "html5ever";
    version = "0.2.0";
    hash = "5c2d6e6b8426a88658a85586a44ffb305ce5a2a8c7c5d71060423c586cd47945";
    deps = with allCrates; [  all__tendril.tendril_0_1 all__phf.phf_0_7 all__string_cache_plugin.string_cache_plugin_0 all__html5ever_macros.html5ever_macros_0_1 all__phf_macros.phf_macros_0_7 all__log.log_0 all__string_cache.string_cache_0 all__time.time_0 all__mac.mac_0 ];
  };
  "html5ever_0_1" = html5ever_0_1_1;
  html5ever_0_2_1 = buildCratesLib {
    name = "html5ever";
    version = "0.2.1";
    hash = "4ee98a9ef86166254bc9a57bfc32c7e1670eb132d6306f7d4b94c553ea54926b";
    deps = with allCrates; [  all__log.log_0 all__string_cache.string_cache_0_1 all__rc.rc_0_1 all__tendril.tendril_0_1 all__mac.mac_0 all__phf.phf_0_7 all__time.time_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_2_2 = buildCratesLib {
    name = "html5ever";
    version = "0.2.2";
    hash = "4594201076adfe834c11e2d60e000f9aeb12b1773d29c76c0713f3a2dbe4f849";
    deps = with allCrates; [  all__time.time_0 all__rc.rc_0_1 all__log.log_0 all__phf.phf_0_7 all__string_cache.string_cache_0_1 all__tendril.tendril_0_1 all__mac.mac_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_2_3 = buildCratesLib {
    name = "html5ever";
    version = "0.2.3";
    hash = "9294faa3efe3630d2a357c67a3bbf7d1f0cdee39e33c2029b466fe4ea34d6f30";
    deps = with allCrates; [  all__log.log_0 all__string_cache.string_cache_0_1 all__phf.phf_0_7 all__rc.rc_0_1 all__tendril.tendril_0_1 all__time.time_0 all__mac.mac_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_2_4 = buildCratesLib {
    name = "html5ever";
    version = "0.2.4";
    hash = "e4088bba61482dfa988bc8205e3f59444fc0533f0686c41c39c16c8d2434ad4a";
    deps = with allCrates; [  all__string_cache.string_cache_0_1 all__rc.rc_0_1 all__tendril.tendril_0_1 all__mac.mac_0 all__time.time_0 all__phf.phf_0_7 all__log.log_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_2_5 = buildCratesLib {
    name = "html5ever";
    version = "0.2.5";
    hash = "d590375ba1b38a39c504198fad7fd1222ee75a03e273419c14953f4d4d3db811";
    deps = with allCrates; [  all__time.time_0 all__log.log_0 all__phf.phf_0_7 all__rc.rc_0_1 all__string_cache.string_cache_0_1 all__mac.mac_0 all__tendril.tendril_0_1 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_2_6 = buildCratesLib {
    name = "html5ever";
    version = "0.2.6";
    hash = "583ccfd77bd291cfbcc8136220f39b570d665a5e55aaa2fb39e0ed76e7d36752";
    deps = with allCrates; [  all__time.time_0 all__string_cache.string_cache_0_1 all__log.log_0 all__phf.phf_0_7 all__tendril.tendril_0_1 all__rc.rc_0_1 all__mac.mac_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_2_7 = buildCratesLib {
    name = "html5ever";
    version = "0.2.7";
    hash = "860ac1b53925dac888668654272df4a7b1231d973b26f598b03f5718b5bbe2a1";
    deps = with allCrates; [  all__rc.rc_0_1 all__string_cache.string_cache_0_1 all__time.time_0 all__log.log_0 all__mac.mac_0 all__tendril.tendril_0_1 all__phf.phf_0_7 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_2_8 = buildCratesLib {
    name = "html5ever";
    version = "0.2.8";
    hash = "e9a08a0e9c45134e34658103bf7380882020bff867ccc4e030074327c9a60ace";
    deps = with allCrates; [  all__string_cache.string_cache_0_1 all__mac.mac_0 all__phf.phf_0_7 all__log.log_0 all__time.time_0 all__tendril.tendril_0_1 all__rc.rc_0_1 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_2_9 = buildCratesLib {
    name = "html5ever";
    version = "0.2.9";
    hash = "06bf238d2caa7f47059c1c439e077529ec98e01ceb18a99f135ee91c42b52efb";
    deps = with allCrates; [  all__phf.phf_0_7 all__mac.mac_0 all__tendril.tendril_0_1 all__rc.rc_0_1 all__string_cache.string_cache_0_1 all__log.log_0 all__time.time_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_2_10 = buildCratesLib {
    name = "html5ever";
    version = "0.2.10";
    hash = "274593a7921ead4bd6550241f054555acb1f109cce7301799ce7fe5c3feb7b06";
    deps = with allCrates; [  all__log.log_0 all__string_cache.string_cache_0_1 all__time.time_0 all__mac.mac_0 all__tendril.tendril_0_1 all__phf.phf_0_7 all__rc.rc_0_1 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_2_11 = buildCratesLib {
    name = "html5ever";
    version = "0.2.11";
    hash = "8b9be3c1a1ffd7e9a67d66a049cc869aa40ed9c20bc7cb43b3d157ff3f1e4200";
    deps = with allCrates; [  all__time.time_0 all__tendril.tendril_0_1 all__log.log_0 all__rc.rc_0_1 all__phf.phf_0_7 all__string_cache.string_cache_0_2 all__mac.mac_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_3_0 = buildCratesLib {
    name = "html5ever";
    version = "0.3.0";
    hash = "3e649700330975b9d7f6f0fcfb706d00483923bdef4845cfb6d2025fe53da59e";
    deps = with allCrates; [  all__mac.mac_0 all__tendril.tendril_0_2 all__log.log_0 all__time.time_0 all__phf.phf_0_7 all__string_cache.string_cache_0_2 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "html5ever_0_2" = html5ever_0_2_11;
  html5ever_0_4_0 = buildCratesLib {
    name = "html5ever";
    version = "0.4.0";
    hash = "c49eaffb158cbc637bbc19771b0a341168f4955219692d1fc9b9607bfd842bc5";
    deps = with allCrates; [  all__time.time_0 all__string_cache.string_cache_0_2 all__log.log_0 all__mac.mac_0 all__phf.phf_0_7 all__tendril.tendril_0_2 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "html5ever_0_3" = html5ever_0_3_0;
  html5ever_0_4_1 = buildCratesLib {
    name = "html5ever";
    version = "0.4.1";
    hash = "0b9f226b2d19ddd989e7b11c2631f5c6104595608a519379a7c66b50a0645d07";
    deps = with allCrates; [  all__log.log_0 all__tendril.tendril_0_2 all__time.time_0 all__phf.phf_0_7 all__string_cache.string_cache_0_2 all__mac.mac_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_4_2 = buildCratesLib {
    name = "html5ever";
    version = "0.4.2";
    hash = "8d7f1794cb23fb66ef9161ee7b47a55c4513bf49819ebc8098873f5db44bb7c5";
    deps = with allCrates; [  all__time.time_0 all__tendril.tendril_0_2 all__string_cache.string_cache_0_2 all__phf.phf_0_7 all__mac.mac_0 all__log.log_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_5_0 = buildCratesLib {
    name = "html5ever";
    version = "0.5.0";
    hash = "d8889f089d81637c7edd94d822f8842ab50ca64ddce097bb8a1a9593d524d300";
    deps = with allCrates; [  all__string_cache.string_cache_0_2 all__log.log_0 all__time.time_0 all__mac.mac_0 all__phf.phf_0_7 all__tendril.tendril_0_2 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "html5ever_0_4" = html5ever_0_4_2;
  html5ever_0_5_1 = buildCratesLib {
    name = "html5ever";
    version = "0.5.1";
    hash = "16afe1f7b7a0716f6710cfff344ea039fdc63fa44240f5703d372aa166c07f2c";
    deps = with allCrates; [  all__string_cache.string_cache_0_2 all__time.time_0 all__tendril.tendril_0_2 all__phf.phf_0_7 all__log.log_0 all__mac.mac_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_5_2 = buildCratesLib {
    name = "html5ever";
    version = "0.5.2";
    hash = "9904ef1edf0f09220d7ec373893c6bb99b71d8c187877c076c0648bfb627cb74";
    deps = with allCrates; [  all__log.log_0 all__string_cache.string_cache_0_2 all__phf.phf_0_7 all__time.time_0 all__tendril.tendril_0_2 all__mac.mac_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_5_3 = buildCratesLib {
    name = "html5ever";
    version = "0.5.3";
    hash = "01e395c2372b369f5e19e4ccddac057a51a687b62558ab2f351ae3c067651dd2";
    deps = with allCrates; [  all__time.time_0 all__phf.phf_0_7 all__log.log_0 all__string_cache.string_cache_0_2 all__tendril.tendril_0_2 all__mac.mac_0 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_5_4 = buildCratesLib {
    name = "html5ever";
    version = "0.5.4";
    hash = "fd04d31858b8fd8ac9d55570da8c822bc6defd2c1ac18a47cb70fc280f42b432";
    deps = with allCrates; [  all__time.time_0 all__log.log_0 all__phf.phf_0_7 all__string_cache.string_cache_0_2 all__mac.mac_0 all__tendril.tendril_0_2 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  html5ever_0_5_5 = buildCratesLib {
    name = "html5ever";
    version = "0.5.5";
    hash = "91cb2a55a080da050d202eced2df684f1617b7bcfcd141abbe207fcdc572e18a";
    deps = with allCrates; [  all__mac.mac_0 all__phf.phf_0_7 all__string_cache.string_cache_0_2 all__tendril.tendril_0_2 all__log.log_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  html5ever_0_6_0 = buildCratesLib {
    name = "html5ever";
    version = "0.6.0";
    hash = "0e95551cd5c1971c653238eda4f8aa925098cad8332e25cc21f20f6dc11f3ca4";
    deps = with allCrates; [  all__string_cache.string_cache_0_2 all__tendril.tendril_0_2 all__phf.phf_0_7 all__mac.mac_0 all__log.log_0 all__syn.syn_0_9 all__phf_codegen.phf_codegen_0_7 all__quote.quote_0_3 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "html5ever_0_5" = html5ever_0_5_5;
  html5ever_0_7_0 = buildCratesLib {
    name = "html5ever";
    version = "0.7.0";
    hash = "1ced1f4d2c39676138a3592a6eec88e7cc367c6206a1a1f042ac0d74930f7471";
    deps = with allCrates; [  all__string_cache.string_cache_0_2 all__log.log_0 all__tendril.tendril_0_2 all__mac.mac_0 all__phf.phf_0_7 all__phf_codegen.phf_codegen_0_7 all__syn.syn_0_9 all__rustc-serialize.rustc-serialize_0_3 all__quote.quote_0_3 ];
  };
  "html5ever_0_6" = html5ever_0_6_0;
  html5ever_0_8_0 = buildCratesLib {
    name = "html5ever";
    version = "0.8.0";
    hash = "74d996f271e5698e3eeae29754d59b2288973e20b898b53899ac7411356a0742";
    deps = with allCrates; [  all__phf.phf_0_7 all__string_cache.string_cache_0_2 all__mac.mac_0 all__log.log_0 all__tendril.tendril_0_2 all__phf_codegen.phf_codegen_0_7 all__rustc-serialize.rustc-serialize_0_3 all__quote.quote_0_3 all__syn.syn_0_9 ];
  };
  "html5ever_0_7" = html5ever_0_7_0;
  html5ever_0_9_0 = buildCratesLib {
    name = "html5ever";
    version = "0.9.0";
    hash = "6a2e00f17a864dfee00d41b46fda2a669e10e96bf71f8c712b3c88f4977188d7";
    deps = with allCrates; [  all__html5ever-atoms.html5ever-atoms_0_1 all__phf.phf_0_7 all__tendril.tendril_0_2 all__mac.mac_0 all__log.log_0 all__rustc-serialize.rustc-serialize_0_3 all__syn.syn_0_9 all__quote.quote_0_3 all__phf_codegen.phf_codegen_0_7 ];
  };
  "html5ever_0_8" = html5ever_0_8_0;
  html5ever_0_10_0 = buildCratesLib {
    name = "html5ever";
    version = "0.10.0";
    hash = "7f8b7dd0ad2b3813f090b4f6ff8799debef84bca012c1af9e854f20d9ae19ea7";
    deps = with allCrates; [  all__html5ever-atoms.html5ever-atoms_0_1 all__phf.phf_0_7 all__tendril.tendril_0_2 all__mac.mac_0 all__log.log_0 all__quote.quote_0_3 all__phf_codegen.phf_codegen_0_7 all__syn.syn_0_9 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "html5ever_0_9" = html5ever_0_9_0;
  html5ever_0_10_1 = buildCratesLib {
    name = "html5ever";
    version = "0.10.1";
    hash = "47e8b18bb73cb3535597d23fbd1998fb45fe88cb12b9acf183a0188331f6d915";
    deps = with allCrates; [  all__phf.phf_0_7 all__mac.mac_0 all__tendril.tendril_0_2 all__log.log_0 all__html5ever-atoms.html5ever-atoms_0_1 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 all__quote.quote_0_3 all__syn.syn_0_9 ];
  };
  html5ever_0_10_2 = buildCratesLib {
    name = "html5ever";
    version = "0.10.2";
    hash = "9464c43c1b84b1e31c10636e6bc85f63eb7cb435a757020a8e1d1a5502254d4c";
    deps = with allCrates; [  all__phf.phf_0_7 all__tendril.tendril_0_2 all__mac.mac_0 all__html5ever-atoms.html5ever-atoms_0_1 all__log.log_0 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 all__syn.syn_0_9 all__quote.quote_0_3 ];
  };
  html5ever_0_10_3 = buildCratesLib {
    name = "html5ever";
    version = "0.10.3";
    hash = "45815593feb142cf01121b9f413d8630c9902192d160e494a579c50628eef498";
    deps = with allCrates; [  all__html5ever-atoms.html5ever-atoms_0_1 all__mac.mac_0 all__log.log_0 all__tendril.tendril_0_2 all__phf.phf_0_7 all__quote.quote_0_3 all__rustc-serialize.rustc-serialize_0_3 all__phf_codegen.phf_codegen_0_7 all__syn.syn_0_10 ];
  };
  "html5ever_0_10" = html5ever_0_10_3;
  "html5ever_0" = html5ever_0_10_3;}