#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rtl-sdr_0_1_0 = buildCratesLib {
    name = "rtl-sdr";
    version = "0.1.0";
    hash = "a70b1281b3878d7fd6a45902894240c902479e9d9791bfca28d47724e9ce7d72";
    deps = with allCrates; [  ];
  };
  rtl-sdr_0_1_1 = buildCratesLib {
    name = "rtl-sdr";
    version = "0.1.1";
    hash = "7af57ae4bff11d6144777187d94c61e42d15a2ed18fd0baee9d878a022ba6005";
    deps = with allCrates; [  ];
  };
  rtl-sdr_0_1_2 = buildCratesLib {
    name = "rtl-sdr";
    version = "0.1.2";
    hash = "043e2536d57662170eeb0161d1ebbef67c8dc3f755ce1bf6655c49aa3acc79ae";
    deps = with allCrates; [  ];
  };
  rtl-sdr_0_1_3 = buildCratesLib {
    name = "rtl-sdr";
    version = "0.1.3";
    hash = "c368edda9c5cc87863d9600b0b00aebb31fe723976736d95908baf710049be9a";
    deps = with allCrates; [  ];
  };
  rtl-sdr_0_1_4 = buildCratesLib {
    name = "rtl-sdr";
    version = "0.1.4";
    hash = "a76abac4f49d8317b2bfe49f400457fcc911c5f2969ae6a62f5cb730d4162204";
    deps = with allCrates; [  ];
  };
  rtl-sdr_0_1_5 = buildCratesLib {
    name = "rtl-sdr";
    version = "0.1.5";
    hash = "06fdb7092d7807b9d33920d8e0ba1d0258dbaf9676f6c4c87dcf7223b4c4599b";
    deps = with allCrates; [  ];
  };
  "rtl-sdr_0_1" = rtl-sdr_0_1_5;
  "rtl-sdr_0" = rtl-sdr_0_1_5;}