#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  linefeed_0_1_0 = buildCratesLib {
    name = "linefeed";
    version = "0.1.0";
    hash = "591cea6a4079befda1ff429dddb44e37348425605b7c71df214e3f808725b825";
    deps = with allCrates; [ kernel32-sys libc ole32-sys assert_matches nix winapi shell32-sys ];
  };
  linefeed_0_1_1 = buildCratesLib {
    name = "linefeed";
    version = "0.1.1";
    hash = "695e327659c57119c3f82abad8e89b4faf102716c7c03434b70b126df2135c79";
    deps = with allCrates; [ libc nix shell32-sys kernel32-sys ole32-sys winapi ];
  };
  linefeed_0_1_2 = buildCratesLib {
    name = "linefeed";
    version = "0.1.2";
    hash = "28754a31b1939ac009270a4c2180ac8f892ac3dfe8f18229bd01629f31aa9704";
    deps = with allCrates; [ winapi libc ole32-sys nix kernel32-sys shell32-sys ];
  };
  linefeed_0_1_3 = buildCratesLib {
    name = "linefeed";
    version = "0.1.3";
    hash = "cee6f54d00c7c2c898405af66d8f67a4d0f61d279096e5b0bd80f7c9917aa94f";
    deps = with allCrates; [ ole32-sys winapi libc shell32-sys nix kernel32-sys ];
  };
  linefeed_0_1_4 = buildCratesLib {
    name = "linefeed";
    version = "0.1.4";
    hash = "eea02a6648e308381d565f1e4be0f926530be60adac6eda4c51826706f6c5599";
    deps = with allCrates; [ nix libc kernel32-sys shell32-sys winapi ole32-sys ];
  };
  linefeed_0_1_5 = buildCratesLib {
    name = "linefeed";
    version = "0.1.5";
    hash = "ff56c1f86fc5461bb140696e89fd6a8d098716d2c6748c8bac701266c3d1301d";
    deps = with allCrates; [ libc shell32-sys ole32-sys winapi kernel32-sys nix ];
  };
  linefeed_0_2_0 = buildCratesLib {
    name = "linefeed";
    version = "0.2.0";
    hash = "0d04dff7f1655f02d86bc44b551c29a77610dc0ee22677a49acbebae45047fde";
    deps = with allCrates; [ libc nix kernel32-sys shell32-sys winapi ole32-sys ];
  };
  linefeed_0_2_1 = buildCratesLib {
    name = "linefeed";
    version = "0.2.1";
    hash = "b2be7d9f93b2410ebc451baf413e58902c7cf382e32eb9ec52ca66b2d291d86d";
    deps = with allCrates; [ libc shell32-sys kernel32-sys ole32-sys winapi nix ];
  };
  linefeed_0_2_2 = buildCratesLib {
    name = "linefeed";
    version = "0.2.2";
    hash = "e715e20eeeacb0d1aa1b68333eecb84c191012dbd091ceca30d3b61ee8f74849";
    deps = with allCrates; [ libc nix ole32-sys kernel32-sys shell32-sys winapi ];
  };}