#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  dvb_0_1_0 = buildCratesLib {
    name = "dvb";
    version = "0.1.0";
    hash = "592a4e181d1655c86acc6b7803b2397874d03b43724f5069bdfdedf4bf590529";
    deps = with allCrates; [ json error-chain hyper ];
  };
  dvb_0_2_0 = buildCratesLib {
    name = "dvb";
    version = "0.2.0";
    hash = "26c5c22fb2370f4974ec415e834fcb330b28ac3b4e35aebc6fa1a449a3f13b84";
    deps = with allCrates; [ error-chain hyper json multimap ];
  };
  dvb_0_2_1 = buildCratesLib {
    name = "dvb";
    version = "0.2.1";
    hash = "b088c8094f0a00f3e2722f2a23ea47ecea02ec209adbddd49a602c989d56275f";
    deps = with allCrates; [ json error-chain multimap hyper ];
  };
  dvb_0_3_0 = buildCratesLib {
    name = "dvb";
    version = "0.3.0";
    hash = "4bf1746122be68fbd1146c417b5f31e8da5e817683cf618f58b08b54830456bb";
    deps = with allCrates; [ lazy_static hyper multimap regex json error-chain ];
  };}