#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  libykpers-sys_0_1_0 = buildCratesLib {
    name = "libykpers-sys";
    version = "0.1.0";
    hash = "6b7a55c8bd428cb77265fa822e74c6aab0761d6c99f4f89e239d95332d3b3f21";
    deps = with allCrates; [ libc pkg-config ];
  };}