#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ksuser-sys_0_0_1 = buildCratesLib {
    name = "ksuser-sys";
    version = "0.0.1";
    hash = "dc622a36e7ac55e4552bf4cf6493da26ead6fe29772ba6d84cf03b3d99e19b8e";
    deps = with allCrates; [  winapi ];
  };
  "ksuser-sys_0_0" = ksuser-sys_0_0_1;
  "ksuser-sys_0" = ksuser-sys_0_0_1;}