#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  wmdrmsdk-sys_0_0_1 = buildCratesLib {
    name = "wmdrmsdk-sys";
    version = "0.0.1";
    hash = "1f96a69555dad2170ad48c6137fa9c80f70e104231f94de40f247328a603ca61";
    deps = with allCrates; [ winapi ];
  };}