#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  jmphash_0_1_0 = buildCratesLib {
    name = "jmphash";
    version = "0.1.0";
    hash = "5ba365879db6fe8ce69658245bedb011e9ea58e9c44ba4af9a8c3cddf46daf8e";
    deps = with allCrates; [ ];
  };}