#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  heapsize_derive_0_1_0 = buildCratesLib {
    name = "heapsize_derive";
    version = "0.1.0";
    hash = "a7b7a9492a930ed605046b60a153a475653b080dcd967280df2234686b7bc492";
    deps = with allCrates; [  all__quote.quote_0_3 all__syn.syn_0_9 all__synstructure.synstructure_0_2 ];
  };
  heapsize_derive_0_1_1 = buildCratesLib {
    name = "heapsize_derive";
    version = "0.1.1";
    hash = "35abd70c0f2d6260b973ea908d7e4e3da729fc2acf18def91f034a2a4f824ff8";
    deps = with allCrates; [  all__syn.syn_0_9 all__synstructure.synstructure_0_2 all__quote.quote_0_3 ];
  };
  heapsize_derive_0_1_2 = buildCratesLib {
    name = "heapsize_derive";
    version = "0.1.2";
    hash = "14babc109024e52a6d18e9a1b9f7ee57107d2cad7a5deba837cf09f8c2db8ca9";
    deps = with allCrates; [  all__quote.quote_0_3 all__synstructure.synstructure_0_2 all__syn.syn_0_9 ];
  };
  heapsize_derive_0_1_3 = buildCratesLib {
    name = "heapsize_derive";
    version = "0.1.3";
    hash = "4b6876925b6c3de6f9073f016f425de0076ab68cf30522107fa586ae6524abfe";
    deps = with allCrates; [  all__quote.quote_0_3 all__syn.syn_0_10 all__synstructure.synstructure_0_4 ];
  };
  "heapsize_derive_0_1" = heapsize_derive_0_1_3;
  "heapsize_derive_0" = heapsize_derive_0_1_3;}