#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  caffe_0_1_0 = buildCratesLib {
    name = "caffe";
    version = "0.1.0";
    hash = "5c91ed47460b691e9dbf17b44b89a0a403d1b74b176979e5030583edb8134877";
    deps = with allCrates; [  all__bindgen_plugin.bindgen_plugin_0_15 all__libc.libc_0_1 ];
  };
  "caffe_0_1" = caffe_0_1_0;
  "caffe_0" = caffe_0_1_0;}