#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  sgxs_0_1_0 = buildCratesLib {
    name = "sgxs";
    version = "0.1.0";
    hash = "cca09448fc751dfca395fe03106aef459bba1f0f8c54a04406eb125afe0a7aba";
    deps = with allCrates; [ byteorder bitflags ioctl libc ];
  };
  sgxs_0_2_0 = buildCratesLib {
    name = "sgxs";
    version = "0.2.0";
    hash = "f048bbca301bcb32c945009288d742cfe3dec6e9bf901d88936b20b744ccc5ee";
    deps = with allCrates; [ ioctl byteorder lazy_static bitflags pe rust-crypto libc broadcast ];
  };
  sgxs_0_3_0 = buildCratesLib {
    name = "sgxs";
    version = "0.3.0";
    hash = "463ae2a2b93441b08cf79839597db6236b9eaaced6c6f235e0f51a26eb14e81b";
    deps = with allCrates; [ rust-crypto pe ioctl byteorder bitflags clap lazy_static libc broadcast ];
  };
  sgxs_0_3_1 = buildCratesLib {
    name = "sgxs";
    version = "0.3.1";
    hash = "7ecfab677a56bdcb1c1dffb0579dd47015d505be6c1671d6f8c7e538b36921c4";
    deps = with allCrates; [ lazy_static broadcast libc clap ioctl bitflags byteorder rust-crypto pe ];
  };
  sgxs_0_4_0 = buildCratesLib {
    name = "sgxs";
    version = "0.4.0";
    hash = "4fc1ca4d2a8cd0f3c52e5b8f28c8585391cd53a95cc22bbc2afc7bdbe2a01a68";
    deps = with allCrates; [ sgx-isa ioctl libc byteorder bitflags openssl time ];
  };
  sgxs_0_4_1 = buildCratesLib {
    name = "sgxs";
    version = "0.4.1";
    hash = "a120126e0329e3c25e4addcb6f0fbcdd7030b06dee8b4c75fef4b5863c0860ad";
    deps = with allCrates; [ bitflags openssl ioctl time byteorder libc sgx-isa ];
  };
  sgxs_0_5_0 = buildCratesLib {
    name = "sgxs";
    version = "0.5.0";
    hash = "fad2c68920b13b0fb29256a72874f51856ff23b0c4aa2bd806eda95edc7082de";
    deps = with allCrates; [ openssl bitflags byteorder time libc sgx-isa ioctl ];
  };
  sgxs_0_5_1 = buildCratesLib {
    name = "sgxs";
    version = "0.5.1";
    hash = "a23e64d9e3102738e03a40a8fb17bf90ec83d77dc7a6934aa66cadac7e08fe69";
    deps = with allCrates; [ bitflags byteorder libc time ioctl openssl sgx-isa ];
  };}