#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  snappy_0_2_0 = buildCratesLib {
    name = "snappy";
    version = "0.2.0";
    hash = "a6cf260f4651b6e67b2a71865a4e4386295dbef5ca66d594705937ab80997c35";
    deps = with allCrates; [ libc ];
  };
  snappy_0_3_0 = buildCratesLib {
    name = "snappy";
    version = "0.3.0";
    hash = "17d70c85c3299944adf664d5c8690cc854780180391a38866856b7187da28a2f";
    deps = with allCrates; [ libc pkg-config ];
  };
  snappy_0_4_0 = buildCratesLib {
    name = "snappy";
    version = "0.4.0";
    hash = "b570b1d39e2fcb136a07e46d15a1fe962ba71c151e4d8d6888f59f1fcd185bb1";
    deps = with allCrates; [ libc snappy-sys ];
  };}