#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cargo-info_0_1_0 = buildCratesLib {
    name = "cargo-info";
    version = "0.1.0";
    hash = "d0ea3a5e9584a18906bc43a8e29153b203b3ef5fd98867c80f69156599289814";
    deps = with allCrates; [ serde_macros clap serde_json requests serde ];
  };
  cargo-info_0_1_1 = buildCratesLib {
    name = "cargo-info";
    version = "0.1.1";
    hash = "fbb5158a24e70cafd12dd07746e65edab953ae1d5d19095ff4e97fcfbcddc65c";
    deps = with allCrates; [ serde clap serde_macros requests serde_json ];
  };
  cargo-info_0_1_2 = buildCratesLib {
    name = "cargo-info";
    version = "0.1.2";
    hash = "fe85223b8026c8957b04ce8087fe67e9a015a93eec018eb2d6ce0c6c2cd7a9cb";
    deps = with allCrates; [ serde_macros clap serde serde_json requests ];
  };
  cargo-info_0_2_0 = buildCratesLib {
    name = "cargo-info";
    version = "0.2.0";
    hash = "c110ee647023648ab0bd0cd92d9e457336b649ee468d5fc4fa429e893e04b7ba";
    deps = with allCrates; [ serde_json requests clap serde serde_macros ];
  };
  cargo-info_0_3_0 = buildCratesLib {
    name = "cargo-info";
    version = "0.3.0";
    hash = "8a07baaacca10ac57fe021324271dddb5440f3bad60e08fbb14a9f994da60594";
    deps = with allCrates; [ clap requests json ];
  };
  cargo-info_0_3_1 = buildCratesLib {
    name = "cargo-info";
    version = "0.3.1";
    hash = "85a293edbea00cf422d7dfb4c1c63b27325c8570a0456c81570a3c689eaef0eb";
    deps = with allCrates; [ requests json clap ];
  };
  cargo-info_0_3_2 = buildCratesLib {
    name = "cargo-info";
    version = "0.3.2";
    hash = "951d3c42c160e9b59b5af017190254a575ce12bf253fb9b67d74297d1ea940b0";
    deps = with allCrates; [ clap requests json ];
  };
  cargo-info_0_3_3 = buildCratesLib {
    name = "cargo-info";
    version = "0.3.3";
    hash = "850764eb433c04efb90460c74810543353eb693da1d0740dc6ac184ca46a8b5f";
    deps = with allCrates; [ json requests clap ];
  };
  cargo-info_0_3_4 = buildCratesLib {
    name = "cargo-info";
    version = "0.3.4";
    hash = "c349e7f8401f229d9e7ce26d08e84b36af769e879721f551d0cedeb26392b44b";
    deps = with allCrates; [ chrono json clap requests ];
  };
  cargo-info_0_4_0 = buildCratesLib {
    name = "cargo-info";
    version = "0.4.0";
    hash = "9101bf188a5903c17aee9d87662a6a80a78194b6fc3f94b49196e9333ca6be86";
    deps = with allCrates; [ chrono itertools requests clap json ];
  };
  cargo-info_0_4_2 = buildCratesLib {
    name = "cargo-info";
    version = "0.4.2";
    hash = "6e0e9ff223f8b165c0e629648c12438c529629b79f7524ff2ce63a3814416a4f";
    deps = with allCrates; [ itertools json requests chrono clap chrono-humanize ];
  };
  cargo-info_0_4_3 = buildCratesLib {
    name = "cargo-info";
    version = "0.4.3";
    hash = "dab5c7ba9baf5ccea646a3958455842b8bdc44adc32a4bc844bf5fde6c762cb3";
    deps = with allCrates; [ chrono chrono-humanize json requests itertools clap ];
  };
  cargo-info_0_5_0 = buildCratesLib {
    name = "cargo-info";
    version = "0.5.0";
    hash = "2d6b86b28e154e0dc0ec816d1cc119d55eefd833b32105e7face37ab232381d8";
    deps = with allCrates; [ chrono-humanize json pager requests clap chrono ];
  };
  cargo-info_0_5_1 = buildCratesLib {
    name = "cargo-info";
    version = "0.5.1";
    hash = "c37a7d276de64abaa92082d80760749f2c1af1a08c4a0aac4d2872f5feb12b0d";
    deps = with allCrates; [ clap pager requests chrono-humanize json chrono ];
  };
  cargo-info_0_5_2 = buildCratesLib {
    name = "cargo-info";
    version = "0.5.2";
    hash = "1364ad245b7a82d45ee59a56f0a13a1d43a8e1f1d2cb459c172685465b9d4fa4";
    deps = with allCrates; [ requests pager chrono-humanize chrono json clap ];
  };
  cargo-info_0_5_3 = buildCratesLib {
    name = "cargo-info";
    version = "0.5.3";
    hash = "34539bf447ac90969f27e3e8e4ccadc76ea7c4906435b2ed3db8912a29cfe0bb";
    deps = with allCrates; [ json clap chrono-humanize requests chrono pager ];
  };
  cargo-info_0_5_4 = buildCratesLib {
    name = "cargo-info";
    version = "0.5.4";
    hash = "5840b96c1c6cabb986dd86793110a0ac5bdd747c37168e69f34c5b6309bc918e";
    deps = with allCrates; [ chrono clap chrono-humanize pager json requests ];
  };
  cargo-info_0_5_5 = buildCratesLib {
    name = "cargo-info";
    version = "0.5.5";
    hash = "03df87f98641e54e3dbe4fc69921485f46721caf07b4164ea03709ff49a3afe3";
    deps = with allCrates; [ clap chrono-humanize requests chrono json pager ];
  };}