#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cargo-kcov_0_1_0 = buildCratesLib {
    name = "cargo-kcov";
    version = "0.1.0";
    hash = "d2e860e00f3655b64b50c47de60836a571f06be16a2bb0f0685889fbdcecd7e6";
    deps = with allCrates; [ clap shlex term rustc-serialize ];
  };
  cargo-kcov_0_2_0 = buildCratesLib {
    name = "cargo-kcov";
    version = "0.2.0";
    hash = "b3e196383efff9269b5b6a5a311dce5553593a6a5b0f56bccd9ca8652c64c4ae";
    deps = with allCrates; [ rustc-serialize shlex term clap regex ];
  };}