#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cargo-deploy_0_1_0 = buildCratesLib {
    name = "cargo-deploy";
    version = "0.1.0";
    hash = "2a36c9f594e5b9a0ad921f7bf820de636961f7180aba4d470238aa88bf4b1862";
    deps = with allCrates; [  all__libc.libc_0_2 all__gcc.gcc_0_3 ];
  };
  cargo-deploy_0_1_1 = buildCratesLib {
    name = "cargo-deploy";
    version = "0.1.1";
    hash = "eafd9fe00aa7eeddaf182535d6f423ed1a72a7886e83cadf072d168acd05a2c7";
    deps = with allCrates; [  all__libc.libc_0_2 all__gcc.gcc_0_3 ];
  };
  "cargo-deploy_0_1" = cargo-deploy_0_1_1;
  "cargo-deploy_0" = cargo-deploy_0_1_1;}