#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cargo-deadlinks_0_1_0 = buildCratesLib {
    name = "cargo-deadlinks";
    version = "0.1.0";
    hash = "000b289328a83d7ba3d64827ac354478b5e7a4761f661298cf1359bb6dba8015";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__cargo-edit.cargo-edit_0_1 all__docopt.docopt_0_6 all__url.url_0_5 all__string_cache.string_cache_0_2 all__tendril.tendril_0_2 all__env_logger.env_logger_0_3 all__html5ever.html5ever_0_5 ];
  };
  "cargo-deadlinks_0_1" = cargo-deadlinks_0_1_0;
  "cargo-deadlinks_0" = cargo-deadlinks_0_1_0;}