#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cargo-extras_0_1_0 = buildCratesLib {
    name = "cargo-extras";
    version = "0.1.0";
    hash = "cfdebb8708dcefb78a90654239e013aaf88aa77241ce616ef254113f3753de5a";
    deps = with allCrates; [ toml clap tabwriter glob time quick-error lazy_static rustc-serialize regex cargo env_logger docopt tempdir shaman notify curl semver walker hoedown log ];
  };
  cargo-extras_0_1_1 = buildCratesLib {
    name = "cargo-extras";
    version = "0.1.1";
    hash = "e6b105de4fe021d55df835bed34ddbc2316a5a3c2ba859a3df4d38ff3f598e44";
    deps = with allCrates; [ semver toml notify tempdir walker rustc-serialize cargo log env_logger shaman glob quick-error regex docopt hoedown time curl clap lazy_static tabwriter ];
  };
  cargo-extras_0_2_0 = buildCratesLib {
    name = "cargo-extras";
    version = "0.2.0";
    hash = "9a5da982a97e6c2022f419c257b5d1d75611981fb3e1ee51a37cba8a4b0911be";
    deps = with allCrates; [ docopt clap tabwriter rustc-serialize time shaman cargo env_logger cargo-edit hoedown walker curl pad tempdir quick-error lazy_static notify log semver toml glob regex ];
  };
  cargo-extras_0_2_1 = buildCratesLib {
    name = "cargo-extras";
    version = "0.2.1";
    hash = "79a7646ffe07b477cac119b68fda0436ace4d00b0fb4e289085eee1d4d3220a5";
    deps = with allCrates; [ cargo pad walker log hoedown regex toml glob semver tempdir cargo-edit clap docopt shaman env_logger tabwriter curl lazy_static notify rustc-serialize quick-error time ];
  };
  cargo-extras_0_2_2 = buildCratesLib {
    name = "cargo-extras";
    version = "0.2.2";
    hash = "7a80fa0c8a35a2595c665d8ffd3cb3e029a2fab54a6ec1599198767c5b5af21e";
    deps = with allCrates; [ curl docopt clap toml rustc-serialize cargo pad hoedown regex walker shaman notify tempdir clippy env_logger cargo-edit glob semver log quick-error time lazy_static tabwriter ];
  };
  cargo-extras_0_2_3 = buildCratesLib {
    name = "cargo-extras";
    version = "0.2.3";
    hash = "b352fa343d2589022b689658591a0c4b6be021779e57b0453f9c743eb71bfdc5";
    deps = with allCrates; [ glob rustc-serialize env_logger hoedown cargo curl docopt tempdir log quick-error pad walker cargo-edit lazy_static toml clap semver time regex shaman notify tabwriter ];
  };
  cargo-extras_0_3_0 = buildCratesLib {
    name = "cargo-extras";
    version = "0.3.0";
    hash = "8f63f531b2a6aa19b9fdf9757645788d5334f4eec26a6cda74bd7ee721ea3ac9";
    deps = with allCrates; [ regex curl time cargo-edit url quick-error pad clap notify docopt tempdir lazy_static semver cargo hoedown git2 gitignore shaman env_logger glob rustc-serialize toml tabwriter log ];
  };}