#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cargo-sphinx_0_1_0 = buildCratesLib {
    name = "cargo-sphinx";
    version = "0.1.0";
    hash = "b3de0e69e56653a275b75c6de1f9955bccb383daec2d753c8cae201d2bec53d4";
    deps = with allCrates; [ quick-error cargo term clap toml ];
  };
  cargo-sphinx_1_0_0 = buildCratesLib {
    name = "cargo-sphinx";
    version = "1.0.0";
    hash = "5ebe6308b63dc5caa4598331acfa749b8d111999293b37dab2f90d1559dc180e";
    deps = with allCrates; [ toml term cargo quick-error clap ];
  };}