#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  cargo-fmt_0_1_0 = buildCratesLib {
    name = "cargo-fmt";
    version = "0.1.0";
    hash = "825eba23d5912e912442bb89b8adc615e08d503c17083c046020444f05f401d4";
    deps = with allCrates; [ walker ];
  };}