#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  lgl_0_1_0 = buildCratesLib {
    name = "lgl";
    version = "0.1.0";
    hash = "671e7d6307a3c3c7b94f4197296eaa4b41473bee02d2c77e7eee63e8055678a4";
    deps = with allCrates; [  ];
  };
  lgl_0_1_1 = buildCratesLib {
    name = "lgl";
    version = "0.1.1";
    hash = "2b13cceea46fb36c4430d9e7c5047a0663b9bb31628a0ec690b345fb4d89c3ef";
    deps = with allCrates; [  ];
  };
  "lgl_0_1" = lgl_0_1_1;
  "lgl_0" = lgl_0_1_1;}