#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  bourbaki_0_0_0 = buildCratesLib {
    name = "bourbaki";
    version = "0.0.0";
    hash = "c29460494b159ba36b68a2a2c3a5bc89fb26ec52596e0ce73e2a4e79bdc9ad66";
    deps = with allCrates; [ ];
  };}