#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  svd_macros_1_0_0 = buildCratesLib {
    name = "svd_macros";
    version = "1.0.0";
    hash = "33cb934c7b088b7d183fbeb3ac09ff7443593409af99ec160845333680e1df86";
    deps = with allCrates; [  all__fromxml.fromxml_1_2 all__svd.svd_1_0_0 ];
  };
  "svd_macros_1_0" = svd_macros_1_0_0;
  "svd_macros_1" = svd_macros_1_0_0;}