#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rzbackup_0_1_0 = buildCratesLib {
    name = "rzbackup";
    version = "0.1.0";
    hash = "9c7b1f6486a73334e7878b225e950adafe6e9f5e3d5271c14faca08c477c6109";
    deps = with allCrates; [  all__libc.libc_0_2 all__protobuf.protobuf_1_0 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  rzbackup_1_0_0 = buildCratesLib {
    name = "rzbackup";
    version = "1.0.0";
    hash = "dcc9859319d2e8111476b17a5fb1c6468e97c9e95d06b79de817789ec1200049";
    deps = with allCrates; [  all__libc.libc_0_2 all__rustc-serialize.rustc-serialize_0_3 all__lru-cache.lru-cache_0_0 all__rust-crypto.rust-crypto_0_2 all__protobuf.protobuf_1_0 ];
  };
  "rzbackup_0" = rzbackup_0_1_0;
  rzbackup_1_0_1 = buildCratesLib {
    name = "rzbackup";
    version = "1.0.1";
    hash = "e3c4e9ad10b700e53667baeb2df3031b1e6eade3a1de763ad77492be354914e1";
    deps = with allCrates; [  all__rust-crypto.rust-crypto_0_2 all__libc.libc_0_2 all__protobuf.protobuf_1_0 all__lru-cache.lru-cache_0_0 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  rzbackup_1_0_2 = buildCratesLib {
    name = "rzbackup";
    version = "1.0.2";
    hash = "3704aed21c28dc3b23f52aa9c67f2115345c1b7596bbc5fd9f41473b810b7ad1";
    deps = with allCrates; [  all__threadpool.threadpool_1_0 all__rustc-serialize.rustc-serialize_0_3 all__futures.futures_0_1 all__futures-cpupool.futures-cpupool_0_1 all__lru-cache.lru-cache_0_0 all__protobuf.protobuf_1_0 all__libc.libc_0_2 all__rust-crypto.rust-crypto_0_2 ];
  };
  rzbackup_2_0_0 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.0";
    hash = "bf1ed83f6942d7a5767a57eb41708da6e0244bdc1cbaa9d129248d9ebb6cb4dc";
    deps = with allCrates; [  all__libc.libc_0_2 all__num_cpus.num_cpus_1_1 all__threadpool.threadpool_1_0 all__futures.futures_0_1 all__protobuf.protobuf_1_0 all__lru-cache.lru-cache_0_0 all__minilzo.minilzo_0_1 all__futures-cpupool.futures-cpupool_0_1 all__rust-crypto.rust-crypto_0_2 all__rustc-serialize.rustc-serialize_0_3 all__clap.clap_2_13 ];
  };
  "rzbackup_1" = rzbackup_1_0_2;
  rzbackup_2_0_1 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.1";
    hash = "4ddfa6b0a4fba21079e2840dded720399852306581589e67d93a734ef6f428e5";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__protobuf.protobuf_1_0 all__lru-cache.lru-cache_0_0 all__minilzo.minilzo_0_1 all__futures-cpupool.futures-cpupool_0_1 all__libc.libc_0_2 all__num_cpus.num_cpus_1_1 all__clap.clap_2_13 all__rust-crypto.rust-crypto_0_2 all__futures.futures_0_1 ];
  };
  rzbackup_2_0_2 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.2";
    hash = "2c5cd7057fa817c8be1b31dff0d769d70b385a8f0206644f6e73fbcbdf2a6d21";
    deps = with allCrates; [  all__num_cpus.num_cpus_1_1 all__futures.futures_0_1 all__lru-cache.lru-cache_0_0 all__protobuf.protobuf_1_0 all__rust-crypto.rust-crypto_0_2 all__minilzo.minilzo_0_1 all__libc.libc_0_2 all__futures-cpupool.futures-cpupool_0_1 all__rustc-serialize.rustc-serialize_0_3 all__clap.clap_2_13 ];
  };
  rzbackup_2_0_3 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.3";
    hash = "d71dadbb6485c424a9d1f2183fd4f0274f1636245074129c0c0034ecabf10978";
    deps = with allCrates; [  all__minilzo.minilzo_0_1 all__lru-cache.lru-cache_0_0 all__protobuf.protobuf_1_0 all__rust-crypto.rust-crypto_0_2 all__libc.libc_0_2 all__clap.clap_2_13 all__futures-cpupool.futures-cpupool_0_1 all__num_cpus.num_cpus_1_1 all__futures.futures_0_1 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  rzbackup_2_0_4 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.4";
    hash = "649fe6834bd9387ed3cefa1f9d0fea8ea13320db200c3814fb9a2fac20c59fd7";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__libc.libc_0_2 all__num_cpus.num_cpus_1_1 all__clap.clap_2_13 all__protobuf.protobuf_1_0 all__rust-crypto.rust-crypto_0_2 all__minilzo.minilzo_0_1 all__futures-cpupool.futures-cpupool_0_1 all__lru-cache.lru-cache_0_0 all__futures.futures_0_1 ];
  };
  rzbackup_2_0_5 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.5";
    hash = "8ecd5f93e8d5c36c251954d3e5812453efbb54d650ea670ef4fd0db40bb0ceda";
    deps = with allCrates; [  all__clap.clap_2_13 all__lru-cache.lru-cache_0_0 all__minilzo.minilzo_0_1 all__rust-crypto.rust-crypto_0_2 all__protobuf.protobuf_1_0 all__futures.futures_0_1 all__libc.libc_0_2 all__num_cpus.num_cpus_1_1 all__rustc-serialize.rustc-serialize_0_3 all__futures-cpupool.futures-cpupool_0_1 ];
  };
  rzbackup_2_0_6 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.6";
    hash = "425096a312d0d19f536156f1c77c6a33610d6fec4aa4a7894558a682c3882bb9";
    deps = with allCrates; [  all__num_cpus.num_cpus_1_1 all__libc.libc_0_2 all__rustc-serialize.rustc-serialize_0_3 all__minilzo.minilzo_0_1 all__futures-cpupool.futures-cpupool_0_1 all__clap.clap_2_13 all__lru-cache.lru-cache_0_0 all__rust-crypto.rust-crypto_0_2 all__protobuf.protobuf_1_0 all__futures.futures_0_1 ];
  };
  rzbackup_2_0_7 = buildCratesLib {
    name = "rzbackup";
    version = "2.0.7";
    hash = "207518609e4845a652bd7e27088cfcd9b592594503fbad67d5bc5559eabb7774";
    deps = with allCrates; [  all__clap.clap_2_13 all__futures-cpupool.futures-cpupool_0_1 all__libc.libc_0_2 all__num_cpus.num_cpus_1_1 all__futures.futures_0_1 all__minilzo.minilzo_0_1 all__rustc-serialize.rustc-serialize_0_3 all__protobuf.protobuf_1_0 all__rust-crypto.rust-crypto_0_2 all__lru-cache.lru-cache_0_0 ];
  };
  "rzbackup_2_0" = rzbackup_2_0_7;
  "rzbackup_2" = rzbackup_2_0_7;}