#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  noise_0_0_1 = buildCratesLib {
    name = "noise";
    version = "0.0.1";
    hash = "7789c5fa2a3c5dc4a75d4274b7d30a3e2bf7a592a2301bfec52af14732624975";
    deps = with allCrates; [  ];
  };
  noise_0_0_2 = buildCratesLib {
    name = "noise";
    version = "0.0.2";
    hash = "a2f99b94d683b3536c4423b48d035ab6caf9ba96c1fda5952e8a280c4f168c98";
    deps = with allCrates; [  ];
  };
  noise_0_0_3 = buildCratesLib {
    name = "noise";
    version = "0.0.3";
    hash = "f5aca370dbe0e5a2e9f73bdebeeb7924343973dc783549f9b5a5bf28fe3c31a2";
    deps = with allCrates; [  ];
  };
  noise_0_0_4 = buildCratesLib {
    name = "noise";
    version = "0.0.4";
    hash = "f9341b5bed2cc3b77e1ee1a7141141bb1249133a1f4f4ae43339d26f1462499e";
    deps = with allCrates; [  ];
  };
  noise_0_1_0 = buildCratesLib {
    name = "noise";
    version = "0.1.0";
    hash = "dc0c14f447f449c9a2555202e3e388199394d1dea7d292dc6b0e2d1b05a7316a";
    deps = with allCrates; [  ];
  };
  "noise_0_0" = noise_0_0_4;
  noise_0_1_1 = buildCratesLib {
    name = "noise";
    version = "0.1.1";
    hash = "40c7c5c01bc7da9d3fad170cb0338cffb254c3467a53f210d2c2821e51307561";
    deps = with allCrates; [  ];
  };
  noise_0_1_2 = buildCratesLib {
    name = "noise";
    version = "0.1.2";
    hash = "74405c42db9e9ee8a85bb9c9adee8869ba61b6543ec1ebac85a89ab416da1f6f";
    deps = with allCrates; [  all__rand.rand_0_1 ];
  };
  noise_0_1_3 = buildCratesLib {
    name = "noise";
    version = "0.1.3";
    hash = "2ab684b624952ebf913912ce0d23dde193ae4a0180b14bb960b28df2b96e4f10";
    deps = with allCrates; [  rand ];
  };
  noise_0_1_4 = buildCratesLib {
    name = "noise";
    version = "0.1.4";
    hash = "4334228844dacf0346cf2935dd0541f556d9b121470c97fe4a46831a6e77629f";
    deps = with allCrates; [  num rand ];
  };
  noise_0_1_5 = buildCratesLib {
    name = "noise";
    version = "0.1.5";
    hash = "354af176bf506b060b738e610c057f98c642d50a0e9150783265a7de2e4dffa8";
    deps = with allCrates; [  rand num ];
  };
  noise_0_2_0 = buildCratesLib {
    name = "noise";
    version = "0.2.0";
    hash = "2beecc561ba77c35a7fefab972a29213a42065811a2da81e63671ecfcbff6f63";
    deps = with allCrates; [  all__num.num_0_1 all__rand.rand_0_3 ];
  };
  "noise_0_1" = noise_0_1_5;
  "noise_0_2" = noise_0_2_0;
  "noise_0" = noise_0_2_0;}