#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  lru-cache_0_0_1 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.1";
    hash = "a5116f918e7ed59699c8dcb1b35b45135b5e10e3b013d5c62fae602e80dedaea";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_0_2 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.2";
    hash = "08e0c1fb93479f3629505f0b9785382e42adf19f0b9e2b6d389297d132d159c9";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_0_3 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.3";
    hash = "81191d4e1d0b78a4d81fb87ba66ed1a0c979394dfc54ca1271c01a2b7cd347fc";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_0_4 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.4";
    hash = "889d0ca50a4240072469fccc19d04c08f4ccbaffbb9548b1e73c7831ad28ddcb";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_0_5 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.5";
    hash = "6dfe2dcd66af6a7f8a8a0195ba482e390dbf108fdcedaa515cb71152c1e6bdf1";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_0_6 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.6";
    hash = "4307b242c5fcf0e72b523345e673f99a5f8576743fdf4db903c02fae331308ba";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_0_7 = buildCratesLib {
    name = "lru-cache";
    version = "0.0.7";
    hash = "42d50dcb5d9f145df83b1043207e1ac0c37c9c779c4e128ca4655abc3f3cbf8c";
    deps = with allCrates; [ linked-hash-map ];
  };
  lru-cache_0_1_0 = buildCratesLib {
    name = "lru-cache";
    version = "0.1.0";
    hash = "656fa4dfcb02bcf1063c592ba3ff6a5303ee1f2afe98c8a889e8b1a77c6dfdb7";
    deps = with allCrates; [ linked-hash-map ];
  };}