#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  iso3166-3_0_1_0 = buildCratesLib {
    name = "iso3166-3";
    version = "0.1.0";
    hash = "7eae7568130ab777599be659ea81d52ea9d18e4f6a33487eab4a8337ea392d50";
    deps = with allCrates; [  ];
  };
  iso3166-3_0_2_0 = buildCratesLib {
    name = "iso3166-3";
    version = "0.2.0";
    hash = "d413c812c6d434ab9942656da294a144113e3e59822840a382ef87d185ad9ad0";
    deps = with allCrates; [  ];
  };
  "iso3166-3_0_1" = iso3166-3_0_1_0;
  iso3166-3_0_3_0 = buildCratesLib {
    name = "iso3166-3";
    version = "0.3.0";
    hash = "be8530cd91427be5d4e2a406a51c4ce0ab433d9e7571898fcd4c53b4b361886c";
    deps = with allCrates; [  ];
  };
  "iso3166-3_0_2" = iso3166-3_0_2_0;
  "iso3166-3_0_3" = iso3166-3_0_3_0;
  "iso3166-3_0" = iso3166-3_0_3_0;}