#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  shingles_0_1_0 = buildCratesLib {
    name = "shingles";
    version = "0.1.0";
    hash = "1ff64e4d87bbacc75fae400357ce2b6d980bc11ab54ea524f09f0f8ef00e0275";
    deps = with allCrates; [ ];
  };
  shingles_0_1_1 = buildCratesLib {
    name = "shingles";
    version = "0.1.1";
    hash = "72bb884be1ddfbded5873be4672cf5aee71210ce0f8ae99787d158b9b72b5ca0";
    deps = with allCrates; [ ];
  };}