#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kernel_density_0_0_1 = buildCratesLib {
    name = "kernel_density";
    version = "0.0.1";
    hash = "4650e4bc6bb55f57f16f669ddb3c643c8b2e99a477f2f1fa9162528322d2a1b1";
    deps = with allCrates; [  all__rand.rand_0_3 all__ordered-float.ordered-float_0_2 ];
  };
  "kernel_density_0_0" = kernel_density_0_0_1;
  "kernel_density_0" = kernel_density_0_0_1;}