#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  conduit-cookie_0_1_0 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.1.0";
    hash = "094558acbf6844a51b34a7c9c1a24d442e18db31413e169d674fce57af3adcae";
    deps = with allCrates; [  all__cookie.cookie_0_1 all__conduit.conduit_0_5 all__conduit-middleware.conduit-middleware_0_5 ];
  };
  conduit-cookie_0_1_1 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.1.1";
    hash = "2e506453a21eaff1d93d2d4a60f40c9179c963b3f50c1ba3f78772a1d96a9768";
    deps = with allCrates; [  all__cookie.cookie_0_1 all__conduit.conduit_0_5 all__conduit-middleware.conduit-middleware_0_5 ];
  };
  conduit-cookie_0_1_2 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.1.2";
    hash = "b3a3335030c3c20501189a39c6172d573176f7c2224c8e1cfeaff532bc3d5850";
    deps = with allCrates; [  all__conduit-middleware.conduit-middleware_0_5 all__cookie.cookie_0_1 all__conduit.conduit_0_5 all__rustc-serialize.rustc-serialize_0_1 ];
  };
  conduit-cookie_0_1_3 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.1.3";
    hash = "6902a1f4911611f4db5610765b1081000412965e2a78355127f0f3bcf51af699";
    deps = with allCrates; [  all__conduit-middleware.conduit-middleware_0_5 all__rustc-serialize.rustc-serialize_0_2 all__conduit.conduit_0_5 all__cookie.cookie_0_1 ];
  };
  conduit-cookie_0_1_4 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.1.4";
    hash = "17b6d745095539b0f38d0d5cec3aa66603285ca2046ca2c38adba6041d7c6b57";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_2 all__cookie.cookie_0_1 all__conduit-middleware.conduit-middleware_0_5 all__conduit.conduit_0_5 ];
  };
  conduit-cookie_0_1_5 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.1.5";
    hash = "a2e925771a8ee1812df493b70b4ad984d52fdccbd94548b2d846ba7ac7bca237";
    deps = with allCrates; [  all__conduit-middleware.conduit-middleware_0_5 all__cookie.cookie_0_1 all__conduit.conduit_0_5 all__rustc-serialize.rustc-serialize_0_2 ];
  };
  conduit-cookie_0_6_0 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.6.0";
    hash = "3c21a23bda4b7d0f6f264033fbda3a2b6a0ba3e305c2a2256e78e8d3c76f0fd9";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_2 all__cookie.cookie_0_1 all__conduit.conduit_0_6 all__conduit-middleware.conduit-middleware_0_6 ];
  };
  "conduit-cookie_0_1" = conduit-cookie_0_1_5;
  conduit-cookie_0_6_1 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.6.1";
    hash = "35dd30f182f0f977a151d5fd55f8f5ab884cba0bd934f06cfde0bb2861ce28fc";
    deps = with allCrates; [  all__cookie.cookie_0_1 all__rustc-serialize.rustc-serialize_0_2 all__conduit.conduit_0_6 all__conduit-middleware.conduit-middleware_0_6 ];
  };
  conduit-cookie_0_6_2 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.6.2";
    hash = "20338577ce4d5205904c5836f611f00b8f2f7561fd801988780e5d41e08fbd21";
    deps = with allCrates; [  all__conduit.conduit_0_6 all__rustc-serialize.rustc-serialize_0_2 all__cookie.cookie_0_1 all__conduit-middleware.conduit-middleware_0_6 ];
  };
  conduit-cookie_0_7_0 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.7.0";
    hash = "c67aed7477757ceca07da458b9db68bfe720552a41ec6432d4941a697c0e100c";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__conduit-middleware.conduit-middleware_0_7 all__conduit.conduit_0_7 all__cookie.cookie_0_1 ];
  };
  "conduit-cookie_0_6" = conduit-cookie_0_6_2;
  conduit-cookie_0_7_2 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.7.2";
    hash = "8723ef5514171301b60bf2841ddc1c0139479cf50a005ebdc56d46edbed86426";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__cookie.cookie_0_1 all__conduit-middleware.conduit-middleware_0_7 all__conduit.conduit_0_7 ];
  };
  conduit-cookie_0_7_3 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.7.3";
    hash = "761d4a2310ea17c0689fb6bc40e66845e2c4ea5480adb57983ef7065596d2005";
    deps = with allCrates; [  all__conduit.conduit_0_7 all__cookie.cookie_0_1 all__rustc-serialize.rustc-serialize_0_3 all__conduit-middleware.conduit-middleware_0_7 ];
  };
  conduit-cookie_0_7_4 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.7.4";
    hash = "7766ab02af6e7292aaf8eeed08786591cb481c93fd0207bb369887a91de7b475";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__conduit.conduit_0_7 all__conduit-middleware.conduit-middleware_0_7 all__cookie.cookie_0_1 ];
  };
  conduit-cookie_0_7_5 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.7.5";
    hash = "15146e17803746c70886b6b23770c211fcfe9ec2f57f1c2d5d4ab60c29714b23";
    deps = with allCrates; [  all__cookie.cookie_0_2 all__conduit.conduit_0_7 all__conduit-middleware.conduit-middleware_0_7 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  conduit-cookie_0_7_6 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.7.6";
    hash = "8672c44b4b81cce05e884432ca5ff13a610bd0d3f55f709d9438cfb043581d6b";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__conduit.conduit_0_7 all__conduit-middleware.conduit-middleware_0_7 all__cookie.cookie_0_2 ];
  };
  conduit-cookie_0_8_0 = buildCratesLib {
    name = "conduit-cookie";
    version = "0.8.0";
    hash = "30d2507cd962fe802c817739ffedc5759f4f4936ee7a4e86d0d5a3caa888dae1";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__conduit-middleware.conduit-middleware_0_8 all__cookie.cookie_0_3 all__conduit.conduit_0_8 ];
  };
  "conduit-cookie_0_7" = conduit-cookie_0_7_6;
  "conduit-cookie_0_8" = conduit-cookie_0_8_0;
  "conduit-cookie_0" = conduit-cookie_0_8_0;}