#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  mli_mep_0_9_0 = buildCratesLib {
    name = "mli_mep";
    version = "0.9.0";
    hash = "efac7906444a3e9a6107ef0683e5ad2d96fea92ba272e48eac0c424fe057e741";
    deps = with allCrates; [ mli num serde_derive rand serde ];
  };}