#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  pine_0_1_0 = buildCratesLib {
    name = "pine";
    version = "0.1.0";
    hash = "7fc62acfd896e6695f846a3c4e94db9ac4f9e4c2111c0d5decb38c6478a70ccd";
    deps = with allCrates; [ ];
  };}