#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libnfqueue_0_1_0 = buildCratesLib {
    name = "libnfqueue";
    version = "0.1.0";
    hash = "0883093de33efb0e141fbff1d417bea73115a70e3ea691d15cd93b7ce249464b";
    deps = with allCrates; [  lazy_static all__log.log_0_3 all__env_logger.env_logger_0_3 all__libc.libc_0_1 ];
  };
  "libnfqueue_0_1" = libnfqueue_0_1_0;
  "libnfqueue_0" = libnfqueue_0_1_0;}