#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  sort_str_to_sql_0_0_1 = buildCratesLib {
    name = "sort_str_to_sql";
    version = "0.0.1";
    hash = "0c72801ecf8cff8132c96c32faa5b79edc9fef708b13fcee3de007766d76a9b2";
    deps = with allCrates; [  ];
  };
  sort_str_to_sql_0_0_2 = buildCratesLib {
    name = "sort_str_to_sql";
    version = "0.0.2";
    hash = "9b9cea29f6b0729bdf996dcbe783919e8645c7225a5742ac9471e5178127960f";
    deps = with allCrates; [  ];
  };
  sort_str_to_sql_0_0_3 = buildCratesLib {
    name = "sort_str_to_sql";
    version = "0.0.3";
    hash = "95a34e3e8a746909a3b332cabeb8b9dad6a842d7a35f8f2023912baba766dd5a";
    deps = with allCrates; [  all__regex.regex_0_1 ];
  };
  sort_str_to_sql_0_0_4 = buildCratesLib {
    name = "sort_str_to_sql";
    version = "0.0.4";
    hash = "9bbd26493f05dc7eccd56275958c23ea2f2ee279dc731d00a70c6cafe9443965";
    deps = with allCrates; [  all__regex_macros.regex_macros_0_1 all__regex.regex_0_1 ];
  };
  sort_str_to_sql_0_0_5 = buildCratesLib {
    name = "sort_str_to_sql";
    version = "0.0.5";
    hash = "2ac107e0a3d796d6c76717e2ef7db584d94dff28f617aaddb1e7f4dce434f588";
    deps = with allCrates; [  all__regex.regex_0_1 all__regex_macros.regex_macros_0_1 ];
  };
  sort_str_to_sql_1_0_0 = buildCratesLib {
    name = "sort_str_to_sql";
    version = "1.0.0";
    hash = "40954ce032cd663a10e915cd05e508f068f9cdaa220a1f8c30ec962ad5dcbdcb";
    deps = with allCrates; [  all__regex.regex_0_1 ];
  };
  "sort_str_to_sql_0" = sort_str_to_sql_0_0_5;
  "sort_str_to_sql_1_0" = sort_str_to_sql_1_0_0;
  "sort_str_to_sql_1" = sort_str_to_sql_1_0_0;}