#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  flif_0_0_0 = buildCratesLib {
    name = "flif";
    version = "0.0.0";
    hash = "54d33b5ac8625fb52487550f8c460b8f4b49590dc880a5b046c3276e5881ba28";
    deps = with allCrates; [ ];
  };}