#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  furnace_0_1_0 = buildCratesLib {
    name = "furnace";
    version = "0.1.0";
    hash = "9866974502cb750ab93d8696c97b9c0adc6f5f79ba7ad498c3b0baf17885b153";
    deps = with allCrates; [  ];
  };
  "furnace_0_1" = furnace_0_1_0;
  "furnace_0" = furnace_0_1_0;}