#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  caesar_0_1_0 = buildCratesLib {
    name = "caesar";
    version = "0.1.0";
    hash = "d3f04b9fe575ea07ef5a081fe012e3a67307edffacd96eb9ac6e80976178ae64";
    deps = with allCrates; [  all__openssl.openssl_0_7 ];
  };
  caesar_0_2_0 = buildCratesLib {
    name = "caesar";
    version = "0.2.0";
    hash = "2f481f3817be5718647ba2337b457ebff76d150710e154c0a9a7dd4c829b5ad6";
    deps = with allCrates; [  all__openssl.openssl_0_7 ];
  };
  "caesar_0_1" = caesar_0_1_0;
  "caesar_0_2" = caesar_0_2_0;
  "caesar_0" = caesar_0_2_0;}