#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-customsearch1-cli_0_3_6 = buildCratesLib {
    name = "google-customsearch1-cli";
    version = "0.3.6";
    hash = "a8037aab194830076275941ae2b524acdbb2137f3775dea89037c8fa9abc8286";
    deps = with allCrates; [ serde_json hyper yup-hyper-mock serde mime clap strsim ];
  };
  google-customsearch1-cli_1_0_0 = buildCratesLib {
    name = "google-customsearch1-cli";
    version = "1.0.0";
    hash = "47120a5c705d4acab4d65301e8f67ec01f6af2e0c5eb3c233804b10c8f38c602";
    deps = with allCrates; [ strsim serde yup-hyper-mock clap serde_json hyper mime ];
  };}