#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-playmoviespartner1-cli_0_3_6 = buildCratesLib {
    name = "google-playmoviespartner1-cli";
    version = "0.3.6";
    hash = "69ab2268896909d0ebf546445d90204e5944bca02d27927caa8cfa4eb9708dc7";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__mime.mime_0_2 all__clap.clap_2_0 all__strsim.strsim_0_5 all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__hyper.hyper_0_9 ];
  };
  google-playmoviespartner1-cli_1_0_0 = buildCratesLib {
    name = "google-playmoviespartner1-cli";
    version = "1.0.0";
    hash = "adbf06a18a408fc8e95bbe234a56f2210c24988627acf4ba257c328a08fa55f6";
    deps = with allCrates; [  all__yup-hyper-mock.yup-hyper-mock_1_0 all__serde.serde_0_8 all__hyper.hyper_0_9 all__clap.clap_2_0 all__mime.mime_0_2 all__strsim.strsim_0_5 all__serde_json.serde_json_0_8 ];
  };
  "google-playmoviespartner1-cli_0" = google-playmoviespartner1-cli_0_3_6;
  "google-playmoviespartner1-cli_1_0" = google-playmoviespartner1-cli_1_0_0;
  "google-playmoviespartner1-cli_1" = google-playmoviespartner1-cli_1_0_0;}