#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-resourceviews1_beta2-cli_0_3_6 = buildCratesLib {
    name = "google-resourceviews1_beta2-cli";
    version = "0.3.6";
    hash = "b27ad7a5fd6949c86fca054023605c14e382b45ea7bad7de56e7b27908f8e6c1";
    deps = with allCrates; [ serde serde_json mime strsim hyper yup-hyper-mock clap ];
  };
  google-resourceviews1_beta2-cli_1_0_0 = buildCratesLib {
    name = "google-resourceviews1_beta2-cli";
    version = "1.0.0";
    hash = "9793f51e4b343a197782b9e0a87a5badb2ddfb5be1a88e5ba5395030942d1744";
    deps = with allCrates; [ yup-hyper-mock mime serde_json clap strsim serde hyper ];
  };}