#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-webfonts1_0_1_0 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.0";
    hash = "6eb83cc3035f1b19a5704ae4c0442f9675e90d4f0dd2f41d8d6c7c6d8b9ae7a8";
    deps = with allCrates; [ url yup-oauth2 mime hyper serde serde_macros ];
  };
  google-webfonts1_0_1_1 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.1";
    hash = "ad71611b976f88c471de857f7f095fd26200858d5ef4153d2c1757f3883768b9";
    deps = with allCrates; [ url hyper serde_macros mime serde yup-oauth2 ];
  };
  google-webfonts1_0_1_2 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.2";
    hash = "feb30ff379b9753ddcace9b32b923f903ea6886b0fd94176f3d099096226e8e1";
    deps = with allCrates; [ url hyper serde_macros mime yup-oauth2 serde ];
  };
  google-webfonts1_0_1_3 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.3";
    hash = "d426d3567dc74123f8b12a88a3dc33d9f2be06ec9a11c439933a56bb13821915";
    deps = with allCrates; [ hyper serde_macros mime url yup-oauth2 serde ];
  };
  google-webfonts1_0_1_4 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.4";
    hash = "80cbd96263c00fa5b683b45dce643d2d236446f2c50be61585d255deca400699";
    deps = with allCrates; [ mime serde serde_macros hyper yup-oauth2 url ];
  };
  google-webfonts1_0_1_5 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.5";
    hash = "cdc7da09edc6ccf40b3930b5ddbd3f16e4b7420420bf7221df3d73263ea7cade";
    deps = with allCrates; [ hyper serde_macros yup-oauth2 url mime serde ];
  };
  google-webfonts1_0_1_6 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.6";
    hash = "ca36093766863b9ce44ae43b716386db858a44f13a1975ae0f4c6dfafa5294ea";
    deps = with allCrates; [ serde serde_macros url yup-oauth2 mime hyper ];
  };
  google-webfonts1_0_1_7 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.7";
    hash = "f61944c92797c3ecfe6f2bbec353f87a77a2c5a09e81bc4fd90c28a16d1d3629";
    deps = with allCrates; [ json-tools serde_macros mime yup-oauth2 url serde hyper ];
  };
  google-webfonts1_0_1_8 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.8";
    hash = "727b3212537665d3a2a0fa09e56307c6aa49dad704f3862f40c7c31b714c0f66";
    deps = with allCrates; [ yup-oauth2 mime serde hyper url serde_codegen syntex ];
  };
  google-webfonts1_0_1_9 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.9";
    hash = "0762b3c47b3e333cf121d23203850a8df6eb87f4272a22389d1ac337be92ec30";
    deps = with allCrates; [ mime url serde yup-oauth2 serde_json hyper serde_codegen syntex ];
  };
  google-webfonts1_0_1_10 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.10";
    hash = "5eb02990bd5a047cdea6b9d617673977c6cde6eb8a7a93f57c3da92cf1112f0a";
    deps = with allCrates; [ hyper url serde yup-oauth2 serde_json mime syntex serde_codegen ];
  };
  google-webfonts1_0_1_11 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.11";
    hash = "97a76c2ec311a203a44a3625207f6aa9eb743eb3b8401f5263ea54db78ae5774";
    deps = with allCrates; [ url yup-oauth2 serde mime hyper serde_json serde_codegen syntex ];
  };
  google-webfonts1_0_1_12 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.12";
    hash = "ee633fff0330527173cd92536b547a58f0f768efbc3bccd70d4c70d5a9022902";
    deps = with allCrates; [ url yup-oauth2 mime serde_json serde hyper syntex serde_codegen ];
  };
  google-webfonts1_0_1_13 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.13";
    hash = "498156b5117acd47d76bf0a1515130eec80703e6b93acbb7bec701d8a3242af6";
    deps = with allCrates; [ serde mime hyper serde_json url yup-oauth2 serde_codegen syntex ];
  };
  google-webfonts1_0_1_14 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.14";
    hash = "62c3ece3ef07a51e8f670e87a41dc7fc020a90f327f7826257ba1dec4ad78f9d";
    deps = with allCrates; [ serde_json hyper url serde mime ];
  };
  google-webfonts1_0_1_15 = buildCratesLib {
    name = "google-webfonts1";
    version = "0.1.15";
    hash = "9d0dbbf03668694f5fd65718a9f8b050a0f088c4e39b34a3f4b6524edc500f53";
    deps = with allCrates; [ serde url mime hyper serde_json ];
  };
  google-webfonts1_1_0_0 = buildCratesLib {
    name = "google-webfonts1";
    version = "1.0.0";
    hash = "fbe87a48d8f4af2a92f50c547238bbe0e6230c7e700b253fe750a69181543c0d";
    deps = with allCrates; [ hyper serde serde_json mime url ];
  };}