#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  google-oauth2_v2_0_1_0 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.0";
    hash = "01f83ac81ca3509623aa5d963d56084b4de13647c61a1c22252488c4b021cf61";
    deps = with allCrates; [  serde url mime hyper yup-oauth2 serde_macros ];
  };
  google-oauth2_v2_0_1_1 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.1";
    hash = "7ce6a47c748cedc45b082dc375a5f5f3a0370e785742d3c326bec0cec8a614b3";
    deps = with allCrates; [  hyper mime yup-oauth2 serde serde_macros url ];
  };
  google-oauth2_v2_0_1_2 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.2";
    hash = "a99d5111696f5bbae93efaba253b7179725a1a221c7a479f1ebc0cb3cd6c53d2";
    deps = with allCrates; [  hyper mime serde_macros yup-oauth2 url serde ];
  };
  google-oauth2_v2_0_1_3 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.3";
    hash = "e5e6f0e231de7fc28caabb7438fb9125f670354beb0ec625602eb2a44ba20f0d";
    deps = with allCrates; [  serde_macros hyper serde mime yup-oauth2 url ];
  };
  google-oauth2_v2_0_1_4 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.4";
    hash = "0b1c7ca5381436dddf6c0d7d59a99d24e262d4eaa9ac52775a063c19a4121aa1";
    deps = with allCrates; [  url serde_macros mime hyper serde yup-oauth2 ];
  };
  google-oauth2_v2_0_1_5 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.5";
    hash = "808a49d632137b7189e3c96fe342d5b0302570a93d3138d07e44883c301620cb";
    deps = with allCrates; [  mime url serde_macros yup-oauth2 serde hyper ];
  };
  google-oauth2_v2_0_1_6 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.6";
    hash = "72e93e36168ba623cfc4ebebe70d4477b6cf2091d7b7621c43e017d0968a0e16";
    deps = with allCrates; [  url mime serde yup-oauth2 hyper serde_macros ];
  };
  google-oauth2_v2_0_1_7 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.7";
    hash = "f1ecfaefa22f05a02feed60e04d3baa1cc90f6c0fcbf09471a23368795f8c4bc";
    deps = with allCrates; [  serde_macros json-tools url hyper yup-oauth2 mime serde ];
  };
  google-oauth2_v2_0_1_8 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.8";
    hash = "accca07a5a23056c15f67bc102a960267fda5e8e433dc8360ad43b4463984121";
    deps = with allCrates; [  yup-oauth2 all__mime.mime_0_0_11 url serde hyper syntex serde_codegen ];
  };
  google-oauth2_v2_0_1_9 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.9";
    hash = "24c280974d407a8f0e90515647d343506a25411e6d9ec29ff024926e4900879d";
    deps = with allCrates; [  hyper yup-oauth2 serde_json url all__mime.mime_0_1 serde syntex serde_codegen ];
  };
  google-oauth2_v2_0_1_10 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.10";
    hash = "612884663b35728f67b3812c729c7f15c3bf22d9453c9a32d3ac63866b29ca24";
    deps = with allCrates; [  url serde all__mime.mime_0_1 serde_json yup-oauth2 all__hyper.hyper_0_7 syntex serde_codegen ];
  };
  google-oauth2_v2_0_1_11 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.11";
    hash = "880926502375d2708e9be13878bf074e24a3be9864e427af7c224e670976f9cc";
    deps = with allCrates; [  all__mime.mime_0_1 yup-oauth2 url all__hyper.hyper_0_7 serde serde_json serde_codegen syntex ];
  };
  google-oauth2_v2_0_1_12 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.12";
    hash = "795e5e9dd6617f0e2dc6aac581946d9e548e94c89e166ac03acaef483f636625";
    deps = with allCrates; [  serde_json yup-oauth2 all__hyper.hyper_0_7 serde all__mime.mime_0_1 url serde_codegen syntex ];
  };
  google-oauth2_v2_0_1_13 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.13";
    hash = "54fab40c1859074f423f4c668d1d9a8e6ee4af8a0aa864e57f5a97b0d6eb1818";
    deps = with allCrates; [  all__serde_json.serde_json_0_6 all__hyper.hyper_0_8 all__serde.serde_0_6 url yup-oauth2 all__mime.mime_0_2 serde_codegen syntex ];
  };
  google-oauth2_v2_0_1_14 = buildCratesLib {
    name = "google-oauth2_v2";
    version = "0.1.14";
    hash = "b4a768e4b76d7881294de8ffdc902772f07c15900ad24b0f13e3b1e6f58af223";
    deps = with allCrates; [  all__serde_json.serde_json_0_7 url all__hyper.hyper_0_9 all__mime.mime_0_2 all__serde.serde_0_7 ];
  };
  "google-oauth2_v2_0_1" = google-oauth2_v2_0_1_14;
  "google-oauth2_v2_0" = google-oauth2_v2_0_1_14;}