#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-dfareporting2d1-cli_0_3_6 = buildCratesLib {
    name = "google-dfareporting2d1-cli";
    version = "0.3.6";
    hash = "371b51ad3176057d2b932a63ab9dae890e92c02edb990322e6975afbd5d7193f";
    deps = with allCrates; [ clap yup-hyper-mock serde serde_json hyper mime strsim ];
  };
  google-dfareporting2d1-cli_1_0_0 = buildCratesLib {
    name = "google-dfareporting2d1-cli";
    version = "1.0.0";
    hash = "75d2752d02deaec0f5733b96967c81ef13247784e5cca29672d85c1164cf922f";
    deps = with allCrates; [ serde serde_json mime clap hyper strsim yup-hyper-mock ];
  };}