#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-content2_sandbox_0_1_9 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "0.1.9";
    hash = "be3f7d585c336b75e34dcfc8c192499bfe23bf57e4f2fad37022fce762f1d071";
    deps = with allCrates; [ hyper serde_json serde mime url yup-oauth2 syntex serde_codegen ];
  };
  google-content2_sandbox_0_1_10 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "0.1.10";
    hash = "0a56c657d4f29a6465ef5c87ba2954e60a3f45994cf44b66ac45644c829d9643";
    deps = with allCrates; [ yup-oauth2 hyper mime serde url serde_json syntex serde_codegen ];
  };
  google-content2_sandbox_0_1_11 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "0.1.11";
    hash = "17fbaa44d44b0eaf0ca1d6fe79ff3d815d6325f94a3e6c035ffce018b7579653";
    deps = with allCrates; [ url hyper serde yup-oauth2 serde_json mime serde_codegen syntex ];
  };
  google-content2_sandbox_0_1_13 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "0.1.13";
    hash = "1737d81043a0841ef7a9c923646dbdbe00e196f832913509ac7fb1732db996d9";
    deps = with allCrates; [ url mime serde serde_json hyper yup-oauth2 serde_codegen syntex ];
  };
  google-content2_sandbox_0_1_14 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "0.1.14";
    hash = "1f6e80b5b1b71b8fa53b9ac5debbb361f0d458a2246d1265de4f67dfbf51ff9f";
    deps = with allCrates; [ serde_json hyper mime serde url ];
  };
  google-content2_sandbox_0_1_15 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "0.1.15";
    hash = "321e45c0f9f1aec64a6e03376aa3e9ade3f676312b2a538f89f41b9a0bd3e0a4";
    deps = with allCrates; [ url mime hyper serde serde_json ];
  };
  google-content2_sandbox_1_0_0 = buildCratesLib {
    name = "google-content2_sandbox";
    version = "1.0.0";
    hash = "dd9dbf17fb22a2b6a820a601d7b4fd1eb100d2a365090a74ac6649222f53ba34";
    deps = with allCrates; [ serde_json hyper mime url serde ];
  };}