#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-dfareporting2d5-cli_0_3_6 = buildCratesLib {
    name = "google-dfareporting2d5-cli";
    version = "0.3.6";
    hash = "b501592ca4e1edd5c835626b00098f48fa4c5517903b33724c87a84565fa47ac";
    deps = with allCrates; [ strsim hyper mime serde_json serde clap yup-hyper-mock ];
  };
  google-dfareporting2d5-cli_1_0_0 = buildCratesLib {
    name = "google-dfareporting2d5-cli";
    version = "1.0.0";
    hash = "e4d2643fc92eefc763cd26a8f99eb10e951d98277b546b0226f01da014aa5114";
    deps = with allCrates; [ mime strsim serde_json hyper yup-hyper-mock clap serde ];
  };}