#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  google-cloudresourcemanager1_0_1_12 = buildCratesLib {
    name = "google-cloudresourcemanager1";
    version = "0.1.12";
    hash = "1dfa1903b72c8a3282862377f84fd4270a58ba5890d94f826f6acd152be4860c";
    deps = with allCrates; [ mime serde url yup-oauth2 serde_json hyper serde_codegen syntex ];
  };
  google-cloudresourcemanager1_0_1_13 = buildCratesLib {
    name = "google-cloudresourcemanager1";
    version = "0.1.13";
    hash = "9b4a4962f62ae7c50e9f4cff7e5d162e7c63a28b3cd21d43220e86e7538e6dd0";
    deps = with allCrates; [ serde_json hyper mime serde url yup-oauth2 serde_codegen syntex ];
  };
  google-cloudresourcemanager1_0_1_14 = buildCratesLib {
    name = "google-cloudresourcemanager1";
    version = "0.1.14";
    hash = "0db257c774de8502471daf769fde18c95e691ab3a78189e019db9bfbecf52632";
    deps = with allCrates; [ mime hyper serde_json serde url ];
  };
  google-cloudresourcemanager1_0_1_15 = buildCratesLib {
    name = "google-cloudresourcemanager1";
    version = "0.1.15";
    hash = "853ef58f055bc6ccef04938b1898114d128e3af008c9714e823d3ab67b1a349a";
    deps = with allCrates; [ serde_json mime hyper url serde ];
  };
  google-cloudresourcemanager1_1_0_0 = buildCratesLib {
    name = "google-cloudresourcemanager1";
    version = "1.0.0";
    hash = "8dede47740153f068c7330024d675d2fcb0757de944678a93ffc92909fb64718";
    deps = with allCrates; [ hyper mime serde_json url serde ];
  };}