#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  roller_0_1_0 = buildCratesLib {
    name = "roller";
    version = "0.1.0";
    hash = "0bd040edea82d594dd4827caa1b88206efaec0853276084cfa62abb69f9f955c";
    deps = with allCrates; [ rustc-serialize regex rust-crypto ];
  };}