#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  treesize_0_0_1 = buildCratesLib {
    name = "treesize";
    version = "0.0.1";
    hash = "e010074fbfce2eeca5d2b145e6865ee5f21f11893bbeaad69e2e7b5d7398359f";
    deps = with allCrates; [  all__tabwriter.tabwriter_0_1 ];
  };
  treesize_0_1_0 = buildCratesLib {
    name = "treesize";
    version = "0.1.0";
    hash = "790235c6d4f7360e1e4dbc0a8e39a8136bfe52280742080727b95cfd3259aa28";
    deps = with allCrates; [  all__tabwriter.tabwriter_0_1 ];
  };
  "treesize_0_0" = treesize_0_0_1;
  treesize_0_1_1 = buildCratesLib {
    name = "treesize";
    version = "0.1.1";
    hash = "37cb60b2f4e72402aaaea2bf2f227579460b46c045e4f2800404b95f47f759d8";
    deps = with allCrates; [  all__tabwriter.tabwriter_0_1 ];
  };
  treesize_0_1_2 = buildCratesLib {
    name = "treesize";
    version = "0.1.2";
    hash = "1dea7ec3ccbdb7cab40a60c10ca833f1617fca07fce65174095858910332f968";
    deps = with allCrates; [  all__tabwriter.tabwriter_0_1 ];
  };
  treesize_0_2_0 = buildCratesLib {
    name = "treesize";
    version = "0.2.0";
    hash = "eb50371c9ab3daf1d8b954065bf56652a93fe0af20e11837693f406386f154c1";
    deps = with allCrates; [  all__clap.clap_2 all__tabwriter.tabwriter_0_1 ];
  };
  "treesize_0_1" = treesize_0_1_2;
  treesize_0_2_1 = buildCratesLib {
    name = "treesize";
    version = "0.2.1";
    hash = "216fded94e7cfe41cd2b03aab45cd4e271c4f2341c115546202d6fdd9c6f23f4";
    deps = with allCrates; [  all__clap.clap_2 all__tabwriter.tabwriter_0_1 ];
  };
  "treesize_0_2" = treesize_0_2_1;
  "treesize_0" = treesize_0_2_1;}