#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  nicehash_0_1_0 = buildCratesLib {
    name = "nicehash";
    version = "0.1.0";
    hash = "63408cc34e87bdcfa452dbfa6a09aa491f49a9997bfe2f5bd99a8e9f9fa0f5e2";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__semver.semver_0_5 all__serde.serde_0_8 all__lazy_static.lazy_static_0_2 all__hyper.hyper_0_9 ];
  };
  nicehash_0_1_1 = buildCratesLib {
    name = "nicehash";
    version = "0.1.1";
    hash = "ef242a80e192e2530cd2fe67c09ba865e33350e978148f4e61a4e6dad94ddf79";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__semver.semver_0_5 all__hyper.hyper_0_9 all__serde.serde_0_8 all__serde_json.serde_json_0_8 ];
  };
  nicehash_0_1_2 = buildCratesLib {
    name = "nicehash";
    version = "0.1.2";
    hash = "d1f1b9206c92157fef090f309c5fbb32e412ff13cfe3d8af3abc081add4c8a06";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__semver.semver_0_5 all__lazy_static.lazy_static_0_2 ];
  };
  nicehash_0_1_4 = buildCratesLib {
    name = "nicehash";
    version = "0.1.4";
    hash = "471b31ec53d3896cc86b52dab2a425d405f25791586b3d22614136b0097d7272";
    deps = with allCrates; [  all__semver.semver_0_5 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 ];
  };
  nicehash_0_2_0 = buildCratesLib {
    name = "nicehash";
    version = "0.2.0";
    hash = "452050d22fc084f5189f77f179a84cb31c753b0201dc49b245433a77de7bfd33";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__semver.semver_0_5 all__serde_json.serde_json_0_8 ];
  };
  "nicehash_0_1" = nicehash_0_1_4;
  "nicehash_0_2" = nicehash_0_2_0;
  "nicehash_0" = nicehash_0_2_0;}