#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  pact_mock_server_0_0_0 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.0.0";
    hash = "567a46958d42cc70795382bd4ec24e43ed138a10f8dcc9f0d1bb1e0e27dab3f6";
    deps = with allCrates; [ lazy_static log env_logger rustful pact_matching rustc-serialize libc hyper p-macro itertools maplit uuid ];
  };
  pact_mock_server_0_0_1 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.0.1";
    hash = "d51ff8264d3e0a2a842599cd2f2f975f619d8bdf27ef973376bf1b4e61d7b457";
    deps = with allCrates; [ uuid hyper rustc-serialize itertools log p-macro libc lazy_static maplit pact_matching env_logger ];
  };
  pact_mock_server_0_0_2 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.0.2";
    hash = "50bafc18fc89bf7b72f7e7bf53b08d00235266eee933741b0155366a66dc5faa";
    deps = with allCrates; [ pact_matching rustc-serialize itertools libc uuid env_logger p-macro log maplit lazy_static hyper ];
  };
  pact_mock_server_0_1_0 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.1.0";
    hash = "9280b633f7a376f213012c9cee6b8dbc583454aa46cb1e94a17b3288dfcadc3e";
    deps = with allCrates; [ lazy_static uuid log env_logger rustc-serialize pact_matching libc p-macro hyper maplit itertools ];
  };
  pact_mock_server_0_1_1 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.1.1";
    hash = "0eaa6593801741f25b5ebcb60644f1a7d5cedfdb3ad03878db3b5e2d058f15d9";
    deps = with allCrates; [ log pact_matching env_logger maplit uuid itertools p-macro libc lazy_static rustc-serialize hyper ];
  };
  pact_mock_server_0_2_0 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.2.0";
    hash = "2f08905ca56aec573efe611960b0cb659c2ebb77467fbcb8d7eb49eccf038ecf";
    deps = with allCrates; [ lazy_static env_logger log itertools maplit rustc-serialize uuid libc hyper p-macro pact_matching ];
  };
  pact_mock_server_0_2_1 = buildCratesLib {
    name = "pact_mock_server";
    version = "0.2.1";
    hash = "383e512560d01df92dd958081342067d5c11126f2959bb17b9ecd18b6bb20f01";
    deps = with allCrates; [ log maplit hyper pact_matching itertools env_logger libc rustc-serialize lazy_static p-macro uuid ];
  };}