#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  grpc_0_0_1 = buildCratesLib {
    name = "grpc";
    version = "0.0.1";
    hash = "79991623a3c1772645761fbef7cac36dd78888cc009667ff84a88adb8ebafd0f";
    deps = with allCrates; [ ];
  };}