#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  hadean-std_0_1_0 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.0";
    hash = "7688351c5347c585b58d3709e9bff5527533af7338664f9cc5bddab7b083aee2";
    deps = with allCrates; [  all__rand.rand_0_3 all__linked-hash-map.linked-hash-map_0_1 all__hadean.hadean_0_1 all__libc.libc_0_2 ];
  };
  hadean-std_0_1_1 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.1";
    hash = "bdacbf0827b7b56578ba0a4c391e291ac92dfc450c80153d3c63448d014ab0e8";
    deps = with allCrates; [  all__rand.rand_0_3 all__hadean.hadean_0_1 all__libc.libc_0_2 all__linked-hash-map.linked-hash-map_0_1 ];
  };
  hadean-std_0_1_2 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.2";
    hash = "8754e84118ae6b1a76718c00aec0ccbac9a29a3465220e543d3288879287f079";
    deps = with allCrates; [  all__hadean.hadean_0_1 all__odds.odds_0_2 all__linked-hash-map.linked-hash-map_0_1 ];
  };
  hadean-std_0_1_3 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.3";
    hash = "fd92182848936f314f437e078217fc42aa215dfb153938e0e29de35f74b615d9";
    deps = with allCrates; [  all__hadean.hadean_0_1 all__odds.odds_0_2 all__linked-hash-map.linked-hash-map_0_1 ];
  };
  hadean-std_0_1_4 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.4";
    hash = "2ef7943a219423b34d617772f542e51d478f48dd59a75e486be30cc563fdf5f0";
    deps = with allCrates; [  all__linked-hash-map.linked-hash-map_0_1 all__hadean.hadean_0_1 all__odds.odds_0_2 ];
  };
  hadean-std_0_1_5 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.5";
    hash = "7909b2adfa95b218c9a9c749cad0af6eff839186333d8149e7c3f2e96e1bf2b4";
    deps = with allCrates; [  all__odds.odds_0_2 all__hadean.hadean_0_1 all__linked-hash-map.linked-hash-map_0_1 ];
  };
  hadean-std_0_1_6 = buildCratesLib {
    name = "hadean-std";
    version = "0.1.6";
    hash = "d1f2174c53747d65d7da18f03f24caf4d19a789d72c4fa1732be186e865fdbb4";
    deps = with allCrates; [  all__hadean.hadean_0_1 all__odds.odds_0_2 all__linked-hash-map.linked-hash-map_0_1 ];
  };
  "hadean-std_0_1" = hadean-std_0_1_6;
  "hadean-std_0" = hadean-std_0_1_6;}