#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  sigar_0_0_1 = buildCratesLib {
    name = "sigar";
    version = "0.0.1";
    hash = "6e0cdf8817620217f596aebb83cc4f80d5fc5cf3028cb348ef4eca144f914641";
    deps = with allCrates; [ libc ];
  };
  sigar_0_0_2 = buildCratesLib {
    name = "sigar";
    version = "0.0.2";
    hash = "fc9ff2b7ddde9c38fe5d616ae7422eb8fdc9aa1055f224acfeee9c59a97b947d";
    deps = with allCrates; [ libc pkg-config ];
  };}