#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  drt-sys_0_0_1 = buildCratesLib {
    name = "drt-sys";
    version = "0.0.1";
    hash = "396ad4cb3dc59db940209f47f3918ecba1ea3d5efb9266a48d05c3e9f088cac6";
    deps = with allCrates; [ winapi ];
  };}