#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  crate-deps_0_1_0 = buildCratesLib {
    name = "crate-deps";
    version = "0.1.0";
    hash = "f6b5a6fe975694a3087ef886f621774aaa16a4172582d39c8305568c7bc87a9b";
    deps = with allCrates; [ crates-index tiny_http ];
  };}