#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  ruplicity_0_1_0 = buildCratesLib {
    name = "ruplicity";
    version = "0.1.0";
    hash = "e4b5be165108e68f66b158d8cb1e5af1b23cdbd89e47b019caf287fd54a76ebd";
    deps = with allCrates; [ flate2 regex try_opt time tar ];
  };
  ruplicity_0_2_0 = buildCratesLib {
    name = "ruplicity";
    version = "0.2.0";
    hash = "c39f072b4900a9011fc6e1886d0be937fa2e0269fb205b4a8ddb63cc3d6262a2";
    deps = with allCrates; [ tabwriter flate2 tar byteorder try_opt time regex ];
  };
  ruplicity_0_2_1 = buildCratesLib {
    name = "ruplicity";
    version = "0.2.1";
    hash = "928b48536aee5055c1c6cbf9a9e1410c71cf99d66a089f20e893639efefb3014";
    deps = with allCrates; [ byteorder time try_opt flate2 tabwriter tar regex ];
  };
  ruplicity_0_2_2 = buildCratesLib {
    name = "ruplicity";
    version = "0.2.2";
    hash = "07e38ac317f7d4c1b7feb9d936e586bf9fbdbb2f5b308b6ca67b37a7bcfde872";
    deps = with allCrates; [ try_opt tabwriter regex time tar byteorder flate2 ];
  };}