#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  unwrap_0_2_0 = buildCratesLib {
    name = "unwrap";
    version = "0.2.0";
    hash = "ba9460a3158e96bd8135f9bc9148e30a1847591cde441471afeedefd7e0643bb";
    deps = with allCrates; [  ];
  };
  unwrap_1_0_0 = buildCratesLib {
    name = "unwrap";
    version = "1.0.0";
    hash = "d70bf657397109c1ea2fe5989248448492cc848f767f0413b873041891aa15b0";
    deps = with allCrates; [  ];
  };
  "unwrap_0" = unwrap_0_2_0;
  unwrap_1_1_0 = buildCratesLib {
    name = "unwrap";
    version = "1.1.0";
    hash = "999361f54269ac2f0832a39b238ffe077ffa15ff7f6f696968a51164eaffa472";
    deps = with allCrates; [  ];
  };
  "unwrap_1_0" = unwrap_1_0_0;
  "unwrap_1_1" = unwrap_1_1_0;
  "unwrap_1" = unwrap_1_1_0;}