#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  librsync-sys_0_1_0 = buildCratesLib {
    name = "librsync-sys";
    version = "0.1.0";
    hash = "62a82ba14145aa428d1928a1524beface683bec48bf6b3a5de3727f03a6eafc3";
    deps = with allCrates; [ libc gcc ];
  };
  librsync-sys_0_1_1 = buildCratesLib {
    name = "librsync-sys";
    version = "0.1.1";
    hash = "bd926b24d2e3d640cc2a93c9dfeacd39fcd53f45b534f8be711a6e84e1ba3f9b";
    deps = with allCrates; [ libc gcc ];
  };}