#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  resutils-sys_0_0_1 = buildCratesLib {
    name = "resutils-sys";
    version = "0.0.1";
    hash = "151e8e606df34f3cf8219be471cccaef61ca855e44ba20c2bd0edc3ca04687a6";
    deps = with allCrates; [ winapi ];
  };}