#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  retry-after_0_1_0 = buildCratesLib {
    name = "retry-after";
    version = "0.1.0";
    hash = "1e0e6d2cc75734c2356d2786beb12bcabc79deb6893a3d8e9744b48a376548b8";
    deps = with allCrates; [ hyper chrono ];
  };
  retry-after_0_2_0 = buildCratesLib {
    name = "retry-after";
    version = "0.2.0";
    hash = "e40cf3cca9323475bcc003a7b37862867bef54b66735570328915927ff6e24c6";
    deps = with allCrates; [ chrono hyper ];
  };}