#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  metaheuristics_0_0_1 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.1";
    hash = "fa0a3650c1a72a7b0a450c0a5f86886d8302fa769d24d15340193ec30f220e13";
    deps = with allCrates; [  ];
  };
  metaheuristics_0_0_2 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.2";
    hash = "85b114203e9b46c5e46b5d9a40ef8fa87362f671a9335a88ca55d10594996768";
    deps = with allCrates; [  time rand ];
  };
  metaheuristics_0_0_3 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.3";
    hash = "3d8a4afda176848c280e933cbcb22dfcf66180e307aa17645dca2d1578f02483";
    deps = with allCrates; [  all__rand.rand_0_3 all__time.time_0_1 ];
  };
  metaheuristics_0_0_4 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.4";
    hash = "9540cf652ea0251c14bddd3b2cb649dcfc87b1b81afd9767c11ed7cd922c2cc7";
    deps = with allCrates; [  all__rand.rand_0_3 all__time.time_0_1 ];
  };
  metaheuristics_0_0_5 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.5";
    hash = "3c3da594a706c5fe9a02c5ef582bb99e88e3017d0350eaf0f0273f6a1d9392d4";
    deps = with allCrates; [  all__rand.rand_0_3 all__time.time_0_1 ];
  };
  metaheuristics_0_0_6 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.6";
    hash = "dfeb4e18a89a9ad3bbe1b77a40627e84beefecfd7e1234bd1f9d7827281768a5";
    deps = with allCrates; [  all__rand.rand_0_3 all__time.time_0_1 ];
  };
  metaheuristics_0_0_7 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.7";
    hash = "8d45f3bd05e45ea31cb931948dc15ff2923bab78412b8f8f56f37c85331ae20c";
    deps = with allCrates; [  all__time.time_0_1 all__rand.rand_0_3 ];
  };
  metaheuristics_0_0_8 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.8";
    hash = "aa0121e0b9b1b038b498235e99f1cf732ca3067e3e76f087686f9844b9228f85";
    deps = with allCrates; [  all__rand.rand_0_3 all__time.time_0_1 ];
  };
  metaheuristics_0_0_9 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.9";
    hash = "52d389666046ee162b4d4931c5e77be1d14d2893c77b86035321a24bed3ff34a";
    deps = with allCrates; [  all__time.time_0_1 all__rand.rand_0_3 ];
  };
  metaheuristics_0_0_10 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.10";
    hash = "9bcc9f4253eb7ad72a06903322a3acede2e8aa2d7fa7f133d2390f278acce77a";
    deps = with allCrates; [  all__time.time_0_1 all__rand.rand_0_3 ];
  };
  metaheuristics_0_0_11 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.11";
    hash = "6461d50db3415a0e9755fc74f57e8dfaea9b2c3e46fe8de21086f479bdfaed96";
    deps = with allCrates; [  all__rand.rand_0_3 all__time.time_0_1 ];
  };
  metaheuristics_0_0_12 = buildCratesLib {
    name = "metaheuristics";
    version = "0.0.12";
    hash = "57eccdce4004e38c034d8c2880adda16db5ee2bc6b0e13dd12dfc93f2cf26da1";
    deps = with allCrates; [  all__time.time_0_1 all__rand.rand_0_3 ];
  };
  "metaheuristics_0_0" = metaheuristics_0_0_12;
  "metaheuristics_0" = metaheuristics_0_0_12;}