#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  crusadertest2_0_1_0 = buildCratesLib {
    name = "crusadertest2";
    version = "0.1.0";
    hash = "0e9ca5bd7ca11f9ac79fd0847f1ec0e4befa42841cc9ae880239c225fd5b8373";
    deps = with allCrates; [ crusadertest1 ];
  };
  crusadertest2_0_2_0 = buildCratesLib {
    name = "crusadertest2";
    version = "0.2.0";
    hash = "558068160253c34ea1ca27dbc59dec5dc58acecfe41aa36a854442dc735dbefa";
    deps = with allCrates; [ crusadertest1 ];
  };}