#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  blacklog_0_1_0 = buildCratesLib {
    name = "blacklog";
    version = "0.1.0";
    hash = "7b49746402e478626a8929146cfacc253f7ad2e42c5237843c40e66d51ff2d01";
    deps = with allCrates; [ peg quick-error ];
  };
  blacklog_0_1_1 = buildCratesLib {
    name = "blacklog";
    version = "0.1.1";
    hash = "77882709e8f16fc9186ca7a2f7a89b2ac526617054df7ea7333e9fbbb1fdc5e3";
    deps = with allCrates; [ chrono quick-error peg ];
  };}