#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  meval_0_0_2 = buildCratesLib {
    name = "meval";
    version = "0.0.2";
    hash = "c49060bb49489ad038100647cea2320138a5b104b4a0860e43f3bb39c3e29f4a";
    deps = with allCrates; [ nom ];
  };
  meval_0_0_3 = buildCratesLib {
    name = "meval";
    version = "0.0.3";
    hash = "ae9818400f7ee263b168b819e356956a6d9f7c1366286ae9cdfd6349fd06eb1d";
    deps = with allCrates; [ nom ];
  };
  meval_0_0_4 = buildCratesLib {
    name = "meval";
    version = "0.0.4";
    hash = "80dcb3f1cb45aecce151e58b86304272a68c0b3684230023a70e9863f191d9cf";
    deps = with allCrates; [ nom ];
  };
  meval_0_0_5 = buildCratesLib {
    name = "meval";
    version = "0.0.5";
    hash = "21203831acca9adbad5e74ed47e8061baf0634ec25dad9360bf5895e148a0395";
    deps = with allCrates; [ nom ];
  };
  meval_0_0_6 = buildCratesLib {
    name = "meval";
    version = "0.0.6";
    hash = "09b087b25c688d373036acbc809d9f62a381f881bbeb9125c4025e9d822e910c";
    deps = with allCrates; [ nom ];
  };
  meval_0_0_7 = buildCratesLib {
    name = "meval";
    version = "0.0.7";
    hash = "420e6e53927b223598f88ab4e7acf31cefe0156ae3ea7c5c0a4f0e493dcc0a94";
    deps = with allCrates; [ fnv nom ];
  };}