#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  draw_state_0_0_1 = buildCratesLib {
    name = "draw_state";
    version = "0.0.1";
    hash = "1060363e5e971906e459e7de9970aed4dd89649cfd3cf6535f45948e1eeaec0e";
    deps = with allCrates; [  bitflags ];
  };
  draw_state_0_0_2 = buildCratesLib {
    name = "draw_state";
    version = "0.0.2";
    hash = "f8321f0a219adc68dc37330af1965f0086587d71190a305e1c9784b6902246f2";
    deps = with allCrates; [  bitflags ];
  };
  draw_state_0_0_5 = buildCratesLib {
    name = "draw_state";
    version = "0.0.5";
    hash = "0548ca77b2d3d7a5792c7c80384e6847924cab45ee52cb2a8e15ddd12ccf75db";
    deps = with allCrates; [  bitflags ];
  };
  draw_state_0_0_7 = buildCratesLib {
    name = "draw_state";
    version = "0.0.7";
    hash = "9f4af35671310ca9565820bd12b3dacabb5730dbe744d984524f7de19a0e4fcc";
    deps = with allCrates; [  bitflags ];
  };
  draw_state_0_0_8 = buildCratesLib {
    name = "draw_state";
    version = "0.0.8";
    hash = "f89f797fb7d7b38515df966587a7e1f50dcdb4f91dc40ce8f1d3a99c79665a51";
    deps = with allCrates; [  bitflags ];
  };
  draw_state_0_1_0 = buildCratesLib {
    name = "draw_state";
    version = "0.1.0";
    hash = "b5fb4331fc216727dbfaa4d1e11ee68f532851ee3750675ace767783cdcccca7";
    deps = with allCrates; [  bitflags ];
  };
  "draw_state_0_0" = draw_state_0_0_8;
  draw_state_0_1_1 = buildCratesLib {
    name = "draw_state";
    version = "0.1.1";
    hash = "37f95fd99f04b4ab5b1963523612e7be026a72e9cd167d5ebe0eca501d30507c";
    deps = with allCrates; [  all__bitflags.bitflags_0_2 ];
  };
  draw_state_0_1_2 = buildCratesLib {
    name = "draw_state";
    version = "0.1.2";
    hash = "53527a32cf8e5e5768f530b8b19ae68be908510b596d416e2c6ca4bdb0ea39b9";
    deps = with allCrates; [  all__bitflags.bitflags_0_2 ];
  };
  draw_state_0_2_0 = buildCratesLib {
    name = "draw_state";
    version = "0.2.0";
    hash = "5268c4bb885b835a19d13daa5e128c647f301d651758b7a1fef8b657f5fc01ce";
    deps = with allCrates; [  all__bitflags.bitflags_0_3 ];
  };
  "draw_state_0_1" = draw_state_0_1_2;
  draw_state_0_3_0 = buildCratesLib {
    name = "draw_state";
    version = "0.3.0";
    hash = "30b6dc5a61cc514c9945125812afe3b5aa2567fc033633e89b1848981e05de11";
    deps = with allCrates; [  all__bitflags.bitflags_0_3 ];
  };
  "draw_state_0_2" = draw_state_0_2_0;
  draw_state_0_4_0 = buildCratesLib {
    name = "draw_state";
    version = "0.4.0";
    hash = "49529af1eb85fe2c95020de036d6d907bcb47ad1a995773f60040531045f0aa9";
    deps = with allCrates; [  all__bitflags.bitflags_0_4 ];
  };
  "draw_state_0_3" = draw_state_0_3_0;
  draw_state_0_5_0 = buildCratesLib {
    name = "draw_state";
    version = "0.5.0";
    hash = "9530c598b7aafdda849654f3574ecb4f6ef92d2f46dbde11d1c4ad49d6f85798";
    deps = with allCrates; [  all__bitflags.bitflags_0_4 ];
  };
  "draw_state_0_4" = draw_state_0_4_0;
  draw_state_0_6_0 = buildCratesLib {
    name = "draw_state";
    version = "0.6.0";
    hash = "1596fcda8b7c1ec84f68d5d09dad7ad01266a1793214d257deb1f6f7d98e8185";
    deps = with allCrates; [  all__bitflags.bitflags_0_6 ];
  };
  "draw_state_0_5" = draw_state_0_5_0;
  "draw_state_0_6" = draw_state_0_6_0;
  "draw_state_0" = draw_state_0_6_0;}