#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  screenprints_0_1_0 = buildCratesLib {
    name = "screenprints";
    version = "0.1.0";
    hash = "7d3bc04dced038d36a15bba50957dbe12a64388351e8f77865e55fda517a5dd3";
    deps = with allCrates; [  ];
  };
  screenprints_0_1_1 = buildCratesLib {
    name = "screenprints";
    version = "0.1.1";
    hash = "f251605c81768cc461ac191ddc6b2b7658e29d9c52a1311ad0809ac8c167d23b";
    deps = with allCrates; [  all__kernel32-sys.kernel32-sys_0_2 all__winapi.winapi_0_2 ];
  };
  "screenprints_0_1" = screenprints_0_1_1;
  "screenprints_0" = screenprints_0_1_1;}