#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  transcodeimageuid-sys_0_0_1 = buildCratesLib {
    name = "transcodeimageuid-sys";
    version = "0.0.1";
    hash = "26e5c82610761c37012ee9427802704773994b3dc1187a0014673bdc2ba3d897";
    deps = with allCrates; [ winapi ];
  };}