#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  clipboard-win_0_2_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.2.0";
    hash = "e27c19c645b507437a3e3154674e2aafda2e90bcabf2ea4ddcf11287ac9a29ea";
    deps = with allCrates; [  num user32-sys kernel32-sys winapi libc ];
  };
  clipboard-win_0_3_1 = buildCratesLib {
    name = "clipboard-win";
    version = "0.3.1";
    hash = "8ebf69855c7ca88499faa71006ae0cdb90770e0cc4c64814baa466186514c984";
    deps = with allCrates; [  kernel32-sys winapi user32-sys libc ];
  };
  "clipboard-win_0_2" = clipboard-win_0_2_0;
  clipboard-win_0_3_2 = buildCratesLib {
    name = "clipboard-win";
    version = "0.3.2";
    hash = "d19a4e9aa7aed947abe82a21c2f20fd562ea723d5c2a1c38dc5e0a3c5745f45e";
    deps = with allCrates; [  libc winapi user32-sys kernel32-sys ];
  };
  clipboard-win_0_3_3 = buildCratesLib {
    name = "clipboard-win";
    version = "0.3.3";
    hash = "e4bd8035b8dbe973f36b690894a04006c363c1d6487049056ff36a96025e7215";
    deps = with allCrates; [  libc winapi user32-sys kernel32-sys ];
  };
  clipboard-win_0_4_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.4.0";
    hash = "91a1090d9e83c85cf2d91d22e7677a03de14e9e732553f38bd41e9d716fbe96a";
    deps = with allCrates; [  user32-sys kernel32-sys libc winapi ];
  };
  "clipboard-win_0_3" = clipboard-win_0_3_3;
  clipboard-win_0_5_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.5.0";
    hash = "898aade7f17cbbe01d3bf0d30418c794e0be42823b46fb97463384e015f0a8ed";
    deps = with allCrates; [  libc user32-sys winapi kernel32-sys ];
  };
  "clipboard-win_0_4" = clipboard-win_0_4_0;
  clipboard-win_0_5_1 = buildCratesLib {
    name = "clipboard-win";
    version = "0.5.1";
    hash = "789f712e08c8ede65c046b8265f1d14d7758fb450b014cd30fd5efa31d2c860f";
    deps = with allCrates; [  kernel32-sys winapi libc user32-sys ];
  };
  clipboard-win_0_5_2 = buildCratesLib {
    name = "clipboard-win";
    version = "0.5.2";
    hash = "9b3ec94252bc1b535046270fe3d4e4a492bebab28af769ddc643d215bac037a4";
    deps = with allCrates; [  kernel32-sys user32-sys libc winapi ];
  };
  clipboard-win_0_6_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.6.0";
    hash = "51c358e648f5810f94602d30c5a85651878342f72f700efe96f4d50199e7688b";
    deps = with allCrates; [  user32-sys winapi libc kernel32-sys ];
  };
  "clipboard-win_0_5" = clipboard-win_0_5_2;
  clipboard-win_0_7_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.7.0";
    hash = "63aa79c2acc68cd83da9834af4fc96e4a7e5826c183828588f611b268a5ad9a3";
    deps = with allCrates; [  libc user32-sys winapi kernel32-sys ];
  };
  "clipboard-win_0_6" = clipboard-win_0_6_0;
  clipboard-win_0_8_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.8.0";
    hash = "b769955c8b8016168b887948f95d59af1086d7d2638a090ee63e898c6ef51664";
    deps = with allCrates; [  kernel32-sys user32-sys libc winapi ];
  };
  "clipboard-win_0_7" = clipboard-win_0_7_0;
  clipboard-win_0_9_0 = buildCratesLib {
    name = "clipboard-win";
    version = "0.9.0";
    hash = "f6479845923a53d3a41af137633d3ab73e7700b8fbcd5b9b2e0d24a9fff3ba29";
    deps = with allCrates; [  user32-sys kernel32-sys winapi libc ];
  };
  "clipboard-win_0_8" = clipboard-win_0_8_0;
  clipboard-win_0_9_1 = buildCratesLib {
    name = "clipboard-win";
    version = "0.9.1";
    hash = "69b8f1fcb5224909342211c5c735e93437bfea2dfaf17de701a725ef278a40a7";
    deps = with allCrates; [  winapi libc user32-sys kernel32-sys ];
  };
  clipboard-win_0_9_2 = buildCratesLib {
    name = "clipboard-win";
    version = "0.9.2";
    hash = "d0c1284c59c6c64a88f9b0399ba07f021bff2583bf21b76edd3478d34c51b5c9";
    deps = with allCrates; [  user32-sys winapi libc kernel32-sys ];
  };
  clipboard-win_0_9_3 = buildCratesLib {
    name = "clipboard-win";
    version = "0.9.3";
    hash = "bc7296908adc18e3fb643b1a0e89b58de0f839770dc9ef68b62e336b1c9ea522";
    deps = with allCrates; [  kernel32-sys user32-sys libc winapi ];
  };
  clipboard-win_1_0_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.0.0";
    hash = "8309a051b8c72db90f519b337ba4c80ced79139ee1f2e1184721f054afe31732";
    deps = with allCrates; [  winapi kernel32-sys user32-sys libc ];
  };
  "clipboard-win_0" = clipboard-win_0_9_3;
  clipboard-win_1_0_1 = buildCratesLib {
    name = "clipboard-win";
    version = "1.0.1";
    hash = "99151c082adf9d65dba284ae5ccecdacd122cdcdd84ed9fdfb0117e066c6b920";
    deps = with allCrates; [  libc winapi user32-sys kernel32-sys ];
  };
  clipboard-win_1_1_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.1.0";
    hash = "d52f4aee5917673421559b03fce2889d4a1c1d4e06fae2bfdb4c810170b81667";
    deps = with allCrates; [  user32-sys kernel32-sys winapi libc ];
  };
  "clipboard-win_1_0" = clipboard-win_1_0_1;
  clipboard-win_1_2_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.2.0";
    hash = "d1b71a26e98a0df08c18deca216477f5931cd103db9e3020cfc5c1ed63153395";
    deps = with allCrates; [  libc user32-sys kernel32-sys winapi ];
  };
  "clipboard-win_1_1" = clipboard-win_1_1_0;
  clipboard-win_1_3_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.3.0";
    hash = "5c161352d514eff03b2630b41ae54c579a0cbae22438f2f1d79f845f33e2b826";
    deps = with allCrates; [  winapi libc kernel32-sys user32-sys ];
  };
  "clipboard-win_1_2" = clipboard-win_1_2_0;
  clipboard-win_1_4_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.4.0";
    hash = "16279b424d200590a5879287d9c1181f905aa55ac382eb3fc70dcb7515c3456c";
    deps = with allCrates; [  user32-sys libc kernel32-sys winapi ];
  };
  "clipboard-win_1_3" = clipboard-win_1_3_0;
  clipboard-win_1_4_1 = buildCratesLib {
    name = "clipboard-win";
    version = "1.4.1";
    hash = "07e2867d462a11a4c90f68aa8ffe8dbbd212e0548d6f2d409e09d960189684ab";
    deps = with allCrates; [  user32-sys libc kernel32-sys winapi ];
  };
  clipboard-win_1_4_2 = buildCratesLib {
    name = "clipboard-win";
    version = "1.4.2";
    hash = "363dab51058b0a012a245d4168d96bd98a7fa408d5ff86a4f9a52f66e32b5ceb";
    deps = with allCrates; [  libc user32-sys winapi kernel32-sys ];
  };
  clipboard-win_1_5_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.5.0";
    hash = "d1df145a5b55c1a8267ad8bdfdb6bb233b26970b186504645e0bc2447cb8be68";
    deps = with allCrates; [  user32-sys winapi libc kernel32-sys ];
  };
  "clipboard-win_1_4" = clipboard-win_1_4_2;
  clipboard-win_1_5_1 = buildCratesLib {
    name = "clipboard-win";
    version = "1.5.1";
    hash = "b2a5dae03ca4fb6771a1d26a7785d96a02dc1bdefe46248cafb2070d49269d98";
    deps = with allCrates; [  winapi user32-sys libc kernel32-sys ];
  };
  clipboard-win_1_5_2 = buildCratesLib {
    name = "clipboard-win";
    version = "1.5.2";
    hash = "94ada843b9363e79d7294101f865ff299c3474508d40a7b552a458af9e6f65f5";
    deps = with allCrates; [  libc user32-sys kernel32-sys winapi ];
  };
  clipboard-win_1_6_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.6.0";
    hash = "439b36c2d02a8867a09aaf4d1af280a974b90950564bc428bdf6e4636e771d4d";
    deps = with allCrates; [  user32-sys kernel32-sys libc winapi ];
  };
  "clipboard-win_1_5" = clipboard-win_1_5_2;
  clipboard-win_1_6_1 = buildCratesLib {
    name = "clipboard-win";
    version = "1.6.1";
    hash = "ca01a851a76a466a85fff2424de2a03711aeca546d1eb857e1dae44c486780a6";
    deps = with allCrates; [  libc user32-sys kernel32-sys winapi ];
  };
  clipboard-win_1_6_2 = buildCratesLib {
    name = "clipboard-win";
    version = "1.6.2";
    hash = "0a228f8ac83fa48f4d731146a4e91c1363bf7237bdacc54fb432754e3012959f";
    deps = with allCrates; [  kernel32-sys user32-sys winapi ];
  };
  clipboard-win_1_7_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.7.0";
    hash = "b46e49de4482b5a0fca2a900ec78e46fa9e57f0539eb33d93ecf893450c2a113";
    deps = with allCrates; [  all__kernel32-sys.kernel32-sys_0_2 all__user32-sys.user32-sys_0_1 all__winapi.winapi_0_2 ];
  };
  "clipboard-win_1_6" = clipboard-win_1_6_2;
  clipboard-win_1_7_1 = buildCratesLib {
    name = "clipboard-win";
    version = "1.7.1";
    hash = "3dd189c51b26f617011a26bd83373f751a11b39abb89c9463110280c73327e42";
    deps = with allCrates; [  all__kernel32-sys.kernel32-sys_0_2 all__user32-sys.user32-sys_0_1 all__winapi.winapi_0_2 ];
  };
  clipboard-win_1_8_0 = buildCratesLib {
    name = "clipboard-win";
    version = "1.8.0";
    hash = "238830bd83336a8620cbc1d6edf6b9222f45a2c52d02c164348fb6b466277b21";
    deps = with allCrates; [  all__user32-sys.user32-sys_0_2 all__kernel32-sys.kernel32-sys_0_2 all__winapi.winapi_0_2 all__windows-error.windows-error_1_0_0 ];
  };
  "clipboard-win_1_7" = clipboard-win_1_7_1;
  "clipboard-win_1_8" = clipboard-win_1_8_0;
  "clipboard-win_1" = clipboard-win_1_8_0;}