#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  sntp_client_1_2_0 = buildCratesLib {
    name = "sntp_client";
    version = "1.2.0";
    hash = "04515ef369032b3f0a72674b54c1d53142d5f81e3ab2bd7b9d1686a0e14eb12d";
    deps = with allCrates; [ clap byteorder time ];
  };}