#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cxa_demangle_0_0_0 = buildCratesLib {
    name = "cxa_demangle";
    version = "0.0.0";
    hash = "210280a8f915134f1e30fc1f921115af280d09646ba45af6f63c3b8371d8fbbb";
    deps = with allCrates; [  ];
  };
  "cxa_demangle_0_0" = cxa_demangle_0_0_0;
  "cxa_demangle_0" = cxa_demangle_0_0_0;}