#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  phf_macros_0_6_0 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.0";
    hash = "7346e30d1535acb9fc669f075b0d5f37f47b1b5a9ccf9df16e642cd9afcde6b3";
    deps = with allCrates; [ phf_shared ];
  };
  phf_macros_0_6_1 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.1";
    hash = "d1408f7d1cf7c095ce4e2fc0a2f2a479ef9c77714b814b409bbc4641d5f631ef";
    deps = with allCrates; [ phf_shared ];
  };
  phf_macros_0_6_2 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.2";
    hash = "68b6eb5ecb4612a8cb3dd096c4ed15eb4403dd347ff64bd5032a7d68a4bcd63c";
    deps = with allCrates; [ phf_shared ];
  };
  phf_macros_0_6_3 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.3";
    hash = "dc4c715935bfea579399f243f26eec4af5bc7d70f6d5edc7a899e3c4be65b3cd";
    deps = with allCrates; [ phf_shared rand ];
  };
  phf_macros_0_6_4 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.4";
    hash = "ee329e3513f101e0a69b7047ce24d907065e9d26aa085120178478736899657c";
    deps = with allCrates; [ rand phf_shared ];
  };
  phf_macros_0_6_5 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.5";
    hash = "36b7eb9ab2d57d8f83d62ca0d9dd0a1c68ec4bdf3eaf8b8902696b6271f64eb0";
    deps = with allCrates; [ phf_shared rand ];
  };
  phf_macros_0_6_6 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.6";
    hash = "6f8a1bbc5390f9e6a817e4d208d4db98bb438a01a7bac1dcc304922fa522965e";
    deps = with allCrates; [ rand phf_shared ];
  };
  phf_macros_0_6_7 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.7";
    hash = "1e889cbba4f0bc54562868f473608ce037fffd068b8693fc8dcf63df97e93e07";
    deps = with allCrates; [ rand phf_shared ];
  };
  phf_macros_0_6_8 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.8";
    hash = "a55f3be3130a2dad4ec4b53cc0db758d66c9b93f8429623e82342b32faba2fe6";
    deps = with allCrates; [ rand phf_shared ];
  };
  phf_macros_0_6_9 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.9";
    hash = "ddce5b3af0072a11d76e6744b2d335bd362d309a5532ec3a339033e939a3a5fe";
    deps = with allCrates; [ rand phf_shared ];
  };
  phf_macros_0_6_10 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.10";
    hash = "a1996802b576b095805ed0b4352fa3bab3b275781ba0f3e5c6faeec43364df0a";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_6_11 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.11";
    hash = "e0d9c05c4e1c2adcbc77b8a99ce785cea1708c112c1295cdf749505f618b12d3";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_6_12 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.12";
    hash = "ca0e930ed4ec0971cd39184b1da6b2ff48dc319634873363c70bfe8d975dfe0a";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_6_13 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.13";
    hash = "f93fc01ab2f8d21f308713ce2154e71f9288ce6fa9f9bbc078f2cc588186ac37";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_6_14 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.14";
    hash = "4b3a5dc800c9ee4f0740d8f6ec1262e40226604820f06c356eb566571d6f0dca";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_6_15 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.15";
    hash = "33e7c30d3d7d3fe56b6633d0b077844b0a33ede806edd1957325ffaa8c836686";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_6_17 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.17";
    hash = "c7f0d5fb42f4cfa7f65a5431ba49e9145bb00a0ec253765492572451e93ff66e";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_6_18 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.18";
    hash = "47235c9ebc80c1397032124d78414ab69a218ef5bd889c76b918f7f6cd2ee5ad";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_6_19 = buildCratesLib {
    name = "phf_macros";
    version = "0.6.19";
    hash = "c192ec8c77468aef6c49c6ed75eebe83b60578aaeb3713e4a3df343a986c02b2";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_0 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.0";
    hash = "689251ffe7f1d1742204bbbb00d41f45cea366645a512d2ade8160db68e3338f";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_1 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.1";
    hash = "b0ce65f2d9ba93fbd025d5085ee58cacff038119b73fea7228016af296bd59e4";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_2 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.2";
    hash = "18e5bfc6260aa203f34d195c59aebef1372ac2a31b330c5df96709a6a84318ad";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_3 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.3";
    hash = "ecabf75a7107f57d9988e7734f23f8266180d68e06c6b5490f7eb9eac6cbd56c";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_4 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.4";
    hash = "01360b24e1aaa7227b1bab9c78226b0e429fd7ffbd279ae44669ea30f29ea181";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_5 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.5";
    hash = "ad94ebb197dbaccc6d1cd3995b04f3a7dc708666245e0b51f176ebea408fc337";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_6 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.6";
    hash = "2696f25d8abbdca1be4d6bef2c2ffb7ed01c56108d09db34c5f15f29987ae4de";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_7 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.7";
    hash = "246dc3fd9a0f8b161dc64f6328b728695cb222f38f66934302efe3e874ca1bd8";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_8 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.8";
    hash = "d4513789c84e3cded5454d9d320992671a67d6e3786d6ab0a5003912aa1c7933";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_9 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.9";
    hash = "9a25df1ef5f90d55608c3d00a573b5f6d582fbc5a170c99a367bcd63ce4100d9";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_10 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.10";
    hash = "cbc250328a7757fe3a7e9bd210c9c165dc653f0413378d0b945aa27f7ed7245c";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_11 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.11";
    hash = "8a6c17e4736a056147bd0665569e093c77b976e93d1f4099d3a28da3883070c2";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_12 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.12";
    hash = "6ffb7576f008abca5f0516b4d198face1f6e077bbbfbe1933b4d49a8199037e6";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_13 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.13";
    hash = "ef265513554b0cffac50abb3aa688b5394406bc6efb6ec2c5c13e425c32591a4";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_14 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.14";
    hash = "3ef4cc2fc44690201d2fb13c6e26324d16e4bfbb6d903672b39398b05f76b030";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_15 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.15";
    hash = "1e8f139395e776f2c5b614ad5562b3f194634199855399da60c1f2c3edce0f3d";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_16 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.16";
    hash = "132ea70eed654520d98d0e54e262292a94bd5f150671d98b9c8d0782fafce37e";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_17 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.17";
    hash = "1ce32ea1f8124c0a5a67611e47d9deb1874d213154213e6659e385d477e65933";
    deps = with allCrates; [ phf_shared phf_generator ];
  };
  phf_macros_0_7_18 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.18";
    hash = "8afd16b67d77b27647f1c0e49457d814cc0e48dad567b3808d783cad7c0eecaa";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_19 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.19";
    hash = "4bbc5912dc544d28df8e58ed9a132c13701758f0a96c8bd08ecc1f23eea27358";
    deps = with allCrates; [ phf_generator phf_shared ];
  };
  phf_macros_0_7_20 = buildCratesLib {
    name = "phf_macros";
    version = "0.7.20";
    hash = "619b2c128703c63376de760377600b924fc0257487f51bc156f596cf8762e497";
    deps = with allCrates; [ phf_shared phf_generator ];
  };}