#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  wechat-rs_0_1_0 = buildCratesLib {
    name = "wechat-rs";
    version = "0.1.0";
    hash = "1fce0da4491da8c3ea8ddc23bed6e2271697d13e7afc919bfbc2d3e2d128f13f";
    deps = with allCrates; [  ];
  };
  "wechat-rs_0_1" = wechat-rs_0_1_0;
  "wechat-rs_0" = wechat-rs_0_1_0;}