#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  pbuf_0_3_2 = buildCratesLib {
    name = "pbuf";
    version = "0.3.2";
    hash = "8c54e2f439015132723a6b10b24f20feac7f0feda2055d7e9cfd01c0b55b5ca8";
    deps = with allCrates; [ byteorder protobuf ];
  };}