#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cleverbot_io_1_0_0 = buildCratesLib {
    name = "cleverbot_io";
    version = "1.0.0";
    hash = "08e0a3c23d5f79d8fe47850c02296ae435e13dd1aa6bcd7022bbce13cc123e47";
    deps = with allCrates; [  all__serde.serde_0_7 all__hyper.hyper_0_7 all__url.url_0_5 all__serde_json.serde_json_0_7 ];
  };
  "cleverbot_io_1_0" = cleverbot_io_1_0_0;
  "cleverbot_io_1" = cleverbot_io_1_0_0;}