#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  armv4t_0_1_0 = buildCratesLib {
    name = "armv4t";
    version = "0.1.0";
    hash = "f5cff269f5efd3e70e06890fa140099f5cf6e41bf2bf6953864b4e47b449ed69";
    deps = with allCrates; [ ];
  };}