#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  ejdb-sys_0_1_0 = buildCratesLib {
    name = "ejdb-sys";
    version = "0.1.0";
    hash = "df90858c001cd05f426eccfe67d2bc5d9bd223e22e5d5c75872ff92bbb3bcbe3";
    deps = with allCrates; [ libc pkg-config ];
  };
  ejdb-sys_0_2_0 = buildCratesLib {
    name = "ejdb-sys";
    version = "0.2.0";
    hash = "39d15c149aaabdcd31f3fdf3ac4059e2c2120a71e8b45129f8b95d962daf603d";
    deps = with allCrates; [ libc pkg-config ];
  };}