#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  elliptic_0_1_0 = buildCratesLib {
    name = "elliptic";
    version = "0.1.0";
    hash = "0a7aeef5e89aceb8ee628e92dd295e3c702e02bba2a840d328f558fde4d25916";
    deps = with allCrates; [  all__elliptic-sys.elliptic-sys_0_1 ];
  };
  elliptic_0_2_0 = buildCratesLib {
    name = "elliptic";
    version = "0.2.0";
    hash = "709920f1b0d7c3bfca3c1f35f666a54a4edc0e06907ee01da97532925489e9fd";
    deps = with allCrates; [  all__elliptic-sys.elliptic-sys_0_1 ];
  };
  "elliptic_0_1" = elliptic_0_1_0;
  elliptic_0_3_0 = buildCratesLib {
    name = "elliptic";
    version = "0.3.0";
    hash = "1f43721a3a116088116fb5894da309767612d4d3552fb35d13785be95a737d39";
    deps = with allCrates; [  all__elliptic-sys.elliptic-sys_0_2 ];
  };
  "elliptic_0_2" = elliptic_0_2_0;
  elliptic_0_4_0 = buildCratesLib {
    name = "elliptic";
    version = "0.4.0";
    hash = "5ab0a70c2c3216efde7a353429abeb783187d7cc4989b733e1f67fc7c9358f28";
    deps = with allCrates; [  all__elliptic-sys.elliptic-sys_0_2 ];
  };
  "elliptic_0_3" = elliptic_0_3_0;
  elliptic_0_5_0 = buildCratesLib {
    name = "elliptic";
    version = "0.5.0";
    hash = "1e7cbf051f3395c0350615ce2a7faa656678349cbfb85b6098f83e327826be54";
    deps = with allCrates; [  all__elliptic-sys.elliptic-sys_0_3 ];
  };
  "elliptic_0_4" = elliptic_0_4_0;
  "elliptic_0_5" = elliptic_0_5_0;
  "elliptic_0" = elliptic_0_5_0;}