#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  winres_0_1_0 = buildCratesLib {
    name = "winres";
    version = "0.1.0";
    hash = "82b153c4696edc73666d54519d32b21cd8855e265b4375fd6cb090e54b94e46a";
    deps = with allCrates; [  all__toml.toml_0_1 ];
  };
  "winres_0_1" = winres_0_1_0;
  "winres_0" = winres_0_1_0;}