#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  capstone-sys_0_1_0 = buildCratesLib {
    name = "capstone-sys";
    version = "0.1.0";
    hash = "2fe106680116a71eae27673c6f0678317a960b57d9c78ad31c1e188dcd0bc019";
    deps = with allCrates; [ libc gcc pkg-config ];
  };
  capstone-sys_0_2_0 = buildCratesLib {
    name = "capstone-sys";
    version = "0.2.0";
    hash = "cdc37c6ae55ec5ffd3ca2f550ea2f7141135f55bfefcb40c04ebc55b815a1b40";
    deps = with allCrates; [ libc pkg-config gcc ];
  };}