#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  glsl-optimizer-sys_0_1_0 = buildCratesLib {
    name = "glsl-optimizer-sys";
    version = "0.1.0";
    hash = "5dec2419ccf871cb55e30d897e4a07ed047b8e365492d78468d033cb945877ba";
    deps = with allCrates; [ libc cmake ];
  };}