#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  stator_0_1_0 = buildCratesLib {
    name = "stator";
    version = "0.1.0";
    hash = "41801d936f6b9182a2e37e1f16f1ef0b7f656923a8584da031d63c79db0fbc06";
    deps = with allCrates; [  ];
  };
  stator_0_1_1 = buildCratesLib {
    name = "stator";
    version = "0.1.1";
    hash = "8a298714c141559549328afcdbe29bbb9cf8336212350dd861fe810e8a8cf387";
    deps = with allCrates; [  ];
  };
  "stator_0_1" = stator_0_1_1;
  "stator_0" = stator_0_1_1;}