#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rust_accountkit_0_1_0 = buildCratesLib {
    name = "rust_accountkit";
    version = "0.1.0";
    hash = "950f3ab3b9d4387a88b1ffbccc2060ddb815bab563708275d0d537504443e91c";
    deps = with allCrates; [ hyper url ];
  };}