#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rust2x_0_0_1 = buildCratesLib {
    name = "rust2x";
    version = "0.0.1";
    hash = "fe3af2967a9e744ca91609d8052110a8c5d3e17d8675dbe5dc048cdc852a83be";
    deps = with allCrates; [  ];
  };
  "rust2x_0_0" = rust2x_0_0_1;
  "rust2x_0" = rust2x_0_0_1;}