#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rustup_prompt_helper_1_0_0 = buildCratesLib {
    name = "rustup_prompt_helper";
    version = "1.0.0";
    hash = "daeb884eaee1f717c9031e9eada99fdaa84df5b49b21a8ff61a5853f81ea2e56";
    deps = with allCrates; [ toml ];
  };}