#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rust-sctp_0_0_1 = buildCratesLib {
    name = "rust-sctp";
    version = "0.0.1";
    hash = "667ccce2a6b7754e090431ab159232a5e33f3c3c92bbd28debc826b9005976d1";
    deps = with allCrates; [ libc sctp-sys ];
  };
  rust-sctp_0_0_2 = buildCratesLib {
    name = "rust-sctp";
    version = "0.0.2";
    hash = "76ab16f233509510cf153d67dd90a4dfb1aa32a106af1fd1d1cec48b20730f95";
    deps = with allCrates; [ libc sctp-sys ];
  };
  rust-sctp_0_0_3 = buildCratesLib {
    name = "rust-sctp";
    version = "0.0.3";
    hash = "bd7913477c96e67c7dfe34e0ebc367ae17f96a8b9d2037414f31ac25e6759b0a";
    deps = with allCrates; [ libc sctp-sys ];
  };
  rust-sctp_0_0_4 = buildCratesLib {
    name = "rust-sctp";
    version = "0.0.4";
    hash = "b062ae9b725abab0ce92a7f6b5029d475eee1164b4ba0e7c3dde3caa5146774a";
    deps = with allCrates; [ sctp-sys libc winapi ws2_32-sys ];
  };
  rust-sctp_0_0_5 = buildCratesLib {
    name = "rust-sctp";
    version = "0.0.5";
    hash = "03d2daf8af8791dac752f3e486fd7c95972136fd6edebf63e77efff9e466eb62";
    deps = with allCrates; [ libc sctp-sys winapi ws2_32-sys ];
  };}