#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rustc_version_0_1_0 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.0";
    hash = "f9855b14a28f528362f8de42ddc6f8f8754c44b8fab5f1b70d72e4d165ed508d";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_1 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.1";
    hash = "3c6eb213bfed4e8bcd0eb8c71209001727681bb5fbd34dcf6fb74b998dfbb2ff";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_2 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.2";
    hash = "f42804a413038062d257c12d0d3ee057f33f4c9db79f0760294a7d0695b080ae";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_3 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.3";
    hash = "c49813a9e3be409e059bcb9d1d781995dbd6cda52148a5fc9575e8cd5c8a5303";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_4 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.4";
    hash = "fc6511729db72b34baae75b74b509cdb9f24630ae47cf1c9ab320035cbe5396d";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_5 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.5";
    hash = "84f5068e8492340ddeae575368c884e77b5d21fbe2b5f0a13172962a49a5f4eb";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_6 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.6";
    hash = "a2716645bfb54c792fe06a2b857a3fa16c40f3a803b49b799cc04cedd780ab8d";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  rustc_version_0_1_7 = buildCratesLib {
    name = "rustc_version";
    version = "0.1.7";
    hash = "c5f5376ea5e30ce23c03eb77cbe4962b988deead10910c372b226388b594c084";
    deps = with allCrates; [  all__semver.semver_0_1 ];
  };
  "rustc_version_0_1" = rustc_version_0_1_7;
  "rustc_version_0" = rustc_version_0_1_7;}