#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rust-forms_0_0_1 = buildCratesLib {
    name = "rust-forms";
    version = "0.0.1";
    hash = "59938cc7424e45755110cc6bdc3d01d41a5952ae0a48ba06ef80f43109ed785c";
    deps = with allCrates; [  ];
  };
  "rust-forms_0_0" = rust-forms_0_0_1;
  "rust-forms_0" = rust-forms_0_0_1;}