#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  loggly_0_1_0 = buildCratesLib {
    name = "loggly";
    version = "0.1.0";
    hash = "854cd2abbd387a66b5bee1f23e7d3370ded821d802e172997b069678f75e2e9a";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "loggly_0_1" = loggly_0_1_0;
  "loggly_0" = loggly_0_1_0;}