#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  logger_0_0_1 = buildCratesLib {
    name = "logger";
    version = "0.0.1";
    hash = "481f9ef40e9334e25a89d77e6f6c5cdae62946b4f73a8fbfa868905bc82e76c6";
    deps = with allCrates; [ iron ];
  };
  logger_0_0_2 = buildCratesLib {
    name = "logger";
    version = "0.0.2";
    hash = "e79207efaf3cc3c923e75d9cac32339bdcdc9eaa46c4edb576467c0d87348128";
    deps = with allCrates; [ iron time term ];
  };
  logger_0_0_3 = buildCratesLib {
    name = "logger";
    version = "0.0.3";
    hash = "1e7f19f82428d30ba13deee1e903f5d6c5ce485f8f2b9b793f6de6da74bb6dcb";
    deps = with allCrates; [ time iron term ];
  };
  logger_0_1_0 = buildCratesLib {
    name = "logger";
    version = "0.1.0";
    hash = "3cf2488134e30432708391618d45fbdbf925223b842bba4f962fd03632b9566b";
    deps = with allCrates; [ term iron ];
  };
  logger_0_2_0 = buildCratesLib {
    name = "logger";
    version = "0.2.0";
    hash = "dc916b778539fc3ccc72698c0f88e0e1e95f6d8ee2af2c531ef8e2119d822156";
    deps = with allCrates; [ time log iron ];
  };}