#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tantivy-cli_0_1_1 = buildCratesLib {
    name = "tantivy-cli";
    version = "0.1.1";
    hash = "ada8fc9883a173959abbecb25beeba6cbd7e6c7cf1407f67a38ccbbef82ec3da";
    deps = with allCrates; [  all__time.time_0_1 all__rustc-serialize.rustc-serialize_0_3 all__tantivy.tantivy_0_1 all__mount.mount_0_2 all__urlencoded.urlencoded_0_4 all__staticfile.staticfile_0_3 all__iron.iron_0_4 all__ansi_term.ansi_term_0_8 all__clap.clap_2 all__persistent.persistent_0_2 ];
  };
  "tantivy-cli_0_1" = tantivy-cli_0_1_1;
  "tantivy-cli_0" = tantivy-cli_0_1_1;}