#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  kademlia_0_1_0 = buildCratesLib {
    name = "kademlia";
    version = "0.1.0";
    hash = "9502e1a31c02a3974ef085735d0cf80cf91dcae9a304e064913f1e0149a3c6eb";
    deps = with allCrates; [  all__rand.rand_0_3 ];
  };
  "kademlia_0_1" = kademlia_0_1_0;
  "kademlia_0" = kademlia_0_1_0;}