#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  fwpuclnt-sys_0_0_1 = buildCratesLib {
    name = "fwpuclnt-sys";
    version = "0.0.1";
    hash = "7fad7e29b791edbbf7d5ae51040dd64f3ac39ee2a58cce7199d6ada17efc0073";
    deps = with allCrates; [ winapi ];
  };}