#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  emit_seq_0_1_0 = buildCratesLib {
    name = "emit_seq";
    version = "0.1.0";
    hash = "72db229e2284fef3cd77e65c87fa012947fc5848ff3b07ba4494f8e2f31f1ca7";
    deps = with allCrates; [ hyper serde_json chrono emit log serde ];
  };
  emit_seq_0_2_0 = buildCratesLib {
    name = "emit_seq";
    version = "0.2.0";
    hash = "60dbb270c1920b3166124161e6d4e52818a06f87064dc8bc7126ab47b3251001";
    deps = with allCrates; [ hyper serde serde_json emit chrono ];
  };
  emit_seq_0_3_0 = buildCratesLib {
    name = "emit_seq";
    version = "0.3.0";
    hash = "9374bfe36b043fb1cf8c8b028ff021b0c0eca96c27a4bfd7dc08abcfb1ac2e77";
    deps = with allCrates; [ hyper serde_json chrono emit serde ];
  };}