#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  session_0_1_0 = buildCratesLib {
    name = "session";
    version = "0.1.0";
    hash = "ebe707a2d7300bdad8691fe340dcd13c5485c1a7fb6ae40b2277009b4e99a922";
    deps = with allCrates; [  all__bincode.bincode_0_5 all__cookie.cookie_0_2 all__rand.rand_0_3 all__iron.iron_0_4 all__r2d2_redis.r2d2_redis_0_3 all__redis.redis_0_5 all__log.log_0_3 all__lazy_static.lazy_static_0_2 all__rustc-serialize.rustc-serialize_0_3 all__r2d2.r2d2_0_7 ];
  };
  session_0_1_1 = buildCratesLib {
    name = "session";
    version = "0.1.1";
    hash = "58860c531dc69f5db3f42967d81893aa3a4d0dfc3c2ede33575545ad17d3fb48";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__rand.rand_0_3 all__bincode.bincode_0_5 all__log.log_0_3 all__r2d2.r2d2_0_7 all__redis.redis_0_5 all__cookie.cookie_0_2 all__iron.iron_0_4 all__rustc-serialize.rustc-serialize_0_3 all__r2d2_redis.r2d2_redis_0_3 ];
  };
  session_0_1_2 = buildCratesLib {
    name = "session";
    version = "0.1.2";
    hash = "bad5c554c511c28af09032ee093f2fc305c93b9ba25ede0f9d71bc474526e18c";
    deps = with allCrates; [  all__bincode.bincode_0_5 all__r2d2_redis.r2d2_redis_0_3 all__redis.redis_0_5 all__cookie.cookie_0_2 all__log.log_0_3 all__rand.rand_0_3 all__r2d2.r2d2_0_7 all__iron.iron_0_4 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 ];
  };
  session_0_1_3 = buildCratesLib {
    name = "session";
    version = "0.1.3";
    hash = "a0965254a9db273e8c17bcd522ebe5f1a60f2345f8afa57fe0840fd714a2f739";
    deps = with allCrates; [  all__iron.iron_0_4 all__bincode.bincode_0_5 all__cookie.cookie_0_2 all__r2d2.r2d2_0_7 all__rustc-serialize.rustc-serialize_0_3 all__r2d2_redis.r2d2_redis_0_3 all__redis.redis_0_5 all__rand.rand_0_3 all__log.log_0_3 ];
  };
  session_0_1_4 = buildCratesLib {
    name = "session";
    version = "0.1.4";
    hash = "17ee53ad319e3832a1260f99bcc3ff3af1cf2c15a73ce511e44f62a8514cc9e0";
    deps = with allCrates; [  all__redis.redis_0_5 all__rand.rand_0_3 all__log.log_0_3 all__bincode.bincode_0_5 all__r2d2_redis.r2d2_redis_0_3 all__r2d2.r2d2_0_7 all__iron.iron_0_4 all__cookie.cookie_0_2 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  session_0_1_5 = buildCratesLib {
    name = "session";
    version = "0.1.5";
    hash = "dca91da211a7297591a5d12efa4ed34f9e01ee689ad2b74d1204466fe6482a0c";
    deps = with allCrates; [  all__iron.iron_0_4 all__bincode.bincode_0_5 all__cookie.cookie_0_2 all__rand.rand_0_3 all__redis.redis_0_5 all__r2d2.r2d2_0_7 all__r2d2_redis.r2d2_redis_0_3 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 ];
  };
  session_0_1_6 = buildCratesLib {
    name = "session";
    version = "0.1.6";
    hash = "8d9080a06aaa84151abae134cc1cd7ef86a12b171ba4b2649c9aba462d135138";
    deps = with allCrates; [  all__redis.redis_0_5 all__rustc-serialize.rustc-serialize_0_3 all__r2d2.r2d2_0_7 all__rand.rand_0_3 all__bincode.bincode_0_5 all__log.log_0_3 all__r2d2_redis.r2d2_redis_0_3 all__cookie.cookie_0_2 all__iron.iron_0_4 ];
  };
  session_0_1_7 = buildCratesLib {
    name = "session";
    version = "0.1.7";
    hash = "48b568553ec120ce930ff0ec235ab91eb330565087c6709deacae66fdcb78aaf";
    deps = with allCrates; [  all__log.log_0_3 all__bincode.bincode_0_5 all__redis.redis_0_5 all__cookie.cookie_0_2 all__r2d2_redis.r2d2_redis_0_3 all__iron.iron_0_4 all__r2d2.r2d2_0_7 all__rand.rand_0_3 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  session_0_1_8 = buildCratesLib {
    name = "session";
    version = "0.1.8";
    hash = "2f6469e5c3e1f8309bf0449745f73022d69cde72029e1389a0aedd04be908c9f";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__redis.redis_0_5 all__r2d2_redis.r2d2_redis_0_3 all__bincode.bincode_0_5 all__log.log_0_3 all__r2d2.r2d2_0_7 all__rand.rand_0_3 all__cookie.cookie_0_2 all__iron.iron_0_4 ];
  };
  "session_0_1" = session_0_1_8;
  "session_0" = session_0_1_8;}