#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  beagle_0_1_0 = buildCratesLib {
    name = "beagle";
    version = "0.1.0";
    hash = "db542a92f534f4ab6892071d7e9c14a573273e998575108677de5204d6094518";
    deps = with allCrates; [  ];
  };
  beagle_0_1_1 = buildCratesLib {
    name = "beagle";
    version = "0.1.1";
    hash = "899ac0180ba22cf852d285d6e2ea6bdb66baf22b9b90efc302ec06ba14c56cf2";
    deps = with allCrates; [  ];
  };
  beagle_0_1_2 = buildCratesLib {
    name = "beagle";
    version = "0.1.2";
    hash = "16fbc5dff1375db12a67a51158489a0b66f23cdad48581c40d11158f6bc6516e";
    deps = with allCrates; [  ];
  };
  beagle_0_1_3 = buildCratesLib {
    name = "beagle";
    version = "0.1.3";
    hash = "4b3c3a0221b37182edf987464848f42eb0ee8787914f01edc2d147687c73dafc";
    deps = with allCrates; [  ];
  };
  beagle_0_1_4 = buildCratesLib {
    name = "beagle";
    version = "0.1.4";
    hash = "0e85167f58cf10062ca6e6b76bf1e80e3f974f5ecf7a00598a994208de7fdb62";
    deps = with allCrates; [  ];
  };
  "beagle_0_1" = beagle_0_1_4;
  "beagle_0" = beagle_0_1_4;}