#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  conch-parser_0_0_0 = buildCratesLib {
    name = "conch-parser";
    version = "0.0.0";
    hash = "2f7c69f5bd568afdf442fe5f6d388956aa79b8c7a51542bbb12a0990152c587d";
    deps = with allCrates; [ ];
  };}