#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mioco_0_0_4 = buildCratesLib {
    name = "mioco";
    version = "0.0.4";
    hash = "193a91e57957bd710ca8eb96142af69bb43afdf7ed8344ea3dfec20ad11ed404";
    deps = with allCrates; [  nix coroutine mio ];
  };
  mioco_0_1_0 = buildCratesLib {
    name = "mioco";
    version = "0.1.0";
    hash = "d8bc0ca4f2bf36a31a68f68b6a579544ca5f2c58b5966913b1291674a65483b4";
    deps = with allCrates; [  bit-vec mio nix env_logger time context spin log ];
  };
  "mioco_0_0" = mioco_0_0_4;
  mioco_0_2_0 = buildCratesLib {
    name = "mioco";
    version = "0.2.0";
    hash = "72bd992a2a3a0378652b4e09045399a406c74cd0e0b53f1cc881a8075a053cb9";
    deps = with allCrates; [  thread-scoped mio num_cpus slab time all__libc.libc_0_1 context nix spin log ];
  };
  "mioco_0_1" = mioco_0_1_0;
  mioco_0_3_0 = buildCratesLib {
    name = "mioco";
    version = "0.3.0";
    hash = "db47179356f63040e7630d5fb8383dd6b1e80a478ccd1002387fd117dca48b75";
    deps = with allCrates; [  mio all__log.log_0_3 nix thread-scoped context num_cpus all__slab.slab_0_1 all__spin.spin_0_3 libc all__time.time_0_1 ];
  };
  "mioco_0_2" = mioco_0_2_0;
  mioco_0_3_1 = buildCratesLib {
    name = "mioco";
    version = "0.3.1";
    hash = "9b4a09bd5debe009a0f41e78a9e6bcb64ad89363ac2fe71dfc590dba4ad1ddd8";
    deps = with allCrates; [  num_cpus thread-scoped context all__log.log_0_3 all__spin.spin_0_3 all__slab.slab_0_1 mio all__time.time_0_1 libc nix ];
  };
  mioco_0_4_0 = buildCratesLib {
    name = "mioco";
    version = "0.4.0";
    hash = "7e96b83f1d813ead89b371cf8fa1e1991f452f30f53c71f867a0620d0f79641c";
    deps = with allCrates; [  all__slab.slab_0_1 all__time.time_0_1 all__context.context_1_0_0 all__num_cpus.num_cpus_0_2 all__log.log_0_3 all__mio.mio_0_5 all__spin.spin_0_3 all__thread-scoped.thread-scoped_1_0_0 all__nix.nix_0_5 all__libc.libc_0_2 ];
  };
  "mioco_0_3" = mioco_0_3_1;
  mioco_0_4_1 = buildCratesLib {
    name = "mioco";
    version = "0.4.1";
    hash = "c80b246375f8d2d456bf68b76d0f21f7976acc2ece9431f5d08fdb13134b540b";
    deps = with allCrates; [  all__nix.nix_0_5 all__num_cpus.num_cpus_0_2 all__time.time_0_1 all__libc.libc_0_2 all__mio.mio_0_5 all__slab.slab_0_1 all__thread-scoped.thread-scoped_1_0_0 all__spin.spin_0_3 all__context.context_1_0_0 all__log.log_0_3 ];
  };
  mioco_0_5_0 = buildCratesLib {
    name = "mioco";
    version = "0.5.0";
    hash = "10d89fd5608c0c4fa66c10cec9a40099d8ae0917d2c6cb8453e4ec1f688de050";
    deps = with allCrates; [  all__owning_ref.owning_ref_0_1 all__spin.spin_0_4 all__nix.nix_0_5 all__log.log_0_3 all__time.time_0_1 all__mio.mio_0_5 all__slab.slab_0_2 all__libc.libc_0_2 all__num_cpus.num_cpus_0_2 all__thread-scoped.thread-scoped_1_0_0 all__context.context_1_0_0 ];
  };
  "mioco_0_4" = mioco_0_4_1;
  mioco_0_6_0 = buildCratesLib {
    name = "mioco";
    version = "0.6.0";
    hash = "156665525fa45f3a0d32f054d9c2292691cdac03f45e527fa69bd062b169cefb";
    deps = with allCrates; [  all__mio.mio_0_5 all__log.log_0_3 all__libc.libc_0_2 all__thread-scoped.thread-scoped_1_0_0 all__spin.spin_0_4 all__num_cpus.num_cpus_0_2 all__context.context_1_0_0 all__nix.nix_0_5 all__owning_ref.owning_ref_0_1 all__time.time_0_1 all__slab.slab_0_2 ];
  };
  "mioco_0_5" = mioco_0_5_0;
  mioco_0_7_0 = buildCratesLib {
    name = "mioco";
    version = "0.7.0";
    hash = "75e7df49709ff610062d5b8414aa7928c733eb3a9002e393a9d4e64e1e3f5ede";
    deps = with allCrates; [  all__context.context_1_0_0 all__owning_ref.owning_ref_0_1 all__libc.libc_0_2 all__slab.slab_0_2 all__spin.spin_0_4 all__time.time_0_1 all__log.log_0_3 all__nix.nix_0_6 all__thread-scoped.thread-scoped_1_0_0 all__mio.mio_0_5 all__num_cpus.num_cpus_0_2 ];
  };
  "mioco_0_6" = mioco_0_6_0;
  mioco_0_8_0 = buildCratesLib {
    name = "mioco";
    version = "0.8.0";
    hash = "7cbbc5c55b2135ed8739097854ddbbed45188a2dc6f58f2bd0e5984a10a60b15";
    deps = with allCrates; [  all__nix.nix_0_6 all__spin.spin_0_4 all__context.context_1_0_0 all__libc.libc_0_2 all__num_cpus.num_cpus_0_2 all__owning_ref.owning_ref_0_2 all__thread-scoped.thread-scoped_1_0_0 all__slab.slab_0_2 all__mio.mio_0_5 all__log.log_0_3 all__time.time_0_1 ];
  };
  "mioco_0_7" = mioco_0_7_0;
  mioco_0_8_1 = buildCratesLib {
    name = "mioco";
    version = "0.8.1";
    hash = "769ff330492de4f3b8f01f92c7b9057fb50645e5dca0d4380e7ffc5152f1b05e";
    deps = with allCrates; [  all__thread-scoped.thread-scoped_1_0_0 all__nix.nix_0_6 all__spin.spin_0_4 all__slab.slab_0_2 all__mio.mio_0_5 all__log.log_0_3 all__context.context_1_0_0 all__libc.libc_0_2 all__num_cpus.num_cpus_1_0_0 all__time.time_0_1 all__owning_ref.owning_ref_0_2 ];
  };
  "mioco_0_8" = mioco_0_8_1;
  "mioco_0" = mioco_0_8_1;}