#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  warn_0_1_0 = buildCratesLib {
    name = "warn";
    version = "0.1.0";
    hash = "58cf43874d880cfc26a0ad534efec02b92781775fcb3246037e1fa543258d8b7";
    deps = with allCrates; [  all__log.log_0_3 ];
  };
  warn_0_1_1 = buildCratesLib {
    name = "warn";
    version = "0.1.1";
    hash = "7d1269c72c8838e97a5a2492d2041239c1afbdf35c0e25960297a2b55ccc31ed";
    deps = with allCrates; [  all__log.log_0_3 ];
  };
  warn_0_2_0 = buildCratesLib {
    name = "warn";
    version = "0.2.0";
    hash = "d38d088c467333812bc60a88ff70dc4305ab1f70f03ee812e73b6344ee049e17";
    deps = with allCrates; [  all__log.log_0_3 ];
  };
  "warn_0_1" = warn_0_1_1;
  "warn_0_2" = warn_0_2_0;
  "warn_0" = warn_0_2_0;}