#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  crowbook-intl-runtime_0_1_0 = buildCratesLib {
    name = "crowbook-intl-runtime";
    version = "0.1.0";
    hash = "62cf6ec512b4d7fb7d8683efa703b17e5b8f5e24a9eb7ec9fb92237f039d941c";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 ];
  };
  "crowbook-intl-runtime_0_1" = crowbook-intl-runtime_0_1_0;
  "crowbook-intl-runtime_0" = crowbook-intl-runtime_0_1_0;}