#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  jsonnet_0_1_0 = buildCratesLib {
    name = "jsonnet";
    version = "0.1.0";
    hash = "970444ea10b23ca1003ed807074ee3f25ee3fb213009e2175d1d93de42af17cd";
    deps = with allCrates; [ libc ];
  };}