#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  ogg_metadata_0_1_0 = buildCratesLib {
    name = "ogg_metadata";
    version = "0.1.0";
    hash = "c593fb78271fa84893d7058506759ce3b92e443a4855458c2d73d6d05ed9c2e1";
    deps = with allCrates; [  all__ogg.ogg_0_2 all__byteorder.byteorder_0_5 ];
  };
  ogg_metadata_0_2_0 = buildCratesLib {
    name = "ogg_metadata";
    version = "0.2.0";
    hash = "1e20473b68e7c94812dcc0478aa039bae163ba4a128f948da3e89eea59f24cd5";
    deps = with allCrates; [  all__ogg.ogg_0_3 all__byteorder.byteorder_0_5 ];
  };
  "ogg_metadata_0_1" = ogg_metadata_0_1_0;
  ogg_metadata_0_3_0 = buildCratesLib {
    name = "ogg_metadata";
    version = "0.3.0";
    hash = "e755cc735fa6faa709cb23048433d9201d6caa85fa96215386ccdd5e9b40ad01";
    deps = with allCrates; [  all__ogg.ogg_0_3 all__byteorder.byteorder_0_5 ];
  };
  "ogg_metadata_0_2" = ogg_metadata_0_2_0;
  "ogg_metadata_0_3" = ogg_metadata_0_3_0;
  "ogg_metadata_0" = ogg_metadata_0_3_0;}