#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  alexa_0_1_0 = buildCratesLib {
    name = "alexa";
    version = "0.1.0";
    hash = "6e528b46fc82cd4f3ef8229619f3e6391ccbf9d40472fc7a5dab9ea7fa112c87";
    deps = with allCrates; [  all__bodyparser.bodyparser_0_4 all__iron.iron_0_4 all__chrono.chrono_0_2 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__serde_codegen.serde_codegen_0_8 ];
  };
  alexa_0_1_1 = buildCratesLib {
    name = "alexa";
    version = "0.1.1";
    hash = "3d9c15ca43af1e06ee8444e0c0e73576d6aae5495b760dc09496d5b3e3b09720";
    deps = with allCrates; [  all__bodyparser.bodyparser_0_4 all__serde_json.serde_json_0_8 all__chrono.chrono_0_2 all__iron.iron_0_4 all__serde.serde_0_8 all__serde_codegen.serde_codegen_0_8 ];
  };
  alexa_0_1_2 = buildCratesLib {
    name = "alexa";
    version = "0.1.2";
    hash = "5379d24ec767ab54070230ff474d5e4b9e8773c1a516d13f1f10f4068ff97685";
    deps = with allCrates; [  all__bodyparser.bodyparser_0_4 all__serde_json.serde_json_0_8 all__chrono.chrono_0_2 all__serde.serde_0_8 all__iron.iron_0_4 all__serde_codegen.serde_codegen_0_8 ];
  };
  "alexa_0_1" = alexa_0_1_2;
  "alexa_0" = alexa_0_1_2;}