#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tgff_0_0_2 = buildCratesLib {
    name = "tgff";
    version = "0.0.2";
    hash = "76fe387549d21c6fdab2cf9cd71f3fbd7f7886e237965cdd3e40f748f182c84d";
    deps = with allCrates; [  ];
  };
  tgff_0_0_3 = buildCratesLib {
    name = "tgff";
    version = "0.0.3";
    hash = "4121205e3e88e61695742240612edf1fde8216fb118d71b866c9a645809a57ca";
    deps = with allCrates; [  ];
  };
  tgff_0_0_5 = buildCratesLib {
    name = "tgff";
    version = "0.0.5";
    hash = "82c9de4c0e3c183025efa6da9dc264e5a8d0098eeee83f86bde994de4b8534ae";
    deps = with allCrates; [  ];
  };
  tgff_0_0_6 = buildCratesLib {
    name = "tgff";
    version = "0.0.6";
    hash = "7fc07688da884eeef7c7c723f67641541cb14a3127ff73a2fc65d34231dd580c";
    deps = with allCrates; [  ];
  };
  tgff_0_0_7 = buildCratesLib {
    name = "tgff";
    version = "0.0.7";
    hash = "c991af5cef371fa627ad6e6eb920955dc724cd172c15f3d218f1ca7e99323dfd";
    deps = with allCrates; [  ];
  };
  tgff_0_0_8 = buildCratesLib {
    name = "tgff";
    version = "0.0.8";
    hash = "4224d142ccc2074b1ea9db87228d0101dcabcefc553e826c30b09300eacb4da5";
    deps = with allCrates; [  ];
  };
  tgff_0_0_9 = buildCratesLib {
    name = "tgff";
    version = "0.0.9";
    hash = "d22bd4f67a12b3a01298d583aaeedf2aab455e5c33834dfe365c5bc8de2e9330";
    deps = with allCrates; [  ];
  };
  tgff_0_1_0 = buildCratesLib {
    name = "tgff";
    version = "0.1.0";
    hash = "b9dbf48f56cd4b861e9ddd74274f949ea3126d4cf33aa5d2a37897a59b571afa";
    deps = with allCrates; [  ];
  };
  "tgff_0_0" = tgff_0_0_9;
  tgff_0_1_1 = buildCratesLib {
    name = "tgff";
    version = "0.1.1";
    hash = "0091c1dcabb45d3a7f409550528c877d2085c963ef2e9d5648af06c1ee93d7e5";
    deps = with allCrates; [  ];
  };
  tgff_0_1_2 = buildCratesLib {
    name = "tgff";
    version = "0.1.2";
    hash = "8e672e35210910dc4cca24e5a4e65961a1a7f86fcf945b4c71fcb3a273773296";
    deps = with allCrates; [  ];
  };
  tgff_0_1_3 = buildCratesLib {
    name = "tgff";
    version = "0.1.3";
    hash = "036fc4e3add9b40c33a057f1a22e6dc2ca4361d8597795338da855913a7b827b";
    deps = with allCrates; [  ];
  };
  tgff_0_1_4 = buildCratesLib {
    name = "tgff";
    version = "0.1.4";
    hash = "117f41e746f6236ba758a440983d9475acb4051b5d37baa4dcf1b4f879e96ac1";
    deps = with allCrates; [  ];
  };
  tgff_0_1_5 = buildCratesLib {
    name = "tgff";
    version = "0.1.5";
    hash = "57c9e929aab1cdb35168dacae0147e89827165d8864043cd0d7bd856af00a9e3";
    deps = with allCrates; [  ];
  };
  tgff_0_1_6 = buildCratesLib {
    name = "tgff";
    version = "0.1.6";
    hash = "024857ae365ba3bd5a0691676a7514c635b1b4a7071a190ed224bf6e36fc95cb";
    deps = with allCrates; [  ];
  };
  tgff_0_1_7 = buildCratesLib {
    name = "tgff";
    version = "0.1.7";
    hash = "ddbdeb7ed64d182541098090ebea95206c6168546cd2a323cfaf8d3e497dc8c2";
    deps = with allCrates; [  ];
  };
  tgff_0_1_8 = buildCratesLib {
    name = "tgff";
    version = "0.1.8";
    hash = "151fac5612499a773d7c2e6136bfac1c45f2acbd90624e7cd354ef8ef654a500";
    deps = with allCrates; [  ];
  };
  tgff_0_1_9 = buildCratesLib {
    name = "tgff";
    version = "0.1.9";
    hash = "73af78919e7e799e65267da6c90edf5e7f0b170be2292e45af59dbeb4093c030";
    deps = with allCrates; [  num ];
  };
  tgff_0_1_10 = buildCratesLib {
    name = "tgff";
    version = "0.1.10";
    hash = "c33264aa41686fb606c7196910132bc395a75301f1df42a0487cc14fe509bfdc";
    deps = with allCrates; [  ];
  };
  "tgff_0_1" = tgff_0_1_10;
  "tgff_0" = tgff_0_1_10;}