#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  parry_0_1_0 = buildCratesLib {
    name = "parry";
    version = "0.1.0";
    hash = "1d976df8691d5a50bf300e8580a9186f1d7a759e78aace90675e5ffe36119e97";
    deps = with allCrates; [ num rayon crossbeam ];
  };}