#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  hdd_standby_0_1_0 = buildCratesLib {
    name = "hdd_standby";
    version = "0.1.0";
    hash = "631e5e0b161c56b64472a58c00db1a5a9f7c4a00e0d6e0843bb3a149388dc2b4";
    deps = with allCrates; [  all__libc.libc_0_2 ];
  };
  "hdd_standby_0_1" = hdd_standby_0_1_0;
  "hdd_standby_0" = hdd_standby_0_1_0;}