#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  uinput_0_1_0 = buildCratesLib {
    name = "uinput";
    version = "0.1.0";
    hash = "324029022d1a15d6d6fc5f45e70f24bc54214c123efd688667b52935bee604e2";
    deps = with allCrates; [ custom_derive enum_derive uinput-sys nix libc ];
  };
  uinput_0_1_1 = buildCratesLib {
    name = "uinput";
    version = "0.1.1";
    hash = "7955c050157c2ebf1221f010fe21250933ed8b9a024c4f8a4517794c6268a862";
    deps = with allCrates; [ libc custom_derive enum_derive uinput-sys nix ];
  };
  uinput_0_1_2 = buildCratesLib {
    name = "uinput";
    version = "0.1.2";
    hash = "c6fb47990632669fb34401b3b67e52120d8334f08c38047924fae8f9a82d46fa";
    deps = with allCrates; [ uinput-sys nix custom_derive enum_derive libc ];
  };}