#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  stainless_0_0_1 = buildCratesLib {
    name = "stainless";
    version = "0.0.1";
    hash = "f5399fcabbbdaaedc2cabbd859ecfa3ed6c2755b58865a08be39f07fccef372a";
    deps = with allCrates; [  ];
  };
  stainless_0_0_2 = buildCratesLib {
    name = "stainless";
    version = "0.0.2";
    hash = "480368f7f0eb78454083ba543edace041450b248af9362c9e54c0a2261a68698";
    deps = with allCrates; [  ];
  };
  stainless_0_0_3 = buildCratesLib {
    name = "stainless";
    version = "0.0.3";
    hash = "3c33bcaa9d81f97330b91ab003f0605cc0efee62dded8c60fc2ee1e1c3ce7214";
    deps = with allCrates; [  ];
  };
  stainless_0_0_4 = buildCratesLib {
    name = "stainless";
    version = "0.0.4";
    hash = "3aadce5ddd738a86165bf9fbcb3b2f7f8e87728830d8bd81abe8148d2fa9fd8c";
    deps = with allCrates; [  ];
  };
  stainless_0_0_5 = buildCratesLib {
    name = "stainless";
    version = "0.0.5";
    hash = "a476370f87448fd00873abb961c5c00551d2057c7a6041c3893a02fdac380333";
    deps = with allCrates; [  ];
  };
  stainless_0_0_6 = buildCratesLib {
    name = "stainless";
    version = "0.0.6";
    hash = "2a49d3d75ed6927fc45a794723e1a905a063f5c627033f0c62ea4454bcf97c70";
    deps = with allCrates; [  ];
  };
  stainless_0_0_7 = buildCratesLib {
    name = "stainless";
    version = "0.0.7";
    hash = "6e3b98001cd8981355d24da6d1dcfbeb0ce55f69fc546f5f6c4c40e09a8cf23d";
    deps = with allCrates; [  ];
  };
  stainless_0_0_8 = buildCratesLib {
    name = "stainless";
    version = "0.0.8";
    hash = "7cc7231cf0006975785c95be5a802ef664861a50efe7ff0ae632f710ff6e955c";
    deps = with allCrates; [  ];
  };
  stainless_0_0_9 = buildCratesLib {
    name = "stainless";
    version = "0.0.9";
    hash = "c4d040e5e3cf55eb5610136a718477b51e6b516948aa2bd7f75e755135f50ba3";
    deps = with allCrates; [  ];
  };
  stainless_0_0_10 = buildCratesLib {
    name = "stainless";
    version = "0.0.10";
    hash = "e2c73b29b90b75041c47169c0e9a2f4ff07bc4fd8faeaaf389858317d7f873a4";
    deps = with allCrates; [  ];
  };
  stainless_0_0_11 = buildCratesLib {
    name = "stainless";
    version = "0.0.11";
    hash = "00da0b2434b1d2b7c0f00f9a60618502620f4eae337d749e705f452c2f1a20c3";
    deps = with allCrates; [  ];
  };
  stainless_0_0_12 = buildCratesLib {
    name = "stainless";
    version = "0.0.12";
    hash = "12756f6731748d022c145378548cb49f6cc339263fb20ddea792bbbf16c977c0";
    deps = with allCrates; [  ];
  };
  stainless_0_0_13 = buildCratesLib {
    name = "stainless";
    version = "0.0.13";
    hash = "89b5d099d9c6203ff130f5bf503faaa6148bf394ec9bb1e59a6510f80c477d85";
    deps = with allCrates; [  ];
  };
  stainless_0_0_14 = buildCratesLib {
    name = "stainless";
    version = "0.0.14";
    hash = "0c484d9642f232904f566c8be986cc48b374bd384d113a0fa1bf76ee92e372d2";
    deps = with allCrates; [  ];
  };
  stainless_0_0_15 = buildCratesLib {
    name = "stainless";
    version = "0.0.15";
    hash = "0e90088c0a765713986e674d11e1a0e75930cbd364ccc4aec0eefa8c705c1089";
    deps = with allCrates; [  ];
  };
  stainless_0_0_16 = buildCratesLib {
    name = "stainless";
    version = "0.0.16";
    hash = "6b058e917362a735362a267dd58f8b9924c925d6a5e2fb1fd0e2673fc62fd378";
    deps = with allCrates; [  ];
  };
  stainless_0_0_17 = buildCratesLib {
    name = "stainless";
    version = "0.0.17";
    hash = "5767aadff02aa8ad5823c2f3051fb069d1d2106061637b130889093bafb0a9fe";
    deps = with allCrates; [  ];
  };
  stainless_0_0_18 = buildCratesLib {
    name = "stainless";
    version = "0.0.18";
    hash = "6b87318ab7fab84a9ebfece8f9ecb8aab089921fa3c76ca65971bbd182632e9e";
    deps = with allCrates; [  ];
  };
  stainless_0_1_0 = buildCratesLib {
    name = "stainless";
    version = "0.1.0";
    hash = "68c834271b1b16a3bac9f3b0aa7b6e44b920d775364098d0044eb1326f582404";
    deps = with allCrates; [  ];
  };
  "stainless_0_0" = stainless_0_0_18;
  stainless_0_1_1 = buildCratesLib {
    name = "stainless";
    version = "0.1.1";
    hash = "0ef71f336b437872c612a9e0e690796aff1b788be2a9206703fc9e8244f03647";
    deps = with allCrates; [  ];
  };
  stainless_0_1_2 = buildCratesLib {
    name = "stainless";
    version = "0.1.2";
    hash = "b641a3cce7ae888ad9a0e25da22a9f75e6cf6e9a41640312f91770c0156578f3";
    deps = with allCrates; [  ];
  };
  stainless_0_1_3 = buildCratesLib {
    name = "stainless";
    version = "0.1.3";
    hash = "f28604db0befd43fd6ef07ca2057e6bb4d06f743907ca1d8dab2955cfa92983b";
    deps = with allCrates; [  ];
  };
  stainless_0_1_4 = buildCratesLib {
    name = "stainless";
    version = "0.1.4";
    hash = "3e375d5b67c356196d500172f7b78ad0620962b27e7c4d1985718ff9e963db77";
    deps = with allCrates; [  ];
  };
  stainless_0_1_5 = buildCratesLib {
    name = "stainless";
    version = "0.1.5";
    hash = "c719bd1cc7837ab0aa8d7bd765595081e5c0348037a640936a6b7f9afe2b154f";
    deps = with allCrates; [  ];
  };
  stainless_0_1_6 = buildCratesLib {
    name = "stainless";
    version = "0.1.6";
    hash = "08dc26c706efcaefc81e3a200beca1546bdf2f0692e41730dfb9577d9bb5da5c";
    deps = with allCrates; [  ];
  };
  stainless_0_1_7 = buildCratesLib {
    name = "stainless";
    version = "0.1.7";
    hash = "e63283f9cb88f8f31939bc7339d2dcab86b30f13b68c432d873bd6fff5b56cc5";
    deps = with allCrates; [  ];
  };
  stainless_0_1_8 = buildCratesLib {
    name = "stainless";
    version = "0.1.8";
    hash = "376da816b3c0145203b9f06018bb5962f4d20f5066ae4da1413aeb28713741b3";
    deps = with allCrates; [  ];
  };
  stainless_0_1_9 = buildCratesLib {
    name = "stainless";
    version = "0.1.9";
    hash = "f3d9b255383ca93c5cad95d506e98efaccd22552683c99207ad99733f651ba67";
    deps = with allCrates; [  ];
  };
  stainless_0_1_10 = buildCratesLib {
    name = "stainless";
    version = "0.1.10";
    hash = "8e1e0644878498a971f448fdff161ef22192d554d6bbade5d0bdb0ea014929f9";
    deps = with allCrates; [  ];
  };
  "stainless_0_1" = stainless_0_1_10;
  "stainless_0" = stainless_0_1_10;}