#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  futures-mio_0_1_0 = buildCratesLib {
    name = "futures-mio";
    version = "0.1.0";
    hash = "00015d54c6c57fcce25c5f23912bbd3e53fbe1e478783494b3f037483823c333";
    deps = with allCrates; [  all__mio.mio_0_6 all__slab.slab_0_2 all__futures.futures_0_1 all__scoped-tls.scoped-tls_0_1 all__log.log_0_3 all__futures-io.futures-io_0_1 ];
  };
  "futures-mio_0_1" = futures-mio_0_1_0;
  "futures-mio_0" = futures-mio_0_1_0;}