#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  stockfighter_0_1_0 = buildCratesLib {
    name = "stockfighter";
    version = "0.1.0";
    hash = "1dc9d79ab5e6edff115ae6c49af5c6a9bda6a751cb610579354d07ad397e92ca";
    deps = with allCrates; [  all__serde_json.serde_json_0_7 all__serde.serde_0_7 all__serializable_enum.serializable_enum_0_3 all__websocket.websocket_0_16 all__hyper.hyper_0_8 all__serde_macros.serde_macros_0_7 all__chrono.chrono_0_2 ];
  };
  stockfighter_0_1_1 = buildCratesLib {
    name = "stockfighter";
    version = "0.1.1";
    hash = "54b13ab3abec88e6e1e8eb4df2b690d1f90ca9c3d70a14eb91439af671acc9fe";
    deps = with allCrates; [  all__serde_json.serde_json_0_7 all__serde_macros.serde_macros_0_7 all__websocket.websocket_0_16 all__chrono.chrono_0_2 all__hyper.hyper_0_8 all__serde.serde_0_7 all__serializable_enum.serializable_enum_0_3 ];
  };
  stockfighter_0_2_0 = buildCratesLib {
    name = "stockfighter";
    version = "0.2.0";
    hash = "e1da23271ca882f5f8d326f9532f65a390cb73f4441e1a1f8d7a3e8982aa32ac";
    deps = with allCrates; [  all__hyper.hyper_0_8 all__serializable_enum.serializable_enum_0_3 all__chrono.chrono_0_2 all__serde.serde_0_7 all__serde_macros.serde_macros_0_7 all__serde_json.serde_json_0_7 ];
  };
  "stockfighter_0_1" = stockfighter_0_1_1;
  stockfighter_0_2_1 = buildCratesLib {
    name = "stockfighter";
    version = "0.2.1";
    hash = "edff93a7583fe6605c8125ca77a6dcb59699ce193a3e635cafa0e2ab2cb1070b";
    deps = with allCrates; [  all__serializable_enum.serializable_enum_0_3 all__serde_json.serde_json_0_7 all__serde.serde_0_7 all__hyper.hyper_0_9 all__serde_macros.serde_macros_0_7 all__chrono.chrono_0_2 ];
  };
  "stockfighter_0_2" = stockfighter_0_2_1;
  "stockfighter_0" = stockfighter_0_2_1;}