#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  grabinput_0_1_0 = buildCratesLib {
    name = "grabinput";
    version = "0.1.0";
    hash = "328a9b8c7ba5e6f07f6b87466ab5aac9af0c5f4c86c6b1a16cf3edc6688df232";
    deps = with allCrates; [  ];
  };
  grabinput_0_1_1 = buildCratesLib {
    name = "grabinput";
    version = "0.1.1";
    hash = "c546f5ae5cf1152f9a931bf59c8999812be7b4903f087b6a3a8e055484659d24";
    deps = with allCrates; [  ];
  };
  grabinput_0_2_0 = buildCratesLib {
    name = "grabinput";
    version = "0.2.0";
    hash = "28fd391a051a979249ba5b34789ae3644dc1057f6ddde98df2016d8a671a4884";
    deps = with allCrates; [  ];
  };
  "grabinput_0_1" = grabinput_0_1_1;
  grabinput_0_2_1 = buildCratesLib {
    name = "grabinput";
    version = "0.2.1";
    hash = "22799229c87c97ee7738fe819aa5a3e858a12a1498a56e5d46965e2bb286b522";
    deps = with allCrates; [  ];
  };
  "grabinput_0_2" = grabinput_0_2_1;
  "grabinput_0" = grabinput_0_2_1;}