#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  ispell_0_1_0 = buildCratesLib {
    name = "ispell";
    version = "0.1.0";
    hash = "4d842517098427e7281c1850a39cd52d46b279daf8355ccd539c73ca122012e2";
    deps = with allCrates; [ ];
  };
  ispell_0_2_0 = buildCratesLib {
    name = "ispell";
    version = "0.2.0";
    hash = "6c99f2974d86e501da7bb3c0eba62d2147ba4f55495eac482f2a48d34b016209";
    deps = with allCrates; [ ];
  };
  ispell_0_3_0 = buildCratesLib {
    name = "ispell";
    version = "0.3.0";
    hash = "447e6b259cf10237fcc9f5f9cbd267f75274395a9d5197c50e8d93499fef5331";
    deps = with allCrates; [ ];
  };}