#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  aruba_ripple_0_0_1 = buildCratesLib {
    name = "aruba_ripple";
    version = "0.0.1";
    hash = "e879a875cf9117eb33f4cced0119105c1fd91505f1e7b9083d90f05846a75066";
    deps = with allCrates; [ url hyper ];
  };}