#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rules_0_0_1 = buildCratesLib {
    name = "rules";
    version = "0.0.1";
    hash = "9621e64216924c290ad0432a6c5537a093d675f562282b71b253115bb60edacf";
    deps = with allCrates; [ ];
  };
  rules_0_0_2 = buildCratesLib {
    name = "rules";
    version = "0.0.2";
    hash = "a7c272549f687c01bd66f4713188aabb849c29234960d2aa5a1c38a12f84c3f8";
    deps = with allCrates; [ ];
  };}