#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rc4_0_0_0 = buildCratesLib {
    name = "rc4";
    version = "0.0.0";
    hash = "e9b3580724b7d95d0a76fae4f1ac6bfa42e7e4973778480fd3ac1162c6c80c24";
    deps = with allCrates; [ ];
  };}