#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rgo_0_1_0 = buildCratesLib {
    name = "rgo";
    version = "0.1.0";
    hash = "98e02b8a094c8ada014784442a30c6925ee9308972de223d35a4b43f21611a8f";
    deps = with allCrates; [ log quick-error time env_logger num convenience lazy_static ];
  };}