#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rlp_0_1_0 = buildCratesLib {
    name = "rlp";
    version = "0.1.0";
    hash = "dae7de513c24a119bfb51d4ac975bce4a9c5683f797eba70cae7e212bb918686";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__elastic-array.elastic-array_0_5 all__ethcore-bigint.ethcore-bigint_0_1 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "rlp_0_1" = rlp_0_1_0;
  "rlp_0" = rlp_0_1_0;}