#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  fastchemail_0_9_0 = buildCratesLib {
    name = "fastchemail";
    version = "0.9.0";
    hash = "e8828d844ffdbdfc55b03080e5d57b63d89a7ae78d3d117d410621b6fc581161";
    deps = with allCrates; [ asciiutils ];
  };
  fastchemail_0_9_1 = buildCratesLib {
    name = "fastchemail";
    version = "0.9.1";
    hash = "7d469d8b62d5ea112408561ce99bcd4d93188af76da8f0cb12f992d7c9d7f228";
    deps = with allCrates; [ asciiutils ];
  };
  fastchemail_0_9_2 = buildCratesLib {
    name = "fastchemail";
    version = "0.9.2";
    hash = "7a57e3955ed858938194e324d311afbe285f928eae65c4d29fd089f6e99503f4";
    deps = with allCrates; [ asciiutils ];
  };
  fastchemail_0_9_3 = buildCratesLib {
    name = "fastchemail";
    version = "0.9.3";
    hash = "d53a754d1608c9d5211a680747dfc46724990f575883332074bbbe0871c1b44c";
    deps = with allCrates; [ asciiutils ];
  };}