#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  fastlog_0_0_1 = buildCratesLib {
    name = "fastlog";
    version = "0.0.1";
    hash = "fe15980e1d0133ab69d42a9c9d79e62374c6f9bfa041698c1d8304307896f543";
    deps = with allCrates; [ time log ];
  };
  fastlog_0_1_0 = buildCratesLib {
    name = "fastlog";
    version = "0.1.0";
    hash = "911a90a670efde38ab8c7e9374f2a230a7c67d7ce000c16ffd5afd51b559f238";
    deps = with allCrates; [ time log ];
  };
  fastlog_0_1_1 = buildCratesLib {
    name = "fastlog";
    version = "0.1.1";
    hash = "8e2a4d94dfa2f9167869fc5a7ad5b581efc68239c1f9daa932130e2c0cf321f0";
    deps = with allCrates; [ log time ];
  };}