#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  preserve_0_1_0 = buildCratesLib {
    name = "preserve";
    version = "0.1.0";
    hash = "c1d02537634dd9c15392d06bfe8d62e4c813d4184cb5ad2b6db49fbb54c15936";
    deps = with allCrates; [ libc rust-crypto rusqlite rustc-serialize tempdir getopts rust-lzma rust-acd rand ];
  };}