#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  english-lint_0_1_0 = buildCratesLib {
    name = "english-lint";
    version = "0.1.0";
    hash = "0f1b4d6aa45eedc6ccb223110d9aca464c693eecd5cb47ef31026496be6cb342";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__aho-corasick.aho-corasick_0_5 ];
  };
  english-lint_0_1_1 = buildCratesLib {
    name = "english-lint";
    version = "0.1.1";
    hash = "b955ed42dfac9ab9d97e387cc16558d68f5efb096d3a21e320b5a8ab328aaffc";
    deps = with allCrates; [  all__regex.regex_0_1 all__aho-corasick.aho-corasick_0_5 all__lazy_static.lazy_static_0_2 ];
  };
  "english-lint_0_1" = english-lint_0_1_1;
  "english-lint_0" = english-lint_0_1_1;}