#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  crc64-rs_0_1_0 = buildCratesLib {
    name = "crc64-rs";
    version = "0.1.0";
    hash = "076fe66de8cd231a89311374d355bc3deed508efb31f87da6faf82af00762d89";
    deps = with allCrates; [  ];
  };
  crc64-rs_0_2_0 = buildCratesLib {
    name = "crc64-rs";
    version = "0.2.0";
    hash = "ea93058a13e2dcae127bdcc695e9ec6d8e76d0e7c490cafdd993fd62f85060df";
    deps = with allCrates; [  ];
  };
  "crc64-rs_0_1" = crc64-rs_0_1_0;
  "crc64-rs_0_2" = crc64-rs_0_2_0;
  "crc64-rs_0" = crc64-rs_0_2_0;}