#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  slog_0_1_0 = buildCratesLib {
    name = "slog";
    version = "0.1.0";
    hash = "0623210fe1ee497f79ff1ac0cb50d2de9c190dd909db727c8cfbda4614c4accd";
    deps = with allCrates; [  all__crossbeam.crossbeam_0_2 ];
  };
  slog_0_2_0 = buildCratesLib {
    name = "slog";
    version = "0.2.0";
    hash = "58386212674e9fe0676b2bf0cddf6923cdd10ca24d41d01228917694db145a6c";
    deps = with allCrates; [  all__serde.serde_0_7 all__serde_json.serde_json_0_7 all__ansi_term.ansi_term_0_7 all__isatty.isatty_0_1 all__crossbeam.crossbeam_0_2 ];
  };
  "slog_0_1" = slog_0_1_0;
  slog_0_3_0 = buildCratesLib {
    name = "slog";
    version = "0.3.0";
    hash = "2aa9c847e9c676108fe04ab2db21ba63ebae067406cbc898f6a295252c07b26b";
    deps = with allCrates; [  all__crossbeam.crossbeam_0_2 all__serde.serde_0_7 all__isatty.isatty_0_1 all__serde_json.serde_json_0_7 all__chrono.chrono_0_2 all__rustc-serialize.rustc-serialize_0_3 all__ansi_term.ansi_term_0_7 ];
  };
  "slog_0_2" = slog_0_2_0;
  slog_0_4_0 = buildCratesLib {
    name = "slog";
    version = "0.4.0";
    hash = "228f2c38420b758a9e8deb4abb9771280a72a19a932344e3477d1e7a9ba2ee08";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__serde.serde_0_7 all__ansi_term.ansi_term_0_7 all__rustc-serialize.rustc-serialize_0_3 all__serde_json.serde_json_0_7 all__crossbeam.crossbeam_0_2 all__isatty.isatty_0_1 ];
  };
  "slog_0_3" = slog_0_3_0;
  slog_0_5_0 = buildCratesLib {
    name = "slog";
    version = "0.5.0";
    hash = "2443935b87573b6fef6900c0044f03cc86c14a5a25ae46e382565efd0a7c8d21";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__crossbeam.crossbeam_0_2 all__chrono.chrono_0_2 ];
  };
  "slog_0_4" = slog_0_4_0;
  slog_0_6_0 = buildCratesLib {
    name = "slog";
    version = "0.6.0";
    hash = "bf6e3c7d56c5f03d81ea1e0713b7fd5b64ea69b9036d627c1c3a11c1fa039314";
    deps = with allCrates; [  all__crossbeam.crossbeam_0_2 all__error-chain.error-chain_0_2 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 ];
  };
  "slog_0_5" = slog_0_5_0;
  slog_0_7_0 = buildCratesLib {
    name = "slog";
    version = "0.7.0";
    hash = "be3b9efc8eb59f550785ca962336f8bd560f2e53c201396c399f3bfa2f9c60f4";
    deps = with allCrates; [  all__error-chain.error-chain_0_2 all__crossbeam.crossbeam_0_2 all__chrono.chrono_0_2 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "slog_0_6" = slog_0_6_0;
  slog_1_0_0 = buildCratesLib {
    name = "slog";
    version = "1.0.0";
    hash = "fff6d8845a2ae6c0da0d09bc7f59b75a5f8b263d9acf608e80991921adf0c136";
    deps = with allCrates; [  ];
  };
  "slog_0" = slog_0_7_0;
  slog_1_0_1 = buildCratesLib {
    name = "slog";
    version = "1.0.1";
    hash = "d816659be2527f0f85437f31ebd3bea98a2553f83c41a6404abae9f530c9ab62";
    deps = with allCrates; [  ];
  };
  slog_1_1_0 = buildCratesLib {
    name = "slog";
    version = "1.1.0";
    hash = "ceff3480ef0f625382d25c89bfa5d4dffbd8ff1c457c107abd7d0a6013d52118";
    deps = with allCrates; [  ];
  };
  "slog_1_0" = slog_1_0_1;
  slog_1_2_0 = buildCratesLib {
    name = "slog";
    version = "1.2.0";
    hash = "a9b9c18083fb1c248355784cf996783000e5eab2af74afcd0f3ec514a301f032";
    deps = with allCrates; [  ];
  };
  "slog_1_1" = slog_1_1_0;
  slog_1_2_1 = buildCratesLib {
    name = "slog";
    version = "1.2.1";
    hash = "7f29d8783f8b8fb78ed0f26caeeb750e94f96a3d22f3c85dd1e2f34a2ae407d9";
    deps = with allCrates; [  ];
  };
  slog_1_3_0 = buildCratesLib {
    name = "slog";
    version = "1.3.0";
    hash = "fd3be6196bc9ddf0b19b520a2bb5276fd7b9c1b7e970b6054348a2e725d61dee";
    deps = with allCrates; [  ];
  };
  "slog_1_2" = slog_1_2_1;
  slog_1_3_1 = buildCratesLib {
    name = "slog";
    version = "1.3.1";
    hash = "6b75cf7e6cfea3aacc4ddca2dfb215021ca51de9bd69f5a2fa02a1b1ebf8b3d5";
    deps = with allCrates; [  ];
  };
  slog_1_3_2 = buildCratesLib {
    name = "slog";
    version = "1.3.2";
    hash = "19138575064905f49832ef72c856d614a78c5b25881f93b48954bf593464b7f5";
    deps = with allCrates; [  ];
  };
  "slog_1_3" = slog_1_3_2;
  "slog_1" = slog_1_3_2;}