#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  slog-extra_0_1_0 = buildCratesLib {
    name = "slog-extra";
    version = "0.1.0";
    hash = "43af8bbfcc724ba1171f1763782b13c1f93752fdfa7943af4bcdf30701e89bfd";
    deps = with allCrates; [ thread_local slog ];
  };
  slog-extra_0_1_1 = buildCratesLib {
    name = "slog-extra";
    version = "0.1.1";
    hash = "f571614f815a4dc3aad7b9052d1e3eefd5ab76bb36efa90d4dc9ac134142b445";
    deps = with allCrates; [ thread_local slog ];
  };}