#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  hotswap-runtime_0_1_0 = buildCratesLib {
    name = "hotswap-runtime";
    version = "0.1.0";
    hash = "c1a72d76cce32479f257be8d29aec3ba7aef4781b48970e56bc6b7bfeffd41a9";
    deps = with allCrates; [  all__parking_lot.parking_lot_0_3 all__libloading.libloading_0_3 ];
  };
  "hotswap-runtime_0_1" = hotswap-runtime_0_1_0;
  "hotswap-runtime_0" = hotswap-runtime_0_1_0;}