#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  closet_0_1_0 = buildCratesLib {
    name = "closet";
    version = "0.1.0";
    hash = "e7d890fb546806ead120959e5cad59bd5f50045df18a57d93a638c5cecacc6c7";
    deps = with allCrates; [ ];
  };
  closet_0_1_1 = buildCratesLib {
    name = "closet";
    version = "0.1.1";
    hash = "d51a59bdc58b1786cad5824a213ba43b4b984e88ab43ba845fd8cd31a6e50a91";
    deps = with allCrates; [ ];
  };
  closet_0_1_2 = buildCratesLib {
    name = "closet";
    version = "0.1.2";
    hash = "5464df726b9a66da167001c1ea888943eed65e0319c80818b4d1a01fd71e7723";
    deps = with allCrates; [ ];
  };
  closet_0_1_3 = buildCratesLib {
    name = "closet";
    version = "0.1.3";
    hash = "be6e83fdfcc26647573fbdf4358917c19c86ee03d6f2403151de0bec862c7321";
    deps = with allCrates; [ ];
  };
  closet_0_2_0 = buildCratesLib {
    name = "closet";
    version = "0.2.0";
    hash = "566e7d67b744cd8c0e7e23660671cc7a0f46ea851cc1b66efee5168e23cf9f7a";
    deps = with allCrates; [ ];
  };}