#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  rst_app_0_1_5 = buildCratesLib {
    name = "rst_app";
    version = "0.1.5";
    hash = "a878f77dad8cc33c1fde38c251a5b932eb949e5a495c8434af7be4b85e242d3d";
    deps = with allCrates; [ lazy_static ansi_term toml strfmt time clap regex itertools log fern ];
  };
  rst_app_0_2_0 = buildCratesLib {
    name = "rst_app";
    version = "0.2.0";
    hash = "92301bfd7765dee0bc63befe5f2a2ae8b7255d572d233be6b7753ac9e9e476c7";
    deps = with allCrates; [ time ansi_term fern toml strfmt lazy_static regex clap log itertools ];
  };
  rst_app_0_2_1 = buildCratesLib {
    name = "rst_app";
    version = "0.2.1";
    hash = "194a703a3f87dee5bdab30d78d7fd5a6ccd4ef8fcbd74b73af01f390639777a2";
    deps = with allCrates; [ log strfmt toml lazy_static regex ansi_term time clap fern itertools ];
  };
  rst_app_0_2_6 = buildCratesLib {
    name = "rst_app";
    version = "0.2.6";
    hash = "2fc2d29c679af2da23cbd05e5daadbf7d820fe941c67fd5d97ec0a2a4debff3e";
    deps = with allCrates; [ regex toml ansi_term lazy_static rustc-serialize log strfmt clap time itertools fern ];
  };
  rst_app_0_3_0 = buildCratesLib {
    name = "rst_app";
    version = "0.3.0";
    hash = "8a7a29287143e40d755aa084d21668f4398f7309bb4a08ba44f892eec98230ac";
    deps = with allCrates; [ itertools ansi_term strfmt log clap serde_json time regex rustc-serialize fern lazy_static serde toml ];
  };
  rst_app_0_3_1 = buildCratesLib {
    name = "rst_app";
    version = "0.3.1";
    hash = "a1418b07e3459ff7c3765b00cfd28a6b9960b15269258228b519326ed2802099";
    deps = with allCrates; [ log rustc-serialize serde strfmt time regex fern clap serde_json toml ansi_term itertools lazy_static ];
  };
  rst_app_0_3_2 = buildCratesLib {
    name = "rst_app";
    version = "0.3.2";
    hash = "21787087cf377468396b8a39abcc64738c80c19c665da5dc4d02ce88616e06b0";
    deps = with allCrates; [ lazy_static itertools log serde_json clap rustc-serialize strfmt time fern regex serde ansi_term toml ];
  };
  rst_app_0_3_3 = buildCratesLib {
    name = "rst_app";
    version = "0.3.3";
    hash = "583130e5944b6fbba90e8b048c0aa686a09942eace76362dd3e616a0018d4ca7";
    deps = with allCrates; [ toml rustc-serialize log regex fern lazy_static clap itertools serde_json time strfmt serde ansi_term ];
  };
  rst_app_0_3_4 = buildCratesLib {
    name = "rst_app";
    version = "0.3.4";
    hash = "126fc9b1afcaa5e8c9373e83af8fd0a8acf9bad02da4203dc88344398e0756b1";
    deps = with allCrates; [ time fern clap log serde_json ansi_term itertools rustc-serialize serde strfmt regex toml lazy_static ];
  };
  rst_app_0_3_5 = buildCratesLib {
    name = "rst_app";
    version = "0.3.5";
    hash = "ed620954bb61b7bf713551575d7bbb344c736df188bd7e209180faa58fed1beb";
    deps = with allCrates; [ toml time fern lazy_static regex strfmt itertools clap ansi_term rustc-serialize serde log serde_json ];
  };
  rst_app_0_3_6 = buildCratesLib {
    name = "rst_app";
    version = "0.3.6";
    hash = "d2cd2afa666416d5f7d690e52021e631f47f977024f8ea627c8e7f92ab0b7a94";
    deps = with allCrates; [ ansi_term regex time toml rustc-serialize lazy_static serde_json serde itertools log strfmt fern clap ];
  };
  rst_app_0_3_7 = buildCratesLib {
    name = "rst_app";
    version = "0.3.7";
    hash = "d0e5f3b72523ed3384a9a7eee02ef7d8faca3dee5c7c1fa17e6d44e6821a7765";
    deps = with allCrates; [ clap itertools log strfmt lazy_static serde toml regex fern rustc-serialize ansi_term time serde_json ];
  };}