#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  anduin_0_0_1 = buildCratesLib {
    name = "anduin";
    version = "0.0.1";
    hash = "0452a44407133127fa452316edd3921fda3fc4825780aaa6e9b22e325a5b3d7b";
    deps = with allCrates; [  ];
  };
  anduin_0_0_2 = buildCratesLib {
    name = "anduin";
    version = "0.0.2";
    hash = "7e5ac96e41689d7734d0226fe587c618b7a9440dcf32945f740bb67968a8a595";
    deps = with allCrates; [  all__time.time_0_1 all__winit.winit_0_5 all__vulkano-win.vulkano-win_0_2 all__vulkano.vulkano_0_2 all__gl.gl_0_6 all__libc.libc_0_2 all__ears.ears_0_3 all__vk-sys.vk-sys_0_1 all__vulkano-shaders.vulkano-shaders_0_2 ];
  };
  anduin_0_0_3 = buildCratesLib {
    name = "anduin";
    version = "0.0.3";
    hash = "3c2a0a44fb5ff4d7bc0062213d8e1e6bbe7944356dd8aa6763580af310dda743";
    deps = with allCrates; [  all__vulkano.vulkano_0_2 all__gl.gl_0_6 all__winit.winit_0_5 all__time.time_0_1 all__vulkano-win.vulkano-win_0_2 all__ears.ears_0_3 all__libc.libc_0_2 all__vulkano-shaders.vulkano-shaders_0_2 all__vk-sys.vk-sys_0_1 ];
  };
  anduin_0_0_4 = buildCratesLib {
    name = "anduin";
    version = "0.0.4";
    hash = "596420e5257578bb6db3068b47044948b60e648ed021a6e0ab3fc384c22c4178";
    deps = with allCrates; [  all__vulkano.vulkano_0_2 all__libc.libc_0_2 all__gl.gl_0_6 all__vulkano-win.vulkano-win_0_2 all__winit.winit_0_5 all__time.time_0_1 all__nalgebra.nalgebra_0_10 all__ears.ears_0_3 all__vk-sys.vk-sys_0_1 all__vulkano-shaders.vulkano-shaders_0_2 ];
  };
  "anduin_0_0" = anduin_0_0_4;
  "anduin_0" = anduin_0_0_4;}