#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  http2parse_0_0_1 = buildCratesLib {
    name = "http2parse";
    version = "0.0.1";
    hash = "7e667091eb8d47562922b78aa351debbd51c32fb60209373beceba33c0735108";
    deps = with allCrates; [  all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_0_2 = buildCratesLib {
    name = "http2parse";
    version = "0.0.2";
    hash = "f7175dc466b9d9a717a9f53dcbcce7f35dc66cd7da0e061a7348645136ea604c";
    deps = with allCrates; [  all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_0_3 = buildCratesLib {
    name = "http2parse";
    version = "0.0.3";
    hash = "1c67728971d9342eb58688fe96f7e3e63914274eb3a5f57ffc3d51eba707ee76";
    deps = with allCrates; [  all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_1_0 = buildCratesLib {
    name = "http2parse";
    version = "0.1.0";
    hash = "13225cf1bbdff61640e1dd4be2f502f751338ce47b76342ef57faaf79fe5bbe4";
    deps = with allCrates; [  all__bitflags.bitflags_0_1 all__byteorder.byteorder_0_3 ];
  };
  "http2parse_0_0" = http2parse_0_0_3;
  http2parse_0_1_2 = buildCratesLib {
    name = "http2parse";
    version = "0.1.2";
    hash = "7c3de0aea171c64dd7b7e599bbdfb8f110a74edb29d9e7f54d7fb3e35bd44bd5";
    deps = with allCrates; [  all__byteorder.byteorder_0_3 all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_1_3 = buildCratesLib {
    name = "http2parse";
    version = "0.1.3";
    hash = "446581764b0e04642f37c88059845b57c1bc5b998a4ac54a5cfdd937be4a2d57";
    deps = with allCrates; [  all__byteorder.byteorder_0_3 all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_1_4 = buildCratesLib {
    name = "http2parse";
    version = "0.1.4";
    hash = "7fcaa629e1912dfccd7c3ad10c72c3e6a7f3a57bfa61abd5c9e9ff8a30b3b601";
    deps = with allCrates; [  all__byteorder.byteorder_0_3 all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_2_0 = buildCratesLib {
    name = "http2parse";
    version = "0.2.0";
    hash = "af09b1e1044e72bae9589c9b275e9bfb7e4a4805c3d249205667bc23c739d7d2";
    deps = with allCrates; [  all__bitflags.bitflags_0_1 all__byteorder.byteorder_0_3 ];
  };
  "http2parse_0_1" = http2parse_0_1_4;
  http2parse_0_2_1 = buildCratesLib {
    name = "http2parse";
    version = "0.2.1";
    hash = "0ba66a2e424f51e7b468af0ebea5b0b754d1168992df25a8705226c7c575e1c8";
    deps = with allCrates; [  all__byteorder.byteorder_0_3 all__bitflags.bitflags_0_1 ];
  };
  http2parse_0_2_2 = buildCratesLib {
    name = "http2parse";
    version = "0.2.2";
    hash = "e6044ac0563561b513400cdccad1ec23bb872f5b1a2124915147e985cb51a23c";
    deps = with allCrates; [  all__byteorder.byteorder_0_3 all__bitflags.bitflags_0_1 ];
  };
  "http2parse_0_2" = http2parse_0_2_2;
  "http2parse_0" = http2parse_0_2_2;}