#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  mutiny_0_1_0 = buildCratesLib {
    name = "mutiny";
    version = "0.1.0";
    hash = "300420ebfc02cf014f77a217ff719d20d954a625c408e94766bcebe959a8fdcf";
    deps = with allCrates; [ psutil getopts term ];
  };
  mutiny_0_2_0 = buildCratesLib {
    name = "mutiny";
    version = "0.2.0";
    hash = "ecac7e73cdd03825a18e9243c9551afd67bff5002949c9a0f616a1bcd85433a4";
    deps = with allCrates; [ psutil log rustc-serialize docopt simple_logger docopt_macros ];
  };}