#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  wai_0_1_0 = buildCratesLib {
    name = "wai";
    version = "0.1.0";
    hash = "794b0376ef0f18bc3d4a4ccd7e92119434fdf53411c400c5b4da028334d3d1aa";
    deps = with allCrates; [ void futures tokio-core env_logger log mio libc ];
  };}