#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  wai_0_1_0 = buildCratesLib {
    name = "wai";
    version = "0.1.0";
    hash = "794b0376ef0f18bc3d4a4ccd7e92119434fdf53411c400c5b4da028334d3d1aa";
    deps = with allCrates; [  all__void.void_1_0_2 all__futures.futures_0_1 all__tokio-core.tokio-core_0_1 all__env_logger.env_logger_0_3 all__log.log_0_3 all__mio.mio_0_6 all__libc.libc_0_2 ];
  };
  "wai_0_1" = wai_0_1_0;
  "wai_0" = wai_0_1_0;}