#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  aws-sdk-rust_0_1_0 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.0";
    hash = "4e5c5cb4d94b0b4bf51f5ee82fd38f84c7d758b9134091065d9882c40d2898d0";
    deps = with allCrates; [  all__url.url_1_2 all__log.log_0_3 all__openssl.openssl_0_7 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__time.time_0_1 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__regex.regex_0_1 all__xml-rs.xml-rs_0_1 all__serde.serde_0_8 ];
  };
  aws-sdk-rust_0_1_1 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.1";
    hash = "2fbb148fbb14c7cbfe84830efdbb7762b85624edf3937fb72dc82de64812afdd";
    deps = with allCrates; [  all__serde.serde_0_8 all__hyper.hyper_0_9 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__xml-rs.xml-rs_0_1 all__serde_json.serde_json_0_8 all__url.url_1_2 all__time.time_0_1 all__openssl.openssl_0_7 all__log.log_0_3 ];
  };
  aws-sdk-rust_0_1_2 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.2";
    hash = "bdeba747b2ab339fab988d998af805d2d463e759a535f47ea5415af2141ab269";
    deps = with allCrates; [  all__log.log_0_3 all__regex.regex_0_1 all__xml-rs.xml-rs_0_1 all__serde.serde_0_8 all__rustc-serialize.rustc-serialize_0_3 all__time.time_0_1 all__serde_json.serde_json_0_8 all__chrono.chrono_0_2 all__hyper.hyper_0_9 all__openssl.openssl_0_7 all__url.url_1_2 ];
  };
  aws-sdk-rust_0_1_3 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.3";
    hash = "17e1253a1ea8b610c27abefb969f43f8d58c4fcfc2eb2bf73f7af222b37732fc";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__chrono.chrono_0_2 all__url.url_1_2 all__regex.regex_0_1 all__xml-rs.xml-rs_0_1 all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 all__openssl.openssl_0_7 all__log.log_0_3 all__time.time_0_1 ];
  };
  aws-sdk-rust_0_1_4 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.4";
    hash = "494c627f6932f0c16cc5d358cec75aabf542ed0279c8836e36664d45f88d7bef";
    deps = with allCrates; [  all__log.log_0_3 all__httparse.httparse_1_1 all__time.time_0_1 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__openssl.openssl_0_7 all__chrono.chrono_0_2 all__regex.regex_0_1 all__url.url_1_2 all__xml-rs.xml-rs_0_1 all__rustc-serialize.rustc-serialize_0_3 all__serde.serde_0_8 ];
  };
  aws-sdk-rust_0_1_5 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.5";
    hash = "9dabdb7c9d810d52fa6a6f0fa5d8487dfd3d9adb5a879a279cf901afce7ee8b8";
    deps = with allCrates; [  all__url.url_1_2 all__serde.serde_0_8 all__regex.regex_0_1 all__time.time_0_1 all__serde_json.serde_json_0_8 all__openssl.openssl_0_7 all__rustc-serialize.rustc-serialize_0_3 all__httparse.httparse_1_1 all__chrono.chrono_0_2 all__log.log_0_3 all__xml-rs.xml-rs_0_1 all__hyper.hyper_0_9 ];
  };
  aws-sdk-rust_0_1_6 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.6";
    hash = "a86a793bf97ed7c6f69fc7de64be9c5867563bb7ce5f2581e717d6cd1fcd7a04";
    deps = with allCrates; [  all__httparse.httparse_1_1 all__xml-rs.xml-rs_0_1 all__log.log_0_3 all__chrono.chrono_0_2 all__time.time_0_1 all__serde_json.serde_json_0_8 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 all__serde.serde_0_8 all__openssl.openssl_0_7 all__hyper.hyper_0_9 all__url.url_1_2 ];
  };
  aws-sdk-rust_0_1_7 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.7";
    hash = "9ff1b79f87029d1945f2b01cca7b1c4340b5f90ce03cac20ca7411f80c491d5b";
    deps = with allCrates; [  all__log.log_0_3 all__xml-rs.xml-rs_0_1 all__regex.regex_0_1 all__time.time_0_1 all__url.url_1_2 all__openssl.openssl_0_7 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__httparse.httparse_1_1 ];
  };
  aws-sdk-rust_0_1_8 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.8";
    hash = "ea61011110fc97e070fbb66b81e5bdfdbb39e2ebdffd775982b66e798a4183ac";
    deps = with allCrates; [  all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__openssl.openssl_0_7 all__serde.serde_0_8 all__url.url_1_2 all__xml-rs.xml-rs_0_1 all__httparse.httparse_1_1 all__time.time_0_1 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__log.log_0_3 all__chrono.chrono_0_2 ];
  };
  aws-sdk-rust_0_1_9 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.9";
    hash = "2aac1c0da903fb7c5d1d136e09590adb812b5d151c9145c3748dd3502d0a8265";
    deps = with allCrates; [  all__time.time_0_1 all__openssl.openssl_0_7 all__rustc-serialize.rustc-serialize_0_3 all__httparse.httparse_1_1 all__log.log_0_3 all__url.url_1_2 all__serde.serde_0_8 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__regex.regex_0_1 all__chrono.chrono_0_2 all__xml-rs.xml-rs_0_1 ];
  };
  aws-sdk-rust_0_1_10 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.10";
    hash = "47e2c94895e9982826f0363660bde2f952400df21b810762585360df14d3b792";
    deps = with allCrates; [  all__serde.serde_0_8 all__xml-rs.xml-rs_0_1 all__log.log_0_3 all__rustc-serialize.rustc-serialize_0_3 all__httparse.httparse_1_1 all__chrono.chrono_0_2 all__openssl.openssl_0_7 all__serde_json.serde_json_0_8 all__url.url_1_2 all__regex.regex_0_1 all__time.time_0_1 all__hyper.hyper_0_9 ];
  };
  aws-sdk-rust_0_1_11 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.11";
    hash = "fe2989d5373679fe0eb8af9a23009194ff959084b79a045d11b0d3809c425e0b";
    deps = with allCrates; [  all__xml-rs.xml-rs_0_1 all__rustc-serialize.rustc-serialize_0_3 all__serde_json.serde_json_0_8 all__chrono.chrono_0_2 all__log.log_0_3 all__httparse.httparse_1_1 all__url.url_1_2 all__openssl.openssl_0_7 all__serde.serde_0_8 all__hyper.hyper_0_9 all__regex.regex_0_1 all__time.time_0_1 ];
  };
  aws-sdk-rust_0_1_12 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.12";
    hash = "ce780dbb68f18a753e906cee8603168f9e808a3ddaf3f04a5b289d0646a021f6";
    deps = with allCrates; [  all__serde.serde_0_8 all__log.log_0_3 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__xml-rs.xml-rs_0_1 all__url.url_1_2 all__httparse.httparse_1_1 all__rustc-serialize.rustc-serialize_0_3 all__openssl.openssl_0_7 all__regex.regex_0_1 all__time.time_0_1 all__chrono.chrono_0_2 ];
  };
  aws-sdk-rust_0_1_13 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.13";
    hash = "eba94f8141fbaa9222d967bfe3d72bfadc9147f1d24d2a0533a5826ff2c80d9b";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__hyper.hyper_0_9 all__time.time_0_1 all__httparse.httparse_1_1 all__xml-rs.xml-rs_0_1 all__log.log_0_3 all__regex.regex_0_1 all__url.url_1_2 all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__chrono.chrono_0_2 all__openssl.openssl_0_7 ];
  };
  aws-sdk-rust_0_1_14 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.14";
    hash = "1b30c5960c125b33ca4e40fa091074e99301b21772259196c59695ca8184626e";
    deps = with allCrates; [  all__time.time_0_1 all__log.log_0_3 all__hyper.hyper_0_9 all__url.url_1_2 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__xml-rs.xml-rs_0_1 all__lsio.lsio_0_1 all__term.term_0_4 all__openssl.openssl_0_7 all__serde_json.serde_json_0_8 all__chrono.chrono_0_2 all__serde.serde_0_8 all__httparse.httparse_1_1 ];
  };
  aws-sdk-rust_0_1_15 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.15";
    hash = "9df5ab35ec048a8485e0161b101ccdfba30b780e8ebc4ed33e73da8a1d24c04d";
    deps = with allCrates; [  all__term.term_0_4 all__openssl.openssl_0_7 all__hyper.hyper_0_9 all__url.url_1_2 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__lsio.lsio_0_1 all__regex.regex_0_1 all__serde.serde_0_8 all__time.time_0_1 all__log.log_0_3 all__md5.md5_0_2 all__httparse.httparse_1_1 all__serde_json.serde_json_0_8 all__xml-rs.xml-rs_0_1 ];
  };
  aws-sdk-rust_0_1_17 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.17";
    hash = "0a7ba9bcf8b94b2a3743a420d6fe34638b649140090bb4d6afbde6f1600ea4d5";
    deps = with allCrates; [  all__openssl.openssl_0_7 all__url.url_1_2 all__xml-rs.xml-rs_0_1 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__httparse.httparse_1_1 all__log.log_0_3 all__serde_json.serde_json_0_8 all__term.term_0_4 all__time.time_0_1 all__chrono.chrono_0_2 all__md5.md5_0_2 all__lsio.lsio_0_1 all__serde.serde_0_8 all__hyper.hyper_0_9 ];
  };
  aws-sdk-rust_0_1_18 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.18";
    hash = "5054699f55a4d89a5bcdbf6f6316a58cf9d784f1d03c10744e7c45d9f18c7d22";
    deps = with allCrates; [  all__lsio.lsio_0_1 all__httparse.httparse_1_1 all__url.url_1_2 all__chrono.chrono_0_2 all__serde.serde_0_8 all__time.time_0_1 all__xml-rs.xml-rs_0_1 all__log.log_0_3 all__term.term_0_4 all__openssl.openssl_0_7 all__hyper.hyper_0_9 all__md5.md5_0_2 all__serde_json.serde_json_0_8 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 ];
  };
  aws-sdk-rust_0_1_19 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.19";
    hash = "4baacfed0fe0867484c9cb265898dbcd3ed41dac39c985641b1fa67a39ed3d1c";
    deps = with allCrates; [  all__httparse.httparse_1_1 all__log.log_0_3 all__md5.md5_0_2 all__chrono.chrono_0_2 all__hyper.hyper_0_9 all__regex.regex_0_1 all__lsio.lsio_0_1 all__time.time_0_1 all__xml-rs.xml-rs_0_1 all__openssl.openssl_0_7 all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__serde_json.serde_json_0_8 all__url.url_1_2 all__serde.serde_0_8 ];
  };
  aws-sdk-rust_0_1_20 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.20";
    hash = "885804da36cc9bc1b52ec9204ba7feef7f6c30173e3f634b2e1d5a32b9d7b777";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__chrono.chrono_0_2 all__log.log_0_3 all__url.url_1_2 all__openssl.openssl_0_7 all__term.term_0_4 all__md5.md5_0_2 all__lsio.lsio_0_1 all__time.time_0_1 all__regex.regex_0_1 all__serde.serde_0_8 all__xml-rs.xml-rs_0_1 all__httparse.httparse_1_1 all__serde_json.serde_json_0_8 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  aws-sdk-rust_0_1_21 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.21";
    hash = "9d593709bd180d07b1cef963d807890541e221294eb231055dbedd93652b83a6";
    deps = with allCrates; [  all__log.log_0_3 all__xml-rs.xml-rs_0_1 all__regex.regex_0_1 all__lsio.lsio_0_1 all__url.url_1_2 all__rustc-serialize.rustc-serialize_0_3 all__serde.serde_0_8 all__hyper.hyper_0_9 all__time.time_0_1 all__md5.md5_0_2 all__openssl.openssl_0_7 all__chrono.chrono_0_2 all__serde_json.serde_json_0_8 all__httparse.httparse_1_1 all__term.term_0_4 ];
  };
  aws-sdk-rust_0_1_22 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.22";
    hash = "447ce7fb6800cf1e25d027b4a393720c3c6fa8491b0f8709c348dd50a8f4dd49";
    deps = with allCrates; [  all__md5.md5_0_2 all__term.term_0_4 all__chrono.chrono_0_2 all__openssl.openssl_0_7 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__httparse.httparse_1_1 all__serde.serde_0_8 all__lsio.lsio_0_1 all__log.log_0_3 all__time.time_0_1 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 all__url.url_1_2 all__xml-rs.xml-rs_0_1 ];
  };
  aws-sdk-rust_0_1_23 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.23";
    hash = "4a24db6a9a066e6703c3ceeff668e547fc0c4f64b6f064e1e0c005590d704481";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__term.term_0_4 all__log.log_0_3 all__xml-rs.xml-rs_0_1 all__lsio.lsio_0_1 all__serde_json.serde_json_0_8 all__time.time_0_1 all__httparse.httparse_1_1 all__openssl.openssl_0_7 all__md5.md5_0_2 all__serde.serde_0_8 all__hyper.hyper_0_9 all__url.url_1_2 all__rustc-serialize.rustc-serialize_0_3 all__regex.regex_0_1 ];
  };
  aws-sdk-rust_0_1_24 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.24";
    hash = "2c25bfde95fc109325cfe9289627a8ddb89a262548bbdd3c7fe8a32bb7454d0c";
    deps = with allCrates; [  all__serde.serde_0_8 all__md5.md5_0_2 all__openssl.openssl_0_7 all__httparse.httparse_1_1 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__chrono.chrono_0_2 all__serde_json.serde_json_0_8 all__hyper.hyper_0_9 all__lsio.lsio_0_1 all__term.term_0_4 all__url.url_1_2 all__xml-rs.xml-rs_0_1 all__regex.regex_0_1 all__time.time_0_1 ];
  };
  aws-sdk-rust_0_1_25 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.25";
    hash = "b9c29d72558dfb7a1ecab932cf0e43d20ad99e7970d4e8ea7242d70b6a7b2423";
    deps = with allCrates; [  all__httparse.httparse_1 all__md5.md5_0_2 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__lsio.lsio_0_1 all__hyper.hyper_0_9 all__url.url_1_2 all__chrono.chrono_0_2 all__serde_json.serde_json_0_8 all__term.term_0_4 all__xml-rs.xml-rs_0_1 all__regex.regex_0_1 all__openssl.openssl_0_7 all__serde.serde_0_8 all__time.time_0_1 ];
  };
  aws-sdk-rust_0_1_26 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.26";
    hash = "95e266399efde815f631fb21dfd118c6723b1a721046c04f8aab7a3119b327aa";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__rustc-serialize.rustc-serialize_0_3 all__term.term_0_4 all__url.url_1_2 all__md5.md5_0_2 all__lsio.lsio_0_1 all__time.time_0_1 all__xml-rs.xml-rs_0_1 all__httparse.httparse_1 all__serde_json.serde_json_0_8 all__openssl.openssl_0_7 all__log.log_0_3 all__regex.regex_0_1 all__serde.serde_0_8 all__hyper.hyper_0_9 ];
  };
  aws-sdk-rust_0_1_27 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.27";
    hash = "8cab9df90861ff035bc783deb0091011922d099a1f0dfe106c6c0ff4b9849619";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__serde.serde_0_8 all__md5.md5_0_2 all__openssl.openssl_0_7 all__regex.regex_0_1 all__xml-rs.xml-rs_0_1 all__httparse.httparse_1 all__rustc-serialize.rustc-serialize_0_3 all__serde_json.serde_json_0_8 all__log.log_0_3 all__lsio.lsio_0_1 all__time.time_0_1 all__url.url_1_2 all__term.term_0_4 all__hyper.hyper_0_9 ];
  };
  aws-sdk-rust_0_1_28 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.28";
    hash = "e57d67de490478c195baafc786e2c399026e24628e07ea7bd9cddea897fbd66e";
    deps = with allCrates; [  all__serde.serde_0_8 all__hyper.hyper_0_9 all__url.url_1_2 all__chrono.chrono_0_2 all__regex.regex_0_1 all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__openssl.openssl_0_7 all__log.log_0_3 all__lsio.lsio_0_1 all__time.time_0_1 all__xml-rs.xml-rs_0_1 all__serde_json.serde_json_0_8 all__md5.md5_0_2 all__httparse.httparse_1 ];
  };
  aws-sdk-rust_0_1_29 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.29";
    hash = "8788a0ef30331708ac708ad031b7acacfc25bd3a70604cf5260ee7a4449c63ed";
    deps = with allCrates; [  all__chrono.chrono_0_2 all__xml-rs.xml-rs_0_1 all__regex.regex_0_1 all__time.time_0_1 all__openssl.openssl_0_7 all__url.url_1_2 all__rustc-serialize.rustc-serialize_0_3 all__term.term_0_4 all__serde.serde_0_8 all__lsio.lsio_0_1 all__hyper.hyper_0_9 all__log.log_0_3 all__md5.md5_0_2 all__serde_json.serde_json_0_8 all__httparse.httparse_1 ];
  };
  aws-sdk-rust_0_1_30 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.30";
    hash = "d8a05353061efe49c2ef052528b04ae5bc60c6b6c77f9df7c5f14026381ee2f1";
    deps = with allCrates; [  all__xml-rs.xml-rs_0_1 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__time.time_0_1 all__chrono.chrono_0_2 all__url.url_1_2 all__rustc-serialize.rustc-serialize_0_3 all__md5.md5_0_2 all__openssl.openssl_0_7 all__log.log_0_3 all__serde.serde_0_8 all__lsio.lsio_0_1 all__httparse.httparse_1 all__term.term_0_4 all__regex.regex_0_1 ];
  };
  aws-sdk-rust_0_1_31 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.31";
    hash = "c900bdb323739cb016656cf67e43ace1af09a26637ac04288c79e16e6f6450d6";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__lsio.lsio_0_1 all__md5.md5_0_2 all__term.term_0_4 all__regex.regex_0_1 all__serde.serde_0_8 all__time.time_0_1 all__log.log_0_3 all__serde_json.serde_json_0_8 all__url.url_1_2 all__httparse.httparse_1 all__openssl.openssl_0_7 all__xml-rs.xml-rs_0_1 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 ];
  };
  aws-sdk-rust_0_1_32 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.32";
    hash = "ad94fbaee9eb5fca9667744dea0465b354f7e6dcb584dfbabff850b5d993f1d1";
    deps = with allCrates; [  all__openssl.openssl_0_7 all__serde.serde_0_8 all__log.log_0_3 all__hyper.hyper_0_9 all__time.time_0_1 all__chrono.chrono_0_2 all__serde_json.serde_json_0_8 all__lsio.lsio_0_1 all__regex.regex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__url.url_1_2 all__term.term_0_4 all__xml-rs.xml-rs_0_1 all__httparse.httparse_1 all__md5.md5_0_2 ];
  };
  aws-sdk-rust_0_1_33 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.33";
    hash = "c21d25954c31482df5cdbdb7ffa77ebe6879dc0b7f93d3a3d74506b2e578f00f";
    deps = with allCrates; [  all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__lsio.lsio_0_1 all__serde.serde_0_8 all__log.log_0_3 all__serde_json.serde_json_0_8 all__time.time_0_1 all__url.url_1_2 all__hyper.hyper_0_9 all__chrono.chrono_0_2 all__openssl.openssl_0_7 all__httparse.httparse_1 all__regex.regex_0_1 all__md5.md5_0_2 all__xml-rs.xml-rs_0_1 ];
  };
  aws-sdk-rust_0_1_34 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.34";
    hash = "1ac6a6ff5207bc9e97570698d63f40ee30050c78b36d9f5a90ac52d3721e6994";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__serde.serde_0_8 all__url.url_1_2 all__xml-rs.xml-rs_0_1 all__httparse.httparse_1 all__lsio.lsio_0_1 all__time.time_0_1 all__chrono.chrono_0_2 all__openssl.openssl_0_7 all__term.term_0_4 all__rustc-serialize.rustc-serialize_0_3 all__md5.md5_0_2 all__serde_json.serde_json_0_8 all__log.log_0_3 all__regex.regex_0_1 ];
  };
  aws-sdk-rust_0_1_35 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.35";
    hash = "5abb6e9492e5071d682f82f98957fb14c1c7a5d9f7da33f153a138c0a7279ef4";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__term.term_0_4 all__log.log_0_3 all__url.url_1_2 all__md5.md5_0_2 all__serde.serde_0_8 all__time.time_0_1 all__xml-rs.xml-rs_0_1 all__rustc-serialize.rustc-serialize_0_3 all__chrono.chrono_0_2 all__httparse.httparse_1 all__hyper.hyper_0_9 all__lsio.lsio_0_1 all__openssl.openssl_0_7 all__regex.regex_0_1 ];
  };
  aws-sdk-rust_0_1_36 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.36";
    hash = "bba0e05415074db4f8a0b8af45fa1339be742d744769f488decd5c6660fa9697";
    deps = with allCrates; [  all__log.log_0_3 all__openssl.openssl_0_7 all__time.time_0_1 all__regex.regex_0_1 all__serde_json.serde_json_0_8 all__url.url_1_2 all__xml-rs.xml-rs_0_1 all__chrono.chrono_0_2 all__hyper.hyper_0_9 all__serde.serde_0_8 all__md5.md5_0_2 all__rustc-serialize.rustc-serialize_0_3 all__lsio.lsio_0_1 all__term.term_0_4 all__httparse.httparse_1 ];
  };
  aws-sdk-rust_0_1_37 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.37";
    hash = "aa09a7d61dde00452fd62b4cdad6f77b20074be242b6fe33a9e552454e5c83a2";
    deps = with allCrates; [  all__md5.md5_0_2 all__hyper.hyper_0_9 all__log.log_0_3 all__term.term_0_4 all__lsio.lsio_0_1 all__chrono.chrono_0_2 all__rustc-serialize.rustc-serialize_0_3 all__xml-rs.xml-rs_0_1 all__serde_json.serde_json_0_8 all__openssl.openssl_0_7 all__serde.serde_0_8 all__url.url_1_2 all__regex.regex_0_1 all__time.time_0_1 all__httparse.httparse_1 ];
  };
  aws-sdk-rust_0_1_38 = buildCratesLib {
    name = "aws-sdk-rust";
    version = "0.1.38";
    hash = "33f27f0bce442322771e3698d542266e231fb9a738b42ae045e8dbd0b7c7eab2";
    deps = with allCrates; [  all__httparse.httparse_1 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 all__xml-rs.xml-rs_0_1 all__lsio.lsio_0_1 all__chrono.chrono_0_2 all__openssl.openssl_0_7 all__term.term_0_4 all__url.url_1_2 all__time.time_0_1 all__log.log_0_3 all__regex.regex_0_1 all__md5.md5_0_2 all__rustc-serialize.rustc-serialize_0_3 all__serde.serde_0_8 ];
  };
  "aws-sdk-rust_0_1" = aws-sdk-rust_0_1_38;
  "aws-sdk-rust_0" = aws-sdk-rust_0_1_38;}