#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rabble_0_1_0 = buildCratesLib {
    name = "rabble";
    version = "0.1.0";
    hash = "e175062dcf8036df10269e927918121a6f58b4c4e8ccf51d9ce9d5f603ea0f56";
    deps = with allCrates; [  all__slog-term.slog-term_1_1 all__log.log_0_3 all__rmp-serialize.rmp-serialize_0_7 all__rustc-serialize.rustc-serialize_0_3 all__ferris.ferris_0_1 all__orset.orset_0_1 all__libc.libc_0_2 all__slog-stdlog.slog-stdlog_1 all__error-chain.error-chain_0_5 all__net2.net2_0_2 all__slog.slog_1 all__amy.amy_0_6 all__time.time_0_1 all__slog-envlogger.slog-envlogger_0_5 ];
  };
  "rabble_0_1" = rabble_0_1_0;
  "rabble_0" = rabble_0_1_0;}