#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  pyltime_0_0_1 = buildCratesLib {
    name = "pyltime";
    version = "0.0.1";
    hash = "2cdd2d9d06a3faa9e91f4caa6581cc78bfa8ff083bf4605275099150ec98117f";
    deps = with allCrates; [  ];
  };
  "pyltime_0_0" = pyltime_0_0_1;
  "pyltime_0" = pyltime_0_0_1;}