#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  cage_0_0_16 = buildCratesLib {
    name = "cage";
    version = "0.0.16";
    hash = "6c437169a2f61f0835439ef52c1c9a4deeb353e12be30e300b957425c71251d1";
    deps = with allCrates; [  all__compose_yml.compose_yml_0_0_42 all__error-chain.error-chain_0_5 all__log.log_0_3 all__retry.retry_0_4 all__serde.serde_0_8 all__rustc-serialize.rustc-serialize_0_3 all__serde_yaml.serde_yaml_0_4 all__hashicorp_vault.hashicorp_vault_0_6 all__env_logger.env_logger_0_3 all__rand.rand_0_3 all__glob.glob_0_2 all__includedir.includedir_0_2 all__handlebars.handlebars_0_21 all__shlex.shlex_0_1 all__url.url_1_2 all__docopt.docopt_0_6 all__phf.phf_0_7 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_0_17 = buildCratesLib {
    name = "cage";
    version = "0.0.17";
    hash = "52639189bd13d03e2475dd1c6844f63418d0ad3d4f61a64bfe77b48585f2cfb1";
    deps = with allCrates; [  all__compose_yml.compose_yml_0_0_42 all__error-chain.error-chain_0_5 all__url.url_1_2 all__hashicorp_vault.hashicorp_vault_0_6 all__shlex.shlex_0_1 all__retry.retry_0_4 all__serde_yaml.serde_yaml_0_4 all__env_logger.env_logger_0_3 all__handlebars.handlebars_0_21 all__rand.rand_0_3 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__serde.serde_0_8 all__docopt.docopt_0_6 all__glob.glob_0_2 all__phf.phf_0_7 all__includedir.includedir_0_2 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_0_18 = buildCratesLib {
    name = "cage";
    version = "0.0.18";
    hash = "ee64442e20f3947efe90ea78366493b09a85766e79c9b03c02afe86d4220c9b1";
    deps = with allCrates; [  all__retry.retry_0_4 all__rustc-serialize.rustc-serialize_0_3 all__serde_yaml.serde_yaml_0_4 all__phf.phf_0_7 all__url.url_1_2 all__docopt.docopt_0_6 all__log.log_0_3 all__includedir.includedir_0_2 all__env_logger.env_logger_0_3 all__glob.glob_0_2 all__hashicorp_vault.hashicorp_vault_0_6 all__error-chain.error-chain_0_5 all__serde.serde_0_8 all__compose_yml.compose_yml_0_0_42 all__rand.rand_0_3 all__handlebars.handlebars_0_21 all__shlex.shlex_0_1 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_0_19 = buildCratesLib {
    name = "cage";
    version = "0.0.19";
    hash = "cf2b66b8d4aabb014f0284fb07459baf780d34e9007bf8d8b03d0468205da9cc";
    deps = with allCrates; [  all__compose_yml.compose_yml_0_0_42 all__env_logger.env_logger_0_3 all__hashicorp_vault.hashicorp_vault_0_6 all__log.log_0_3 all__retry.retry_0_4 all__handlebars.handlebars_0_21 all__rustc-serialize.rustc-serialize_0_3 all__includedir.includedir_0_2 all__shlex.shlex_0_1 all__docopt.docopt_0_6 all__phf.phf_0_7 all__serde.serde_0_8 all__glob.glob_0_2 all__serde_yaml.serde_yaml_0_4 all__rand.rand_0_3 all__url.url_1_2 all__error-chain.error-chain_0_5 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_0_20 = buildCratesLib {
    name = "cage";
    version = "0.0.20";
    hash = "73cfc71f5521a8abcfef58bfdba60e28cab2d6aa7dea3b7ada4e13e5b3006d5f";
    deps = with allCrates; [  all__url.url_1_2 all__error-chain.error-chain_0_5 all__phf.phf_0_7 all__log.log_0_3 all__hashicorp_vault.hashicorp_vault_0_6 all__serde_yaml.serde_yaml_0_4 all__serde.serde_0_8 all__includedir.includedir_0_2 all__handlebars.handlebars_0_21 all__rand.rand_0_3 all__shlex.shlex_0_1 all__rustc-serialize.rustc-serialize_0_3 all__retry.retry_0_4 all__env_logger.env_logger_0_3 all__compose_yml.compose_yml_0_0_42 all__docopt.docopt_0_6 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_0_21 = buildCratesLib {
    name = "cage";
    version = "0.0.21";
    hash = "7b11d3dd77afeb82d6dc0716f195de6117ebb9b05b6b96080c8e3f215d0c316e";
    deps = with allCrates; [  all__url.url_1_2 all__clap.clap_2_14 all__phf.phf_0_7 all__lazy_static.lazy_static_0_2 all__includedir.includedir_0_2 all__semver.semver_0_5 all__serde_yaml.serde_yaml_0_4 all__yaml-rust.yaml-rust_0_3 all__rustc-serialize.rustc-serialize_0_3 all__hashicorp_vault.hashicorp_vault_0_6 all__rand.rand_0_3 all__retry.retry_0_4 all__compose_yml.compose_yml_0_0_43 all__glob.glob_0_2 all__handlebars.handlebars_0_21 all__shlex.shlex_0_1 all__log.log_0_3 all__env_logger.env_logger_0_3 all__error-chain.error-chain_0_5 all__serde.serde_0_8 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_0_22 = buildCratesLib {
    name = "cage";
    version = "0.0.22";
    hash = "9a2ee2b1ffc1ddefccd3c094e8f301ce098ee7bfcfb6a1ee5383211d75821f7d";
    deps = with allCrates; [  all__glob.glob_0_2 all__serde_yaml.serde_yaml_0_4 all__serde.serde_0_8 all__includedir.includedir_0_2 all__semver.semver_0_5 all__hashicorp_vault.hashicorp_vault_0_6 all__phf.phf_0_7 all__handlebars.handlebars_0_21 all__clap.clap_2_14 all__rand.rand_0_3 all__url.url_1_2 all__log.log_0_3 all__shlex.shlex_0_1 all__compose_yml.compose_yml_0_0_44 all__retry.retry_0_4 all__yaml-rust.yaml-rust_0_3 all__env_logger.env_logger_0_3 all__lazy_static.lazy_static_0_2 all__rustc-serialize.rustc-serialize_0_3 all__error-chain.error-chain_0_5 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_0 = buildCratesLib {
    name = "cage";
    version = "0.1.0";
    hash = "f7518ca880d43bd991aa93822f719bb502748609a9f76dea935bd2dbf037400e";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_2 all__serde.serde_0_8 all__handlebars.handlebars_0_21 all__serde_yaml.serde_yaml_0_4 all__error-chain.error-chain_0_5 all__semver.semver_0_5 all__yaml-rust.yaml-rust_0_3 all__colored.colored_1_3 all__glob.glob_0_2 all__clap.clap_2_14 all__env_logger.env_logger_0_3 all__phf.phf_0_7 all__hashicorp_vault.hashicorp_vault_0_6 all__compose_yml.compose_yml_0_0_44 all__retry.retry_0_4 all__rustc-serialize.rustc-serialize_0_3 all__includedir.includedir_0_2 all__url.url_1_2 all__log.log_0_3 all__rand.rand_0_3 all__shlex.shlex_0_1 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  "cage_0_0" = cage_0_0_22;
  cage_0_1_1 = buildCratesLib {
    name = "cage";
    version = "0.1.1";
    hash = "aa0bb8f2446f9723bd755a18d222cb25ab8fc4ef6f4b9061a431cc36dcf423a9";
    deps = with allCrates; [  all__phf.phf_0_7 all__compose_yml.compose_yml_0_0_44 all__handlebars.handlebars_0_21 all__hashicorp_vault.hashicorp_vault_0_6 all__env_logger.env_logger_0_3 all__includedir.includedir_0_2 all__shlex.shlex_0_1 all__retry.retry_0_4 all__log.log_0_3 all__colored.colored_1_3 all__rustc-serialize.rustc-serialize_0_3 all__serde_yaml.serde_yaml_0_4 all__glob.glob_0_2 all__error-chain.error-chain_0_5 all__lazy_static.lazy_static_0_2 all__rand.rand_0_3 all__serde.serde_0_8 all__semver.semver_0_5 all__clap.clap_2_14 all__url.url_1_2 all__yaml-rust.yaml-rust_0_3 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_1_2 = buildCratesLib {
    name = "cage";
    version = "0.1.2";
    hash = "611a09668fd6c1ca22abe32a24da74534d5890d7ec876dd68ab35e7d77252025";
    deps = with allCrates; [  all__glob.glob_0_2 all__includedir.includedir_0_2 all__serde_yaml.serde_yaml_0_4 all__hashicorp_vault.hashicorp_vault_0_6 all__retry.retry_0_4 all__url.url_1_2 all__clap.clap_2_14 all__error-chain.error-chain_0_5 all__env_logger.env_logger_0_3 all__compose_yml.compose_yml_0_0_44 all__yaml-rust.yaml-rust_0_3 all__rand.rand_0_3 all__lazy_static.lazy_static_0_2 all__handlebars.handlebars_0_21 all__shlex.shlex_0_1 all__phf.phf_0_7 all__semver.semver_0_5 all__log.log_0_3 all__colored.colored_1_3 all__rustc-serialize.rustc-serialize_0_3 all__serde.serde_0_8 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_3 = buildCratesLib {
    name = "cage";
    version = "0.1.3";
    hash = "ace0d168bd55197b95427972de7c8f97140ea68cb929ac10313bc3fdf6bfd341";
    deps = with allCrates; [  all__compose_yml.compose_yml_0_0_45 all__rayon.rayon_0_4 all__glob.glob_0_2 all__handlebars.handlebars_0_21 all__env_logger.env_logger_0_3 all__url.url_1_2 all__log.log_0_3 all__semver.semver_0_5 all__serde.serde_0_8 all__clap.clap_2_14 all__rustc-serialize.rustc-serialize_0_3 all__rand.rand_0_3 all__retry.retry_0_4 all__includedir.includedir_0_2 all__phf.phf_0_7 all__serde_yaml.serde_yaml_0_4 all__yaml-rust.yaml-rust_0_3 all__shlex.shlex_0_1 all__hashicorp_vault.hashicorp_vault_0_6 all__colored.colored_1_3 all__error-chain.error-chain_0_5 all__lazy_static.lazy_static_0_2 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_4 = buildCratesLib {
    name = "cage";
    version = "0.1.4";
    hash = "e5315e5c4eaa3566e1aa42c36f720a51d888219e6000f78307d1ac2b672173af";
    deps = with allCrates; [  all__compose_yml.compose_yml_0_0_45 all__includedir.includedir_0_2 all__retry.retry_0_4 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__rayon.rayon_0_4 all__clap.clap_2_14 all__env_logger.env_logger_0_3 all__handlebars.handlebars_0_21 all__url.url_1_2 all__error-chain.error-chain_0_5 all__colored.colored_1_3 all__glob.glob_0_2 all__semver.semver_0_5 all__serde.serde_0_8 all__yaml-rust.yaml-rust_0_3 all__shlex.shlex_0_1 all__serde_yaml.serde_yaml_0_4 all__phf.phf_0_7 all__rand.rand_0_3 all__log.log_0_3 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_5 = buildCratesLib {
    name = "cage";
    version = "0.1.5";
    hash = "98525ef333c500519255c9b3e202fd8b7e44663c84a47305d139b420cea36a63";
    deps = with allCrates; [  all__retry.retry_0_4 all__env_logger.env_logger_0_3 all__rustc-serialize.rustc-serialize_0_3 all__serde.serde_0_8 all__yaml-rust.yaml-rust_0_3 all__glob.glob_0_2 all__compose_yml.compose_yml_0_0_45 all__includedir.includedir_0_2 all__shlex.shlex_0_1 all__clap.clap_2_14 all__rayon.rayon_0_4 all__rand.rand_0_3 all__phf.phf_0_7 all__serde_yaml.serde_yaml_0_4 all__lazy_static.lazy_static_0_2 all__semver.semver_0_5 all__log.log_0_3 all__colored.colored_1_3 all__error-chain.error-chain_0_5 all__url.url_1_2 all__handlebars.handlebars_0_21 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_6 = buildCratesLib {
    name = "cage";
    version = "0.1.6";
    hash = "2306bd061a3ea0376c83d3c8503dc42f92a3189f575b895ac2a2d6150c5c378c";
    deps = with allCrates; [  all__phf.phf_0_7 all__lazy_static.lazy_static_0_2 all__rayon.rayon_0_4 all__error-chain.error-chain_0_5 all__url.url_1_2 all__yaml-rust.yaml-rust_0_3 all__env_logger.env_logger_0_3 all__log.log_0_3 all__rustc-serialize.rustc-serialize_0_3 all__semver.semver_0_5 all__rand.rand_0_3 all__glob.glob_0_2 all__serde.serde_0_8 all__retry.retry_0_4 all__includedir.includedir_0_2 all__compose_yml.compose_yml_0_0_45 all__colored.colored_1_3 all__handlebars.handlebars_0_21 all__serde_yaml.serde_yaml_0_4 all__clap.clap_2_14 all__shlex.shlex_0_1 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_1_7 = buildCratesLib {
    name = "cage";
    version = "0.1.7";
    hash = "dc20f640818e935aa6d18b7d38a1b85c57f8edd8ccd75247cb71036c41f319da";
    deps = with allCrates; [  all__handlebars.handlebars_0_21 all__yaml-rust.yaml-rust_0_3 all__error-chain.error-chain_0_5 all__log.log_0_3 all__includedir.includedir_0_2 all__boondock.boondock_0_0_46 all__semver.semver_0_5 all__url.url_1_2 all__retry.retry_0_4 all__rand.rand_0_3 all__compose_yml.compose_yml_0_0_45 all__lazy_static.lazy_static_0_2 all__regex.regex_0_1 all__shlex.shlex_0_1 all__env_logger.env_logger_0_3 all__glob.glob_0_2 all__phf.phf_0_7 all__rustc-serialize.rustc-serialize_0_3 all__serde.serde_0_8 all__serde_yaml.serde_yaml_0_4 all__colored.colored_1_3 all__rayon.rayon_0_4 all__clap.clap_2_14 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  cage_0_1_8 = buildCratesLib {
    name = "cage";
    version = "0.1.8";
    hash = "7ce9a75d7ba25c9a5f0d149aef3f2c2dda29f510b77987e8cf2095de9b62913b";
    deps = with allCrates; [  all__env_logger.env_logger_0_3 all__phf.phf_0_7 all__rayon.rayon_0_4 all__glob.glob_0_2 all__regex.regex_0_1 all__clap.clap_2_14 all__shlex.shlex_0_1 all__serde.serde_0_8 all__boondock.boondock_0_0_47 all__rustc-serialize.rustc-serialize_0_3 all__lazy_static.lazy_static_0_2 all__url.url_1_2 all__retry.retry_0_4 all__error-chain.error-chain_0_5 all__yaml-rust.yaml-rust_0_3 all__log.log_0_3 all__serde_yaml.serde_yaml_0_4 all__rand.rand_0_3 all__includedir.includedir_0_2 all__compose_yml.compose_yml_0_0_45 all__semver.semver_0_5 all__colored.colored_1_3 all__handlebars.handlebars_0_21 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_9 = buildCratesLib {
    name = "cage";
    version = "0.1.9";
    hash = "6444bcbd0ba7003e28c20094b966adb64619f4930461c4381c1388f47621eccc";
    deps = with allCrates; [  all__serde.serde_0_8 all__glob.glob_0_2 all__semver.semver_0_5 all__serde_yaml.serde_yaml_0_4 all__colored.colored_1_3 all__rayon.rayon_0_4 all__rustc-serialize.rustc-serialize_0_3 all__shlex.shlex_0_1 all__handlebars.handlebars_0_21 all__regex.regex_0_1 all__rand.rand_0_3 all__yaml-rust.yaml-rust_0_3 all__lazy_static.lazy_static_0_2 all__url.url_1_2 all__boondock.boondock_0_0_47 all__compose_yml.compose_yml_0_0_45 all__clap.clap_2_14 all__env_logger.env_logger_0_3 all__error-chain.error-chain_0_5 all__log.log_0_3 all__phf.phf_0_7 all__retry.retry_0_4 all__includedir.includedir_0_2 all__glob.glob_0_2 all__includedir_codegen.includedir_codegen_0_2 ];
  };
  cage_0_1_10 = buildCratesLib {
    name = "cage";
    version = "0.1.10";
    hash = "6e102dee2c93b72711091a6885a9f5d4db152467868eaf4b3929f5629e9fa3f5";
    deps = with allCrates; [  all__error-chain.error-chain_0_5 all__lazy_static.lazy_static_0_2 all__yaml-rust.yaml-rust_0_3 all__rustc-serialize.rustc-serialize_0_3 all__glob.glob_0_2 all__rand.rand_0_3 all__colored.colored_1_3 all__includedir.includedir_0_2 all__compose_yml.compose_yml_0_0_48 all__clap.clap_2_14 all__boondock.boondock_0_0_47 all__env_logger.env_logger_0_3 all__serde.serde_0_8 all__retry.retry_0_4 all__phf.phf_0_7 all__url.url_1_2 all__handlebars.handlebars_0_21 all__log.log_0_3 all__regex.regex_0_1 all__rayon.rayon_0_4 all__serde_yaml.serde_yaml_0_4 all__semver.semver_0_5 all__shlex.shlex_0_1 all__includedir_codegen.includedir_codegen_0_2 all__glob.glob_0_2 ];
  };
  "cage_0_1" = cage_0_1_10;
  "cage_0" = cage_0_1_10;}