#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  srclient-sys_0_0_1 = buildCratesLib {
    name = "srclient-sys";
    version = "0.0.1";
    hash = "fea684ecb7ba3ccf933ebb12c70a8c790a3945b8018128261b5fe8fcf6f530ad";
    deps = with allCrates; [ winapi ];
  };}