#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  hdfs_0_0_1 = buildCratesLib {
    name = "hdfs";
    version = "0.0.1";
    hash = "2aea3a11f13763ebc900d11954728acef601d858309a4625a06eebf7786056b9";
    deps = with allCrates; [  all__log.log_0_3 all__url.url_0_2 all__gcc.gcc_0_3 ];
  };
  hdfs_0_0_2 = buildCratesLib {
    name = "hdfs";
    version = "0.0.2";
    hash = "868122839e6c833415592e410cd467e7a83ba50e5e1fca44392af32cc333582d";
    deps = with allCrates; [  all__log.log_0_3 all__url.url_0_2 all__gcc.gcc_0_3 ];
  };
  hdfs_0_0_3 = buildCratesLib {
    name = "hdfs";
    version = "0.0.3";
    hash = "c53e8a4ddb98de1065c1714294d205e300a4e98b8ee15134f2a05d96a5c24e44";
    deps = with allCrates; [  all__itertools.itertools_0_4 all__log.log_0_3 all__url.url_0_2 all__libc.libc_0_1 all__gcc.gcc_0_3 ];
  };
  hdfs_0_0_4 = buildCratesLib {
    name = "hdfs";
    version = "0.0.4";
    hash = "46294f9d1c3dc20cf62027fe6b45766316891640dbeee32fcfd0a6cfe1a372e3";
    deps = with allCrates; [  all__itertools.itertools_0_4 all__url.url_0_2 all__log.log_0_3 all__libc.libc_0_1 all__gcc.gcc_0_3 ];
  };
  "hdfs_0_0" = hdfs_0_0_4;
  "hdfs_0" = hdfs_0_0_4;}