#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  bloomchain_0_1_0 = buildCratesLib {
    name = "bloomchain";
    version = "0.1.0";
    hash = "3f421095d2a76fc24cd3fb3f912b90df06be7689912b1bdb423caefae59c258d";
    deps = with allCrates; [  ];
  };
  "bloomchain_0_1" = bloomchain_0_1_0;
  "bloomchain_0" = bloomchain_0_1_0;}