#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  serial_0_0_1 = buildCratesLib {
    name = "serial";
    version = "0.0.1";
    hash = "5a6ac85a8cc5e4ca8128ae8cc51eaf673bf0b57d85b334eb2328b409fed92558";
    deps = with allCrates; [ termios ];
  };
  serial_0_0_2 = buildCratesLib {
    name = "serial";
    version = "0.0.2";
    hash = "b05a38570c6f2caa4ae239a2d0a721d569156075b76fa3e3063bde35af3c914d";
    deps = with allCrates; [ termios ];
  };
  serial_0_0_3 = buildCratesLib {
    name = "serial";
    version = "0.0.3";
    hash = "e76fcdcc62c139745410d3fb64f33d7f5f5449b0c7b211881f536406610c23b0";
    deps = with allCrates; [ termios ];
  };
  serial_0_0_4 = buildCratesLib {
    name = "serial";
    version = "0.0.4";
    hash = "c9c950220ff9b59c9fc535a1dab9c2dabb95be69ef07ad2eb02cf75355737dfc";
    deps = with allCrates; [ time libc termios ];
  };
  serial_0_0_5 = buildCratesLib {
    name = "serial";
    version = "0.0.5";
    hash = "1de9ed6c53645d990d5c340fa3e7b93d64c01e5956be4a3637d9b46d49c4fcdd";
    deps = with allCrates; [ time libc termios termios termios termios termios termios termios termios termios termios termios termios termios ];
  };
  serial_0_1_0 = buildCratesLib {
    name = "serial";
    version = "0.1.0";
    hash = "dff7d34cb88e2457cdfcc43f2449c2c85ef3cf531d2708deb44a150aa4db6e30";
    deps = with allCrates; [ libc time termios termios termios termios termios termios termios termios termios termios termios termios termios ];
  };
  serial_0_1_1 = buildCratesLib {
    name = "serial";
    version = "0.1.1";
    hash = "f8f5b70883c466668446dfa113bf00c9d6925f033372e1f916e6e3d3a83a3745";
    deps = with allCrates; [ time libc termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ];
  };
  serial_0_1_2 = buildCratesLib {
    name = "serial";
    version = "0.1.2";
    hash = "e62dd6afdb15eec92da955b41011eb5a1ec5aeba702626f621658a9621db7ce0";
    deps = with allCrates; [ time libc ioctl-rs termios termios ioctl-rs termios ioctl-rs termios ioctl-rs ioctl-rs termios termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs ];
  };
  serial_0_1_3 = buildCratesLib {
    name = "serial";
    version = "0.1.3";
    hash = "7f40c2b361c0e86a324cea016e258e1aa21ff2c93395ea1f2f7e3d84ffd45412";
    deps = with allCrates; [ libc time termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ];
  };
  serial_0_2_0 = buildCratesLib {
    name = "serial";
    version = "0.2.0";
    hash = "8602f0ab3d643ef94b65e932b4e5daa22c57dc93171567c5f5899755ebacb5a9";
    deps = with allCrates; [ time libc ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios ];
  };
  serial_0_2_1 = buildCratesLib {
    name = "serial";
    version = "0.2.1";
    hash = "70140d158ef5486e750b030d6d28d9191016181905eaa43e3e76c91eb5935df3";
    deps = with allCrates; [ time libc ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios ];
  };
  serial_0_3_0 = buildCratesLib {
    name = "serial";
    version = "0.3.0";
    hash = "49e276d0044dcb0e4f1168ccbabe9dfa2e09702f567b3fbd7081ba28c9008bb1";
    deps = with allCrates; [ libc ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs ];
  };
  serial_0_3_1 = buildCratesLib {
    name = "serial";
    version = "0.3.1";
    hash = "280ae30ca61d9c21b3f5e79d68cb7d9c1cbe2691debc3174ef951552afb4225e";
    deps = with allCrates; [ libc termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios ];
  };
  serial_0_3_2 = buildCratesLib {
    name = "serial";
    version = "0.3.2";
    hash = "5c766b0f30e5829926d7722c40ec1b59b6d217f140a81ba68aad42541f2bacfc";
    deps = with allCrates; [ libc ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios termios ioctl-rs termios ioctl-rs termios ioctl-rs ioctl-rs termios ];
  };
  serial_0_3_3 = buildCratesLib {
    name = "serial";
    version = "0.3.3";
    hash = "b5ba6bcfca825a5471fc4c4fa2407fd6c2be0fa2f75596834195824ba5efdf46";
    deps = with allCrates; [ libc termios ioctl-rs ioctl-rs termios termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios ];
  };
  serial_0_3_4 = buildCratesLib {
    name = "serial";
    version = "0.3.4";
    hash = "cb5e265c52312c3e72a08afb6ac62ba3b9d1778c2193f57d74e307334689c7c8";
    deps = with allCrates; [ libc termios ioctl-rs ioctl-rs termios termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios termios ioctl-rs termios ioctl-rs ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios ioctl-rs termios ];
  };}