#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  sha1_0_0_1 = buildCratesLib {
    name = "sha1";
    version = "0.0.1";
    hash = "3725fcb79a49ff9cdcb0e63eaa7c2ddd356e0d3b47e9560f3a0f7d0142bb61a0";
    deps = with allCrates; [  ];
  };
  sha1_0_0_2 = buildCratesLib {
    name = "sha1";
    version = "0.0.2";
    hash = "28556000e3970601931d5c5fa42002937fdd8be715d508d3ca61f4f35a6b8ca6";
    deps = with allCrates; [  ];
  };
  sha1_0_0_3 = buildCratesLib {
    name = "sha1";
    version = "0.0.3";
    hash = "b560a5ab9abf883d2aadfb39125da68eb7ece1d856d4f72e7b02f70822284a1e";
    deps = with allCrates; [  ];
  };
  sha1_0_0_5 = buildCratesLib {
    name = "sha1";
    version = "0.0.5";
    hash = "acb50478705a7f4f79d85036f9c250b4a4136697d47ddb4a8e072af02b53560e";
    deps = with allCrates; [  ];
  };
  sha1_0_0_6 = buildCratesLib {
    name = "sha1";
    version = "0.0.6";
    hash = "bcf2d8f8ce2d1e02be98821c26da95f2b55dc8e0cfd84538c1e9ea43ed51b091";
    deps = with allCrates; [  ];
  };
  sha1_0_0_7 = buildCratesLib {
    name = "sha1";
    version = "0.0.7";
    hash = "93ec917e5fc326fcacc67b021f6eb0b33f935c177f21385c5439143b6a4535df";
    deps = with allCrates; [  ];
  };
  sha1_0_0_8 = buildCratesLib {
    name = "sha1";
    version = "0.0.8";
    hash = "a3bdb4e45a0d240cb06e762cd358e57ff938327d5be467d4d24f03cdefeebb5b";
    deps = with allCrates; [  byteorder ];
  };
  sha1_0_1_0 = buildCratesLib {
    name = "sha1";
    version = "0.1.0";
    hash = "afbc4130b1dabe726954cd328de3c86c972f0fadd5d71b948c8bcc528f2c829a";
    deps = with allCrates; [  byteorder ];
  };
  "sha1_0_0" = sha1_0_0_8;
  sha1_0_1_1 = buildCratesLib {
    name = "sha1";
    version = "0.1.1";
    hash = "a307a40d5834140e4213a6952483b84e9ad53bdcab918b7335a6e305e505a53c";
    deps = with allCrates; [  byteorder ];
  };
  sha1_0_2_0 = buildCratesLib {
    name = "sha1";
    version = "0.2.0";
    hash = "cc30b1e1e8c40c121ca33b86c23308a090d19974ef001b4bf6e61fd1a0fb095c";
    deps = with allCrates; [  ];
  };
  "sha1_0_1" = sha1_0_1_1;
  "sha1_0_2" = sha1_0_2_0;
  "sha1_0" = sha1_0_2_0;}