#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  libmmap_0_1_0 = buildCratesLib {
    name = "libmmap";
    version = "0.1.0";
    hash = "40d17093e7f10c3f501271a33b9871ad4320882e693267b4d2c611f084cafa61";
    deps = with allCrates; [ libc ];
  };}