#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  comdlg32-sys_0_0_1 = buildCratesLib {
    name = "comdlg32-sys";
    version = "0.0.1";
    hash = "016370586b73a00d297ffc3a0d313db525583d430759e2355bbfb3811eac7871";
    deps = with allCrates; [  winapi ];
  };
  comdlg32-sys_0_2_0 = buildCratesLib {
    name = "comdlg32-sys";
    version = "0.2.0";
    hash = "686401f71bac7db6a866bbfc00b2a4a3ae172967282bf3b5442c3af27750b529";
    deps = with allCrates; [  all__winapi.winapi_0_2 all__winapi-build.winapi-build_0_1 ];
  };
  "comdlg32-sys_0_0" = comdlg32-sys_0_0_1;
  "comdlg32-sys_0_2" = comdlg32-sys_0_2_0;
  "comdlg32-sys_0" = comdlg32-sys_0_2_0;}