#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  thread-id_1_0_0 = buildCratesLib {
    name = "thread-id";
    version = "1.0.0";
    hash = "bc917e123ece06e3200090265d3cda3000d769b92a27add6769c4fc12ee2a903";
    deps = with allCrates; [ libc kernel32-sys ];
  };
  thread-id_2_0_0 = buildCratesLib {
    name = "thread-id";
    version = "2.0.0";
    hash = "a9539db560102d1cef46b8b78ce737ff0bb64e7e18d35b2a5688f7d097d0ff03";
    deps = with allCrates; [ libc kernel32-sys ];
  };
  thread-id_3_0_0 = buildCratesLib {
    name = "thread-id";
    version = "3.0.0";
    hash = "4437c97558c70d129e40629a5b385b3fb1ffac301e63941335e4d354081ec14a";
    deps = with allCrates; [ libc ];
  };}
