#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  gudev_0_1_0 = buildCratesLib {
    name = "gudev";
    version = "0.1.0";
    hash = "c47d25897837eff8e12f5b0131ddcb1fedd228a0a9155bd7bb0346bc476e6a38";
    deps = with allCrates; [  all__glib.glib_0_1 all__libc.libc_0_2 all__gudev-sys.gudev-sys_0_1 all__glib-sys.glib-sys_0_3 ];
  };
  gudev_0_1_1 = buildCratesLib {
    name = "gudev";
    version = "0.1.1";
    hash = "9196327308044a655cd5a41b2b67f8d15d55f73f41d769c6cb1b26d2c649bbb9";
    deps = with allCrates; [  all__glib-sys.glib-sys_0_3 all__gudev-sys.gudev-sys_0_1 all__libc.libc_0_2 all__glib.glib_0_1 ];
  };
  "gudev_0_1" = gudev_0_1_1;
  "gudev_0" = gudev_0_1_1;}