#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  evalrs_0_0_1 = buildCratesLib {
    name = "evalrs";
    version = "0.0.1";
    hash = "0238398e83ea2334c113192902083a4ce646a22c1ee214e602ddd482612fedde";
    deps = with allCrates; [  all__regex.regex_0_1 all__clap.clap_2_19 all__tempdir.tempdir_0_3 ];
  };
  evalrs_0_0_2 = buildCratesLib {
    name = "evalrs";
    version = "0.0.2";
    hash = "9d1a7aa8c4282f07cef35545d1da0e891cb8613bdbfdd97498361009903ab02f";
    deps = with allCrates; [  all__tempdir.tempdir_0_3 all__clap.clap_2_19 all__regex.regex_0_1 ];
  };
  evalrs_0_0_3 = buildCratesLib {
    name = "evalrs";
    version = "0.0.3";
    hash = "f6bcd4f7fca1e9b4caf74ee1559ba7ddbaad6744061392c6c6f82a32632cc01b";
    deps = with allCrates; [  all__regex.regex_0_1 all__tempdir.tempdir_0_3 all__clap.clap_2_19 ];
  };
  "evalrs_0_0" = evalrs_0_0_3;
  "evalrs_0" = evalrs_0_0_3;}