#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  nettraits_0_1_0 = buildCratesLib {
    name = "nettraits";
    version = "0.1.0";
    hash = "a8bbeb1b3754996edcf680b15a78d12817b936006474a8775c23529a6a88c6dd";
    deps = with allCrates; [  ];
  };
  "nettraits_0_1" = nettraits_0_1_0;
  "nettraits_0" = nettraits_0_1_0;}