#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  objpool_0_1_0 = buildCratesLib {
    name = "objpool";
    version = "0.1.0";
    hash = "9036088f04711fb593b48c49a425bd2bdf809c892c0b56b85e5bcf798a453b13";
    deps = with allCrates; [ ];
  };
  objpool_0_2_0 = buildCratesLib {
    name = "objpool";
    version = "0.2.0";
    hash = "949c6531044fe76f89774bf77511a30b2bac7763f55430975f0265491f4cf39a";
    deps = with allCrates; [ ];
  };}