#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  panini_0_0_0 = buildCratesLib {
    name = "panini";
    version = "0.0.0";
    hash = "bd3535ad236fc1123c2ba73f1c39a710fbd086c508696de4151113f2a9d7c164";
    deps = with allCrates; [  all__ref_slice.ref_slice_1_0 all__gearley.gearley_0_0 all__cfg.cfg_0_3 all__typed-arena.typed-arena_1_2 ];
  };
  "panini_0_0" = panini_0_0_0;
  "panini_0" = panini_0_0_0;}