#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  dssec-sys_0_0_1 = buildCratesLib {
    name = "dssec-sys";
    version = "0.0.1";
    hash = "67699de74240afc7b4a7671b189d4157fed2f64a0cbd19099fcaf38dbc63b757";
    deps = with allCrates; [ winapi ];
  };}