#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  xz-decom_0_2_0 = buildCratesLib {
    name = "xz-decom";
    version = "0.2.0";
    hash = "26e62a9a446974a622975877478bd76507a3b910df3e885d3660427059d08a5c";
    deps = with allCrates; [ xz-embedded-sys ];
  };}