#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  genetic-files_1_0_0 = buildCratesLib {
    name = "genetic-files";
    version = "1.0.0";
    hash = "0ac06d7d1af1c45123be3af482195b8a8c954d80d12344124693203026a6af31";
    deps = with allCrates; [ itertools rand clap ];
  };}