#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  minesweeper_0_1_0 = buildCratesLib {
    name = "minesweeper";
    version = "0.1.0";
    hash = "6eb78eb2bfef5c3509af211e370aba5ead76a27453e0e19d830ce03deb78e838";
    deps = with allCrates; [ piston_window find_folder clap rand ];
  };
  minesweeper_1_0_0 = buildCratesLib {
    name = "minesweeper";
    version = "1.0.0";
    hash = "01ab3f13d822d5c864a0b00c1b6619644bf6c3d992487d616b9fb8f40edbadce";
    deps = with allCrates; [ rand piston_window clap find_folder ];
  };
  minesweeper_1_1_0 = buildCratesLib {
    name = "minesweeper";
    version = "1.1.0";
    hash = "2613ec54953295877844599324d2f3340f96f8c38efad45548d07cc270eda9a7";
    deps = with allCrates; [ piston_window find_folder rand clap ];
  };
  minesweeper_1_2_0 = buildCratesLib {
    name = "minesweeper";
    version = "1.2.0";
    hash = "c85df9e5e1e4f130d2e36611c12c58348b6a8e41d19d17e31cf470a48fd4f5b4";
    deps = with allCrates; [ piston_window chrono find_folder clap rand ];
  };
  minesweeper_1_2_1 = buildCratesLib {
    name = "minesweeper";
    version = "1.2.1";
    hash = "e104c6c5b29895201c8b48311b8551061e764ea480f3b2fb636b119765064ba0";
    deps = with allCrates; [ chrono clap find_folder piston_window rand ];
  };}