#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  libloading_0_2_0 = buildCratesLib {
    name = "libloading";
    version = "0.2.0";
    hash = "e2e11ea0af5fc3c215736165032f3ef4bef51dbe9460ddbf63d21d764185bd1c";
    deps = with allCrates; [  all__kernel32-sys.kernel32-sys_0_2 all__lazy_static.lazy_static_0_1 all__winapi.winapi_0_2 ];
  };
  libloading_0_2_1 = buildCratesLib {
    name = "libloading";
    version = "0.2.1";
    hash = "9bf296a78f7aa1c3ad23da173565367769c84e34af19c6e2d6f6b63da7189b9f";
    deps = with allCrates; [  all__lazy_static.lazy_static_0_1 all__winapi.winapi_0_2 all__kernel32-sys.kernel32-sys_0_2 ];
  };
  libloading_0_2_2 = buildCratesLib {
    name = "libloading";
    version = "0.2.2";
    hash = "dfa2c300418af0c8042e94f921274743fd05aa028bd365b42ce3469a6db15000";
    deps = with allCrates; [  all__winapi.winapi_0_2 all__lazy_static.lazy_static_0_2 all__kernel32-sys.kernel32-sys_0_2 ];
  };
  libloading_0_2_3 = buildCratesLib {
    name = "libloading";
    version = "0.2.3";
    hash = "ec941308eab1678c9026901477f8b7a2d58eb54d2cb72ed2f45d9a042ad105f0";
    deps = with allCrates; [  all__winapi.winapi_0_2 all__kernel32-sys.kernel32-sys_0_2 all__lazy_static.lazy_static_0_2 all__target_build_utils.target_build_utils_0_1 ];
  };
  "libloading_0_2" = libloading_0_2_3;
  "libloading_0" = libloading_0_2_3;}