#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  vorbis-shortener_0_1_0 = buildCratesLib {
    name = "vorbis-shortener";
    version = "0.1.0";
    hash = "f18b5e43fe07c78a82194c80dad6b903db78f7b981b5c61d7873ccc7fd496622";
    deps = with allCrates; [  all__gtk.gtk_0_1 all__vorbis.vorbis_0_1 ];
  };
  vorbis-shortener_0_1_1 = buildCratesLib {
    name = "vorbis-shortener";
    version = "0.1.1";
    hash = "d15ff568359266f472fde8526a8d934e173716f74a5c55ae86311ba84ed35dfa";
    deps = with allCrates; [  all__gtk.gtk_0_1 all__vorbis.vorbis_0_1 ];
  };
  "vorbis-shortener_0_1" = vorbis-shortener_0_1_1;
  "vorbis-shortener_0" = vorbis-shortener_0_1_1;}