#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  chemfiles-sys_0_4_0 = buildCratesLib {
    name = "chemfiles-sys";
    version = "0.4.0";
    hash = "f8c468071622277a398b032b0fc9d48a87c20899226c3de21b54ffbe2cc9873c";
    deps = with allCrates; [  libc cmake ];
  };
  chemfiles-sys_0_5_0 = buildCratesLib {
    name = "chemfiles-sys";
    version = "0.5.0";
    hash = "054b11a8a3ffbf6e2bd03be0477c077b41e8fe40d59c947b4d96810a0d5ce013";
    deps = with allCrates; [  all__libc.libc_0_2 all__cmake.cmake_0_1 ];
  };
  "chemfiles-sys_0_4" = chemfiles-sys_0_4_0;
  chemfiles-sys_0_6_0 = buildCratesLib {
    name = "chemfiles-sys";
    version = "0.6.0";
    hash = "53de4d104f254f7f645fb130e6a734f372b0933906d5a4170dae6e790489ee0b";
    deps = with allCrates; [  all__libc.libc_0_2 all__cmake.cmake_0_1 ];
  };
  "chemfiles-sys_0_5" = chemfiles-sys_0_5_0;
  "chemfiles-sys_0_6" = chemfiles-sys_0_6_0;
  "chemfiles-sys_0" = chemfiles-sys_0_6_0;}