#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  bitpack_0_1_0 = buildCratesLib {
    name = "bitpack";
    version = "0.1.0";
    hash = "156b29fef3de4d3392852c6f597798574a4855fed8550493863b0920b62ace9c";
    deps = with allCrates; [ byteorder ];
  };}