#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  humannum_0_1_0 = buildCratesLib {
    name = "humannum";
    version = "0.1.0";
    hash = "2543f51658681860b1ad9aee0aac90182bc8b971f71a3d9eb1d38e23e1158a4b";
    deps = with allCrates; [  all__num-traits.num-traits_0_1 all__quick-error.quick-error_1_0_0 ];
  };
  "humannum_0_1" = humannum_0_1_0;
  "humannum_0" = humannum_0_1_0;}