#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  mex-sys_0_1_0 = buildCratesLib {
    name = "mex-sys";
    version = "0.1.0";
    hash = "f45cac876aabdd1256292ac1e72f77a48fc84a8ef539759599339033a1b0908c";
    deps = with allCrates; [  ];
  };
  "mex-sys_0_1" = mex-sys_0_1_0;
  "mex-sys_0" = mex-sys_0_1_0;}