#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  michromer_0_1_0 = buildCratesLib {
    name = "michromer";
    version = "0.1.0";
    hash = "0b279c39cadbbb11473b39d2b62e5022461563eca9f1fd43ba4f3d76590f687e";
    deps = with allCrates; [  all__hyper.hyper_0_9 all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 ];
  };
  michromer_0_1_1 = buildCratesLib {
    name = "michromer";
    version = "0.1.1";
    hash = "a92540d574787708d6f7c446c182227d784e58bb8e59e5d431a5c872b734ba7e";
    deps = with allCrates; [  all__rustc-serialize.rustc-serialize_0_3 all__log.log_0_3 all__hyper.hyper_0_9 ];
  };
  michromer_0_2_0 = buildCratesLib {
    name = "michromer";
    version = "0.2.0";
    hash = "6a3728098b89714e933e9f14b68f2ae03067ffd3f8aa59ab2e92200d919fe5ef";
    deps = with allCrates; [  all__serde_json.serde_json_0_7 all__chrono.chrono_0_2 all__log.log_0_3 all__hyper.hyper_0_9 all__serde.serde_0_7 all__serde_macros.serde_macros_0_7 ];
  };
  "michromer_0_1" = michromer_0_1_1;
  michromer_0_3_0 = buildCratesLib {
    name = "michromer";
    version = "0.3.0";
    hash = "1f37da3a09e7899d3eb91a2bcbae64e94c8b948d21b9db8699d0f506c136cbdb";
    deps = with allCrates; [  all__serde_macros.serde_macros_0_7 all__hyper.hyper_0_9 all__serde_json.serde_json_0_7 all__chrono.chrono_0_2 all__serde.serde_0_7 all__log.log_0_3 ];
  };
  "michromer_0_2" = michromer_0_2_0;
  michromer_0_3_1 = buildCratesLib {
    name = "michromer";
    version = "0.3.1";
    hash = "7ae0813b2b3821959b5f77c6391b348f144d747976b559fa66e0378deaae5bad";
    deps = with allCrates; [  all__log.log_0_3 all__chrono.chrono_0_2 all__hyper.hyper_0_9 all__serde_macros.serde_macros_0_7 all__serde.serde_0_7 all__serde_json.serde_json_0_7 ];
  };
  michromer_0_3_2 = buildCratesLib {
    name = "michromer";
    version = "0.3.2";
    hash = "3a082770511506877a7422997c6651d169c3137697c3240de2b8c0b40fe66370";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_macros.serde_macros_0_8 all__log.log_0_3 all__chrono.chrono_0_2 all__hyper.hyper_0_9 all__serde_json.serde_json_0_8 ];
  };
  michromer_0_3_3 = buildCratesLib {
    name = "michromer";
    version = "0.3.3";
    hash = "56997f88e55c9401d4bb8b2730e4eb689e6d13b35a4464ec450f61ef2d3e179a";
    deps = with allCrates; [  all__serde_json.serde_json_0_8 all__serde.serde_0_8 all__serde_macros.serde_macros_0_8 all__chrono.chrono_0_2 all__hyper.hyper_0_9 all__log.log_0_3 ];
  };
  michromer_0_3_4 = buildCratesLib {
    name = "michromer";
    version = "0.3.4";
    hash = "0a5830e1039b34ea41410647901b86ab6e0b41741ff434655a474aa7b12980f3";
    deps = with allCrates; [  all__serde.serde_0_8 all__serde_json.serde_json_0_8 all__log.log_0_3 all__serde_macros.serde_macros_0_8 all__hyper.hyper_0_9 all__chrono.chrono_0_2 ];
  };
  "michromer_0_3" = michromer_0_3_4;
  "michromer_0" = michromer_0_3_4;}