#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  orichalcum_0_0_0 = buildCratesLib {
    name = "orichalcum";
    version = "0.0.0";
    hash = "276ae5fd0f47c27b4c6fb7d9037c94139efd916cece88b10009061d44eeffa0c";
    deps = with allCrates; [  ];
  };
  "orichalcum_0_0" = orichalcum_0_0_0;
  "orichalcum_0" = orichalcum_0_0_0;}