#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  mutator_0_1_0 = buildCratesLib {
    name = "mutator";
    version = "0.1.0";
    hash = "3a77eaa26ead5ef6c9b07a99a546cbfa479fc78573f93ad78302b906c6f0393f";
    deps = with allCrates; [ ];
  };}