#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  evic_0_1_0 = buildCratesLib {
    name = "evic";
    version = "0.1.0";
    hash = "ac68a3f3d965ca4528e5d19ccbd31802409dd040e04396dd29dacfa9ec0b7f9c";
    deps = with allCrates; [ getopts ];
  };
  evic_0_1_1 = buildCratesLib {
    name = "evic";
    version = "0.1.1";
    hash = "81841b9b975bebc35160eb06a91702e4ab1cce06a689949fdf291cd6c10f43c3";
    deps = with allCrates; [ getopts ];
  };}