#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  linuxver_0_1_0 = buildCratesLib {
    name = "linuxver";
    version = "0.1.0";
    hash = "371bed477e3927e27aa8a6c9bebb0d08a4696ac82b80c8402bc61fe0dc8df6ab";
    deps = with allCrates; [ semver nix ];
  };}