#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  plugger-ruby_0_1_0 = buildCratesLib {
    name = "plugger-ruby";
    version = "0.1.0";
    hash = "1289b44a36ae5ab38906c4537d0e4b29fce8cc917f137ad3145c1b3822717008";
    deps = with allCrates; [  all__plugger-core.plugger-core_0_1 all__rurust.rurust_0_1 all__plugger-macros.plugger-macros_0_1 ];
  };
  plugger-ruby_0_1_1 = buildCratesLib {
    name = "plugger-ruby";
    version = "0.1.1";
    hash = "4f82dfeabf98eb36822ee49e4d7d0eec28d5622c445ba13ec046c2f8b89be174";
    deps = with allCrates; [  all__plugger-macros.plugger-macros_0_1 all__libc.libc_0_2 all__rurust.rurust_0_1 all__plugger-core.plugger-core_0_1 ];
  };
  "plugger-ruby_0_1" = plugger-ruby_0_1_1;
  "plugger-ruby_0" = plugger-ruby_0_1_1;}