#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  peakbag_0_1_0 = buildCratesLib {
    name = "peakbag";
    version = "0.1.0";
    hash = "9be4a4227910ea48973da316fe8f7b029a7c2f5e1c62988b7edce35c62dad927";
    deps = with allCrates; [ num log ];
  };}