#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  peakbag_0_1_0 = buildCratesLib {
    name = "peakbag";
    version = "0.1.0";
    hash = "9be4a4227910ea48973da316fe8f7b029a7c2f5e1c62988b7edce35c62dad927";
    deps = with allCrates; [  all__num.num_0_1 all__log.log_0_3 ];
  };
  "peakbag_0_1" = peakbag_0_1_0;
  "peakbag_0" = peakbag_0_1_0;}