#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  ransid_0_1_1 = buildCratesLib {
    name = "ransid";
    version = "0.1.1";
    hash = "be0ce9cfcfaee10edcc0d31e9686904ef9a4442e3295ba778a73b3bf4b5c88f4";
    deps = with allCrates; [ ];
  };
  ransid_0_1_2 = buildCratesLib {
    name = "ransid";
    version = "0.1.2";
    hash = "659a4d46f3b6da2fbd17cdb769162afb9fe0e6097c7783b7504d685e1fa020e8";
    deps = with allCrates; [ ];
  };
  ransid_0_2_0 = buildCratesLib {
    name = "ransid";
    version = "0.2.0";
    hash = "ce0c1b4c0dc24c14bcc71fa373d1bce433ea250691313b0cc1bc73e333a2bda0";
    deps = with allCrates; [ ];
  };
  ransid_0_2_1 = buildCratesLib {
    name = "ransid";
    version = "0.2.1";
    hash = "eaeb0d9272dbbcc23c90acb25bbee7771f5dcd8b6b2c0736e97dfd2176fc8dd8";
    deps = with allCrates; [ ];
  };
  ransid_0_2_2 = buildCratesLib {
    name = "ransid";
    version = "0.2.2";
    hash = "a694b6e2051563bf428cd409d42b4737ae77832a58f5a9e3d8448760bcf50041";
    deps = with allCrates; [ ];
  };}