#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  gc_0_0_1 = buildCratesLib {
    name = "gc";
    version = "0.0.1";
    hash = "61b000eff8f4b3510d1146fb023b5b2f4ffb30f1ab39a8637b6aac1c233e2b9c";
    deps = with allCrates; [ gc_plugin ];
  };
  gc_0_0_2 = buildCratesLib {
    name = "gc";
    version = "0.0.2";
    hash = "49ceb2d8404f07c83252cb3db39fa44836312ac37c80c9073741872fdede58b1";
    deps = with allCrates; [ gc_plugin ];
  };
  gc_0_0_3 = buildCratesLib {
    name = "gc";
    version = "0.0.3";
    hash = "2a082db4f93b4cad295c1b06e16e7c064fc956737f4e75108a9f234adbea266f";
    deps = with allCrates; [ gc_plugin ];
  };
  gc_0_0_4 = buildCratesLib {
    name = "gc";
    version = "0.0.4";
    hash = "bc0a552625cd7c740b0a74653333da0388f1a07c41b7fc30fc9d420731227dd8";
    deps = with allCrates; [ gc_plugin ];
  };
  gc_0_0_5 = buildCratesLib {
    name = "gc";
    version = "0.0.5";
    hash = "dab5d8e6ca342e27742661cb9d687ee80d0532ab5b7d18534dbd15759bc53168";
    deps = with allCrates; [ gc_plugin ];
  };
  gc_0_0_6 = buildCratesLib {
    name = "gc";
    version = "0.0.6";
    hash = "abfeb12f423d637ece736658050acd5b374cde6ecd14387c62f2940ec6b6d45b";
    deps = with allCrates; [ ];
  };
  gc_0_0_7 = buildCratesLib {
    name = "gc";
    version = "0.0.7";
    hash = "69f4c7955ed0a84c63bc80207c22309676affee6e02dacaf8daafbe12488080a";
    deps = with allCrates; [ ];
  };
  gc_0_0_8 = buildCratesLib {
    name = "gc";
    version = "0.0.8";
    hash = "039f3e5011e20d21bfd8ac5a4a345cf046e3214b85c65e9bc3ec70d4a1235136";
    deps = with allCrates; [ ];
  };
  gc_0_0_9 = buildCratesLib {
    name = "gc";
    version = "0.0.9";
    hash = "df56d46cc3227842c6c979c6956edcf09a743af3db152ef242d4e48c97772cd1";
    deps = with allCrates; [ ];
  };
  gc_0_1_0 = buildCratesLib {
    name = "gc";
    version = "0.1.0";
    hash = "455f2fe1adda84ef8aced43910b9bbac42a32dfa686a401802586327fb0f5b84";
    deps = with allCrates; [ ];
  };
  gc_0_1_1 = buildCratesLib {
    name = "gc";
    version = "0.1.1";
    hash = "c648122e581104c7f08c0faff4d441e54b08f18eaf7fa54c9a1fa9acd76454fe";
    deps = with allCrates; [ ];
  };
  gc_0_2_0 = buildCratesLib {
    name = "gc";
    version = "0.2.0";
    hash = "644260751650a1fa9cc7d66d770ab7ecec32db2110bdd020639ac0af80248911";
    deps = with allCrates; [ ];
  };
  gc_0_2_1 = buildCratesLib {
    name = "gc";
    version = "0.2.1";
    hash = "b0cfa13f64d65b999a2ad1f89ea35285f2468b7bbe5e096d1851fcfef6105fcb";
    deps = with allCrates; [ ];
  };}