#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  pe_0_1_0 = buildCratesLib {
    name = "pe";
    version = "0.1.0";
    hash = "0dd93f55e72f600bac608cf159ffe7772635ec0489484de5ad1341575ff544b8";
    deps = with allCrates; [  all__bitflags.bitflags_0_4 ];
  };
  pe_0_1_1 = buildCratesLib {
    name = "pe";
    version = "0.1.1";
    hash = "de31e953ee9f97fce65decc96536d4df6a9ac7e51e13e2b635aae46e507b9048";
    deps = with allCrates; [  all__bitflags.bitflags_0_4 ];
  };
  "pe_0_1" = pe_0_1_1;
  "pe_0" = pe_0_1_1;}