#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  rb_0_1_0 = buildCratesLib {
    name = "rb";
    version = "0.1.0";
    hash = "6a66b5cd78aab0f767d5fb4f006b9382408bc9096ec574781b6271b4b003b5dd";
    deps = with allCrates; [  ];
  };
  rb_0_1_1 = buildCratesLib {
    name = "rb";
    version = "0.1.1";
    hash = "e343f5f23570a912bcd9275765f9087e587c2ac2527404e04ed7b9ec14b9c4a6";
    deps = with allCrates; [  ];
  };
  rb_0_1_2 = buildCratesLib {
    name = "rb";
    version = "0.1.2";
    hash = "d6ed1699368fa085089907af281a7540b9821ba5174aa943555c0483d113913d";
    deps = with allCrates; [  ];
  };
  rb_0_1_3 = buildCratesLib {
    name = "rb";
    version = "0.1.3";
    hash = "ab7ddbebc712c651d495e0f9f1770d17cf279ac3c8f5c490a8e1ac8b7d930415";
    deps = with allCrates; [  ];
  };
  rb_0_2_0 = buildCratesLib {
    name = "rb";
    version = "0.2.0";
    hash = "bf4244668d567959acbf78b19ce254f4f82bdf731b7349b79e3ae01504e28980";
    deps = with allCrates; [  ];
  };
  "rb_0_1" = rb_0_1_3;
  "rb_0_2" = rb_0_2_0;
  "rb_0" = rb_0_2_0;}