#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  wf_0_1_0 = buildCratesLib {
    name = "wf";
    version = "0.1.0";
    hash = "ad28dc247c1f9bd8709899430bf0c810f0e2a7e3f94b28ff74de0fbd3c2bfaa9";
    deps = with allCrates; [ itertools getopts ];
  };
  wf_0_1_1 = buildCratesLib {
    name = "wf";
    version = "0.1.1";
    hash = "a85c277fd2a3411b546bf94cd891c76d6618b7e5592566a0b9c83f1c10c45c89";
    deps = with allCrates; [ itertools getopts ];
  };}