#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  susurrus_0_1_0 = buildCratesLib {
    name = "susurrus";
    version = "0.1.0";
    hash = "071c8206313fff36f33c19c3fb2d7e8cf3b11d336e94f192847c80f822100716";
    deps = with allCrates; [  sodiumoxide byteorder ];
  };
  "susurrus_0_1" = susurrus_0_1_0;
  "susurrus_0" = susurrus_0_1_0;}