#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  chacha20-poly1305-aead_0_1_0 = buildCratesLib {
    name = "chacha20-poly1305-aead";
    version = "0.1.0";
    hash = "f9a8f34d9164d30924252e126d4faf0ffa366f7a8a3b89db535c00e9b784b3ff";
    deps = with allCrates; [  all__constant_time_eq.constant_time_eq_0_1 ];
  };
  chacha20-poly1305-aead_0_1_1 = buildCratesLib {
    name = "chacha20-poly1305-aead";
    version = "0.1.1";
    hash = "dbbd5c2a366006b0b731dcad09ba11c9ef87303d3f9b18ef002416cbddf8cc46";
    deps = with allCrates; [  all__constant_time_eq.constant_time_eq_0_1 ];
  };
  chacha20-poly1305-aead_0_1_2 = buildCratesLib {
    name = "chacha20-poly1305-aead";
    version = "0.1.2";
    hash = "77d2058ba29594f69c75e8a9018e0485e3914ca5084e3613cd64529042f5423b";
    deps = with allCrates; [  all__constant_time_eq.constant_time_eq_0_1 ];
  };
  "chacha20-poly1305-aead_0_1" = chacha20-poly1305-aead_0_1_2;
  "chacha20-poly1305-aead_0" = chacha20-poly1305-aead_0_1_2;}