#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  argparse_0_1_0 = buildCratesLib {
    name = "argparse";
    version = "0.1.0";
    hash = "eb6db768d9b35d2ff79568e2db65210350d323c1ea7fbd541ead168f5d72011b";
    deps = with allCrates; [  ];
  };
  argparse_0_1_1 = buildCratesLib {
    name = "argparse";
    version = "0.1.1";
    hash = "da86f198ce413e0f37f5b7bab444ffbd34d3d8decc019dc2e9559c014677132b";
    deps = with allCrates; [  ];
  };
  argparse_0_1_2 = buildCratesLib {
    name = "argparse";
    version = "0.1.2";
    hash = "03d0001427b76944bee382ac8f6b9766f4e7ed203af2f3e876423133e35e4ce9";
    deps = with allCrates; [  ];
  };
  argparse_0_1_3 = buildCratesLib {
    name = "argparse";
    version = "0.1.3";
    hash = "3bb44712d07c8824935c3020dfc4031fc892706696abef474d9d4fe5aa2ea5d6";
    deps = with allCrates; [  ];
  };
  argparse_0_2_0 = buildCratesLib {
    name = "argparse";
    version = "0.2.0";
    hash = "2bbcaac5be37e8ae35625be73fe951b440c0ab83a3a59e7ddbc8d4a53ea1012f";
    deps = with allCrates; [  ];
  };
  "argparse_0_1" = argparse_0_1_3;
  argparse_0_2_1 = buildCratesLib {
    name = "argparse";
    version = "0.2.1";
    hash = "37bb99f5e39ee8b23b6e227f5b8f024207e8616f44aa4b8c76ecd828011667ef";
    deps = with allCrates; [  ];
  };
  "argparse_0_2" = argparse_0_2_1;
  "argparse_0" = argparse_0_2_1;}