#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
{
  hbs-sys_0_2_0 = buildCratesLib {
    name = "hbs-sys";
    version = "0.2.0";
    hash = "c5ffaf934963a66278f275fb6279a6a7ff8f620cfc01c60db1b7e6d9fbd23b54";
    deps = with allCrates; [ hbs-common-sys libc hbs-builder ];
  };
  hbs-sys_0_2_1 = buildCratesLib {
    name = "hbs-sys";
    version = "0.2.1";
    hash = "a01ff81faae4c302227cbc07f4d4c131b596df8dd4e0982ae6857b99e68d60c8";
    deps = with allCrates; [ hbs-common-sys libc hbs-builder ];
  };}