#DON'T EDIT. AUTOGENERATED FILE
{buildCratesLib, allCrates}:
rec {
  tariff_0_1_0 = buildCratesLib {
    name = "tariff";
    version = "0.1.0";
    hash = "a242f10ab70b556dfb248799a717b76faefe74a284d0a61331e0db54ac4ea049";
    deps = with allCrates; [  all__docopt.docopt_0_6 all__bson.bson_0_1 all__mongodb.mongodb_0_1 all__rustc-serialize.rustc-serialize_0_3 ];
  };
  "tariff_0_1" = tariff_0_1_0;
  "tariff_0" = tariff_0_1_0;}